"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type User = { username: string; display_name: string; role: string; permissions: string[] }; type Session = { authenticated: boolean; user: User | null };
type Row = { project_id: number | null; project_code: string; project_name: string; currency_code: string; sales_source_amount: string; purchase_source_amount: string; ar_total: string; ar_settled: string; ar_outstanding: string; ap_total: string; ap_settled: string; ap_outstanding: string; customer_receipts: string; supplier_payments: string; net_cash: string; transaction_contribution: string; unattributed_amount: string };
const can = (user: User | null | undefined, permission: string) => Boolean(user && (user.permissions.includes("*") || user.permissions.includes(permission))); const message = (error: unknown) => error instanceof ErpApiError ? error.message : "系统暂时无法完成请求";
export function FinanceProjectsWorkspace() { const [session, setSession] = useState<Session | null>(null); const [rows, setRows] = useState<Row[]>([]); const [error, setError] = useState(""); const load = useCallback(async () => { try { const current = await api<Session>("/api/session"); setSession(current); if (current.authenticated && can(current.user, "finance.project.read")) setRows((await api<{ rows: Row[] }>("/api/finance/projects")).rows); } catch (cause) { setError(message(cause)); } }, []); useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]); if (!session) return <main className="sourcing-shell">正在读取会话…</main>; if (!session.authenticated) return <main className="sourcing-shell">请先登录。</main>; if (!can(session.user, "finance.project.read")) return <main className="sourcing-shell">没有项目财务汇总权限。</main>; return <main className="sourcing-shell"><div className="sourcing-banner">按项目和币种独立展示 · 禁止跨币种聚合</div><header className="sourcing-header"><div><Link href="/" className="sourcing-back">← 经营工作台</Link><p className="sourcing-kicker">项目现金流追溯</p><h1>项目收支追溯</h1><p>来源金额沿稳定业务 ID 自动归属；无法核对的历史来源仅列入“未归属”，不按名称或单号猜测。</p></div></header><section className="sourcing-panel"><h2>项目与币种</h2>{rows.map((row) => <article className="sourcing-card" key={`${row.project_code}-${row.currency_code}`}><div><b>{row.project_code} · {row.project_name}</b><span className="sourcing-status status-completed">{row.currency_code}</span></div><p>销售来源 {row.sales_source_amount} · 采购来源 {row.purchase_source_amount} · 交易贡献 {row.transaction_contribution}</p><p>AR {row.ar_total} / 已收 {row.ar_settled} / 未结 {row.ar_outstanding} · AP {row.ap_total} / 已付 {row.ap_settled} / 未结 {row.ap_outstanding}</p><p><b>客户收款 {row.customer_receipts} · 供应商付款 {row.supplier_payments} · 净现金 {row.net_cash}</b></p>{row.project_id === null ? <small>未归属 {row.unattributed_amount}</small> : null}</article>)}{!rows.length ? <div className="sourcing-state">当前没有项目财务来源。</div> : null}</section><div className="sourcing-state">交易贡献和净现金流不是毛利、净利润或会计利润；未包含人工、制造费用、公司费用、税、折旧、汇率和库存成本。未收款 AR 不作为现金收入。</div>{error ? <div className="sourcing-state sourcing-error">{error}</div> : null}</main>; }
