"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {api,ErpApiError} from "../../../public/erp/api-client.js";
import {statusLabel} from "../../../public/erp/status-localization.js";
import "../../procurement/sourcing/sourcing.css";
type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};type Center={id:number;work_center_code:string;name_cn:string;work_center_type:string;status:string;description:string;version:number};
const can=(s:Session|null,p:string)=>Boolean(s?.user&&(s.user.permissions.includes("*")||s.user.permissions.includes(p)));
export default function WorkCentersPage(){const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<Center[]>([]),[error,setError]=useState("");async function load(){const s=await api<Session>("/api/session");setSession(s);if(s.authenticated)setRows((await api<{rows:Center[]}>("/api/production/work-centers")).rows);}useEffect(()=>{void api<Session>("/api/session").then(async s=>{setSession(s);if(s.authenticated)setRows((await api<{rows:Center[]}>("/api/production/work-centers")).rows);}).catch(e=>setError(e instanceof ErpApiError?e.message:"读取失败"));},[]);async function post(path:string,body:Record<string,unknown>){if(!session)return;try{await api(path,{method:"POST",body:JSON.stringify(body),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});await load();}catch(e){setError(e instanceof ErpApiError?e.message:"操作失败");}}async function create(form:FormData){await post("/api/production/work-centers",{work_center_code:form.get("code"),name_cn:form.get("name"),work_center_type:form.get("type"),description:form.get("description")});}
return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/">← 经营工作台</Link><h1>工作中心</h1><p>稳定编码、受控启停；不保存设备密码、网络地址或控制参数。</p></div></header>{can(session,"production.work_center.manage")?<section className="sourcing-panel"><h2>新增工作中心</h2><form action={create}><input name="code" required placeholder="SMT-PRINT"/><input name="name" required placeholder="中文名称"/><input name="type" required placeholder="类型"/><input name="description" placeholder="说明"/><button>创建启用状态的工作中心</button></form></section>:null}<section className="sourcing-panel"><h2>主数据</h2>{rows.map(row=><article className="sourcing-card" key={row.id}><b>{row.work_center_code} · {row.name_cn}</b><small>{row.work_center_type} · {statusLabel(row.status)} · v{row.version}</small><p>{row.description}</p>{can(session,"production.work_center.manage")?<button onClick={()=>post(`/api/production/work-centers/${row.id}/status`,{expected_version:row.version,status:row.status==="ACTIVE"?"INACTIVE":"ACTIVE"})}>{row.status==="ACTIVE"?"停用":"启用"}</button>:null}</article>)}</section>{error?<div className="sourcing-state sourcing-error">{error}</div>:null}</main>}
