import { createHash, randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { ProductionError } from "../production-selfhost/errors.ts";
import { ProductionRepository } from "../production-selfhost/repository.ts";
import type { ProductionMeta, ProductionResult } from "../production-selfhost/types.ts";
import { initializeOperationProjections, refreshOperationProjections } from "./projections.ts";

const id = (value: unknown, field: string) => { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed <= 0) throw new ProductionError("REQUEST_VALIDATION_FAILED", `${field} 必须为正整数`); return parsed; };
const version = (value: unknown, field = "expected_version") => id(value, field);
const quantity = (value: unknown, field: string, allowZero = false) => { const raw = String(value ?? "").trim(); if (!/^(?:0|[1-9]\d{0,17})(?:\.\d{1,6})?$/.test(raw) || (!allowZero && Number(raw) <= 0)) throw new ProductionError("REQUEST_VALIDATION_FAILED", `${field} 必须为${allowZero ? "非负" : "正"}数且最多 6 位小数`); return raw; };
const text = (value: unknown, field: string, maximum: number, required = false) => { const result = String(value ?? "").trim().normalize("NFKC"); if ((required && !result) || result.length > maximum || /[\u0000-\u001f\u007f]/.test(result)) throw new ProductionError("REQUEST_VALIDATION_FAILED", `${field} 无效`); return result; };
const timestamp = (value: unknown, field: string) => { if (value == null || value === "") return null; const parsed = new Date(String(value)); if (Number.isNaN(parsed.valueOf())) throw new ProductionError("REQUEST_VALIDATION_FAILED", `${field} 不是有效时间`); return parsed.toISOString(); };
const digest = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");

export class ProductionOperationService {
  readonly repository: ProductionRepository;
  readonly fault?: (checkpoint: string) => void | Promise<void>;
  constructor(repository: ProductionRepository, fault?: (checkpoint: string) => void | Promise<void>) { this.repository = repository; this.fault = fault; }

  async operators() { return this.repository.pool.query("select username,display_name,role,version from app_users where is_active and role in ('production','manager','admin') order by display_name,username"); }
  async operations(workOrderId?: number) { const values: unknown[] = []; const where = workOrderId ? (values.push(workOrderId), "where p.work_order_id=$1") : ""; return this.repository.pool.query(`select p.*,wo.work_order_code,wo.status work_order_status,op.sequence_no,op.operation_code,op.operation_name,op.work_center_id,op.work_center_code,op.work_center_name,op.quality_gate_mode,w.source_input_qty::text,w.waiting_input_qty::text,w.dispatched_qty::text,w.in_progress_qty::text,w.completed_good_qty::text,w.scrap_qty::text,w.transferred_to_next_qty::text,w.available_for_next_qty::text,w.final_output_available_qty::text,w.quality_required_qty::text,w.quality_inspected_qty::text,w.quality_released_qty::text,w.quality_hold_qty::text,w.version wip_version from production_work_order_operation_projections p join production_work_orders wo on wo.id=p.work_order_id join production_work_order_routing_snapshot_operations op on op.id=p.snapshot_operation_id join production_operation_wip_projections w on w.operation_projection_id=p.id ${where} order by wo.created_at desc,wo.id desc,op.sequence_no`, values); }
  async runs(workOrderId?: number) { const values: unknown[] = []; const where = workOrderId ? (values.push(workOrderId), "where r.work_order_id=$1") : ""; return this.repository.pool.query(`select r.*,wo.work_order_code,op.sequence_no,op.operation_code,op.operation_name,op.work_center_code,op.quality_gate_mode,u.display_name assigned_operator_name,w.quality_required_qty::text,w.quality_inspected_qty::text,w.quality_released_qty::text,w.quality_hold_qty::text,w.available_for_next_qty::text,w.final_output_available_qty::text from production_operation_runs r join production_work_orders wo on wo.id=r.work_order_id join production_work_order_routing_snapshot_operations op on op.id=r.snapshot_operation_id join production_work_order_operation_projections p on p.snapshot_operation_id=op.id join production_operation_wip_projections w on w.operation_projection_id=p.id join app_users u on u.username=r.assigned_operator ${where} order by r.created_at desc,r.id desc`, values); }
  async wip(workOrderId?: number) { return this.operations(workOrderId); }

  private async lockProjection(client: PoolClient, snapshotOperationId: number, expectedVersion?: number) {
    const result = await client.query(`select p.*,wo.status work_order_status,wo.planned_qty,op.sequence_no,op.operation_code,op.operation_name,op.work_center_id,op.work_center_code,op.work_center_name,op.quality_gate_mode,w.waiting_input_qty,w.available_for_next_qty,w.quality_hold_qty,w.version wip_version from production_work_order_operation_projections p join production_work_orders wo on wo.id=p.work_order_id join production_work_order_routing_snapshot_operations op on op.id=p.snapshot_operation_id join production_operation_wip_projections w on w.operation_projection_id=p.id where p.snapshot_operation_id=$1 for update of p,w,wo`, [snapshotOperationId]);
    const row = result.rows[0]; if (!row) throw new ProductionError("SNAPSHOT_OPERATION_NOT_FOUND", "工单快照工序不存在", 404); if (expectedVersion != null && Number(row.version) !== expectedVersion) throw new ProductionError("OPERATION_VERSION_CONFLICT", "工序投影版本已变化，请刷新后重试", 409); return row;
  }
  private async lockRun(client: PoolClient, runId: number, expectedVersion: number) { const result = await client.query("select r.*,p.next_snapshot_operation_id,p.version operation_version from production_operation_runs r join production_work_order_operation_projections p on p.snapshot_operation_id=r.snapshot_operation_id where r.id=$1 for update of r,p", [runId]); const row = result.rows[0]; if (!row) throw new ProductionError("OPERATION_RUN_NOT_FOUND", "工序派工批次不存在", 404); if (Number(row.version) !== expectedVersion) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "派工批次版本已变化，请刷新后重试", 409); return row; }
  private enforceAssignee(meta: ProductionMeta, run: Record<string, unknown>) { if (meta.actor.role === "production" && run.assigned_operator !== meta.actor.username) throw new ProductionError("OPERATION_RUN_OPERATOR_FORBIDDEN", "生产人员只能执行分配给自己的批次", 403); }

  async dispatch(meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> {
    const snapshotOperationId = id(input.snapshot_operation_id, "snapshot_operation_id"), dispatchedQty = quantity(input.quantity, "quantity"), assignedOperator = text(input.assigned_operator, "assigned_operator", 32, true), expected = version(input.expected_operation_version, "expected_operation_version"), plannedStart = timestamp(input.planned_start, "planned_start"), plannedEnd = timestamp(input.planned_end, "planned_end");
    if (plannedStart && plannedEnd && plannedEnd < plannedStart) throw new ProductionError("REQUEST_VALIDATION_FAILED", "planned_end 不得早于 planned_start");
    return this.repository.execute(meta, async (client) => {
      const projection = await this.lockProjection(client, snapshotOperationId, expected);
      if (!["RELEASED", "IN_PROGRESS"].includes(projection.work_order_status)) throw new ProductionError("WORK_ORDER_STATE_CONFLICT", "工单必须处于 RELEASED 或 IN_PROGRESS", 409);
      if (!['READY','IN_PROGRESS'].includes(projection.status)) throw new ProductionError("OPERATION_NOT_READY", "工序前置投入不足，不能派工", 409);
      const available = await client.query("select $1::numeric<=$2::numeric ok", [dispatchedQty, projection.waiting_input_qty]); if (!available.rows[0].ok) throw new ProductionError("OPERATION_DISPATCH_OVER_AVAILABLE", "派工数量超过当前可用投入", 409);
      const operator = await client.query("select username,role from app_users where username=$1 and is_active for share", [assignedOperator]); if (!operator.rows[0] || !['production','manager','admin'].includes(operator.rows[0].role)) throw new ProductionError("OPERATION_OPERATOR_INELIGIBLE", "指派人员未启用或不具备生产执行能力", 422);
      const runCode = await this.repository.nextCode(client, "PRODUCTION_OPERATION_RUN", "POR"), sourceDigest = digest({ snapshot_operation_id: snapshotOperationId, work_center_id: Number(projection.work_center_id), work_center_code: projection.work_center_code, work_center_name: projection.work_center_name, assigned_operator: assignedOperator, dispatched_qty: dispatchedQty, planned_start: plannedStart, planned_end: plannedEnd });
      const saved = await client.query(`insert into production_operation_runs(run_code,work_order_id,snapshot_operation_id,work_center_id,work_center_code,work_center_name,assigned_operator,dispatched_qty,planned_start,planned_end,source_digest,operation_id,created_by,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *`, [runCode, Number(projection.work_order_id), snapshotOperationId, Number(projection.work_center_id), projection.work_center_code, projection.work_center_name, assignedOperator, dispatchedQty, plannedStart, plannedEnd, sourceDigest, meta.operationId, meta.actor.username, meta.requestId]);
      const runId = Number(saved.rows[0].id);
      if (projection.previous_snapshot_operation_id != null) {
        const sources = await client.query(`select r.id,(case when op.quality_gate_mode='IPQC' then coalesce(q.released,0) else r.good_qty end-coalesce(a.used,0))::text available
          from production_operation_runs r join production_work_order_routing_snapshot_operations op on op.id=r.snapshot_operation_id
          left join lateral(select sum(x.quantity) used from production_operation_run_input_allocations x join production_operation_runs target on target.id=x.run_id where x.source_run_id=r.id and target.status not in ('CANCELLED','REVERSED')) a on true
          left join lateral(select sum(qi.released_qty) released from quality_inspections qi join production_operation_run_reports rr on rr.id=qi.production_operation_run_report_id where rr.run_id=r.id and qi.lifecycle_status='CLOSED' and qi.decision_status='RELEASED') q on true
          where r.snapshot_operation_id=$1 and r.status not in ('CANCELLED','REVERSED') and case when op.quality_gate_mode='IPQC' then coalesce(q.released,0) else r.good_qty end-coalesce(a.used,0)>0 order by r.id for update of r,op`, [Number(projection.previous_snapshot_operation_id)]);
        let remaining = Number(dispatchedQty); for (const source of sources.rows) { if (remaining <= 0) break; const allocated = Math.min(remaining, Number(source.available)).toFixed(6); await client.query("insert into production_operation_run_input_allocations(run_id,source_run_id,quantity,operation_id,created_by,request_id) values($1,$2,$3,$4,$5,$6)", [runId, Number(source.id), allocated, randomUUID(), meta.actor.username, meta.requestId]); remaining = Number((remaining - Number(allocated)).toFixed(6)); }
        if (remaining > 0) throw new ProductionError("OPERATION_UPSTREAM_ALLOCATION_CONFLICT", "前序工序良品已被并发消费", 409);
      }
      await client.query("insert into production_operation_run_events(run_id,event_type,to_status,actor,request_id) values($1,'DISPATCHED','READY',$2,$3)", [runId, meta.actor.username, meta.requestId]);
      await this.fault?.("after_operation_dispatch_facts"); await refreshOperationProjections(client, Number(projection.work_order_id));
      return { status: 201, body: { ok: true, data: saved.rows[0], request_id: meta.requestId }, objectId: runId };
    });
  }

  async start(runId: number, meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> { const expected = version(input.expected_version); return this.repository.execute(meta, async (client) => { const run = await this.lockRun(client, runId, expected); this.enforceAssignee(meta, run); if (run.status !== "READY") throw new ProductionError("OPERATION_RUN_STATE_CONFLICT", "只有有效 READY 派工可以开工", 409); const saved = await client.query("update production_operation_runs set status='IN_PROGRESS',started_by=$3,started_at=now(),version=version+1,updated_at=now() where id=$1 and version=$2 and status='READY' returning *", [runId, expected, meta.actor.username]); if (!saved.rows[0]) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "派工批次已被并发开工", 409); await client.query("insert into production_operation_run_events(run_id,event_type,from_status,to_status,actor,request_id) values($1,'STARTED','READY','IN_PROGRESS',$2,$3)", [runId, meta.actor.username, meta.requestId]); await this.fault?.("after_operation_started"); await refreshOperationProjections(client, Number(run.work_order_id)); return { status: 200, body: { ok: true, data: saved.rows[0], request_id: meta.requestId }, objectId: runId }; }); }

  async report(runId: number, meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> {
    const expected = version(input.expected_version), processed = quantity(input.processed_qty, "processed_qty"), good = quantity(input.good_qty, "good_qty", true), scrap = quantity(input.scrap_qty, "scrap_qty", true), remark = text(input.remark, "remark", 1000);
    if (Number((Number(good) + Number(scrap)).toFixed(6)) !== Number(processed)) throw new ProductionError("OPERATION_QUANTITY_NOT_CONSERVED", "good_qty + scrap_qty 必须等于 processed_qty", 422);
    return this.repository.execute(meta, async (client) => { const run = await this.lockRun(client, runId, expected); this.enforceAssignee(meta, run); if (run.status !== "IN_PROGRESS") throw new ProductionError("OPERATION_RUN_STATE_CONFLICT", "只有已开工批次可以工序报工", 409); const allowed = await client.query("select $1::numeric+$2::numeric<=$3::numeric ok", [run.processed_qty, processed, run.dispatched_qty]); if (!allowed.rows[0].ok) throw new ProductionError("OPERATION_REPORT_OVER_DISPATCHED", "累计处理数量超过派工数量", 409); const reportCode = await this.repository.nextCode(client, "PRODUCTION_OPERATION_REPORT", "OPR"), savedReport = await client.query("insert into production_operation_run_reports(report_code,run_id,snapshot_operation_id,processed_qty,good_qty,scrap_qty,remark,operation_id,reported_by,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *", [reportCode, runId, Number(run.snapshot_operation_id), processed, good, scrap, remark, meta.operationId, meta.actor.username, meta.requestId]); const final = await client.query("select ($1::numeric+$2::numeric=$3::numeric) completed", [run.processed_qty, processed, run.dispatched_qty]), target = final.rows[0].completed ? "COMPLETED" : "IN_PROGRESS"; const saved = await client.query(`update production_operation_runs set processed_qty=processed_qty+$3::numeric,good_qty=good_qty+$4::numeric,scrap_qty=scrap_qty+$5::numeric,status=$6,version=version+1,updated_at=now() where id=$1 and version=$2 and status='IN_PROGRESS' and processed_qty+$3::numeric<=dispatched_qty returning *`, [runId, expected, processed, good, scrap, target]); if (!saved.rows[0]) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "工序报工发生并发冲突", 409); await client.query("insert into production_operation_run_events(run_id,report_id,event_type,from_status,to_status,processed_qty,good_qty,scrap_qty,actor,request_id) values($1,$2,'REPORTED','IN_PROGRESS',$3,$4,$5,$6,$7,$8)", [runId, Number(savedReport.rows[0].id), target, processed, good, scrap, meta.actor.username, meta.requestId]); await this.fault?.("after_operation_report_facts"); await refreshOperationProjections(client, Number(run.work_order_id)); return { status: 201, body: { ok: true, data: { report: savedReport.rows[0], run: saved.rows[0] }, request_id: meta.requestId }, objectId: Number(savedReport.rows[0].id) }; });
  }

  async cancel(runId: number, meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> { const expected = version(input.expected_version), reason = text(input.reason, "取消原因", 1000, true); return this.repository.execute(meta, async (client) => { const run = await this.lockRun(client, runId, expected); if (run.status !== "READY") throw new ProductionError("OPERATION_RUN_CANNOT_CANCEL", "只有尚未开工且无报工的派工可以取消", 409); const saved = await client.query("update production_operation_runs set status='CANCELLED',cancelled_by=$3,cancelled_at=now(),cancellation_reason=$4,version=version+1,updated_at=now() where id=$1 and version=$2 and status='READY' returning *", [runId, expected, meta.actor.username, reason]); if (!saved.rows[0]) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "派工取消发生并发冲突", 409); await client.query("insert into production_operation_run_events(run_id,event_type,from_status,to_status,reason,actor,request_id) values($1,'CANCELLED','READY','CANCELLED',$2,$3,$4)", [runId, reason, meta.actor.username, meta.requestId]); await refreshOperationProjections(client, Number(run.work_order_id)); return { status: 200, body: { ok: true, data: saved.rows[0], request_id: meta.requestId }, objectId: runId }; }); }

  async reverse(runId: number, meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> { const expected = version(input.expected_version), reason = text(input.reason, "冲销原因", 1000, true); return this.repository.execute(meta, async (client) => { const run = await this.lockRun(client, runId, expected); if (!["IN_PROGRESS", "COMPLETED"].includes(run.status) || Number(run.processed_qty) <= 0) throw new ProductionError("OPERATION_RUN_NOT_REVERSIBLE", "只有已有报工且未冲销的批次可以冲销", 409); const consumed = await client.query(`select 1 from production_operation_run_input_allocations a join production_operation_runs target on target.id=a.run_id where a.source_run_id=$1 and target.status not in ('CANCELLED','REVERSED') limit 1`, [runId]); if (consumed.rows[0]) throw new ProductionError("OPERATION_RUN_DOWNSTREAM_CONSUMED", "该批次良品已被下一工序消费，不能冲销", 409); if (run.next_snapshot_operation_id == null) { const downstream = await client.query(`select 1 from production_reports r left join production_report_reversals x on x.report_id=r.id where r.work_order_id=$1 and x.id is null limit 1`, [Number(run.work_order_id)]); if (downstream.rows[0]) throw new ProductionError("OPERATION_RUN_DOWNSTREAM_CONSUMED", "末工序输出已被最终报工消费，不能冲销", 409); }
      const quality = await client.query(`select 1 from quality_inspections q join production_operation_run_reports rr on rr.id=q.production_operation_run_report_id where rr.run_id=$1 union all select 1 from quality_inspections q join production_reports r on r.id=q.production_report_id where r.work_order_id=$2 limit 1`, [runId, Number(run.work_order_id)]); if (quality.rows[0]) throw new ProductionError("OPERATION_RUN_QUALITY_REFERENCE_EXISTS", "工序来源已有品质下游引用，不能冲销", 409);
      const code = await this.repository.nextCode(client, "PRODUCTION_OPERATION_REVERSAL", "ORV"), reversal = await client.query("insert into production_operation_run_reversals(reversal_code,run_id,processed_qty,good_qty,scrap_qty,reason,operation_id,reversed_by,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *", [code, runId, run.processed_qty, run.good_qty, run.scrap_qty, reason, meta.operationId, meta.actor.username, meta.requestId]); const saved = await client.query("update production_operation_runs set status='REVERSED',version=version+1,updated_at=now() where id=$1 and version=$2 and status in ('IN_PROGRESS','COMPLETED') returning *", [runId, expected]); if (!saved.rows[0]) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "工序批次并发冲销冲突", 409); await client.query("insert into production_operation_run_events(run_id,reversal_id,event_type,from_status,to_status,processed_qty,good_qty,scrap_qty,reason,actor,request_id) values($1,$2,'REVERSED',$3,'REVERSED',$4,$5,$6,$7,$8,$9)", [runId, Number(reversal.rows[0].id), run.status, run.processed_qty, run.good_qty, run.scrap_qty, reason, meta.actor.username, meta.requestId]); await this.fault?.("after_operation_reversal_facts"); await refreshOperationProjections(client, Number(run.work_order_id)); return { status: 201, body: { ok: true, data: { reversal: reversal.rows[0], run: saved.rows[0] }, request_id: meta.requestId }, objectId: Number(reversal.rows[0].id) }; }); }

  async initialize(client: PoolClient, workOrderId: number) { await initializeOperationProjections(client, workOrderId); }
}
