import { createHash, randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { ProductionError } from "../production-selfhost/errors.ts";
import { ProductionRepository } from "../production-selfhost/repository.ts";
import type { ProductionMeta, ProductionResult } from "../production-selfhost/types.ts";
import { refreshReworkExecution } from "../production-rework-execution-selfhost/projections.ts";
import { initializeOperationProjections, refreshOperationProjections } from "./projections.ts";

const id = (value: unknown, field: string) => { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed <= 0) throw new ProductionError("REQUEST_VALIDATION_FAILED", `${field} 必须为正整数`); return parsed; };
const version = (value: unknown, field = "expected_version") => id(value, field);
const quantity = (value: unknown, field: string, allowZero = false) => { const raw = String(value ?? "").trim(); if (!/^(?:0|[1-9]\d{0,17})(?:\.\d{1,6})?$/.test(raw) || (!allowZero && Number(raw) <= 0)) throw new ProductionError("REQUEST_VALIDATION_FAILED", `${field} 必须为${allowZero ? "非负" : "正"}数且最多 6 位小数`); return raw; };
const text = (value: unknown, field: string, maximum: number, required = false) => { const result = String(value ?? "").trim().normalize("NFKC"); if ((required && !result) || result.length > maximum || /[\u0000-\u001f\u007f]/.test(result)) throw new ProductionError("REQUEST_VALIDATION_FAILED", `${field} 无效`); return result; };
const timestamp = (value: unknown, field: string) => { if (value == null || value === "") return null; const parsed = new Date(String(value)); if (Number.isNaN(parsed.valueOf())) throw new ProductionError("REQUEST_VALIDATION_FAILED", `${field} 不是有效时间`); return parsed.toISOString(); };
const digest = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");

export class ProductionOperationService {
  readonly repository: ProductionRepository;
  readonly fault?: (checkpoint: string) => void | Promise<void>;
  constructor(repository: ProductionRepository, fault?: (checkpoint: string) => void | Promise<void>) { this.repository = repository; this.fault = fault; }

  async operators() { return this.repository.pool.query("select username,display_name,role,version from app_users where is_active and role in ('production','manager','admin') order by display_name,username"); }
  async operations(workOrderId?: number) { const values: unknown[] = []; const where = workOrderId ? (values.push(workOrderId), "where p.work_order_id=$1") : ""; return this.repository.pool.query(`select p.*,wo.work_order_code,wo.status work_order_status,op.sequence_no,op.operation_code,op.operation_name,op.work_center_id,op.work_center_code,op.work_center_name,op.quality_gate_mode,w.source_input_qty::text,w.waiting_input_qty::text,w.dispatched_qty::text,w.in_progress_qty::text,w.completed_good_qty::text,w.scrap_qty::text,w.transferred_to_next_qty::text,w.available_for_next_qty::text,w.final_output_available_qty::text,w.quality_required_qty::text,w.quality_inspected_qty::text,w.quality_released_qty::text,w.quality_hold_qty::text,w.version wip_version from production_work_order_operation_projections p join production_work_orders wo on wo.id=p.work_order_id join production_work_order_routing_snapshot_operations op on op.id=p.snapshot_operation_id join production_operation_wip_projections w on w.operation_projection_id=p.id ${where} order by wo.created_at desc,wo.id desc,op.sequence_no`, values); }
  async runs(workOrderId?: number) { const values: unknown[] = []; const where = workOrderId ? (values.push(workOrderId), "where r.work_order_id=$1") : ""; return this.repository.pool.query(`select r.*,b.batch_code,wo.work_order_code,op.sequence_no,op.operation_code,op.operation_name,op.work_center_code,op.quality_gate_mode,u.display_name assigned_operator_name,w.quality_required_qty::text,w.quality_inspected_qty::text,w.quality_released_qty::text,w.quality_hold_qty::text,w.available_for_next_qty::text,w.final_output_available_qty::text from production_operation_runs r left join production_batches b on b.id=r.production_batch_id join production_work_orders wo on wo.id=r.work_order_id join production_work_order_routing_snapshot_operations op on op.id=r.snapshot_operation_id join production_work_order_operation_projections p on p.snapshot_operation_id=op.id join production_operation_wip_projections w on w.operation_projection_id=p.id join app_users u on u.username=r.assigned_operator ${where} order by r.created_at desc,r.id desc`, values); }
  async wip(workOrderId?: number) { return this.operations(workOrderId); }
  async reworkExecutions() { return this.repository.pool.query(`select p.*,r.request_code,r.revision_no,r.canonical_digest,r.target_snapshot_operation_id,r.target_sequence_no,r.target_operation_code,r.target_operation_name,r.target_work_center_code,n.ncr_code,n.failed_qty original_failed_qty,n.status ncr_status,wo.work_order_code
    from production_rework_execution_projections p join production_rework_requests r on r.id=p.rework_request_id join production_nonconformances n on n.id=p.nonconformance_id join production_work_orders wo on wo.id=n.work_order_id order by p.updated_at desc,p.id desc`); }
  async reinspectionSources() { return this.repository.pool.query(`select rr.id operation_run_report_id,rr.report_code,rr.good_qty::text remaining_qty,run.id run_id,run.run_code,run.rework_request_id,r.request_code,r.revision_no,n.id nonconformance_id,n.ncr_code,n.failed_qty original_failed_qty,run.work_order_id,wo.work_order_code,run.snapshot_operation_id,op.sequence_no,op.operation_code,op.operation_name,op.work_center_code,p.status execution_status,p.rework_pending_reinspection_qty::text
    from production_operation_run_reports rr join production_operation_runs run on run.id=rr.run_id and run.run_kind='REWORK' and run.status not in ('CANCELLED','REVERSED') join production_rework_requests r on r.id=run.rework_request_id join production_nonconformances n on n.id=run.nonconformance_id join production_work_orders wo on wo.id=run.work_order_id join production_work_order_routing_snapshot_operations op on op.id=run.snapshot_operation_id join production_rework_execution_projections p on p.rework_request_id=r.id left join lateral(select coalesce(sum(q.inspected_qty),0) inspected from quality_inspections q where q.production_operation_run_report_id=rr.id) used on true where rr.good_qty>coalesce(used.inspected,0) order by rr.reported_at,rr.id`); }

  private async lockProjection(client: PoolClient, snapshotOperationId: number, expectedVersion?: number) {
    const result = await client.query(`select p.*,wo.status work_order_status,wo.planned_qty,op.sequence_no,op.operation_code,op.operation_name,op.work_center_id,op.work_center_code,op.work_center_name,op.quality_gate_mode,w.waiting_input_qty,w.available_for_next_qty,w.quality_hold_qty,w.version wip_version from production_work_order_operation_projections p join production_work_orders wo on wo.id=p.work_order_id join production_work_order_routing_snapshot_operations op on op.id=p.snapshot_operation_id join production_operation_wip_projections w on w.operation_projection_id=p.id where p.snapshot_operation_id=$1 for update of p,w,wo`, [snapshotOperationId]);
    const row = result.rows[0]; if (!row) throw new ProductionError("SNAPSHOT_OPERATION_NOT_FOUND", "工单快照工序不存在", 404); if (expectedVersion != null && Number(row.version) !== expectedVersion) throw new ProductionError("OPERATION_VERSION_CONFLICT", "工序投影版本已变化，请刷新后重试", 409); return row;
  }
  private async lockRun(client: PoolClient, runId: number, expectedVersion: number) { const result = await client.query("select r.*,p.next_snapshot_operation_id,p.version operation_version from production_operation_runs r join production_work_order_operation_projections p on p.snapshot_operation_id=r.snapshot_operation_id where r.id=$1 for update of r,p", [runId]); const row = result.rows[0]; if (!row) throw new ProductionError("OPERATION_RUN_NOT_FOUND", "工序派工批次不存在", 404); if (Number(row.version) !== expectedVersion) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "派工批次版本已变化，请刷新后重试", 409); return row; }
  private enforceAssignee(meta: ProductionMeta, run: Record<string, unknown>) { if (meta.actor.role === "production" && run.assigned_operator !== meta.actor.username) throw new ProductionError("OPERATION_RUN_OPERATOR_FORBIDDEN", "生产人员只能执行分配给自己的批次", 403); }

  async dispatch(meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> {
    const snapshotOperationId = id(input.snapshot_operation_id, "snapshot_operation_id"), productionBatchId = input.production_batch_id == null || input.production_batch_id === "" ? null : id(input.production_batch_id, "production_batch_id"), dispatchedQty = quantity(input.quantity, "quantity"), assignedOperator = text(input.assigned_operator, "assigned_operator", 32, true), expected = version(input.expected_operation_version, "expected_operation_version"), plannedStart = timestamp(input.planned_start, "planned_start"), plannedEnd = timestamp(input.planned_end, "planned_end");
    if (plannedStart && plannedEnd && plannedEnd < plannedStart) throw new ProductionError("REQUEST_VALIDATION_FAILED", "planned_end 不得早于 planned_start");
    return this.repository.execute(meta, async (client) => {
      const projection = await this.lockProjection(client, snapshotOperationId, expected);
      if (!["RELEASED", "IN_PROGRESS"].includes(projection.work_order_status)) throw new ProductionError("WORK_ORDER_STATE_CONFLICT", "工单必须处于 RELEASED 或 IN_PROGRESS", 409);
      if (!['READY','IN_PROGRESS'].includes(projection.status)) throw new ProductionError("OPERATION_NOT_READY", "工序前置投入不足，不能派工", 409);
      const available = await client.query("select $1::numeric<=$2::numeric ok", [dispatchedQty, projection.waiting_input_qty]); if (!available.rows[0].ok) throw new ProductionError("OPERATION_DISPATCH_OVER_AVAILABLE", "派工数量超过当前可用投入", 409);
      const batchMode = await client.query("select s.id batch_set_id,b.id batch_id,b.planned_qty from production_batch_sets s left join production_batches b on b.batch_set_id=s.id and b.id=$2 where s.work_order_id=$1 and s.status='RELEASED' for share of s", [Number(projection.work_order_id), productionBatchId]);
      if (batchMode.rows[0] && !batchMode.rows[0].batch_id) throw new ProductionError("PRODUCTION_BATCH_REQUIRED", "批次模式工单必须提交属于该工单的生产批次", 409);
      if (!batchMode.rows[0] && productionBatchId) throw new ProductionError("PRODUCTION_BATCH_MODE_CONFLICT", "ORDER 模式工单不能提交生产批次", 409);
      const operator = await client.query("select username,role from app_users where username=$1 and is_active for share", [assignedOperator]); if (!operator.rows[0] || !['production','manager','admin'].includes(operator.rows[0].role)) throw new ProductionError("OPERATION_OPERATOR_INELIGIBLE", "指派人员未启用或不具备生产执行能力", 422);
      const runCode = await this.repository.nextCode(client, "PRODUCTION_OPERATION_RUN", "POR"), sourceDigest = digest({ snapshot_operation_id: snapshotOperationId, production_batch_id: productionBatchId, work_center_id: Number(projection.work_center_id), work_center_code: projection.work_center_code, work_center_name: projection.work_center_name, assigned_operator: assignedOperator, dispatched_qty: dispatchedQty, planned_start: plannedStart, planned_end: plannedEnd });
      const saved = await client.query(`insert into production_operation_runs(run_code,work_order_id,production_batch_id,snapshot_operation_id,work_center_id,work_center_code,work_center_name,assigned_operator,dispatched_qty,planned_start,planned_end,source_digest,operation_id,created_by,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) returning *`, [runCode, Number(projection.work_order_id), productionBatchId, snapshotOperationId, Number(projection.work_center_id), projection.work_center_code, projection.work_center_name, assignedOperator, dispatchedQty, plannedStart, plannedEnd, sourceDigest, meta.operationId, meta.actor.username, meta.requestId]);
      const runId = Number(saved.rows[0].id);
      if (projection.previous_snapshot_operation_id != null) {
        const sources = await client.query("select * from public.cyd_web_lock_operation_upstream_sources($1,$2)", [Number(projection.previous_snapshot_operation_id), productionBatchId]);
        let remaining = Number(dispatchedQty); for (const source of sources.rows) { if (remaining <= 0) break; const allocated = Math.min(remaining, Number(source.available)).toFixed(6); await client.query("insert into production_operation_run_input_allocations(run_id,source_run_id,quantity,operation_id,created_by,request_id) values($1,$2,$3,$4,$5,$6)", [runId, Number(source.id), allocated, randomUUID(), meta.actor.username, meta.requestId]); remaining = Number((remaining - Number(allocated)).toFixed(6)); }
        if (remaining > 0) throw new ProductionError("OPERATION_UPSTREAM_ALLOCATION_CONFLICT", "前序工序良品已被并发消费", 409);
      }
      await client.query("insert into production_operation_run_events(run_id,event_type,to_status,actor,request_id) values($1,'DISPATCHED','READY',$2,$3)", [runId, meta.actor.username, meta.requestId]);
      await this.fault?.("after_operation_dispatch_facts"); await refreshOperationProjections(client, Number(projection.work_order_id));
      return { status: 201, body: { ok: true, data: saved.rows[0], request_id: meta.requestId }, objectId: runId };
    });
  }

  async dispatchRework(reworkRequestId:number,meta:ProductionMeta,input:Record<string,unknown>):Promise<ProductionResult>{
    if(input.production_batch_id!==undefined)throw new ProductionError("SERVER_MANAGED_FIELD_FORBIDDEN","返工生产批次由原 NCR 稳定来源继承，浏览器不得选择或覆盖",422);
    const dispatchedQty=quantity(input.quantity,"quantity"),assignedOperator=text(input.assigned_operator,"assigned_operator",32,true),expected=version(input.expected_execution_version,"expected_execution_version"),plannedStart=timestamp(input.planned_start,"planned_start"),plannedEnd=timestamp(input.planned_end,"planned_end");if(plannedStart&&plannedEnd&&plannedEnd<plannedStart)throw new ProductionError("REQUEST_VALIDATION_FAILED","planned_end 不得早于 planned_start");
    return this.repository.execute(meta,async(client)=>{const found=await client.query(`select p.version execution_version,p.rework_waiting_dispatch_qty,r.*,v.id request_version_id,n.inspection_id,n.production_operation_run_report_id source_report_id,n.work_order_id,n.status ncr_status,a.status ncr_allocation_status,op.work_center_id,op.work_center_code,op.work_center_name,wo.status work_order_status from production_rework_execution_projections p join production_rework_requests r on r.id=p.rework_request_id join production_rework_request_versions v on v.rework_request_id=r.id and v.canonical_digest=r.canonical_digest and v.target_snapshot_operation_id=r.target_snapshot_operation_id and v.quantity=r.quantity join production_nonconformances n on n.id=r.nonconformance_id join production_nonconformance_allocations a on a.rework_request_id=r.id and a.nonconformance_id=n.id and a.allocation_type='REWORK' join production_work_order_routing_snapshot_operations op on op.id=r.target_snapshot_operation_id join production_work_order_routing_snapshots s on s.id=op.snapshot_id and s.work_order_id=n.work_order_id join production_work_orders wo on wo.id=n.work_order_id where r.id=$1 for update of p,r,n,a`,[reworkRequestId]);const row=found.rows[0];if(!row)throw new ProductionError("REWORK_REQUEST_NOT_FOUND","返工申请不存在或提交快照无效",404);if(row.status!=="ACCEPTED"||row.ncr_allocation_status!=="ACTIVE"||["CANCELLED","RESOLVED"].includes(row.ncr_status))throw new ProductionError("REWORK_REQUEST_NOT_EXECUTABLE","只有存在有效分配的已接收返工申请可以派工",409);if(Number(row.execution_version)!==expected)throw new ProductionError("REWORK_EXECUTION_VERSION_CONFLICT","返工执行投影版本已变化，请刷新后重试",409);if(!["RELEASED","IN_PROGRESS"].includes(row.work_order_status))throw new ProductionError("WORK_ORDER_STATE_CONFLICT","返工工单必须处于 RELEASED 或 IN_PROGRESS",409);if(!(await client.query("select $1::numeric<=$2::numeric ok",[dispatchedQty,row.rework_waiting_dispatch_qty])).rows[0].ok)throw new ProductionError("REWORK_DISPATCH_OVER_ACCEPTED","返工派工数量超过已接收可派余额",409);const operator=await client.query("select username,role from app_users where username=$1 and is_active for share",[assignedOperator]);if(!operator.rows[0]||!["production","manager","admin"].includes(operator.rows[0].role))throw new ProductionError("OPERATION_OPERATOR_INELIGIBLE","指派人员未启用或不具备生产执行能力",422);
      const sourceBatch=(await client.query("select run.production_batch_id from production_operation_run_reports rr join production_operation_runs run on run.id=rr.run_id where rr.id=$1",[row.source_report_id])).rows[0]?.production_batch_id??null;const runCode=await this.repository.nextCode(client,"PRODUCTION_OPERATION_RUN","POR"),sourceDigest=digest({run_kind:"REWORK",rework_request_id:reworkRequestId,production_batch_id:sourceBatch,canonical_digest:row.canonical_digest,target_snapshot_operation_id:Number(row.target_snapshot_operation_id),assigned_operator:assignedOperator,dispatched_qty:dispatchedQty,planned_start:plannedStart,planned_end:plannedEnd});const saved=await client.query(`insert into production_operation_runs(run_code,run_kind,rework_request_id,nonconformance_id,source_inspection_id,source_operation_run_report_id,work_order_id,production_batch_id,snapshot_operation_id,work_center_id,work_center_code,work_center_name,assigned_operator,dispatched_qty,planned_start,planned_end,source_digest,operation_id,created_by,request_id) values($1,'REWORK',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) returning *`,[runCode,reworkRequestId,row.nonconformance_id,row.inspection_id,row.source_report_id,row.work_order_id,sourceBatch,row.target_snapshot_operation_id,row.work_center_id,row.work_center_code,row.work_center_name,assignedOperator,dispatchedQty,plannedStart,plannedEnd,sourceDigest,meta.operationId,meta.actor.username,meta.requestId]);const runId=Number(saved.rows[0].id);await client.query(`insert into production_rework_run_allocations(rework_request_id,rework_request_version_id,nonconformance_id,run_id,quantity,operation_id,created_by,request_id) values($1,$2,$3,$4,$5,$6,$7,$8)`,[reworkRequestId,row.request_version_id,row.nonconformance_id,runId,dispatchedQty,meta.operationId,meta.actor.username,meta.requestId]);await client.query("insert into production_operation_run_events(run_id,event_type,to_status,actor,request_id) values($1,'DISPATCHED','READY',$2,$3)",[runId,meta.actor.username,meta.requestId]);await this.fault?.("after_rework_dispatch_facts");await refreshOperationProjections(client,Number(row.work_order_id));const execution=await refreshReworkExecution(client,reworkRequestId,meta.actor.username,meta.requestId,"DISPATCHED",runId,dispatchedQty);return{status:201,body:{ok:true,data:saved.rows[0],execution,request_id:meta.requestId},objectId:runId};});
  }

  async start(runId: number, meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> { const expected = version(input.expected_version); return this.repository.execute(meta, async (client) => { const run = await this.lockRun(client, runId, expected); this.enforceAssignee(meta, run); if (run.status !== "READY") throw new ProductionError("OPERATION_RUN_STATE_CONFLICT", "只有有效 READY 派工可以开工", 409); const saved = await client.query("update production_operation_runs set status='IN_PROGRESS',started_by=$3,started_at=now(),version=version+1,updated_at=now() where id=$1 and version=$2 and status='READY' returning *", [runId, expected, meta.actor.username]); if (!saved.rows[0]) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "派工批次已被并发开工", 409); await client.query("insert into production_operation_run_events(run_id,event_type,from_status,to_status,actor,request_id) values($1,'STARTED','READY','IN_PROGRESS',$2,$3)", [runId, meta.actor.username, meta.requestId]); await this.fault?.("after_operation_started"); await refreshOperationProjections(client, Number(run.work_order_id)); await refreshReworkExecution(client,run.rework_request_id?Number(run.rework_request_id):null,meta.actor.username,meta.requestId,"STARTED",runId,run.dispatched_qty); return { status: 200, body: { ok: true, data: saved.rows[0], request_id: meta.requestId }, objectId: runId }; }); }

  async report(runId: number, meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> {
    const expected = version(input.expected_version), processed = quantity(input.processed_qty, "processed_qty"), good = quantity(input.good_qty, "good_qty", true), scrap = quantity(input.scrap_qty, "scrap_qty", true), remark = text(input.remark, "remark", 1000);
    if (Number((Number(good) + Number(scrap)).toFixed(6)) !== Number(processed)) throw new ProductionError("OPERATION_QUANTITY_NOT_CONSERVED", "good_qty + scrap_qty 必须等于 processed_qty", 422);
    return this.repository.execute(meta, async (client) => { const run = await this.lockRun(client, runId, expected); this.enforceAssignee(meta, run); if (run.status !== "IN_PROGRESS") throw new ProductionError("OPERATION_RUN_STATE_CONFLICT", "只有已开工批次可以工序报工", 409); const allowed = await client.query("select $1::numeric+$2::numeric<=$3::numeric ok", [run.processed_qty, processed, run.dispatched_qty]); if (!allowed.rows[0].ok) throw new ProductionError("OPERATION_REPORT_OVER_DISPATCHED", "累计处理数量超过派工数量", 409); const reportCode = await this.repository.nextCode(client, "PRODUCTION_OPERATION_REPORT", "OPR"), savedReport = await client.query("insert into production_operation_run_reports(report_code,run_id,snapshot_operation_id,processed_qty,good_qty,scrap_qty,remark,operation_id,reported_by,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *", [reportCode, runId, Number(run.snapshot_operation_id), processed, good, scrap, remark, meta.operationId, meta.actor.username, meta.requestId]); const final = await client.query("select ($1::numeric+$2::numeric=$3::numeric) completed", [run.processed_qty, processed, run.dispatched_qty]), target = final.rows[0].completed ? "COMPLETED" : "IN_PROGRESS"; const saved = await client.query(`update production_operation_runs set processed_qty=processed_qty+$3::numeric,good_qty=good_qty+$4::numeric,scrap_qty=scrap_qty+$5::numeric,status=$6,version=version+1,updated_at=now() where id=$1 and version=$2 and status='IN_PROGRESS' and processed_qty+$3::numeric<=dispatched_qty returning *`, [runId, expected, processed, good, scrap, target]); if (!saved.rows[0]) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "工序报工发生并发冲突", 409); await client.query("insert into production_operation_run_events(run_id,report_id,event_type,from_status,to_status,processed_qty,good_qty,scrap_qty,actor,request_id) values($1,$2,'REPORTED','IN_PROGRESS',$3,$4,$5,$6,$7,$8)", [runId, Number(savedReport.rows[0].id), target, processed, good, scrap, meta.actor.username, meta.requestId]); await this.fault?.("after_operation_report_facts"); await refreshOperationProjections(client, Number(run.work_order_id)); await refreshReworkExecution(client,run.rework_request_id?Number(run.rework_request_id):null,meta.actor.username,meta.requestId,"REPORTED",runId,processed); return { status: 201, body: { ok: true, data: { report: savedReport.rows[0], run: saved.rows[0] }, request_id: meta.requestId }, objectId: Number(savedReport.rows[0].id) }; });
  }

  async cancel(runId: number, meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> { const expected = version(input.expected_version), reason = text(input.reason, "取消原因", 1000, true); return this.repository.execute(meta, async (client) => { const run = await this.lockRun(client, runId, expected); if (run.status !== "READY") throw new ProductionError("OPERATION_RUN_CANNOT_CANCEL", "只有尚未开工且无报工的派工可以取消", 409); const saved = await client.query("update production_operation_runs set status='CANCELLED',cancelled_by=$3,cancelled_at=now(),cancellation_reason=$4,version=version+1,updated_at=now() where id=$1 and version=$2 and status='READY' returning *", [runId, expected, meta.actor.username, reason]); if (!saved.rows[0]) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "派工取消发生并发冲突", 409); await client.query("insert into production_operation_run_events(run_id,event_type,from_status,to_status,reason,actor,request_id) values($1,'CANCELLED','READY','CANCELLED',$2,$3,$4)", [runId, reason, meta.actor.username, meta.requestId]); if(run.rework_request_id)await client.query("update production_rework_run_allocations set status='RELEASED',released_by=$2,released_request_id=$3,released_at=now(),updated_at=now() where run_id=$1 and status='ACTIVE'",[runId,meta.actor.username,meta.requestId]); await refreshOperationProjections(client, Number(run.work_order_id)); await refreshReworkExecution(client,run.rework_request_id?Number(run.rework_request_id):null,meta.actor.username,meta.requestId,"CANCELLED",runId,run.dispatched_qty); return { status: 200, body: { ok: true, data: saved.rows[0], request_id: meta.requestId }, objectId: runId }; }); }

  async reverse(runId: number, meta: ProductionMeta, input: Record<string, unknown>): Promise<ProductionResult> { const expected = version(input.expected_version), reason = text(input.reason, "冲销原因", 1000, true); return this.repository.execute(meta, async (client) => { const run = await this.lockRun(client, runId, expected); if (!["IN_PROGRESS", "COMPLETED"].includes(run.status) || Number(run.processed_qty) <= 0) throw new ProductionError("OPERATION_RUN_NOT_REVERSIBLE", "只有已有报工且未冲销的批次可以冲销", 409); const consumed = await client.query(`select 1 from production_operation_run_input_allocations a join production_operation_runs target on target.id=a.run_id where a.source_run_id=$1 and target.status not in ('CANCELLED','REVERSED') limit 1`, [runId]); if (consumed.rows[0]) throw new ProductionError("OPERATION_RUN_DOWNSTREAM_CONSUMED", "该批次良品已被下一工序消费，不能冲销", 409); if (run.next_snapshot_operation_id == null) { const downstream = await client.query(`select 1 from production_reports r left join production_report_reversals x on x.report_id=r.id where r.work_order_id=$1 and x.id is null limit 1`, [Number(run.work_order_id)]); if (downstream.rows[0]) throw new ProductionError("OPERATION_RUN_DOWNSTREAM_CONSUMED", "末工序输出已被最终报工消费，不能冲销", 409); }
      const quality = await client.query(`select 1 from quality_inspections q join production_operation_run_reports rr on rr.id=q.production_operation_run_report_id where rr.run_id=$1 union all select 1 from quality_inspections q join production_reports r on r.id=q.production_report_id where r.work_order_id=$2 limit 1`, [runId, Number(run.work_order_id)]); if (quality.rows[0]) throw new ProductionError("OPERATION_RUN_QUALITY_REFERENCE_EXISTS", "工序来源已有品质下游引用，不能冲销", 409);
      const code = await this.repository.nextCode(client, "PRODUCTION_OPERATION_REVERSAL", "ORV"), reversal = await client.query("insert into production_operation_run_reversals(reversal_code,run_id,processed_qty,good_qty,scrap_qty,reason,operation_id,reversed_by,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *", [code, runId, run.processed_qty, run.good_qty, run.scrap_qty, reason, meta.operationId, meta.actor.username, meta.requestId]); const saved = await client.query("update production_operation_runs set status='REVERSED',version=version+1,updated_at=now() where id=$1 and version=$2 and status in ('IN_PROGRESS','COMPLETED') returning *", [runId, expected]); if (!saved.rows[0]) throw new ProductionError("OPERATION_RUN_VERSION_CONFLICT", "工序批次并发冲销冲突", 409); await client.query("insert into production_operation_run_events(run_id,reversal_id,event_type,from_status,to_status,processed_qty,good_qty,scrap_qty,reason,actor,request_id) values($1,$2,'REVERSED',$3,'REVERSED',$4,$5,$6,$7,$8,$9)", [runId, Number(reversal.rows[0].id), run.status, run.processed_qty, run.good_qty, run.scrap_qty, reason, meta.actor.username, meta.requestId]); if(run.rework_request_id)await client.query("update production_rework_run_allocations set status='RELEASED',released_by=$2,released_request_id=$3,released_at=now(),updated_at=now() where run_id=$1 and status='ACTIVE'",[runId,meta.actor.username,meta.requestId]); await this.fault?.("after_operation_reversal_facts"); await refreshOperationProjections(client, Number(run.work_order_id)); await refreshReworkExecution(client,run.rework_request_id?Number(run.rework_request_id):null,meta.actor.username,meta.requestId,"REVERSED",runId,run.processed_qty); return { status: 201, body: { ok: true, data: { reversal: reversal.rows[0], run: saved.rows[0] }, request_id: meta.requestId }, objectId: Number(reversal.rows[0].id) }; }); }

  async initialize(client: PoolClient, workOrderId: number) { await initializeOperationProjections(client, workOrderId); }
}
