"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { api,ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";
type User={username:string;display_name:string;role:string;permissions:string[]};type Session={authenticated:boolean;user:User|null;csrf_token?:string};
type Queue={queue_id:number;id:number;version:number;po_code:string;po_status:string;purchase_order_line_id:number;purchase_order_line_version:number;supplier_code:string;supplier_name:string;internal_material_code:string;standard_name:string;unit_code:string;planned_quantity:string;received_quantity:string;remaining_quantity:string;promised_delivery_date:string;balance_version:number;on_hand_quantity:string;overdue:boolean};
const can=(u:User|null|undefined,p:string)=>Boolean(u&&(u.permissions.includes("*")||u.permissions.includes(p)));const msg=(e:unknown)=>e instanceof ErpApiError?`${e.message}${e.requestId?`（请求 ${e.requestId}）`:""}`:"系统暂时无法完成请求";
export function WarehouseReceivingWorkspace(){const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<Queue[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const load=useCallback(async()=>{try{const current=await api<Session>("/api/session");setSession(current);if(current.authenticated&&can(current.user,"procurement.fulfillment.read"))setRows((await api<{data:Queue[]}>("/api/procurement/fulfillment/receiving-queue?page_size=100")).data)}catch(e){setError(msg(e))}},[]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function receive(event:FormEvent<HTMLFormElement>,row:Queue){event.preventDefault();if(!session)return;const form=new FormData(event.currentTarget);setBusy(true);setError("");try{await api(`/api/procurement/delivery-plans/${row.id}/receipts`,{method:"POST",body:JSON.stringify({quantity:String(form.get("quantity")||""),expected_version:row.version,expected_line_version:row.purchase_order_line_version,expected_balance_version:row.balance_version,reason:String(form.get("reason")||"")}),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});setNotice("收货、PO/计划、库存、采购财务来源、事件和审计已在同一事务过账");await load()}catch(e){setError(msg(e))}finally{setBusy(false)}}
 if(!session)return <main className="sourcing-shell">正在读取会话…</main>;if(!session.authenticated)return <main className="sourcing-shell">请先登录。</main>;if(!can(session.user,"procurement.fulfillment.read"))return <main className="sourcing-shell"><div className="sourcing-state sourcing-error">没有待入库读取权限。</div></main>;
 return <main className="sourcing-shell"><div className="sourcing-banner">仓库收货为过账动作 · 支持分批，禁止超收；已过账记录只能按规则全额冲销</div><header className="sourcing-header"><div><Link href="/" className="sourcing-back">← 经营工作台</Link><p className="sourcing-kicker">WAREHOUSE RECEIVING</p><h1>待入库与分批收货</h1><p>从关系化到货计划发起收货，服务端校验数量、版本、余额与权限。</p></div><div><b>{session.user!.display_name||session.user!.username}</b><span>{session.user!.role}</span></div></header><section className="sourcing-panel"><h2>待入库队列</h2>{rows.map(row=><article className="sourcing-card" key={row.id}><div><b>{row.po_code} · {row.internal_material_code}</b><span className={`sourcing-status status-${row.overdue?"late":"pending"}`}>{row.overdue?"逾期":"待到货"}</span></div><p>{row.supplier_code} · {row.supplier_name} · {row.standard_name}</p><small>计划 {row.planned_quantity} · 已收 {row.received_quantity} · 未收 {row.remaining_quantity} {row.unit_code} · 当前库存 {row.on_hand_quantity} · 承诺 {String(row.promised_delivery_date).slice(0,10)}</small>{can(session.user,"procurement.receiving.receive")?<form className="sourcing-form" onSubmit={e=>receive(e,row)}><label>本次收货数量<input name="quantity" required defaultValue={row.remaining_quantity}/></label><label>收货说明<input name="reason" required defaultValue="仓库按到货计划收货" maxLength={1000}/></label><button disabled={busy}>确认过账收货</button></form>:null}</article>)}{!rows.length?<div className="sourcing-state">当前没有待入库计划。</div>:null}</section>{notice?<div className="sourcing-state">{notice}</div>:null}{error?<div className="sourcing-state sourcing-error">{error}</div>:null}</main>}
