"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};
type WorkOrder={id:number;work_order_code:string;status:string;version:number;planned_qty:string};
type Batch={id:number;batch_code:string;planned_qty:string;version:number};
type BatchSet={id:number;batch_set_code:string;work_order_id:number;work_order_code:string;status:string;version:number;canonical_digest:string|null;work_order_planned_qty:string;batch_total:string;batch_count:number;batches:Batch[]|null};
type ProjectedBatch=Batch&{batch_status:string;processed_qty:string;good_qty:string;scrap_qty:string;released_qty:string;completed_qty:string;rework_qty:string;quality_hold_qty:string;work_order_code:string;canonical_digest:string};
const can=(session:Session|null,permission:string)=>Boolean(session?.user&&(session.user.permissions.includes("*")||session.user.permissions.includes(permission)));
const key=()=>crypto.randomUUID();

export default function ProductionBatchesPage(){
 const[session,setSession]=useState<Session|null>(null),[orders,setOrders]=useState<WorkOrder[]>([]),[sets,setSets]=useState<BatchSet[]>([]),[batches,setBatches]=useState<ProjectedBatch[]>([]),[error,setError]=useState("");
 async function load(){const current=await api<Session>("/api/session");setSession(current);if(!current.authenticated)return;const[work,setRows,batchRows]=await Promise.all([api<{data:WorkOrder[]}>("/api/work-orders?page_size=100"),api<{rows:BatchSet[]}>("/api/production/batch-sets"),api<{rows:ProjectedBatch[]}>("/api/production/batches")]);setOrders(work.data);setSets(setRows.rows);setBatches(batchRows.rows);}
 useEffect(()=>{void load().catch(cause=>setError(cause instanceof ErpApiError?cause.message:"读取失败"));},[]);
 async function write(path:string,method:"POST"|"PATCH",body:Record<string,unknown>){if(!session?.csrf_token)return;setError("");try{await api(path,{method,body:JSON.stringify(body),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:key()}});await load();}catch(cause){setError(cause instanceof ErpApiError?`${cause.message} (${cause.code})`:"操作失败");}}
 async function createSet(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),workOrderId=Number(form.get("work_order_id")),wo=orders.find(row=>row.id===workOrderId);if(wo)await write("/api/production/batch-sets","POST",{work_order_id:wo.id,expected_work_order_version:wo.version});}
 async function addBatch(event:FormEvent<HTMLFormElement>,set:BatchSet){event.preventDefault();const form=new FormData(event.currentTarget);await write(`/api/production/batch-sets/${set.id}/batches`,"POST",{planned_qty:String(form.get("planned_qty")),expected_batch_set_version:set.version});}
 async function updateBatch(event:FormEvent<HTMLFormElement>,set:BatchSet,batch:Batch){event.preventDefault();const form=new FormData(event.currentTarget);await write(`/api/production/batches/${batch.id}`,"PATCH",{planned_qty:String(form.get("planned_qty")),expected_version:batch.version,expected_batch_set_version:set.version});}
 return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/">← 经营工作台</Link><h1>Manufacturing Batch 与全过程谱系</h1><p><strong>生产批次谱系已建立，但仓库批次库存尚未启用。</strong> Batch code 是生产身份，不是 Inventory Lot；成品 Ledger 仍使用 MAIN 与空 lot_code。</p><nav><Link href="/production/dispatch">按 Batch 派工</Link> · <Link href="/production/wip">Batch WIP</Link> · <Link href="/warehouse/production-completions">Batch Completion</Link></nav></div></header>
 {error?<div className="sourcing-state sourcing-error">{error}</div>:null}
 {can(session,"production.batch.manage")?<section className="sourcing-panel"><h2>建立 DRAFT Batch Set</h2><form className="sourcing-form" onSubmit={createSet}><label>已释放工单<select name="work_order_id" required>{orders.filter(row=>["RELEASED","IN_PROGRESS"].includes(row.status)&&!sets.some(set=>set.work_order_id===row.id)).map(row=><option key={row.id} value={row.id}>{row.work_order_code} · planned {row.planned_qty}</option>)}</select></label><button>创建 Batch Set</button></form></section>:null}
 <section className="sourcing-panel"><h2>Batch Sets</h2>{sets.map(set=><article className="sourcing-card" key={set.id}><b>{set.batch_set_code} · {set.work_order_code} · {set.status}</b><small>Set #{set.id} · v{set.version} · Batch {set.batch_count} · 合计 {set.batch_total}/{set.work_order_planned_qty}</small>{set.canonical_digest?<p>digest <code>{set.canonical_digest}</code></p>:null}{(set.batches??[]).map(batch=>set.status==="DRAFT"&&can(session,"production.batch.manage")?<form className="sourcing-form" key={batch.id} onSubmit={event=>void updateBatch(event,set,batch)}><b>{batch.batch_code}</b><label>planned quantity<input name="planned_qty" type="number" min="0.000001" step="0.000001" defaultValue={batch.planned_qty} required/></label><button>CAS 保存</button><button type="button" onClick={()=>void write(`/api/production/batches/${batch.id}/delete`,"POST",{expected_version:batch.version,expected_batch_set_version:set.version})}>删除 DRAFT Batch</button></form>:<p key={batch.id}>{batch.batch_code} · planned {batch.planned_qty}</p>)}{!(set.batches??[]).length?<p>尚无 Batch</p>:null}{set.status==="DRAFT"&&can(session,"production.batch.manage")?<><form className="sourcing-form" onSubmit={event=>void addBatch(event,set)}><label>Batch planned quantity<input name="planned_qty" type="number" min="0.000001" step="0.000001" required/></label><button>服务端生成 Batch code</button></form><button onClick={()=>void write(`/api/production/batch-sets/${set.id}/release`,"POST",{expected_version:set.version})}>RELEASE 并固化 digest</button></>:null}</article>)}</section>
 <section className="sourcing-panel"><h2>Batch 状态投影</h2>{batches.map(batch=><article className="sourcing-card" key={batch.id}><b>{batch.batch_code} · {batch.work_order_code} · {batch.batch_status}</b><small>planned {batch.planned_qty} · processed {batch.processed_qty} · good {batch.good_qty} · scrap {batch.scrap_qty} · released {batch.released_qty} · completed {batch.completed_qty}</small><p>NORMAL/REWORK 加工次数分别沿 Run 事实追踪；rework {batch.rework_qty} · Quality Hold {batch.quality_hold_qty}</p><nav><Link href={`/production/batches?batch=${batch.id}`}>详情</Link> · <a href={`/api/production/batches/${batch.id}/wip`}>WIP JSON</a> · <a href={`/api/production/batches/${batch.id}/genealogy`}>genealogy JSON</a></nav></article>)}</section>
 </main>;
}
