import { createHash, randomUUID } from "node:crypto";
import type { Pool } from "pg";
import type { IdentityActor } from "../identity-selfhost/types.ts";
import { ProductionError, mapProductionError } from "../production-selfhost/errors.ts";
import { ProductionRepository } from "../production-selfhost/repository.ts";
import { ProductionRoutingService } from "./service.ts";

type Dependencies = Readonly<{ pool: Pool; actor: IdentityActor; requestId: string; requireCsrf: () => void }>;
const can = (actor: IdentityActor, permission: string) => actor.permissions.includes("*") || actor.permissions.includes(permission);
const need = (actor: IdentityActor, permission: string) => { if (!can(actor, permission)) throw new ProductionError("PERMISSION_DENIED", "没有权限执行此操作", 403); };
const response = (body: unknown, status: number, requestId: string, replay = false) => { const headers = new Headers({"Cache-Control":"no-store","X-Request-ID":requestId}); if (replay) headers.set("Idempotency-Replayed","true"); return Response.json(body,{status,headers}); };
const stable = (value: unknown): unknown => Array.isArray(value) ? value.map(stable) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b]) => a.localeCompare(b)).map(([key,item]) => [key,stable(item)])) : value;
async function body(request: Request) { const raw = await request.text(); if (!raw || Buffer.byteLength(raw) > 256 * 1024) throw new ProductionError("REQUEST_VALIDATION_FAILED", "请求正文为空或超过 256 KiB"); let value: unknown; try { value = JSON.parse(raw); } catch { throw new ProductionError("REQUEST_VALIDATION_FAILED", "请求正文不是有效 JSON"); } if (!value || typeof value !== "object" || Array.isArray(value)) throw new ProductionError("REQUEST_VALIDATION_FAILED", "请求正文必须是对象"); const forbidden = ["canonical_digest","routing_digest","created_by","updated_by","submitted_by","released_by","request_id","actor","version","current_version_no"].find((key) => key in (value as Record<string,unknown>)); if (forbidden) throw new ProductionError("SERVER_MANAGED_FIELD_FORBIDDEN", `${forbidden} 由服务端维护`, 422); return { value: value as Record<string,unknown>, digest: createHash("sha256").update(JSON.stringify(stable(value))).digest("hex") }; }
function meta(request: Request, deps: Dependencies, action: string, digest: string) { const key = request.headers.get("idempotency-key") || ""; if (key.length < 8 || key.length > 200) throw new ProductionError("IDEMPOTENCY_KEY_REQUIRED", "写操作必须提供有效 Idempotency-Key"); const route = new URL(request.url).pathname; return { actor: deps.actor, requestId: deps.requestId, operationId: randomUUID(), keyDigest: createHash("sha256").update(`${deps.actor.username}:${request.method}:${route}:${key}`).digest("hex"), requestDigest: digest, method: request.method, route, action }; }

export async function handleProductionRoutingApi(request: Request, deps: Dependencies): Promise<Response|null> {
  const url = new URL(request.url), path = url.pathname, wcStatus = path.match(/^\/api\/production\/work-centers\/([1-9]\d*)\/status$/), routingDetail = path.match(/^\/api\/production\/routing-versions\/([1-9]\d*)$/), operations = path.match(/^\/api\/production\/routing-versions\/([1-9]\d*)\/operations$/), transition = path.match(/^\/api\/production\/routing-versions\/([1-9]\d*)\/(submit|release|return)$/), revise = path.match(/^\/api\/production\/routings\/([1-9]\d*)\/versions$/), woSnapshot = path.match(/^\/api\/work-orders\/([1-9]\d*)\/routing-snapshot$/);
  if (!["/api/production/work-centers","/api/production/routings","/api/production/dispatch"].includes(path) && !wcStatus && !routingDetail && !operations && !transition && !revise && !woSnapshot) return null;
  const repository = new ProductionRepository(deps.pool), service = new ProductionRoutingService(repository); let action = "PRODUCTION_ROUTING_REQUEST";
  try {
    if (request.method === "GET") { if (path === "/api/production/work-centers") { need(deps.actor,"production.work_center.read"); const result = await service.listWorkCenters(); return response({rows:result.rows,data:result.rows,request_id:deps.requestId},200,deps.requestId); } if (path === "/api/production/routings") { need(deps.actor,"production.routing.read"); const result = await service.listRoutings(url.searchParams.get("status") || undefined); return response({rows:result.rows,data:result.rows,request_id:deps.requestId},200,deps.requestId); } if (routingDetail) { need(deps.actor,"production.routing.read"); return response({data:await service.detail(Number(routingDetail[1])),request_id:deps.requestId},200,deps.requestId); } if (woSnapshot) { need(deps.actor,"production.routing.snapshot.read"); return response({data:await service.workOrderSnapshot(Number(woSnapshot[1])),request_id:deps.requestId},200,deps.requestId); } if (path === "/api/production/dispatch") { need(deps.actor,"production.routing.snapshot.read"); const result = await service.dispatch(); return response({rows:result.rows,data:result.rows,request_id:deps.requestId},200,deps.requestId); } throw new ProductionError("METHOD_NOT_ALLOWED","接口不支持该请求方法",405); }
    if (!["POST","PATCH"].includes(request.method)) throw new ProductionError("METHOD_NOT_ALLOWED","接口不支持该请求方法",405); deps.requireCsrf(); const parsed = await body(request); let result;
    if (path === "/api/production/work-centers" && request.method === "POST") { action="WORK_CENTER_CREATED"; need(deps.actor,"production.work_center.manage"); result=await service.createWorkCenter(meta(request,deps,action,parsed.digest),parsed.value); }
    else if (wcStatus) { action="WORK_CENTER_STATUS_CHANGED"; need(deps.actor,"production.work_center.manage"); result=await service.setWorkCenterStatus(Number(wcStatus[1]),meta(request,deps,action,parsed.digest),parsed.value); }
    else if (path === "/api/production/routings" && request.method === "POST") { action="ROUTING_CREATED"; need(deps.actor,"production.routing.manage"); result=await service.createRouting(meta(request,deps,action,parsed.digest),parsed.value); }
    else if (revise) { action="ROUTING_REVISED"; need(deps.actor,"production.routing.manage"); result=await service.revise(Number(revise[1]),meta(request,deps,action,parsed.digest),parsed.value); }
    else if (operations && request.method === "PATCH") { action="ROUTING_OPERATIONS_REPLACED"; need(deps.actor,"production.routing.manage"); result=await service.replaceOperations(Number(operations[1]),meta(request,deps,action,parsed.digest),parsed.value); }
    else if (transition) { action=`ROUTING_${transition[2].toUpperCase()}`; need(deps.actor,transition[2]==="submit"?"production.routing.manage":"production.routing.review"); result=await service.transition(Number(transition[1]),transition[2] as 'submit'|'release'|'return',meta(request,deps,action,parsed.digest),parsed.value); }
    else throw new ProductionError("NOT_FOUND","接口不存在",404);
    return response(result.body,result.status,deps.requestId,result.replayed);
  } catch (error) { const mapped=mapProductionError(error); await repository.failureAudit(deps.actor.username,deps.requestId,action,mapped.code); return response({error:{code:mapped.code,message:mapped.message,details:mapped.details,request_id:deps.requestId},code:mapped.code,message:mapped.message,details:mapped.details,request_id:deps.requestId},mapped.status,deps.requestId); }
}
