import { createHash, randomUUID } from "node:crypto";
import type { Pool } from "pg";
import type { IdentityActor } from "../identity-selfhost/types.ts";
import { FinanceError, mapFinanceError } from "./errors.ts";
import { documentType, id } from "./rules.ts";
import { FinanceRepository } from "./repository.ts";
import { FINANCE_BOUNDARY, FinanceService } from "./service.ts";

type Dependencies = Readonly<{ pool: Pool; actor: IdentityActor; requestId: string; requireCsrf: () => void }>;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const allowed = (actor: IdentityActor, permission: string) => actor.permissions.includes("*") || actor.permissions.includes(permission);
const requirePermission = (actor: IdentityActor, permission: string) => { if (!allowed(actor, permission)) throw new FinanceError("PERMISSION_DENIED", "没有权限执行此操作", 403); };
const response = (body: unknown, status: number, requestId: string, replayed = false) => { const headers = new Headers({ "Cache-Control": "no-store", "X-Request-ID": requestId }); if (replayed) headers.set("Idempotency-Replayed", "true"); return Response.json(body, { status, headers }); };
const stable = (value: unknown): unknown => Array.isArray(value) ? value.map(stable) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, child]) => [key, stable(child)])) : value;
const pageValue = (value: string | null, field: string, fallback: number, maximum: number) => { if (!value) return fallback; const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 1 || parsed > maximum) throw new FinanceError("REQUEST_VALIDATION_FAILED", `${field} 必须是正整数`); return parsed; };
async function readBody(request: Request) { const raw = await request.text(); if (!raw || Buffer.byteLength(raw) > 256 * 1024) throw new FinanceError("REQUEST_VALIDATION_FAILED", "请求正文为空或超过 256 KiB"); let value: unknown; try { value = JSON.parse(raw); } catch { throw new FinanceError("REQUEST_VALIDATION_FAILED", "请求正文不是有效 JSON"); } if (!value || typeof value !== "object" || Array.isArray(value)) throw new FinanceError("REQUEST_VALIDATION_FAILED", "请求正文必须是对象"); const forbidden = ["username", "role", "permissions", "created_by", "createdBy", "handled_by", "request_id", "operation_id", "doc_code", "payment_code", "settlement_code", "status", "doc_status", "settled_amount", "paid_amount", "balance_amount", "total_amount", "currency_code", "customer_id", "supplier_id", "sales_order_id", "po_id", "purchase_order_id", "source_type", "source_id", "payment_type"].find((key) => key in (value as Record<string, unknown>)); if (forbidden) throw new FinanceError("REQUEST_VALIDATION_FAILED", `请求正文不能指定服务端字段：${forbidden}`); return { value: value as Record<string, unknown>, digest: createHash("sha256").update(JSON.stringify(stable(value))).digest("hex") }; }
function mutationMeta(request: Request, dependencies: Dependencies, route: string, action: string, requestDigest: string) { const key = request.headers.get("Idempotency-Key") || ""; if (key.length < 8 || key.length > 200) throw new FinanceError("IDEMPOTENCY_KEY_REQUIRED", "写操作必须提供有效 Idempotency-Key"); return { actor: dependencies.actor, requestId: dependencies.requestId, operationId: randomUUID(), keyDigest: createHash("sha256").update(`${dependencies.actor.username}:${request.method}:${route}:${key}`).digest("hex"), requestDigest, method: request.method, route, action }; }

export async function handleFinanceApi(request: Request, dependencies: Dependencies): Promise<Response | null> {
  const url = new URL(request.url); const path = url.pathname; const document = path.match(/^\/api\/financial-documents\/([1-9]\d*)$/); const documentSettlement = path.match(/^\/api\/financial-documents\/([1-9]\d*)\/settlements$/); const reversal = path.match(/^\/api\/(?:financial-payments|finance-settlements)\/([1-9]\d*)\/reversal$/); const fixed = ["/api/finance-summary", "/api/financial-documents", "/api/financial-payments", "/api/finance/source-options", "/api/finance/documents", "/api/finance/settlements", "/api/financial-documents/from-source", "/api/financial-documents/from-sales-order", "/api/financial-documents/from-purchase-order"];
  if (!fixed.includes(path) && !document && !documentSettlement && !reversal) return null;
  const repository = new FinanceRepository(dependencies.pool); const service = new FinanceService(repository); let action = "FINANCE_REQUEST";
  try {
    if (request.method === "GET") {
      requirePermission(dependencies.actor, "finance.read");
      if (document) return response({ data: await service.get(dependencies.actor, Number(document[1])), boundary: FINANCE_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId);
      if (path === "/api/finance-summary") return response({ ...(await service.summary(dependencies.actor)), boundary: FINANCE_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId);
      if (path === "/api/finance/source-options") { requirePermission(dependencies.actor, "finance.post"); const found = await service.sourceOptions(dependencies.actor, url.searchParams.get("document_type") || url.searchParams.get("doc_type") || "", pageValue(url.searchParams.get("limit"), "limit", 100, 100)); return response({ rows: found.rows, data: found.rows, boundary: FINANCE_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId); }
      const page = pageValue(url.searchParams.get("page"), "page", 1, 1_000_000); const size = pageValue(url.searchParams.get("page_size"), "page_size", 50, 100); const offset = (page - 1) * size;
      if (path === "/api/financial-payments" || path === "/api/finance/settlements") { const rows = await service.listSettlements(dependencies.actor, size, offset, url.searchParams.get("doc_id") ? id(url.searchParams.get("doc_id"), "doc_id") : undefined); return response({ rows, data: rows, pagination: { page, page_size: size }, boundary: FINANCE_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId); }
      const rows = await service.list(dependencies.actor, size, offset, url.searchParams.get("doc_type") || undefined, url.searchParams.get("status") || undefined); return response({ rows, data: rows, pagination: { page, page_size: size }, boundary: FINANCE_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId);
    }
    if (request.method !== "POST") throw new FinanceError("METHOD_NOT_ALLOWED", "接口不支持该请求方法", 405); dependencies.requireCsrf(); const parsed = await readBody(request); let result;
    if (["/api/finance/documents", "/api/financial-documents/from-source", "/api/financial-documents/from-sales-order", "/api/financial-documents/from-purchase-order"].includes(path)) { action = "FINANCE_DOCUMENT_POSTED"; requirePermission(dependencies.actor, "finance.post"); const fixedType = path.includes("sales-order") ? "AR" : path.includes("purchase-order") ? "AP" : documentType(parsed.value.doc_type ?? parsed.value.document_type); result = await service.create(mutationMeta(request, dependencies, path, action, parsed.digest), { ...parsed.value, doc_type: fixedType }); }
    else if (["/api/financial-payments", "/api/finance/settlements"].includes(path) || documentSettlement) { action = "FINANCE_SETTLEMENT_POSTED"; requirePermission(dependencies.actor, "finance.pay"); result = await service.settle(mutationMeta(request, dependencies, path, action, parsed.digest), { ...parsed.value, ...(documentSettlement ? { document_id: Number(documentSettlement[1]) } : {}) }); }
    else if (reversal) { action = "FINANCE_SETTLEMENT_REVERSED"; requirePermission(dependencies.actor, "finance.reverse"); result = await service.reverseSettlement(Number(reversal[1]), mutationMeta(request, dependencies, path, action, parsed.digest), parsed.value); }
    else throw new FinanceError("NOT_FOUND", "接口不存在", 404);
    return response(result.body, result.status, dependencies.requestId, result.replayed);
  } catch (error) { const known = mapFinanceError(error); if (UUID.test(dependencies.requestId)) await repository.failureAudit(dependencies.actor.username, dependencies.requestId, action, known.code); console.error(JSON.stringify({ level: "error", event: "finance_api_failed", request_id: dependencies.requestId, code: known.code })); return response({ error: { code: known.code, message: known.message, request_id: dependencies.requestId }, code: known.code, message: known.message, request_id: dependencies.requestId }, known.status, dependencies.requestId); }
}
