"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState, type ReactNode } from "react";
import { api, ErpApiError } from "../../public/erp/api-client.js";
import "./planning.css";

type User={username:string;display_name:string;role:string;permissions:string[]};type Session={authenticated:boolean;user:User|null;csrf_token?:string};
type PackageRow={id:number;project_code:string;project_name:string;customer_name:string;package_version_no:number;status:string;target_delivery_date?:string};
type PlanRow={id:number;plan_version_no:number;required_date:string;status:string;version:number;request_code?:string};
type PlanLine={id:number;unit_code:string;material_snapshot:Record<string,unknown>;gross_requirement:string;stock_available:string;eligible_inbound:string;stock_allocated:string;inbound_allocated:string;net_purchase_requirement:string};
type PlanDetail={header:PlanRow&{project_code:string;package_version_no:number;return_reason?:string};lines:PlanLine[];allocations:Array<{id:number;allocation_type:string;quantity:string;po_code?:string}>;events:Array<{id:number;event_type:string;actor:string;reason:string;created_at:string}>};
type RequestRow={id:number;request_code:string;status:string;version:number;project_code:string;project_name:string;plan_version_no:number;required_date:string;line_count:number;requested_quantity:string};
type RequestDetail={header:RequestRow;lines:Array<{id:number;unit_code:string;requested_quantity:string;material_snapshot:Record<string,unknown>}>};
const labels:Record<string,string>={DRAFT:"预览",STALE:"已失效",SUBMITTED:"待采购接收",ACCEPTED:"采购已接收",RETURNED:"采购已退回",STOCK:"库存",INBOUND:"在途",GENERATED:"已生成",REGENERATED:"已重新生成",PURCHASE_ACCEPTED:"采购接收",PURCHASE_RETURNED:"采购退回"};
const can=(user:User|null|undefined,permission:string)=>Boolean(user&&(user.permissions.includes("*")||user.permissions.includes(permission)));
const dateOnly=(value:string|undefined)=>value?value.slice(0,10):"";
const errorMessage=(reason:unknown)=>reason instanceof ErpApiError?`${reason.message}${reason.requestId?`（请求 ${reason.requestId}）`:""}`:"系统暂时无法完成请求";
function Status({value}:{value:string}){return <span className={`planning-status status-${value.toLowerCase()}`}>{labels[value]||value}</span>}
function State({children,error=false}:{children:ReactNode;error?:boolean}){return <div className={error?"planning-state planning-error":"planning-state"} role={error?"alert":undefined}>{children}</div>}
function Shell({title,subtitle,user,children}:{title:string;subtitle:string;user:User;children:ReactNode}){return <main className="planning-shell"><div className="planning-banner">并行验收环境 · 物料需求与采购申请交接；不询价、不选供应商、不创建采购订单或收货单</div><header className="planning-header"><div><Link href="/" className="planning-back">← 经营工作台</Link><p className="planning-kicker">PLANNING TO PURCHASE</p><h1>{title}</h1><p>{subtitle}</p></div><div className="planning-user"><b>{user.display_name||user.username}</b><span>{user.role}</span></div></header>{children}</main>}
async function mutation(session:Session,path:string,body:Record<string,unknown>){if(!session.csrf_token)throw new Error("missing csrf");return api(path,{method:"POST",body:JSON.stringify(body),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}})}

export function MaterialRequirementWorkspace(){
 const[session,setSession]=useState<Session|null>(null),[packages,setPackages]=useState<PackageRow[]>([]),[selected,setSelected]=useState<PackageRow|null>(null),[plans,setPlans]=useState<PlanRow[]>([]),[detail,setDetail]=useState<PlanDetail|null>(null);const[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const current=await api<Session>("/api/session");setSession(current);if(!current.authenticated||!can(current.user,"planning.requirement.read"))return;setPackages((await api<{data:PackageRow[]}>("/api/planning-handoffs?status=ACCEPTED&page_size=100")).data);if(selected)setPlans((await api<{data:PlanRow[]}>(`/api/planning-packages/${selected.id}/material-requirement-plans`)).data)}catch(reason){setError(errorMessage(reason))}},[selected]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function choosePackage(row:PackageRow){setSelected(row);setDetail(null);try{setPlans((await api<{data:PlanRow[]}>(`/api/planning-packages/${row.id}/material-requirement-plans`)).data)}catch(reason){setError(errorMessage(reason))}}
 async function choosePlan(id:number){try{setDetail((await api<{data:PlanDetail}>(`/api/material-requirement-plans/${id}`)).data)}catch(reason){setError(errorMessage(reason))}}
 async function write(path:string,body:Record<string,unknown>,message:string){if(!session)return;setBusy(true);setError("");try{const result=await mutation(session,path,body) as {plan_id?:number};setNotice(message);await load();if(result.plan_id)await choosePlan(result.plan_id)}catch(reason){setError(errorMessage(reason))}finally{setBusy(false)}}
 function generate(event:FormEvent<HTMLFormElement>){event.preventDefault();if(selected)void write(`/api/planning-packages/${selected.id}/material-requirement-plans`,{required_date:String(new FormData(event.currentTarget).get("required_date")||"")},"已重新核算并保存 DRAFT 预览")}
 if(!session)return <State>{error||"正在读取会话…"}</State>;if(!session.authenticated)return <State>请先登录。</State>;if(!can(session.user,"planning.requirement.read"))return <State error>没有权限读取物料需求计划。</State>;
 return <Shell title="物料需求计划工作台" subtitle="从最新已接收交接包汇总固化物料；提交时服务端加锁重算。" user={session.user!}><div className="planning-grid"><aside className="planning-panel"><div className="planning-title"><h2>已接收交接包</h2><span className="planning-count">{packages.length}</span></div><div className="planning-list">{packages.map(row=><button className={`planning-row ${selected?.id===row.id?"active":""}`} key={row.id} onClick={()=>void choosePackage(row)}><b>{row.project_code} · 包 v{row.package_version_no}</b><Status value={row.status}/><strong>{row.project_name}</strong></button>)}</div>{selected?<><h2 className="planning-section-title">计划版本</h2><div className="planning-list">{plans.map(row=><button className="planning-row" key={row.id} onClick={()=>void choosePlan(row.id)}><b>需求计划 v{row.plan_version_no}</b><Status value={row.status}/><strong>{dateOnly(row.required_date)} · {row.request_code||"无采购申请"}</strong></button>)}</div></>:null}</aside><section className="planning-panel">{selected&&can(session.user,"planning.requirement.prepare")&&!plans.some(row=>["SUBMITTED","ACCEPTED"].includes(row.status))?<form className="planning-card planning-form" onSubmit={generate}><label>需求日期<input type="date" name="required_date" defaultValue={dateOnly(selected.target_delivery_date)} required/></label><button disabled={busy}>{plans[0]?.status==="RETURNED"?"创建修订版并重新核算":"生成物料需求预览"}</button><small>DRAFT 不占用库存或在途；再次生成会使旧预览失效。</small></form>:null}{detail?<PlanView detail={detail}/>:<State>选择交接包后生成预览，或查看历史计划。</State>}{detail?.header.status==="DRAFT"&&can(session.user,"planning.requirement.submit")?<div className="planning-actions"><button disabled={busy} onClick={()=>void write(`/api/material-requirement-plans/${detail.header.id}/submit`,{expected_version:detail.header.version},"提交成功：分配与采购申请已原子固化")}>加锁重算并提交采购部</button></div>:null}{notice?<State>{notice}</State>:null}{error?<State error>{error}</State>:null}</section></div></Shell>
}
function PlanView({detail}:{detail:PlanDetail}){return <><div className="planning-title"><h2>{detail.header.project_code} · 需求计划 v{detail.header.plan_version_no}</h2><Status value={detail.header.status}/></div>{detail.header.return_reason?<div className="planning-return"><b>采购退回原因</b><p>{detail.header.return_reason}</p></div>:null}<dl className="planning-facts"><div><dt>需求日期</dt><dd>{dateOnly(detail.header.required_date)}</dd></div><div><dt>来源交接包</dt><dd>v{detail.header.package_version_no}</dd></div><div><dt>采购申请</dt><dd>{detail.header.request_code||"净需求为 0，不生成"}</dd></div></dl><table className="planning-lines"><thead><tr><th>固化物料 / 单位</th><th>毛需求</th><th>库存可用 / 分配</th><th>在途可用 / 分配</th><th>净采购</th></tr></thead><tbody>{detail.lines.map(line=>{const snap=line.material_snapshot||{};return <tr key={line.id}><td><b>{String(snap.internal_material_code||"")} · {String(snap.standard_name||"")}</b><br/>{line.unit_code}</td><td>{line.gross_requirement}</td><td>{line.stock_available} / {line.stock_allocated}</td><td>{line.eligible_inbound} / {line.inbound_allocated}</td><td><b>{line.net_purchase_requirement}</b></td></tr>})}</tbody></table><div className="planning-card"><h3>Planning Allocation</h3>{detail.allocations.length?detail.allocations.map(row=><p key={row.id}><Status value={row.allocation_type}/> {row.quantity}{row.po_code?` · ${row.po_code}`:" · MAIN 库存"}</p>):<p>预览阶段不创建分配；提交后也不会修改正式 reserved_qty。</p>}</div><div className="planning-card"><h3>不可变事件</h3>{detail.events.map(event=><div key={event.id}><Status value={event.event_type}/> <b>{event.actor}</b> · {new Date(event.created_at).toLocaleString("zh-CN")}{event.reason?<p>{event.reason}</p>:null}</div>)}</div></>}

export function PurchaseRequestWorkspace(){
 const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<RequestRow[]>([]),[detail,setDetail]=useState<RequestDetail|null>(null);const[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const current=await api<Session>("/api/session");setSession(current);if(current.authenticated&&can(current.user,"planning.purchase_request.read"))setRows((await api<{data:RequestRow[]}>("/api/purchase-requests?status=SUBMITTED&page_size=100")).data)}catch(reason){setError(errorMessage(reason))}},[]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function choose(id:number){try{setDetail((await api<{data:RequestDetail}>(`/api/purchase-requests/${id}`)).data)}catch(reason){setError(errorMessage(reason))}}
 async function decide(kind:"accept"|"return",reason=""){if(!session||!detail)return;setBusy(true);setError("");try{await mutation(session,`/api/purchase-requests/${detail.header.id}/${kind}`,{expected_version:detail.header.version,...(kind==="return"?{reason}:{})});setNotice(kind==="accept"?"已接收；未创建询价、报价或采购订单":"已退回；该版本 Planning Allocation 已释放");setDetail(null);await load()}catch(cause){setError(errorMessage(cause))}finally{setBusy(false)}}
 function returnRequest(event:FormEvent<HTMLFormElement>){event.preventDefault();void decide("return",String(new FormData(event.currentTarget).get("reason")||""))}
 if(!session)return <State>{error||"正在读取会话…"}</State>;if(!session.authenticated)return <State>请先登录。</State>;if(!can(session.user,"planning.purchase_request.read"))return <State error>没有权限读取采购申请。</State>;
 return <Shell title="采购申请接收工作台" subtitle="只接收或退回净采购申请，不进入询价、供应商、采购订单或收货。" user={session.user!}><div className="planning-grid"><aside className="planning-panel"><div className="planning-title"><h2>待接收申请</h2><span className="planning-count">{rows.length}</span></div><div className="planning-list">{rows.map(row=><button className="planning-row" key={row.id} onClick={()=>void choose(row.id)}><b>{row.request_code}</b><Status value={row.status}/><strong>{row.project_code} · {row.line_count} 行 · {row.requested_quantity}</strong></button>)}</div></aside><section className="planning-panel">{detail?<><div className="planning-title"><h2>{detail.header.request_code} · {detail.header.project_name}</h2><Status value={detail.header.status}/></div><dl className="planning-facts"><div><dt>项目</dt><dd>{detail.header.project_code}</dd></div><div><dt>计划版本</dt><dd>v{detail.header.plan_version_no}</dd></div><div><dt>需求日期</dt><dd>{dateOnly(detail.header.required_date)}</dd></div></dl><table className="planning-lines"><thead><tr><th>固化物料</th><th>单位</th><th>申请数量</th></tr></thead><tbody>{detail.lines.map(line=>{const snap=line.material_snapshot||{};return <tr key={line.id}><td><b>{String(snap.internal_material_code||"")} · {String(snap.standard_name||"")}</b></td><td>{line.unit_code}</td><td>{line.requested_quantity}</td></tr>})}</tbody></table>{can(session.user,"planning.purchase_request.decide")?<div className="planning-actions"><button disabled={busy} onClick={()=>void decide("accept")}>接收采购申请</button><form className="planning-form" onSubmit={returnRequest}><label>退回原因<textarea name="reason" required maxLength={1000}/></label><button className="planning-danger" disabled={busy}>退回计划部</button></form></div>:null}</>:<State>选择申请查看不可变申请行。</State>}{notice?<State>{notice}</State>:null}{error?<State error>{error}</State>:null}</section></div></Shell>
}
