"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { api, ErpApiError } from "../../public/erp/api-client.js";
import "./planning.css";

type User={username:string;display_name:string;role:string;permissions:string[]};type Session={authenticated:boolean;user:User|null;csrf_token?:string};
type Candidate={product_id:number;product_code:string;product_name:string;product_version_id:number;product_version_code:string;bom_header_id:number;bom_code:string;bom_version_id:number;bom_version_code:string;bom_line_count:number};
type Resolution={requirement_item_id:number;line_no:number;provisional_name:string;quantity:string;unit_id:number|null;unit_pending:boolean;unit_code?:string;specification_requirement:string;product_version_id?:number;bom_version_id?:number};
type ResolutionData={project:{id:number;project_code:string;project_name:string;project_owner:string;version:number;requirement_version_id:number};rows:Resolution[];candidates:Candidate[]};
type PackageRow={id:number;project_id:number;project_code:string;project_name:string;customer_name:string;package_version_no:number;status:string;version:number;package_digest:string;item_count:number;return_reason?:string;submitted_at?:string;accepted_at?:string};
type BomLine={id:number;line_no:number;quantity_per:string;loss_rate:string;calculated_gross_quantity:string;unit_code:string;specification_snapshot:Record<string,unknown>;material_digest:string};
type PackageItem={id:number;line_no:number;provisional_name:string;required_quantity:string;unit_code:string;product_code:string;product_name:string;product_version_code:string;bom_code:string;bom_version_code:string;bom_lines:BomLine[]};
type PackageDetail={header:PackageRow&{project_goal:string;project_owner:string;customer_code:string;customer_name:string;customer_requirement_summary:string;prepared_by:string;submitted_by?:string;returned_by?:string;accepted_by?:string};items:PackageItem[];documents:Array<{id:number;document_type:string;display_name:string;original_filename:string;mime_type:string;sha256:string;size_bytes:string}>;events:Array<{id:number;event_type:string;actor:string;reason:string;request_id:string;created_at:string}>};
const labels:Record<string,string>={DRAFT:"草稿",SUBMITTED:"待计划部接收",RETURNED:"已退回",ACCEPTED:"已接收",RESUBMITTED:"重新提交"};
const errorMessage=(reason:unknown)=>reason instanceof ErpApiError?`${reason.message}${reason.requestId?`（请求 ${reason.requestId}）`:""}`:"系统暂时无法完成请求";
const can=(user:User|null|undefined,permission:string)=>Boolean(user&&(user.permissions.includes("*")||user.permissions.includes(permission)));
function Status({value}:{value:string}){return <span className={`planning-status status-${value.toLowerCase()}`}>{labels[value]||value}</span>}
function State({children,error=false}:{children:ReactNode;error?:boolean}){return <div className={error?"planning-state planning-error":"planning-state"} role={error?"alert":undefined}>{children}</div>}
function Shell({title,subtitle,user,children}:{title:string;subtitle:string;user:User;children:ReactNode}){return <main className="planning-shell"><div className="planning-banner">并行验收环境 · 只交接产品/BOM/零件规格，不计算缺料，不创建采购或生产单据</div><header className="planning-header"><div><Link href="/" className="planning-back">← 经营工作台</Link><p className="planning-kicker">PROJECT TO PLANNING</p><h1>{title}</h1><p>{subtitle}</p></div><div className="planning-user"><b>{user.display_name||user.username}</b><span>{user.role}</span></div></header>{children}</main>}
async function mutation(session:Session,path:string,body:Record<string,unknown>){if(!session.csrf_token)throw new Error("missing csrf");return api(path,{method:"POST",body:JSON.stringify(body),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}})}

export function EngineeringPlanningWorkspace({projectId}:{projectId:number}){
 const[session,setSession]=useState<Session|null>(null);const[data,setData]=useState<ResolutionData|null>(null);const[packages,setPackages]=useState<PackageRow[]>([]);const[detail,setDetail]=useState<PackageDetail|null>(null);const[choices,setChoices]=useState<Record<number,number>>({});const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[error,setError]=useState("");
 const detailId=detail?.header.id;const load=useCallback(async()=>{setError("");try{const current=await api<Session>("/api/session");setSession(current);if(!current.authenticated||!can(current.user,"planning.read"))return;const [resolutionResult,packageResult]=await Promise.all([api<{data:ResolutionData}>(`/api/projects/${projectId}/requirement-resolutions`),api<{data:PackageRow[]}>(`/api/projects/${projectId}/planning-packages`)]);setData(resolutionResult.data);setPackages(packageResult.data);const selected:Record<number,number>={};for(const row of resolutionResult.data.rows){if(row.bom_version_id)selected[row.requirement_item_id]=Number(row.bom_version_id)}setChoices(selected);if(detailId)setDetail((await api<{data:PackageDetail}>(`/api/planning-packages/${detailId}`)).data);}catch(reason){setError(errorMessage(reason));}},[projectId,detailId]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 const byBom=useMemo(()=>new Map((data?.candidates||[]).map(row=>[Number(row.bom_version_id),row])),[data?.candidates]);
 async function write(path:string,body:Record<string,unknown>,success:string){if(!session)return;setBusy(true);setError("");setNotice("");try{await mutation(session,path,body);setNotice(success);setDetail(null);await load();}catch(reason){setError(errorMessage(reason));}finally{setBusy(false)}}
 async function saveResolutions(){if(!data)return;const rows=data.rows.flatMap(row=>{const candidate=byBom.get(choices[row.requirement_item_id]);return candidate?[{requirement_item_id:row.requirement_item_id,product_id:candidate.product_id,product_version_id:candidate.product_version_id,bom_header_id:candidate.bom_header_id,bom_version_id:candidate.bom_version_id}]:[]});await write(`/api/projects/${projectId}/requirement-resolutions`,{expected_version:data.project.version,resolutions:rows},"需求明细解析已保存");}
 async function selectPackage(id:number){setError("");try{setDetail((await api<{data:PackageDetail}>(`/api/planning-packages/${id}`)).data);}catch(reason){setError(errorMessage(reason));}}
 if(!session)return <State error={Boolean(error)}>{error||"正在读取会话…"}</State>;if(!session.authenticated)return <State>请先从经营工作台登录。</State>;if(!can(session.user,"planning.prepare"))return <State error>此页面仅供项目负责人或获准管理人员使用。</State>;if(!data)return <State error={Boolean(error)}>{error||"正在读取项目与解析…"}</State>;
 const latest=packages[0];const canCreate=!latest||latest.status==="RETURNED";return <Shell title={`${data.project.project_code} · 计划交接`} subtitle="逐项锁定已发布 Product/BOM，预览零件规格快照并提交计划部门。" user={session.user!}><div className="planning-grid"><aside className="planning-panel"><div className="planning-title"><div><p className="planning-kicker">PACKAGE HISTORY</p><h2>交接包版本</h2></div><span className="planning-count">{packages.length}</span></div><div className="planning-list">{packages.length?packages.map(row=><button key={row.id} className={`planning-row ${detail?.header.id===row.id?"active":""}`} onClick={()=>void selectPackage(row.id)}><span><b>交接包 v{row.package_version_no}</b><small>{row.package_digest.slice(0,12)}…</small></span><Status value={row.status}/><strong>{row.item_count} 项需求</strong>{row.return_reason?<small>{row.return_reason}</small>:null}</button>):<State>尚未生成计划交接包。</State>}</div></aside><section className="planning-panel">{detail?<PackageView detail={detail}/>:<><div className="planning-title"><div><p className="planning-kicker">REQUIREMENT RESOLUTION</p><h2>需求明细解析</h2></div><span>{data.project.project_owner}</span></div>{data.rows.map(row=><div className="planning-card planning-resolution" key={row.requirement_item_id}><div><b>{row.line_no}. {row.provisional_name}</b><p>{row.quantity} {row.unit_pending?"单位待确认":row.unit_code}</p><small>{row.specification_requirement||"未填写规格要求"}</small></div><select aria-label={`需求 ${row.line_no} Product BOM`} value={choices[row.requirement_item_id]||""} onChange={event=>setChoices(value=>({...value,[row.requirement_item_id]:Number(event.target.value)}))}><option value="">请选择已发布 Product / BOM</option>{data.candidates.map(candidate=><option key={candidate.bom_version_id} value={candidate.bom_version_id}>{candidate.product_code} / {candidate.product_version_code} · {candidate.bom_code} / {candidate.bom_version_code} · {candidate.bom_line_count} 行</option>)}</select></div>)}<div className="planning-actions"><button disabled={busy||!data.rows.some(row=>choices[row.requirement_item_id])} onClick={()=>void saveResolutions()}>保存解析</button>{canCreate?<button disabled={busy} className="planning-secondary" onClick={()=>void write(`/api/projects/${projectId}/planning-packages`,{expected_version:data.project.version},"不可变交接包已生成")}>生成交接包 v{packages.length+1}</button>:null}</div></>}{detail?.header.status==="DRAFT"?<div className="planning-actions"><button disabled={busy} onClick={()=>void write(`/api/planning-packages/${detail.header.id}/submit`,{expected_version:detail.header.version},detail.header.package_version_no>1?"修订包已重新提交":"交接包已提交计划部")}>{detail.header.package_version_no>1?"重新提交计划部":"提交计划部"}</button></div>:null}{notice?<State>{notice}</State>:null}{error?<State error>{error}</State>:null}</section></div></Shell>;
}

export function PlanningHandoffWorkspace(){
 const[session,setSession]=useState<Session|null>(null);const[pending,setPending]=useState<PackageRow[]>([]);const[accepted,setAccepted]=useState<PackageRow[]>([]);const[detail,setDetail]=useState<PackageDetail|null>(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[error,setError]=useState("");
 const load=useCallback(async()=>{setError("");try{const current=await api<Session>("/api/session");setSession(current);if(!current.authenticated||!can(current.user,"planning.read"))return;const [queue,history]=await Promise.all([api<{data:PackageRow[]}>("/api/planning-handoffs?status=SUBMITTED&page_size=100"),api<{data:PackageRow[]}>("/api/planning-handoffs?status=ACCEPTED&page_size=100")]);setPending(queue.data);setAccepted(history.data);}catch(reason){setError(errorMessage(reason));}},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 async function choose(id:number){setError("");try{setDetail((await api<{data:PackageDetail}>(`/api/planning-packages/${id}`)).data);}catch(reason){setError(errorMessage(reason));}}
 async function decide(kind:"accept"|"return",reason=""){if(!session||!detail)return;setBusy(true);setError("");setNotice("");try{await mutation(session,`/api/planning-packages/${detail.header.id}/${kind}`,{expected_version:detail.header.version,...(kind==="return"?{reason}:{})});setNotice(kind==="accept"?"计划交接包已接收；未自动启动物料需求":"已退回项目部，旧包保持不可变");setDetail(null);await load();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false)}}
 function returnPackage(event:FormEvent<HTMLFormElement>){event.preventDefault();void decide("return",String(new FormData(event.currentTarget).get("reason")||""))}
 if(!session)return <State error={Boolean(error)}>{error||"正在读取会话…"}</State>;if(!session.authenticated)return <State>请先从经营工作台登录。</State>;if(!can(session.user,"planning.read"))return <State error>没有权限读取计划交接。</State>;
 return <Shell title="计划部门交接工作台" subtitle="只读核对项目、产品、BOM 与零件规格；接收或填写原因退回。" user={session.user!}><div className="planning-grid"><aside className="planning-panel"><div className="planning-title"><div><p className="planning-kicker">INBOX</p><h2>待接收交接包</h2></div><span className="planning-count">{pending.length}</span></div><div className="planning-list">{pending.length?pending.map(row=><button key={row.id} className="planning-row" onClick={()=>void choose(row.id)}><span><b>{row.project_code} · v{row.package_version_no}</b><small>{row.customer_name}</small></span><Status value="SUBMITTED"/><strong>{row.project_name}</strong></button>):<State>当前没有待接收交接包。</State>}</div><h2 className="planning-section-title">已接收历史</h2><div className="planning-list">{accepted.map(row=><button key={row.id} className="planning-row" onClick={()=>void choose(row.id)}><span><b>{row.project_code} · v{row.package_version_no}</b><small>{row.customer_name}</small></span><Status value="ACCEPTED"/><strong>{row.project_name}</strong></button>)}</div></aside><section className="planning-panel">{detail?<><PackageView detail={detail}/>{detail.header.status==="SUBMITTED"&&can(session.user,"planning.accept")?<div className="planning-actions"><button disabled={busy} onClick={()=>void decide("accept")}>接收交接包</button><form className="planning-form" onSubmit={returnPackage}><label>退回原因<textarea name="reason" required maxLength={1000} placeholder="说明需项目部修订的产品、BOM 或规格问题"/></label><button className="planning-danger" disabled={busy}>退回项目部</button></form></div>:null}</>:<State>从左侧选择交接包查看不可变快照。</State>}{notice?<State>{notice}</State>:null}{error?<State error>{error}</State>:null}</section></div></Shell>;
}

function PackageView({detail}:{detail:PackageDetail}){return <><div className="planning-title"><div><p className="planning-kicker">IMMUTABLE SNAPSHOT</p><h2>{detail.header.project_code} · 交接包 v{detail.header.package_version_no}</h2></div><Status value={detail.header.status}/></div>{detail.header.return_reason?<div className="planning-return"><b>计划部退回原因</b><p>{detail.header.return_reason}</p></div>:null}<dl className="planning-facts"><div><dt>客户</dt><dd>{detail.header.customer_code} · {detail.header.customer_name}</dd></div><div><dt>项目负责人</dt><dd>{detail.header.project_owner}</dd></div><div><dt>包摘要</dt><dd>{detail.header.package_digest.slice(0,16)}…</dd></div></dl><div className="planning-card"><h3>客户需求摘要</h3><p>{detail.header.customer_requirement_summary}</p></div>{detail.items.map(item=><article className="planning-card" key={item.id}><h3>{item.line_no}. {item.provisional_name}</h3><p>{item.product_code} / {item.product_version_code} · {item.bom_code} / {item.bom_version_code} · 需求 {item.required_quantity} {item.unit_code}</p><table className="planning-lines"><thead><tr><th>行</th><th>零件规格快照</th><th>单耗 / 损耗</th><th>毛需求</th></tr></thead><tbody>{item.bom_lines.map(line=>{const snap=line.specification_snapshot;return <tr key={line.id}><td>{line.line_no}</td><td><b>{String(snap.internal_material_code||"")} · {String(snap.standard_name||"")}</b><br/><code>{String(snap.manufacturer_part_number||snap.manufacturer||snap.brand||"无附加型号")}</code></td><td>{line.quantity_per} / {line.loss_rate}</td><td>{line.calculated_gross_quantity} {line.unit_code}</td></tr>})}</tbody></table></article>)}<div className="planning-card"><h3>受控项目资料</h3>{detail.documents.length?detail.documents.map(doc=><div className="planning-doc" key={doc.id}><b>{doc.document_type} · {doc.display_name}</b><span>{doc.original_filename} · {doc.mime_type} · {doc.size_bytes} bytes</span><small>SHA {doc.sha256.slice(0,16)}…</small></div>):<p>没有关联资料。</p>}</div><div className="planning-card"><h3>交接事件</h3><div className="planning-history">{detail.events.length?detail.events.map(event=><div key={event.id}><Status value={event.event_type}/> <b>{event.actor}</b> · {new Date(event.created_at).toLocaleString("zh-CN")}{event.reason?<p>{event.reason}</p>:null}</div>):<p>尚未提交计划部。</p>}</div></div></>}
