"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};
type RequestRow={id:number;request_code:string;ncr_code:string;work_order_code:string;revision_no:number;supersedes_request_id?:number;target_snapshot_operation_id:number;target_sequence_no:number;target_operation_code:string;target_operation_name:string;target_work_center_code:string;quantity:string;reason:string;status:string;version:number;canonical_digest?:string;return_reason:string};
const can=(session:Session|null,permission:string)=>Boolean(session?.user&&(session.user.permissions.includes("*")||session.user.permissions.includes(permission)));
export default function QualityReworkRequestsPage(){const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<RequestRow[]>([]),[error,setError]=useState("");async function load(){const current=await api<Session>("/api/session");setSession(current);if(current.authenticated&&can(current,"quality.rework_request.read"))setRows((await api<{data:RequestRow[]}>("/api/quality/rework-requests?page_size=100")).data);}useEffect(()=>{const timer=setTimeout(()=>void load().catch(c=>setError(c instanceof ErpApiError?c.message:"读取失败")),0);return()=>clearTimeout(timer);},[]);async function write(path:string,method:"POST"|"PATCH",body:Record<string,unknown>){if(!session?.csrf_token)return;try{await api(path,{method,body:JSON.stringify(body),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}});await load();}catch(c){setError(c instanceof ErpApiError?`${c.message} (${c.code})`:"操作失败");}}async function edit(event:FormEvent<HTMLFormElement>,row:RequestRow){event.preventDefault();const form=new FormData(event.currentTarget);await write(`/api/quality/rework-requests/${row.id}`,"PATCH",{expected_version:row.version,target_snapshot_operation_id:row.target_snapshot_operation_id,quantity:String(form.get("quantity")),reason:String(form.get("reason"))});}return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/quality/nonconformances">← NCR 队列</Link><h1>质量返工申请</h1><p>DRAFT 可 CAS 修改；SUBMITTED 固化 digest；RETURNED 必须从 NCR 页面基于旧请求创建新修订。</p></div></header>{error?<div className="sourcing-state sourcing-error">{error}</div>:null}<section className="sourcing-panel">{rows.map(row=><article className="sourcing-card" key={row.id}><div><b>{row.request_code} · {row.ncr_code} · v{row.revision_no}</b><span className="sourcing-status">{row.status} · CAS {row.version}</span></div><small>{row.work_order_code} · 目标 Snapshot Operation #{row.target_snapshot_operation_id} · {row.target_sequence_no} {row.target_operation_code} {row.target_operation_name} · Work Center {row.target_work_center_code}</small><p>数量 {row.quantity} · {row.reason}</p>{row.canonical_digest?<code>{row.canonical_digest}</code>:null}{row.return_reason?<p>退回原因：{row.return_reason}</p>:null}{row.status==="DRAFT"&&can(session,"quality.rework_request.create")?<form onSubmit={event=>void edit(event,row)}><label>数量<input name="quantity" defaultValue={row.quantity}/></label><label>原因<input name="reason" defaultValue={row.reason}/></label><button>CAS 保存</button><button type="button" onClick={()=>void write(`/api/quality/rework-requests/${row.id}/cancel`,"POST",{expected_version:row.version,reason:"质量取消未提交草稿"})}>取消 DRAFT</button>{can(session,"quality.rework_request.submit")?<button type="button" onClick={()=>void write(`/api/quality/rework-requests/${row.id}/submit`,"POST",{expected_version:row.version})}>提交并固化 digest</button>:null}</form>:null}</article>)}</section></main>}
