"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {api,ErpApiError} from "../../public/erp/api-client.js";

type User={username:string;display_name:string;role:string;role_label?:string;permissions:string[];must_change_password:boolean;version:number};type Session={authenticated:boolean;setup_required?:boolean;user:User|null;csrf_token?:string};
type Module={code:string;label:string;description:string;href:string;native:boolean};type Summary={generated_at:string;authority:string;consistency:string;groups:Record<string,Record<string,unknown>>;modules:Module[]};type Metric={code:string;label:string;value:string|number;hint:string;tone:string;href:string};type Event={domain:string;action:string;object_code:string;actor:string;request_id:string;created_at:string};type Audit={action:string;result:string;username:string;route_code:string;request_id:string;created_at:string;detail:string};type Management={summary:Summary;modules:Module[];metrics:Metric[];risks:Array<{code:string;level:string;text:string;href:string}>;recent_events:Event[];recent_activity:Audit[]};type Backup={verification_status:string;latest_verification:null|{verified_at:string}};type Loadable<T>={status:"idle"|"loading"|"ready"|"forbidden"|"error";data:T|null;message?:string};
const initial=<T,>():Loadable<T>=>({status:"idle",data:null});const explain=(e:unknown)=>e instanceof ErpApiError?`${e.message}${e.requestId?`（请求 ${e.requestId}）`:""}`:"系统暂时无法完成请求";const isForbidden=(e:unknown)=>e instanceof ErpApiError&&e.status===403;

export function ErpWorkbench(){
 const[session,setSession]=useState<Session|null>(null);const[authError,setAuthError]=useState("");const[busy,setBusy]=useState(false);const[summary,setSummary]=useState<Loadable<Summary>>(initial);const[management,setManagement]=useState<Loadable<Management>>(initial);const[backup,setBackup]=useState<Loadable<Backup>>(initial);
 const loadCard=useCallback(async<T,>(path:string,setter:(v:Loadable<T>)=>void)=>{setter({status:"loading",data:null});try{setter({status:"ready",data:await api<T>(path)});}catch(e){setter({status:isForbidden(e)?"forbidden":"error",data:null,message:explain(e)});}},[]);
 const loadWorkspace=useCallback(async(next:Session)=>{if(!next.authenticated||!next.user||next.user.must_change_password)return;void loadCard("/api/summary",setSummary);if(next.user.permissions.includes("dashboard.management.read")||next.user.permissions.includes("*"))void loadCard("/api/management-dashboard",setManagement);else setManagement({status:"forbidden",data:null});if(next.user.permissions.includes("system.backup.read")||next.user.permissions.includes("*"))void loadCard("/api/backup-governance",setBackup);else setBackup({status:"forbidden",data:null});},[loadCard]);
 const load=useCallback(async()=>{setAuthError("");try{const next=await api<Session>("/api/session");setSession(next);await loadWorkspace(next);}catch(e){setAuthError(explain(e));}},[loadWorkspace]);useEffect(()=>{let active=true;void api<Session>("/api/session").then(async next=>{if(!active)return;setSession(next);await loadWorkspace(next);}).catch(e=>{if(active)setAuthError(explain(e));});return()=>{active=false};},[loadWorkspace]);
 async function authenticate(path:"/api/login"|"/api/setup",body:Record<string,string>){setBusy(true);setAuthError("");try{const result=await api<{user:User;csrf_token:string}>(path,{method:"POST",body:JSON.stringify(body)});const next:Session={authenticated:true,user:result.user,csrf_token:result.csrf_token};setSession(next);await loadWorkspace(next);}catch(e){setAuthError(explain(e));}finally{setBusy(false);}}
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await authenticate("/api/login",{username:String(d.get("username")||""),password:String(d.get("password")||"")});}async function setup(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await authenticate("/api/setup",{setup_token:String(d.get("setup_token")||""),username:String(d.get("username")||""),display_name:String(d.get("display_name")||""),password:String(d.get("password")||"")});}
 async function changePassword(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session?.user||!session.csrf_token)return;const d=new FormData(e.currentTarget);setBusy(true);setAuthError("");try{await api("/api/me/password",{method:"POST",body:JSON.stringify({old_password:d.get("old_password"),new_password:d.get("new_password"),expected_version:session.user.version}),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}});await api("/api/logout",{method:"POST",body:"{}",protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}}).catch(()=>null);setSession(null);await load();}catch(reason){setAuthError(explain(reason));}finally{setBusy(false);}}
 async function logout(){if(session?.csrf_token)await api("/api/logout",{method:"POST",body:"{}",protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}}).catch(()=>null);setSession(null);setSummary(initial());setManagement(initial());setBackup(initial());await load();}
 if(!session)return <main className="wb-center"><section className="wb-auth"><p className="wb-eyebrow">CHENYIDA · SELF-HOSTED</p><h1>晨亿达 ERP</h1><p>{authError||"正在验证本机会话…"}</p>{authError?<button onClick={()=>void load()}>重新连接</button>:<span className="wb-loader"/>}</section></main>;
 if(!session.authenticated)return <main className="wb-center"><section className="wb-auth"><p className="wb-eyebrow">CHENYIDA · SELF-HOSTED</p><h1>{session.setup_required?"初始化管理员":"登录晨亿达 ERP"}</h1><p>Node.js / PostgreSQL 自托管非生产基线</p>{session.setup_required?<form onSubmit={setup}><label>初始化凭证<input name="setup_token" type="password" required/></label><label>管理员账号<input name="username" required/></label><label>显示名称<input name="display_name" required/></label><label>管理员密码<input name="password" type="password" required/></label><button disabled={busy}>{busy?"正在初始化…":"安全初始化"}</button></form>:<form onSubmit={login}><label>账号<input name="username" required/></label><label>密码<input name="password" type="password" required/></label><button disabled={busy}>{busy?"正在登录…":"登录"}</button></form>}{authError?<p className="wb-error" role="alert">{authError}</p>:null}</section></main>;
 if(session.user?.must_change_password)return <main className="wb-center"><section className="wb-auth"><p className="wb-eyebrow">首次登录保护</p><h1>请先修改临时密码</h1><p>完成后会撤销现有会话，请使用新密码重新登录。</p><form onSubmit={changePassword}><label>临时密码<input name="old_password" type="password" required/></label><label>新密码<input name="new_password" type="password" required/></label><button disabled={busy}>{busy?"正在更新…":"修改并重新登录"}</button></form>{authError?<p className="wb-error">{authError}</p>:null}</section></main>;
 const retry=()=>void loadWorkspace(session);const view=management.data;const modules=view?.modules??summary.data?.modules??[];
 return <main className="wb-shell"><div className="wb-nonprod">非生产开发基线 · 尚未迁移真实数据、部署或切流</div><header className="wb-header"><div><p className="wb-eyebrow">CHENYIDA · SELF-HOSTED</p><h1>经营工作台</h1><p>实时只读投影 · Node 服务端 / PostgreSQL 权威数据</p></div><div className="wb-user"><span><b>{session.user?.display_name||session.user?.username}</b><small>{session.user?.role_label||session.user?.role}</small></span><button className="wb-quiet" onClick={retry}>刷新</button><button className="wb-quiet" onClick={()=>void logout()}>退出</button></div></header>
 {management.status==="ready"&&view?<><section className="wb-metrics">{view.metrics.map(i=><a key={i.code} className={`wb-metric tone-${i.tone}`} href={i.href}><small>{i.label}</small><strong>{i.value}</strong><span>{i.hint}</span></a>)}</section><section className="wb-panel"><div className="wb-title"><div><p className="wb-eyebrow">ACTION QUEUE</p><h2>经营风险与待办</h2></div><time>{new Date(view.summary.generated_at).toLocaleString("zh-CN")}</time></div><div className="wb-risks">{view.risks.map(i=><a key={i.code} href={i.href} className={`wb-risk level-${i.level}`}><span>{i.level==="high"?"优先":i.level==="medium"?"关注":"正常"}</span><p>{i.text}</p><b>→</b></a>)}</div></section></>:<CardState state={management} forbiddenText="当前角色使用基础工作台；管理汇总已由服务端裁剪。" retry={retry}/>}
 <section className="wb-panel wb-module-panel"><div className="wb-title"><div><p className="wb-eyebrow">MODULES</p><h2>获准业务入口</h2></div><span className="wb-pill">{modules.length} 个</span></div>{summary.status==="error"&&!modules.length?<CardState state={summary} retry={retry}/>:<div className="wb-modules">{modules.map(m=><a key={m.code} href={m.href}><span>{m.native?"原生":"兼容业务台"}</span><h3>{m.label}</h3><p>{m.description}</p></a>)}</div>}</section>
 <div className="wb-grid wb-secondary" id="operations"><section className="wb-panel"><div className="wb-title"><div><p className="wb-eyebrow">AUTHORITY</p><h2>数据口径</h2></div></div>{summary.status==="ready"&&summary.data?<dl className="wb-facts"><div><dt>权威运行面</dt><dd>{summary.data.authority}</dd></div><div><dt>一致性</dt><dd>{summary.data.consistency}</dd></div><div><dt>角色数据域</dt><dd>{Object.keys(summary.data.groups).join(" / ")||"无"}</dd></div><div><dt>生成时间</dt><dd>{new Date(summary.data.generated_at).toLocaleString("zh-CN")}</dd></div></dl>:<CardState state={summary} retry={retry}/>}</section><section className="wb-panel"><div className="wb-title"><div><p className="wb-eyebrow">RECOVERY GOVERNANCE</p><h2>备份与恢复治理</h2></div>{backup.data?<span className={`wb-pill status-${backup.data.verification_status.toLowerCase()}`}>{backup.data.verification_status}</span>:null}</div>{backup.status==="ready"&&backup.data?<><dl className="wb-facts"><div><dt>浏览器操作</dt><dd>创建 / 恢复均禁用</dd></div><div><dt>恢复目标</dt><dd>仅新建空目标</dd></div><div><dt>一致性窗口</dt><dd>停止 Web / Worker 后捕获</dd></div><div><dt>最近验证</dt><dd>{backup.data.latest_verification?new Date(backup.data.latest_verification.verified_at).toLocaleString("zh-CN"):"未验证"}</dd></div></dl><p className="wb-note">只读展示可信 manifest；离线 CLI、跨故障域副本与人工授权才可执行。</p></>:<CardState state={backup} forbiddenText="当前角色无权读取备份状态。" retry={retry}/>}</section></div>
 {view?.recent_events.length?<section className="wb-panel wb-module-panel"><div className="wb-title"><div><p className="wb-eyebrow">SAFE EVENTS</p><h2>最近受控业务事件</h2></div></div><div className="wb-activity">{view.recent_events.map((e,i)=><div key={`${e.request_id}-${i}`}><span>{e.domain}</span><p><b>{e.action} · {e.object_code}</b><small>{e.actor||"system"} · 请求 {e.request_id}</small></p><time>{new Date(e.created_at).toLocaleString("zh-CN")}</time></div>)}</div></section>:null}{view?.recent_activity.length?<section className="wb-panel wb-module-panel"><div className="wb-title"><div><p className="wb-eyebrow">AUDIT</p><h2>最近系统审计</h2></div></div><div className="wb-activity">{view.recent_activity.map((e,i)=><div key={`${e.request_id}-${i}`}><span>{e.result}</span><p><b>{e.action} · {e.detail}</b><small>{e.username||"system"} · 请求 {e.request_id}</small></p><time>{new Date(e.created_at).toLocaleString("zh-CN")}</time></div>)}</div></section>:null}<footer>库存数量按单位分别汇总，不跨单位相加。<a href="/erp/index.html">进入 legacy 兼容业务台</a></footer></main>;
}
function CardState<T>({state,forbiddenText="当前角色无权读取此卡片。",retry}:{state:Loadable<T>;forbiddenText?:string;retry:()=>void}){if(state.status==="loading"||state.status==="idle")return <div className="wb-card-state"><span className="wb-loader"/>正在读取…</div>;if(state.status==="forbidden")return <div className="wb-card-state">{forbiddenText}</div>;if(state.status==="error")return <div className="wb-card-state wb-error">{state.message}<button className="wb-quiet" onClick={retry}>重试</button></div>;return null;}
