"use client";
import {FormEvent,useCallback,useEffect,useState,type ReactNode} from "react";
import {api,ErpApiError,isHistorySessionRestore,logoutSession,setProtectedViewState,suspendProtectedViews} from "../../public/erp/api-client.js";

type User={username:string;display_name:string;role:string;role_label?:string;permissions:string[];must_change_password:boolean;version:number};type Session={authenticated:boolean;setup_required?:boolean;user:User|null;csrf_token?:string};
type Module={code:string;label:string;description:string;href:string;native:boolean};type Summary={generated_at:string;authority:string;consistency:string;groups:Record<string,Record<string,unknown>>;modules:Module[]};type Loadable<T>={status:"idle"|"loading"|"ready"|"forbidden"|"error";data:T|null;message?:string};
const initial=<T,>():Loadable<T>=>({status:"idle",data:null});const explain=(e:unknown)=>e instanceof ErpApiError?`${e.message}（${e.code}${e.requestId?` · 请求 ${e.requestId}`:""}）`:"系统暂时无法完成请求";const isForbidden=(e:unknown)=>e instanceof ErpApiError&&e.status===403;

type RoleCode="administrator"|"procurement"|"market"|"planning"|"engineering"|"finance"|"production"|"warehouse";
type RoleDefinition={code:RoleCode;label:string;mark:string;description:string;moduleCodes:string[]};
const ROLE_ENTRANCES:RoleDefinition[]=[
 {code:"administrator",label:"管理员",mark:"管",description:"用户权限、往来单位与系统治理",moduleCodes:["users","partners","supplier-mapping-review","operations"]},
 {code:"procurement",label:"采购",mark:"采",description:"供应商映射、询价定标与采购履约",moduleCodes:["supplier-mappings","procurement-sourcing","procurement-fulfillment","procurement"]},
 {code:"market",label:"市场",mark:"市",description:"客户项目、销售交付与成品分配",moduleCodes:["market-projects","sales-delivery","finished-goods-allocation","sales"]},
 {code:"planning",label:"计划",mark:"计",description:"项目交接、物料需求与生产下达",moduleCodes:["planning-handoffs","material-requirements","purchase-requests","production-handoffs"]},
 {code:"engineering",label:"工程",mark:"工",description:"物料主数据、项目接收与产品 BOM",moduleCodes:["material","engineering-projects","engineering"]},
 {code:"finance",label:"财务",mark:"财",description:"应收应付、收付款与项目收支",moduleCodes:["finance-payables","finance-receivables","finance-settlements","finance-projects","finance"]},
 {code:"production",label:"生产",mark:"产",description:"工单、派工、报工与品质闭环",moduleCodes:["production-work-orders","production-reporting","production-quality","production-batches","production-dispatch","production-operations","production-wip","production","quality"]},
 {code:"warehouse",label:"仓库",mark:"仓",description:"收货、领退料、完工入库与发货",moduleCodes:["warehouse-receiving","production-issues","incoming-quality","production-completions","finished-goods-inventory-lots","warehouse-shipping","inventory"]},
];

function AuthFrame({children}:{children:ReactNode}){
 return <main className="wb-center"><div className="wb-auth-layout"><aside className="wb-auth-brand" aria-label="晨亿达 ERP 平台简介"><div className="wb-auth-lockup"><span className="wb-brand-mark" aria-hidden="true">CY</span><div><b>晨亿达 ERP</b><small>制造业一体化协同平台</small></div></div><div className="wb-auth-message"><p className="wb-eyebrow">CHENYIDA · SELF-HOSTED</p><h2>让物料、供应链与生产经营共用一套可信数据。</h2><p>从内部编码、BOM 到采购、库存、生产、品质和财务，关键动作全部由服务端受控执行。</p></div><ul className="wb-auth-capabilities" aria-label="平台能力"><li><b>主数据</b><span>一物一码 · 版本治理</span></li><li><b>供应链</b><span>寻源采购 · 库存追溯</span></li><li><b>制造</b><span>计划生产 · 品质闭环</span></li><li><b>经营</b><span>销售财务 · 审计恢复</span></li></ul><p className="wb-auth-stack"><span aria-hidden="true"/>Node.js + PostgreSQL · 私有化部署</p></aside><div className="wb-auth-panel">{children}<p className="wb-auth-footnote">受控访问 · 会话与操作均按权限校验</p></div></div></main>;
}

export function ErpWorkbench(){
 const[session,setSession]=useState<Session|null>(null);const[authError,setAuthError]=useState("");const[busy,setBusy]=useState(false);const[summary,setSummary]=useState<Loadable<Summary>>(initial);const[selectedRole,setSelectedRole]=useState<RoleCode>("administrator");
 const loadCard=useCallback(async<T,>(path:string,setter:(v:Loadable<T>)=>void)=>{setter({status:"loading",data:null});try{setter({status:"ready",data:await api<T>(path)});}catch(e){setter({status:isForbidden(e)?"forbidden":"error",data:null,message:explain(e)});}},[]);
 const loadWorkspace=useCallback(async(next:Session)=>{if(!next.authenticated||!next.user||next.user.must_change_password)return;void loadCard("/api/summary",setSummary);},[loadCard]);
 const clearWorkspace=useCallback(()=>{setSummary(initial());setSelectedRole("administrator");},[]);
 const publishSession=useCallback((next:Session)=>{setSession(next);window.requestAnimationFrame(()=>setProtectedViewState(next.authenticated?"authenticated":"anonymous"));},[]);
 const load=useCallback(async()=>{suspendProtectedViews();setSession(null);clearWorkspace();setAuthError("");try{const next=await api<Session>("/api/session");publishSession(next);await loadWorkspace(next);}catch(e){setProtectedViewState("anonymous");setAuthError(explain(e));}},[clearWorkspace,loadWorkspace,publishSession]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 useEffect(()=>{const onPageHide=()=>suspendProtectedViews();const onPageShow=(event:PageTransitionEvent)=>{if(isHistorySessionRestore(event))void load();};window.addEventListener("pagehide",onPageHide);window.addEventListener("pageshow",onPageShow);return()=>{window.removeEventListener("pagehide",onPageHide);window.removeEventListener("pageshow",onPageShow);};},[load]);
 async function authenticate(path:"/api/login"|"/api/setup",body:Record<string,string>){setBusy(true);setAuthError("");try{const result=await api<{user:User;csrf_token:string}>(path,{method:"POST",body:JSON.stringify(body)});const next:Session={authenticated:true,user:result.user,csrf_token:result.csrf_token};publishSession(next);await loadWorkspace(next);}catch(e){setProtectedViewState("anonymous");setAuthError(explain(e));}finally{setBusy(false);}}
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await authenticate("/api/login",{username:String(d.get("username")||""),password:String(d.get("password")||"")});}async function setup(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await authenticate("/api/setup",{setup_token:String(d.get("setup_token")||""),username:String(d.get("username")||""),display_name:String(d.get("display_name")||""),password:String(d.get("password")||"")});}
 async function changePassword(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session?.user||!session.csrf_token)return;const d=new FormData(e.currentTarget);setBusy(true);setAuthError("");try{await api("/api/me/password",{method:"POST",body:JSON.stringify({old_password:d.get("old_password"),new_password:d.get("new_password"),expected_version:session.user.version}),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}});await logoutSession(session.csrf_token);clearWorkspace();publishSession({authenticated:false,user:null});window.location.replace("/");}catch(reason){setProtectedViewState("authenticated");setAuthError(explain(reason));}finally{setBusy(false);}}
 async function logout(){if(!session?.csrf_token){setAuthError("退出失败：当前页面缺少 CSRF 上下文，请刷新后重试（PROTECTED_WRITE_CONTEXT_REQUIRED）");return;}setBusy(true);setAuthError("");suspendProtectedViews();try{await logoutSession(session.csrf_token);clearWorkspace();publishSession({authenticated:false,user:null});window.location.replace("/");}catch(reason){setProtectedViewState("authenticated");setAuthError(`退出失败：${explain(reason)}`);}finally{setBusy(false);}}
 if(!session)return <AuthFrame><section className="wb-auth" aria-live="polite"><p className="wb-auth-kicker">安全连接</p><h1>正在进入工作台</h1><p>{authError||"正在验证本机会话与访问权限…"}</p>{authError?<button className="wb-auth-submit" onClick={()=>void load()}>重新连接</button>:<span className="wb-loader"/>}</section></AuthFrame>;
 if(!session.authenticated)return <AuthFrame><section className="wb-auth"><p className="wb-auth-kicker">{session.setup_required?"系统初始化":"账号登录"}</p><h1>{session.setup_required?"初始化管理员":"欢迎使用晨亿达 ERP"}</h1><p>{session.setup_required?"建立首个受控管理员账号。":"请输入由管理员分配的账号和密码。"}</p>{session.setup_required?<form onSubmit={setup} aria-busy={busy}><label>初始化凭证<input name="setup_token" type="password" autoComplete="off" required/></label><label>管理员账号<input name="username" autoComplete="username" required/></label><label>显示名称<input name="display_name" autoComplete="name" required/></label><label>管理员密码<input name="password" type="password" autoComplete="new-password" required/></label><button className="wb-auth-submit" disabled={busy}>{busy?"正在初始化…":"安全初始化"}</button></form>:<form onSubmit={login} aria-busy={busy}><label>账号<input name="username" autoComplete="username" placeholder="请输入账号" required/></label><label>密码<input name="password" type="password" autoComplete="current-password" placeholder="请输入密码" required/></label><button className="wb-auth-submit" disabled={busy}>{busy?"正在登录…":"登录工作台"}</button></form>}{authError?<p className="wb-error" role="alert">{authError}</p>:null}</section></AuthFrame>;
 if(session.user?.must_change_password)return <AuthFrame><section className="wb-auth"><p className="wb-auth-kicker">首次登录保护</p><h1>设置新的登录密码</h1><p>完成后会撤销当前会话，请使用新密码重新登录。</p><form onSubmit={changePassword} aria-busy={busy}><label>临时密码<input name="old_password" type="password" autoComplete="current-password" required/></label><label>新密码<input name="new_password" type="password" autoComplete="new-password" required/></label><button className="wb-auth-submit" disabled={busy}>{busy?"正在更新…":"修改并重新登录"}</button></form>{authError?<p className="wb-error" role="alert">{authError}</p>:null}</section></AuthFrame>;
 const retry=()=>void loadWorkspace(session);const modules=summary.data?.modules??[];const byCode=new Map(modules.map(module=>[module.code,module]));const groups=ROLE_ENTRANCES.map(role=>({...role,modules:role.moduleCodes.map(code=>byCode.get(code)).filter((module):module is Module=>Boolean(module))}));const active=groups.find(group=>group.code===selectedRole&&group.modules.length)||groups.find(group=>group.modules.length)||groups[0];
 return <main className="wb-shell" data-cyd-protected-view><header className="wb-header"><div className="wb-header-brand"><span className="wb-brand-mark" aria-hidden="true">CY</span><div><p className="wb-eyebrow">CHENYIDA ERP</p><h1>角色工作台</h1><p>统一业务门户 · PostgreSQL 权威数据</p></div></div><div className="wb-user"><span><b>{session.user?.display_name||session.user?.username}</b><small>{session.user?.role_label||session.user?.role}</small></span><button className="wb-quiet" onClick={retry}>刷新入口</button><button className="wb-quiet" disabled={busy} onClick={()=>void logout()}>安全退出</button></div></header><div className="wb-contextbar"><span>首页 / 角色工作台</span><span className="wb-authority"><i aria-hidden="true"/>服务端权限实时裁剪</span></div><div className="wb-nonprod">非生产开发基线 · 尚未迁移真实数据、部署或切流</div>{authError?<p className="wb-error" role="alert">{authError}</p>:null}
 <section className="wb-role-intro"><div><p className="wb-eyebrow">BUSINESS ENTRANCE</p><h2>选择您的业务入口</h2><p>按部门集中常用业务，进入后再处理具体单据与任务。</p></div><span>共 8 个部门</span></section>
 <div className="wb-role-hub"><nav className="wb-role-tabs" role="tablist" aria-label="业务部门入口">{groups.map((group,index)=>{const selected=group.code===active.code;const allowed=group.modules.length>0;return <button key={group.code} type="button" role="tab" id={`role-tab-${group.code}`} aria-controls="role-module-panel" aria-selected={selected} disabled={!allowed} className={selected?"is-active":""} onClick={()=>setSelectedRole(group.code)}><span className="wb-role-mark" aria-hidden="true">{group.mark}</span><span className="wb-role-copy"><strong>{group.label}</strong><small>{group.description}</small></span><span className="wb-role-count">{allowed?`${group.modules.length} 项业务`:"暂无权限"}</span><i aria-hidden="true">›</i><span className="wb-role-order" aria-hidden="true">{String(index+1).padStart(2,"0")}</span></button>})}</nav><section className="wb-role-panel" id="role-module-panel" role="tabpanel" aria-labelledby={`role-tab-${active.code}`}><header><span className="wb-role-emblem" aria-hidden="true">{active.mark}</span><div><p className="wb-eyebrow">{active.code.toUpperCase()}</p><h2>{active.label}入口</h2><p>{active.description}</p></div><span className="wb-role-total">{active.modules.length} 项获准业务</span></header>{summary.status==="ready"?<nav className="wb-role-modules" aria-label={`${active.label}获准业务`}>{active.modules.map(module=><a key={module.code} href={module.href}><span><strong>{module.label}</strong><small>{module.description}</small></span><em>{module.native?"原生":"兼容业务台"}</em><b aria-hidden="true">→</b></a>)}</nav>:<CardState state={summary} forbiddenText="当前账号没有可用的工作台入口。" retry={retry}/>}<p className="wb-role-security"><i aria-hidden="true"/>这里只展示服务端已授权模块；进入业务后仍会再次校验账号权限。</p></section></div>
 <footer><span>工作台入口按当前账号权限实时生成。</span><span>库存数量按单位分别汇总，不跨单位相加。</span></footer></main>;
}
function CardState<T>({state,forbiddenText="当前角色无权读取此卡片。",retry}:{state:Loadable<T>;forbiddenText?:string;retry:()=>void}){if(state.status==="loading"||state.status==="idle")return <div className="wb-card-state"><span className="wb-loader"/>正在读取…</div>;if(state.status==="forbidden")return <div className="wb-card-state">{forbiddenText}</div>;if(state.status==="error")return <div className="wb-card-state wb-error">{state.message}<button className="wb-quiet" onClick={retry}>重试</button></div>;return null;}
