"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};
type Option={completion_line_id:number;sales_order_line_id:number;completion_code:string;work_order_code:string;sales_order_code:string;material_code:string;material_name:string;unit_code:string;completion_version:number;sales_order_line_version:number;completion_remaining_qty:string;sales_order_remaining_qty:string;allocatable_qty:string};
type Allocation={id:number;completion_code:string;work_order_code:string;sales_order_code:string;material_code:string;material_name:string;unit_code:string;quantity:string;status:"ACTIVE"|"CANCELLED";version:number;inspected_qty:string;released_qty:string};
type Pending={path:string;body:string;key:string;label:string};
const can=(s:Session|null,p:string)=>Boolean(s?.user&&(s.user.permissions.includes("*")||s.user.permissions.includes(p)));

export default function FinishedGoodsAllocationPage(){
  const[session,setSession]=useState<Session|null>(null),[options,setOptions]=useState<Option[]>([]),[rows,setRows]=useState<Allocation[]>([]),[loading,setLoading]=useState(true),[forbidden,setForbidden]=useState(false),[error,setError]=useState(""),[pending,setPending]=useState<Pending|null>(null);
  async function load(){setLoading(true);setError("");try{const current=await api<Session>("/api/session");setSession(current);if(!current.authenticated||!can(current,"quality.finished_goods_allocation.read")){setForbidden(true);setOptions([]);setRows([]);return;}setForbidden(false);const[available,allocated]=await Promise.all([api<{data:Option[]}>("/api/quality/finished-goods-allocation-options?limit=100"),api<{data:Allocation[]}>("/api/quality/finished-goods-allocations?page_size=100")]);setOptions(available.data);setRows(allocated.data);}catch(e){if(e instanceof ErpApiError&&e.status===403)setForbidden(true);else setError(e instanceof ErpApiError?`${e.message}${e.requestId?`（请求 ${e.requestId}）`:""}`:"读取失败");}finally{setLoading(false);}}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[]);
  async function write(operation:Pending){if(!session?.csrf_token)return;setError("");try{await api(operation.path,{method:"POST",body:operation.body,protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:operation.key}});setPending(null);await load();}catch(e){if(e instanceof ErpApiError&&e.resultUnknown){setPending(operation);setError(`${operation.label}结果未知；请使用原操作标识重试，系统不会重复分配。`);}else{setPending(null);setError(e instanceof ErpApiError?`${e.message}${e.code.includes("VERSION")?"；请刷新后按最新版本重试":""}`:`${operation.label}失败`);if(e instanceof ErpApiError&&[403,409].includes(e.status))await load();}}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),selected=options[Number(form.get("option"))];if(!selected)return;const body=JSON.stringify({completion_line_id:selected.completion_line_id,sales_order_line_id:selected.sales_order_line_id,quantity:String(form.get("quantity")),expected_completion_version:selected.completion_version,expected_sales_order_line_version:selected.sales_order_line_version});await write({path:"/api/quality/finished-goods-allocations",body,key:crypto.randomUUID(),label:"创建分配"});}
  async function cancel(row:Allocation){await write({path:`/api/quality/finished-goods-allocations/${row.id}/cancel`,body:JSON.stringify({expected_version:row.version,reason:"销售受控取消未检验成品分配"}),key:crypto.randomUUID(),label:"取消分配"});}
  if(loading)return <main className="sourcing-shell"><div className="sourcing-state">正在读取成品订单分配…</div></main>;
  if(forbidden)return <main className="sourcing-shell"><div className="sourcing-state sourcing-error">403：当前账号无权读取成品订单分配。</div></main>;
  return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/">← 经营工作台</Link><h1>成品订单稳定分配</h1><p>Completion Line 与当前销售订单明细建立稳定关系；不改变库存 reserved_qty，也不执行发货。</p></div></header>
    {can(session,"quality.finished_goods_allocation.create")?<section className="sourcing-panel"><h2>创建分配</h2>{options.length?<form className="sourcing-form" onSubmit={create}><label>可信来源<select name="option" required>{options.map((o,index)=><option key={`${o.completion_line_id}-${o.sales_order_line_id}`} value={index}>{o.completion_code} / {o.sales_order_code} · {o.material_code} · 可分配 {o.allocatable_qty} {o.unit_code}</option>)}</select></label><label>数量<input name="quantity" required defaultValue={options[0]?.allocatable_qty}/></label><button>确认稳定分配</button></form>:<div className="sourcing-state">没有客户、产品版本、成品物料与单位均匹配的可分配来源。</div>}</section>:null}
    <section className="sourcing-panel"><h2>分配事实</h2>{rows.length?rows.map(row=><article className="sourcing-card" key={row.id}><div><b>{row.completion_code} → {row.sales_order_code}</b><span className="sourcing-status">{row.status}</span></div><small>{row.work_order_code} · {row.material_code} {row.material_name} · 分配 {row.quantity} {row.unit_code} · 已 FQC {row.inspected_qty} · 已关闭放行 {row.released_qty}</small>{row.status==="ACTIVE"&&Number(row.inspected_qty)===0&&can(session,"quality.finished_goods_allocation.cancel")?<button className="danger" onClick={()=>void cancel(row)}>取消未检验分配</button>:null}</article>):<div className="sourcing-state">尚无成品订单分配。</div>}</section>
    {pending?<div className="sourcing-state"><button onClick={()=>void write(pending)}>使用原幂等键重试：{pending.label}</button></div>:null}{error?<div className="sourcing-state sourcing-error">{error}</div>:null}</main>;
}
