import { createHash } from "node:crypto";
import { constants } from "node:fs";
import { lstat, open, realpath } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import clusterRecoveryPolicy from "../../../operations/postgresql-cluster-recovery-policy-v1.json" with { type:"json" };
import { validateBackupRecoveryReadinessV4 } from "../../../scripts/backup-recovery-readiness-v4.mjs";
import { CLUSTER_POLICY_CONTRACT } from "../../../scripts/postgresql-cluster-recovery-contract.mjs";
import type { BackupRecoveryReadiness, BackupRecoveryReadinessV3, BackupVerification, LegacyBackupVerification, RuntimeReleaseIdentity } from "./types.ts";

const SHA=/^[0-9a-f]{64}$/,IMAGE=/^sha256:[0-9a-f]{64}$/,IDENTIFIER=/^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/;
const MIGRATION=/^\d{4}_[a-z0-9_]+\.sql$/,VERSION=/^0\.1\.0-alpha\.\d+$/,COMMIT=/^[0-9a-f]{40}$/;
const ISO_UTC=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const CONTAINER_ID=/^[0-9a-f]{64}$/,RUNTIME_HOSTNAME=/^[0-9a-f]{12,64}$/;
const LEVELS=new Set(["LOCAL_VERIFIED","OFFHOST_VERIFIED","RESTORE_VERIFIED"]),CLASSES=new Set(["TEST","UAT","PRODUCTION"]);
const FILES={postgresql_dump:"postgresql.dump",uploads:"uploads.tar.gz",attachments:"attachments.tar.gz",backup_status:"backup-status.tar.gz"} as const;
const LEGACY_FILES={postgresql_dump:"postgresql.dump",uploads:"uploads.tar.gz",attachments:"attachments.tar.gz"} as const;
export const RUNTIME_RELEASE_IDENTITY_FILE="/run/chenyida-erp-release/release-identity.json";
const RELEASE_IDENTITY_CONTRACT="chenyida-erp-runtime-release-identity/v3",RELEASE_RUNTIME_GUARD_CONTRACT="chenyida-erp-release-runtime-guard/v1",POST_DEPLOY_RUNTIME_GUARD_MODE="POST_DEPLOY_CURRENT_RUNTIME_STRICT",RELEASE_RUNTIME_POLICY_SHA256="74d3f8d24e7b15f0cc5ce4e0e21c963b0e95735c502a471666c02165c7e53c1b",RELEASE_ROOT_MARKER=".chenyida-erp-release-identity-root-v1",RELEASE_ROOT_MARKER_VALUE="chenyida-erp-release-identity-root/v1\n";
const RECEIPT_ROOT_MARKER=".chenyida-erp-receipt-root-v2",RECEIPT_ROOT_MARKER_VALUE="chenyida-erp-receipt-root/v2\n";

const iso=(value:unknown)=>typeof value==="string"&&ISO_UTC.test(value)&&!Number.isNaN(Date.parse(value));
const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==="object"&&!Array.isArray(value);
const exact=(value:Record<string,unknown>,expected:readonly string[])=>{const actual=Object.keys(value).sort(),keys=[...expected].sort();return actual.length===keys.length&&actual.every((key,index)=>key===keys[index]);};
const canonicalValue=(value:unknown):string=>{if(value===null||typeof value==="boolean"||typeof value==="string")return JSON.stringify(value);if(typeof value==="number"){if(!Number.isSafeInteger(value)||Object.is(value,-0))throw new Error("canonical");return JSON.stringify(value);}if(Array.isArray(value))return`[${value.map(canonicalValue).join(",")}]`;if(record(value))return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonicalValue(value[key])}`).join(",")}}`;throw new Error("canonical");};
const canonicalJson=(value:unknown)=>`${canonicalValue(value)}\n`;
const identifier=(value:unknown)=>typeof value==="string"&&IDENTIFIER.test(value);
const decimalIdentifier=(value:unknown)=>typeof value==="string"&&/^\d{1,30}$/.test(value);
const artifact=(value:unknown,file:string,entries:boolean)=>record(value)&&exact(value,entries?["file","sha256","bytes","entries"]:["file","sha256","bytes"])&&value.file===file&&typeof value.sha256==="string"&&SHA.test(value.sha256)&&typeof value.bytes==="number"&&Number.isSafeInteger(value.bytes)&&value.bytes>0&&(!entries||(typeof value.entries==="number"&&Number.isSafeInteger(value.entries)&&value.entries>=0));

class StrictJson {
  private index=0; private readonly source:string; constructor(source:string){this.source=source;}
  parse(){const value=this.value();this.space();if(this.index!==this.source.length)throw new Error("trailing");return value;}
  private space(){while(/\s/.test(this.source[this.index]||""))this.index+=1;}
  private value():unknown{this.space();const token=this.source[this.index];if(token==="{")return this.object();if(token==="[")return this.array();if(token==='"')return this.string();for(const [word,value] of [["true",true],["false",false],["null",null]] as const){if(this.source.slice(this.index,this.index+word.length)===word){this.index+=word.length;return value;}}const match=this.source.slice(this.index).match(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/);if(!match)throw new Error("value");this.index+=match[0].length;const result=Number(match[0]);if(!Number.isFinite(result))throw new Error("number");return result;}
  private string(){const start=this.index++;let escaped=false;while(this.index<this.source.length){const current=this.source[this.index];if(!escaped&&current==='"'){this.index+=1;return JSON.parse(this.source.slice(start,this.index));}if(!escaped&&current.charCodeAt(0)<0x20)throw new Error("string");if(!escaped&&current==="\\")escaped=true;else escaped=false;this.index+=1;}throw new Error("string");}
  private object(){const result:Record<string,unknown>={},keys=new Set<string>();this.index+=1;this.space();if(this.source[this.index]==="}"){this.index+=1;return result;}while(this.index<this.source.length){this.space();if(this.source[this.index]!=='"')throw new Error("key");const key=this.string();if(keys.has(key))throw new Error("duplicate");keys.add(key);this.space();if(this.source[this.index]!==":")throw new Error("colon");this.index+=1;result[key]=this.value();this.space();if(this.source[this.index]==="}"){this.index+=1;return result;}if(this.source[this.index]!==",")throw new Error("separator");this.index+=1;}throw new Error("object");}
  private array(){const result:unknown[]=[];this.index+=1;this.space();if(this.source[this.index]==="]"){this.index+=1;return result;}while(this.index<this.source.length){result.push(this.value());this.space();if(this.source[this.index]==="]"){this.index+=1;return result;}if(this.source[this.index]!==",")throw new Error("separator");this.index+=1;}throw new Error("array");}
}

export function parseBackupVerification(value:unknown):BackupVerification|null{
  if(!record(value)||!exact(value,["schema_version","contract","result","backup_id","created_at","verified_at","expires_at","location_id","deployment","application","migration","policy","consistency","reconciliation","manifest_sha256","artifacts","evidence"]))return null;
  if(value.schema_version!==2||value.contract!=="chenyida-erp-backup-verification/v2"||typeof value.result!=="string"||!LEVELS.has(value.result)||!identifier(value.backup_id)||!iso(value.created_at)||!iso(value.verified_at)||!iso(value.expires_at)||!identifier(value.location_id)||typeof value.manifest_sha256!=="string"||!SHA.test(value.manifest_sha256))return null;
  if(!record(value.deployment)||!exact(value.deployment,["class","id","database","database_system_identifier","database_oid","database_marker","database_bytes","database_server_major","database_encoding","database_collate","database_ctype","database_locale_provider","database_collation_version"])||typeof value.deployment.class!=="string"||!CLASSES.has(value.deployment.class)||!identifier(value.deployment.id)||!identifier(value.deployment.database)||!decimalIdentifier(value.deployment.database_system_identifier)||!decimalIdentifier(value.deployment.database_oid)||!identifier(value.deployment.database_marker)||typeof value.deployment.database_bytes!=="number"||!Number.isSafeInteger(value.deployment.database_bytes)||value.deployment.database_bytes<1||!decimalIdentifier(value.deployment.database_server_major)||![value.deployment.database_encoding,value.deployment.database_collate,value.deployment.database_ctype,value.deployment.database_locale_provider,value.deployment.database_collation_version].every(identifier)||value.deployment.database_locale_provider!=="libc")return null;
  if(!record(value.application)||!exact(value.application,["version","git_commit","web_image_digest","worker_image_digest"])||typeof value.application.version!=="string"||!VERSION.test(value.application.version)||typeof value.application.git_commit!=="string"||!COMMIT.test(value.application.git_commit)||typeof value.application.web_image_digest!=="string"||!IMAGE.test(value.application.web_image_digest)||typeof value.application.worker_image_digest!=="string"||!IMAGE.test(value.application.worker_image_digest))return null;
  if(!record(value.migration)||!exact(value.migration,["head","manifest_file","manifest_sha256"])||typeof value.migration.head!=="string"||!MIGRATION.test(value.migration.head)||value.migration.manifest_file!=="migrations.txt"||typeof value.migration.manifest_sha256!=="string"||!SHA.test(value.migration.manifest_sha256))return null;
  if(!record(value.policy)||!exact(value.policy,["id","rpo_hours"])||!identifier(value.policy.id)||typeof value.policy.rpo_hours!=="number"||!Number.isSafeInteger(value.policy.rpo_hours)||value.policy.rpo_hours<1||value.policy.rpo_hours>168)return null;
  if(!record(value.consistency)||!exact(value.consistency,["method","database_snapshot","database_guard","writer_boundary","content_reconciliation","dump_scope","web_container","web_container_id","worker_container","worker_container_id","recovery_point_at","verified_after"])||value.consistency.method!=="QUIESCED_APPLICATION_AND_SNAPSHOT_WITH_CONTENT_RECONCILIATION"||value.consistency.database_snapshot!=="PG_DUMP_CONSISTENT_SNAPSHOT"||value.consistency.database_guard!=="DEFAULT_TRANSACTION_READ_ONLY_DEFENSE_IN_DEPTH"||value.consistency.writer_boundary!=="EXACT_COMPOSE_WEB_WORKER_STOPPED"||value.consistency.content_reconciliation!=="BEFORE_AFTER_FULL_RELATION_CONTENT_DIGESTS"||value.consistency.dump_scope!=="COMPLETE_APPLICATION_DATABASE_LOGICAL_DUMP_NO_OWNER_OR_ACL"||!identifier(value.consistency.web_container)||typeof value.consistency.web_container_id!=="string"||!SHA.test(value.consistency.web_container_id)||!identifier(value.consistency.worker_container)||typeof value.consistency.worker_container_id!=="string"||!SHA.test(value.consistency.worker_container_id)||!iso(value.consistency.recovery_point_at)||!iso(value.consistency.verified_after))return null;
  if(!record(value.reconciliation)||!exact(value.reconciliation,["contract","file","sha256"])||value.reconciliation.contract!=="chenyida-erp-backup-reconciliation/v1"||value.reconciliation.file!=="reconciliation.json"||typeof value.reconciliation.sha256!=="string"||!SHA.test(value.reconciliation.sha256))return null;
  if(!record(value.artifacts)||!exact(value.artifacts,Object.keys(FILES)))return null;for(const key of Object.keys(FILES) as Array<keyof typeof FILES>)if(!artifact(value.artifacts[key],FILES[key],key!=="postgresql_dump"))return null;
  if(!record(value.evidence))return null;
  if(value.result==="LOCAL_VERIFIED"){
    if(!exact(value.evidence,["kind","source_machine_identity_sha256","source_root_device","source_root_inode","source_root_identity_sha256","attestation"])||value.evidence.kind!=="LOCAL_CAPTURE_VERIFICATION"||typeof value.evidence.source_machine_identity_sha256!=="string"||!SHA.test(value.evidence.source_machine_identity_sha256)||!decimalIdentifier(value.evidence.source_root_device)||!decimalIdentifier(value.evidence.source_root_inode)||typeof value.evidence.source_root_identity_sha256!=="string"||!SHA.test(value.evidence.source_root_identity_sha256)||createHash("sha256").update(`${value.evidence.source_machine_identity_sha256}\n${value.evidence.source_root_device}\n${value.evidence.source_root_inode}\n`).digest("hex")!==value.evidence.source_root_identity_sha256||value.evidence.attestation!=="TRUSTED_EXECUTION_UID_AND_FIXED_SOURCE_MACHINE_ROOT")return null;
  }
  else if(value.result==="OFFHOST_VERIFIED"){
    if(!exact(value.evidence,["kind","transfer_id","source_location_id","source_machine_identity_sha256","local_receipt_sha256","receiver_machine_identity_sha256","receiver_root_device","receiver_root_inode","receiver_identity_sha256","attestation"])||value.evidence.kind!=="OFFHOST_RECEIVER_VERIFICATION"||!identifier(value.evidence.transfer_id)||!identifier(value.evidence.source_location_id)||value.evidence.source_location_id===value.location_id||typeof value.evidence.source_machine_identity_sha256!=="string"||!SHA.test(value.evidence.source_machine_identity_sha256)||typeof value.evidence.local_receipt_sha256!=="string"||!SHA.test(value.evidence.local_receipt_sha256)||typeof value.evidence.receiver_machine_identity_sha256!=="string"||!SHA.test(value.evidence.receiver_machine_identity_sha256)||value.evidence.receiver_machine_identity_sha256===value.evidence.source_machine_identity_sha256||!decimalIdentifier(value.evidence.receiver_root_device)||!decimalIdentifier(value.evidence.receiver_root_inode)||typeof value.evidence.receiver_identity_sha256!=="string"||!SHA.test(value.evidence.receiver_identity_sha256)||createHash("sha256").update(`${value.evidence.receiver_machine_identity_sha256}\n${value.evidence.receiver_root_device}\n${value.evidence.receiver_root_inode}\n`).digest("hex")!==value.evidence.receiver_identity_sha256||value.evidence.attestation!=="TRUSTED_EXECUTION_UID_AND_DISTINCT_MACHINE_FIXED_RECEIVER_ROOT")return null;
  }else{
    if(!exact(value.evidence,["kind","source_location_id","offhost_location_id","offhost_receiver_identity_sha256","offhost_receipt_sha256","restore_run_id","restored_at","target","reconciliation","reconciliation_sha256","attestation"])||value.evidence.kind!=="ISOLATED_RESTORE_VERIFICATION"||!identifier(value.evidence.source_location_id)||!identifier(value.evidence.offhost_location_id)||new Set([value.evidence.source_location_id,value.evidence.offhost_location_id,value.location_id]).size!==3||typeof value.evidence.offhost_receiver_identity_sha256!=="string"||!SHA.test(value.evidence.offhost_receiver_identity_sha256)||typeof value.evidence.offhost_receipt_sha256!=="string"||!SHA.test(value.evidence.offhost_receipt_sha256)||!identifier(value.evidence.restore_run_id)||!iso(value.evidence.restored_at)||typeof value.evidence.reconciliation_sha256!=="string"||!SHA.test(value.evidence.reconciliation_sha256)||value.evidence.attestation!=="TRUSTED_EXECUTION_UID_AND_DISTINCT_CLUSTER_ACTIVE_INSPECTION"||!record(value.evidence.reconciliation)||!record(value.evidence.target))return null;
    const reconciliation=value.evidence.reconciliation;if(!exact(reconciliation,["contract","source_sha256","target_database_report_sha256","target_file_trees_sha256","result"])||reconciliation.contract!=="chenyida-erp-restore-reconciliation/v1"||reconciliation.result!=="MATCHED"||[reconciliation.source_sha256,reconciliation.target_database_report_sha256,reconciliation.target_file_trees_sha256].some((item)=>typeof item!=="string"||!SHA.test(item)))return null;
    const reconciliationDigestInput={contract:reconciliation.contract,source_sha256:reconciliation.source_sha256,target_database_report_sha256:reconciliation.target_database_report_sha256,target_file_trees_sha256:reconciliation.target_file_trees_sha256,result:reconciliation.result};if(createHash("sha256").update(JSON.stringify(reconciliationDigestInput)).digest("hex")!==value.evidence.reconciliation_sha256||reconciliation.source_sha256!==value.reconciliation.sha256)return null;
    const target=value.evidence.target;if(!exact(target,["deployment_class","deployment_id","database_name","database_system_identifier","database_oid","marker_id","cluster_marker_id","database_server_major","database_encoding","database_collate","database_ctype","database_locale_provider","database_collation_version","file_root_name"])||target.deployment_class!=="TEST"||!identifier(target.deployment_id)||!identifier(target.database_name)||!decimalIdentifier(target.database_system_identifier)||!decimalIdentifier(target.database_oid)||!identifier(target.marker_id)||!identifier(target.cluster_marker_id)||!decimalIdentifier(target.database_server_major)||![target.database_encoding,target.database_collate,target.database_ctype,target.database_locale_provider,target.database_collation_version].every(identifier)||target.database_locale_provider!=="libc"||!identifier(target.file_root_name)||!(target.database_name as string).endsWith("_restore_test")||!(target.file_root_name as string).endsWith("_restore_test")||target.database_system_identifier===value.deployment.database_system_identifier||target.database_server_major!==value.deployment.database_server_major||target.database_encoding!==value.deployment.database_encoding||target.database_collate!==value.deployment.database_collate||target.database_ctype!==value.deployment.database_ctype||target.database_locale_provider!==value.deployment.database_locale_provider||target.database_collation_version!==value.deployment.database_collation_version||value.evidence.restored_at!==value.verified_at)return null;
  }
  const created=Date.parse(value.created_at as string),verified=Date.parse(value.verified_at as string),expires=Date.parse(value.expires_at as string),recoveryPoint=Date.parse(value.consistency.recovery_point_at as string),after=Date.parse(value.consistency.verified_after as string);
  if(recoveryPoint>after||after>created||verified<created||verified>expires||expires!==recoveryPoint+(value.policy.rpo_hours as number)*60*60*1000)return null;
  return value as unknown as BackupVerification;
}

export function parseBackupRecoveryReadinessV3(value:unknown):BackupRecoveryReadinessV3|null{
  try{
    if(!record(value)||!exact(value,["schema_version","contract","result","evidence_scope","backup_id","created_at","verified_at","expires_at","inner_restore","transfer","operations","attestation","readiness_sha256"]))return null;
    if(value.schema_version!==3||value.contract!=="chenyida-erp-backup-verification/v3"||!new Set(["RECOVERY_READY","SYNTHETIC_ISOLATED_VERIFIED"]).has(value.result as string)||!new Set(["ACTUAL_OFFHOST","SYNTHETIC_ISOLATED"]).has(value.evidence_scope as string)||!identifier(value.backup_id)||!iso(value.created_at)||!iso(value.verified_at)||!iso(value.expires_at)||typeof value.readiness_sha256!=="string"||!SHA.test(value.readiness_sha256)||value.attestation!=="ROOT_PUBLISHED_INNER_V2_RESTORE_SIGNED_ENCRYPTED_OFFHOST_AND_OPERATIONS_POLICY_VERIFIED")return null;
    if((value.result==="RECOVERY_READY")!==(value.evidence_scope==="ACTUAL_OFFHOST"))return null;
    const created=Date.parse(value.created_at as string),verified=Date.parse(value.verified_at as string),expires=Date.parse(value.expires_at as string);if(created>verified||verified>expires)return null;
    if(!record(value.inner_restore)||!exact(value.inner_restore,["receipt_file_sha256","receipt_canonical_sha256","receipt"])||typeof value.inner_restore.receipt_file_sha256!=="string"||!SHA.test(value.inner_restore.receipt_file_sha256)||typeof value.inner_restore.receipt_canonical_sha256!=="string"||!SHA.test(value.inner_restore.receipt_canonical_sha256))return null;
    const restore=parseBackupVerification(value.inner_restore.receipt);if(!restore||restore.result!=="RESTORE_VERIFIED"||restore.backup_id!==value.backup_id||restore.created_at!==value.created_at||restore.expires_at!==value.expires_at||createHash("sha256").update(canonicalJson(restore)).digest("hex")!==value.inner_restore.receipt_canonical_sha256||restore.evidence.kind!=="ISOLATED_RESTORE_VERIFICATION")return null;
    const transferKeys=["transfer_id","envelope_sha256","receiver_receipt_sha256","acceptance_sha256","offhost_receipt_sha256","payload_algorithm","key_agreement","key_derivation","signature_algorithm","source_location_id","source_machine_identity_sha256","receiver_location_id","receiver_machine_identity_sha256","receiver_identity_sha256","source_signing_key_fingerprint","receiver_encryption_key_fingerprint","receiver_receipt_key_fingerprint"];
    if(!record(value.transfer)||!exact(value.transfer,transferKeys)||!identifier(value.transfer.transfer_id)||!identifier(value.transfer.source_location_id)||!identifier(value.transfer.receiver_location_id)||value.transfer.source_location_id===value.transfer.receiver_location_id||value.transfer.payload_algorithm!=="AES-256-GCM"||value.transfer.key_agreement!=="X25519"||value.transfer.key_derivation!=="HKDF-SHA256"||value.transfer.signature_algorithm!=="Ed25519")return null;
    for(const key of ["envelope_sha256","receiver_receipt_sha256","acceptance_sha256","offhost_receipt_sha256","source_machine_identity_sha256","receiver_machine_identity_sha256","receiver_identity_sha256","source_signing_key_fingerprint","receiver_encryption_key_fingerprint","receiver_receipt_key_fingerprint"])if(typeof value.transfer[key]!=="string"||!SHA.test(value.transfer[key] as string))return null;
    if(value.transfer.source_machine_identity_sha256===value.transfer.receiver_machine_identity_sha256||value.transfer.source_location_id!==restore.evidence.source_location_id||value.transfer.receiver_location_id!==restore.evidence.offhost_location_id||value.transfer.receiver_identity_sha256!==restore.evidence.offhost_receiver_identity_sha256||value.transfer.offhost_receipt_sha256!==restore.evidence.offhost_receipt_sha256)return null;
    if(!record(value.operations)||!exact(value.operations,["policy_id","policy_sha256","policy_scope","schedule_observation_sha256","schedule_status","rpo_status","scheduler_installation_status","retention_plan_sha256","retention_status","retention_execution"])||!identifier(value.operations.policy_id)||typeof value.operations.policy_sha256!=="string"||!SHA.test(value.operations.policy_sha256)||typeof value.operations.schedule_observation_sha256!=="string"||!SHA.test(value.operations.schedule_observation_sha256)||typeof value.operations.retention_plan_sha256!=="string"||!SHA.test(value.operations.retention_plan_sha256)||!new Set(["SYNTHETIC_TEST_ONLY","TEST","UAT","PRODUCTION"]).has(value.operations.policy_scope as string)||value.operations.schedule_status!=="ON_TIME"||value.operations.rpo_status!=="WITHIN_RPO"||value.operations.retention_status!=="POLICY_VALID_DRY_RUN"||value.operations.retention_execution!=="DRY_RUN_DELETION_FORBIDDEN")return null;
    if(value.evidence_scope==="ACTUAL_OFFHOST"){
      if(!new Set(["UAT","PRODUCTION"]).has(value.operations.policy_scope as string)||value.operations.scheduler_installation_status!=="INSTALLED_AND_OBSERVED"||value.operations.policy_scope!==restore.deployment.class)return null;
    }else if(!new Set(["SYNTHETIC_TEST_ONLY","TEST"]).has(value.operations.policy_scope as string)||value.operations.scheduler_installation_status!=="REPOSITORY_EVALUATOR_ONLY"||restore.deployment.class!=="TEST")return null;
    const body={...value};delete body.readiness_sha256;if(createHash("sha256").update(canonicalJson(body)).digest("hex")!==value.readiness_sha256)return null;
    return value as unknown as BackupRecoveryReadinessV3;
  }catch{return null;}
}

export function parseBackupRecoveryReadiness(value:unknown):BackupRecoveryReadiness|null{
  if(clusterRecoveryPolicy.schema_version===1&&clusterRecoveryPolicy.contract===CLUSTER_POLICY_CONTRACT&&record(value)&&value.result==="RECOVERY_READY"&&value.evidence_scope==="ACTUAL_OFFHOST")return null;
  try{return validateBackupRecoveryReadinessV4(value,clusterRecoveryPolicy) as BackupRecoveryReadiness;}catch{return null;}
}

function parseLegacy(value:unknown):LegacyBackupVerification|null{
  if(!record(value)||!exact(value,["schema_version","result","backup_id","created_at","verified_at","application_version","git_commit","migration_head","artifacts"])||value.schema_version!==1||value.result!=="VERIFIED"||!identifier(value.backup_id)||!iso(value.created_at)||!iso(value.verified_at)||typeof value.application_version!=="string"||!VERSION.test(value.application_version)||typeof value.git_commit!=="string"||!COMMIT.test(value.git_commit)||typeof value.migration_head!=="string"||!MIGRATION.test(value.migration_head)||!record(value.artifacts)||!exact(value.artifacts,Object.keys(LEGACY_FILES)))return null;
  for(const key of Object.keys(LEGACY_FILES) as Array<keyof typeof LEGACY_FILES>)if(!artifact(value.artifacts[key],LEGACY_FILES[key],key!=="postgresql_dump"))return null;
  return value as unknown as LegacyBackupVerification;
}

export function parseRuntimeReleaseIdentity(value:unknown):RuntimeReleaseIdentity|null{
  if(!record(value)||!exact(value,["schema_version","contract","deployment_class","deployment_id","release_id","release_manifest_sha256","postdeploy_receipt_sha256","supervisor_bundle_sha256","authorization_sha256","runtime_guard","runtime_policy_sha256","application_version","git_commit","git_tree","migration_head","migration_manifest_sha256","caddy_container_id","caddy_image_digest","postgres_container_id","postgres_image_digest","web_container_id","web_image_digest","worker_container_id","worker_image_digest","generated_at"]))return null;
  const control=[value.release_manifest_sha256,value.postdeploy_receipt_sha256,value.supervisor_bundle_sha256,value.authorization_sha256,value.runtime_policy_sha256,value.migration_manifest_sha256],containers=[value.caddy_container_id,value.postgres_container_id,value.web_container_id,value.worker_container_id],images=[value.caddy_image_digest,value.postgres_image_digest,value.web_image_digest,value.worker_image_digest];
  if(value.schema_version!==3||value.contract!==RELEASE_IDENTITY_CONTRACT||typeof value.deployment_class!=="string"||!CLASSES.has(value.deployment_class)||!identifier(value.deployment_id)||!identifier(value.release_id)||!control.every(item=>typeof item==="string"&&SHA.test(item))||value.runtime_policy_sha256!==RELEASE_RUNTIME_POLICY_SHA256||!record(value.runtime_guard)||!exact(value.runtime_guard,["contract","mode"])||value.runtime_guard.contract!==RELEASE_RUNTIME_GUARD_CONTRACT||value.runtime_guard.mode!==POST_DEPLOY_RUNTIME_GUARD_MODE||typeof value.application_version!=="string"||!VERSION.test(value.application_version)||typeof value.git_commit!=="string"||!COMMIT.test(value.git_commit)||typeof value.git_tree!=="string"||!COMMIT.test(value.git_tree)||typeof value.migration_head!=="string"||!MIGRATION.test(value.migration_head)||!containers.every(item=>typeof item==="string"&&CONTAINER_ID.test(item))||new Set(containers).size!==4||!images.every(item=>typeof item==="string"&&IMAGE.test(item))||new Set(images).size!==4||typeof value.generated_at!=="string"||!/\.\d{3}Z$/.test(value.generated_at)||!iso(value.generated_at))return null;
  return value as unknown as RuntimeReleaseIdentity;
}

export type BackupExpectedIdentity={deploymentClass:"TEST"|"UAT"|"PRODUCTION";deploymentId:string;databaseName:string;databaseSystemIdentifier:string;databaseOid:string;databaseMarker:string;databaseServerMajor:string;databaseEncoding:string;databaseCollate:string;databaseCtype:string;databaseLocaleProvider:string;databaseCollationVersion:string;applicationVersion:string;gitCommit:string;webImageDigest:string;workerImageDigest:string;migrationHead:string;migrationManifestSha256:string;policyId:string;rpoHours:number;operationsPolicyId:string;operationsPolicySha256:string;operationsPolicyScope:"TEST"|"UAT"|"PRODUCTION";offhostLocationId:string;offhostReceiverIdentitySha256:string;restoreLocationId:string;restoreTargetDeploymentId:string;restoreTargetSystemIdentifier:string;restoreTargetClusterMarkerId:string;trustMode:"TRUSTED_ROOT_EXECUTOR"};
export type RuntimeIdentity={database?:{name:string;system_identifier:string;oid:string;marker:string;server_major:string;encoding:string;collate:string;ctype:string;locale_provider:string;collation_version:string};applicationVersion?:string;gitCommit?:string;migrationHead?:string;migrationManifestSha256?:string;hostname?:string};

async function trustedReleaseText(file:string,gid:number,mode:number,maxBytes:number){
  const before=await lstat(file);if(!before.isFile()||before.isSymbolicLink()||before.nlink!==1||before.uid!==0||before.gid!==gid||(before.mode&0o7777)!==mode||before.size<2||before.size>maxBytes)throw new Error("unsafe release identity file");
  const handle=await open(file,constants.O_RDONLY|constants.O_NOFOLLOW);try{const opened=await handle.stat();if(opened.dev!==before.dev||opened.ino!==before.ino)throw new Error("release identity replaced");const text=await handle.readFile("utf8"),afterHandle=await handle.stat(),afterPath=await lstat(file);if(afterHandle.dev!==opened.dev||afterHandle.ino!==opened.ino||afterHandle.size!==opened.size||afterHandle.mtimeMs!==opened.mtimeMs||afterHandle.ctimeMs!==opened.ctimeMs||afterPath.dev!==opened.dev||afterPath.ino!==opened.ino||afterPath.uid!==0||afterPath.gid!==gid||afterPath.nlink!==1||(afterPath.mode&0o7777)!==mode)throw new Error("release identity changed");return text;}finally{await handle.close();}
}

async function runtimeReleaseIdentity(file:string):Promise<RuntimeReleaseIdentity|null>{
  try{
    const gid=typeof process.getgid==="function"?process.getgid():-1,root=dirname(file);if(gid<0||file!==join(root,"release-identity.json")||await realpath(root)!==root)return null;
    const rootStat=await lstat(root);if(!rootStat.isDirectory()||rootStat.isSymbolicLink()||rootStat.uid!==0||rootStat.gid!==gid||(rootStat.mode&0o7777)!==0o750)return null;
    if((await trustedReleaseText(join(root,RELEASE_ROOT_MARKER),gid,0o440,256))!==RELEASE_ROOT_MARKER_VALUE)return null;
    return parseRuntimeReleaseIdentity(new StrictJson(await trustedReleaseText(file,gid,0o440,64*1024)).parse());
  }catch{return null;}
}

async function configuredIdentity(runtime:RuntimeIdentity,releaseIdentityFile:string,now:number):Promise<BackupExpectedIdentity|null>{
  const deploymentClass=(process.env.ERP_DEPLOYMENT_CLASS||"").toUpperCase(),deploymentId=process.env.ERP_RELEASE_EXPECTED_DEPLOYMENT_ID||"",approvedVersion=process.env.ERP_RELEASE_EXPECTED_VERSION||"",approvedGit=process.env.ERP_RELEASE_EXPECTED_GIT_COMMIT||"",approvedManifest=process.env.ERP_RELEASE_EXPECTED_MANIFEST_SHA256||"",approvedSupervisor=process.env.ERP_RELEASE_EXPECTED_SUPERVISOR_BUNDLE_SHA256||"",maxAgeSeconds=Number(process.env.ERP_RELEASE_IDENTITY_MAX_AGE_SECONDS||0);
  const release=await runtimeReleaseIdentity(releaseIdentityFile),generated=release?Date.parse(release.generated_at):Number.NaN,hostname=runtime.hostname||"";
  if(!release||!Number.isSafeInteger(maxAgeSeconds)||maxAgeSeconds<60||maxAgeSeconds>604800||generated>now+5*60*1000||now-generated>maxAgeSeconds*1000||!SHA.test(approvedManifest)||!SHA.test(approvedSupervisor)||!RUNTIME_HOSTNAME.test(hostname)||!release.web_container_id.startsWith(hostname)||release.deployment_class!==deploymentClass||release.deployment_id!==deploymentId||release.release_manifest_sha256!==approvedManifest||release.supervisor_bundle_sha256!==approvedSupervisor||release.application_version!==approvedVersion||release.git_commit!==approvedGit||release.migration_head!==runtime.migrationHead||release.migration_manifest_sha256!==runtime.migrationManifestSha256||runtime.applicationVersion!==approvedVersion||runtime.gitCommit!==approvedGit)return null;
  const candidate={deploymentClass,deploymentId,databaseName:runtime.database?.name||"",databaseSystemIdentifier:runtime.database?.system_identifier||"",databaseOid:runtime.database?.oid||"",databaseMarker:`${deploymentClass}.${deploymentId}`,databaseServerMajor:runtime.database?.server_major||"",databaseEncoding:runtime.database?.encoding||"",databaseCollate:runtime.database?.collate||"",databaseCtype:runtime.database?.ctype||"",databaseLocaleProvider:runtime.database?.locale_provider||"",databaseCollationVersion:runtime.database?.collation_version||"",applicationVersion:release.application_version,gitCommit:release.git_commit,webImageDigest:release.web_image_digest,workerImageDigest:release.worker_image_digest,migrationHead:runtime.migrationHead||"",migrationManifestSha256:runtime.migrationManifestSha256||"",policyId:process.env.ERP_BACKUP_POLICY_ID||"",rpoHours:Number(process.env.ERP_BACKUP_RPO_HOURS||0),operationsPolicyId:process.env.ERP_BACKUP_OPERATIONS_POLICY_ID||"",operationsPolicySha256:process.env.ERP_BACKUP_OPERATIONS_POLICY_SHA256||"",operationsPolicyScope:(process.env.ERP_BACKUP_OPERATIONS_POLICY_SCOPE||"").toUpperCase(),offhostLocationId:process.env.ERP_BACKUP_EXPECTED_OFFHOST_LOCATION_ID||"",offhostReceiverIdentitySha256:process.env.ERP_BACKUP_EXPECTED_OFFHOST_RECEIVER_IDENTITY_SHA256||"",restoreLocationId:process.env.ERP_BACKUP_EXPECTED_RESTORE_LOCATION_ID||"",restoreTargetDeploymentId:process.env.ERP_BACKUP_EXPECTED_RESTORE_TARGET_ID||"",restoreTargetSystemIdentifier:process.env.ERP_BACKUP_EXPECTED_RESTORE_TARGET_SYSTEM_IDENTIFIER||"",restoreTargetClusterMarkerId:process.env.ERP_BACKUP_EXPECTED_RESTORE_TARGET_CLUSTER_MARKER_ID||"",trustMode:process.env.ERP_BACKUP_EVIDENCE_TRUST_MODE||""};
  const marker=`chenyida-erp-deployment/v2:${deploymentClass}:${deploymentId}`;
  if(!CLASSES.has(candidate.deploymentClass)||!identifier(candidate.deploymentId)||!identifier(candidate.databaseName)||!decimalIdentifier(candidate.databaseSystemIdentifier)||!decimalIdentifier(candidate.databaseOid)||!decimalIdentifier(candidate.databaseServerMajor)||![candidate.databaseEncoding,candidate.databaseCollate,candidate.databaseCtype,candidate.databaseLocaleProvider,candidate.databaseCollationVersion].every(identifier)||candidate.databaseLocaleProvider!=="libc"||runtime.database?.marker!==marker||!VERSION.test(candidate.applicationVersion)||!COMMIT.test(candidate.gitCommit)||!IMAGE.test(candidate.webImageDigest)||!IMAGE.test(candidate.workerImageDigest)||!MIGRATION.test(candidate.migrationHead)||!SHA.test(candidate.migrationManifestSha256)||!identifier(candidate.policyId)||!Number.isSafeInteger(candidate.rpoHours)||candidate.rpoHours<1||candidate.rpoHours>168||!identifier(candidate.operationsPolicyId)||!SHA.test(candidate.operationsPolicySha256)||!new Set(["TEST","UAT","PRODUCTION"]).has(candidate.operationsPolicyScope)||candidate.operationsPolicyScope!==candidate.deploymentClass||!identifier(candidate.offhostLocationId)||!SHA.test(candidate.offhostReceiverIdentitySha256)||!identifier(candidate.restoreLocationId)||!identifier(candidate.restoreTargetDeploymentId)||!decimalIdentifier(candidate.restoreTargetSystemIdentifier)||candidate.restoreTargetSystemIdentifier===candidate.databaseSystemIdentifier||!identifier(candidate.restoreTargetClusterMarkerId)||candidate.trustMode!=="TRUSTED_ROOT_EXECUTOR")return null;
  return candidate as BackupExpectedIdentity;
}

async function safeStatusText(statusFile:string){
  const gid=typeof process.getgid==="function"?process.getgid():-1,root=dirname(statusFile);if(gid<0||!new Set(["latest.json","recovery-readiness.json"]).has(basename(statusFile))||await realpath(root)!==root)throw new Error("unsafe receipt path");
  const rootStat=await lstat(root);if(!rootStat.isDirectory()||rootStat.isSymbolicLink()||rootStat.uid!==0||rootStat.gid!==gid||(rootStat.mode&0o7777)!==0o2750)throw new Error("unsafe receipt root");
  const markerPath=join(root,RECEIPT_ROOT_MARKER),marker=await lstat(markerPath),markerMode=marker.mode&0o7777;if(!marker.isFile()||marker.isSymbolicLink()||marker.nlink!==1||marker.uid!==0||marker.gid!==gid||![0o400,0o440].includes(markerMode)||marker.size<2||marker.size>128||await trustedReleaseText(markerPath,gid,markerMode,128)!==RECEIPT_ROOT_MARKER_VALUE)throw new Error("unsafe receipt marker");
  const before=await lstat(statusFile);if(!before.isFile()||before.isSymbolicLink()||before.nlink!==1||before.uid!==0||before.gid!==gid||(before.mode&0o7777)!==0o640||before.size<2||before.size>1024*1024)throw new Error("unsafe receipt");
  const handle=await open(statusFile,constants.O_RDONLY|constants.O_NOFOLLOW);try{const opened=await handle.stat();if(opened.dev!==before.dev||opened.ino!==before.ino||opened.size!==before.size||opened.mtimeMs!==before.mtimeMs||opened.ctimeMs!==before.ctimeMs)throw new Error("receipt replaced");const text=await handle.readFile("utf8"),after=await handle.stat(),pathAfter=await lstat(statusFile);if(after.dev!==opened.dev||after.ino!==opened.ino||after.size!==opened.size||after.mtimeMs!==opened.mtimeMs||after.ctimeMs!==opened.ctimeMs||pathAfter.dev!==opened.dev||pathAfter.ino!==opened.ino||pathAfter.nlink!==1||pathAfter.uid!==0||pathAfter.gid!==gid||(pathAfter.mode&0o7777)!==0o640)throw new Error("receipt changed");return text;}finally{await handle.close();}
}

type SafeBackupVerification=Readonly<{backup_id:string;result:string;verified_at:string;recovery_point_at:string|null;expires_at:string|null}>;
const safeLegacyVerification=(value:LegacyBackupVerification):SafeBackupVerification=>({backup_id:value.backup_id,result:"LEGACY_LOCAL_ONLY",verified_at:value.verified_at,recovery_point_at:null,expires_at:null});
const safeV2Verification=(value:BackupVerification):SafeBackupVerification=>({backup_id:value.backup_id,result:"LEGACY_V2_INNER_ONLY",verified_at:value.verified_at,recovery_point_at:value.consistency.recovery_point_at,expires_at:value.expires_at});
const safeRecoveryReadinessV3=(value:BackupRecoveryReadinessV3,result:string=value.result):SafeBackupVerification=>({backup_id:value.backup_id,result,verified_at:value.verified_at,recovery_point_at:value.inner_restore.receipt.consistency.recovery_point_at,expires_at:value.expires_at});
const safeRecoveryReadiness=(value:BackupRecoveryReadiness):SafeBackupVerification=>({backup_id:value.backup_id,result:value.result,verified_at:value.verified_at,recovery_point_at:value.data_readiness.receipt.inner_restore.receipt.consistency.recovery_point_at,expires_at:value.expires_at});

export async function backupGovernance(statusFile:string,options:{now?:Date;expectedIdentity?:BackupExpectedIdentity;runtimeIdentity?:RuntimeIdentity;releaseIdentityFile?:string}={}){
  const base={mode:"OFFLINE_ONLY",browser_create_enabled:false,browser_restore_enabled:false,restore_target:"TASK_CREATED_DISPOSABLE_TEST_DATABASE_ONLY",cross_failure_domain_required:true,consistency:"QUIESCED_APPLICATION_AND_SNAPSHOT_WITH_CONTENT_RECONCILIATION",verification_status:"UNVERIFIED",evidence_scope:"NONE",transfer_status:"UNVERIFIED",encryption_status:"UNVERIFIED",cluster_transfer_status:"UNVERIFIED",cluster_security_status:"UNVERIFIED",credential_binding_status:"UNVERIFIED",tablespace_status:"UNVERIFIED",recovery_execution_status:"UNVERIFIED",schedule_status:"UNCONFIGURED",retention_status:"UNCONFIGURED",identity_status:"UNCONFIGURED",policy_status:"UNCONFIGURED",assurance_status:"UNCONFIGURED",recovery_ready:false,latest_verification:null as SafeBackupVerification|null};
  try{
    const suppliedNow=options.now||new Date(),now=suppliedNow instanceof Date?suppliedNow.getTime():Number.NaN;if(!Number.isFinite(now))return{...base,verification_status:"INVALID"};
    const raw=new StrictJson(await safeStatusText(statusFile)).parse(),legacy=parseLegacy(raw);if(legacy)return{...base,verification_status:"LEGACY_LOCAL_ONLY",evidence_scope:"LEGACY_V1_LOCAL_ONLY",latest_verification:safeLegacyVerification(legacy)};
    const legacyV2=parseBackupVerification(raw);if(legacyV2)return{...base,verification_status:"LEGACY_V2_INNER_ONLY",evidence_scope:"LEGACY_V2_INNER_ONLY",latest_verification:safeV2Verification(legacyV2)};
    const legacyV3=parseBackupRecoveryReadinessV3(raw);if(legacyV3)return{...base,verification_status:"LEGACY_V3_NO_CLUSTER_SECURITY",evidence_scope:"LEGACY_V3_NO_CLUSTER_SECURITY",transfer_status:"VERIFIED",encryption_status:"VERIFIED",schedule_status:legacyV3.operations.schedule_status,retention_status:legacyV3.operations.retention_status,latest_verification:safeRecoveryReadinessV3(legacyV3,"LEGACY_V3_NO_CLUSTER_SECURITY")};
    const parsed=parseBackupRecoveryReadiness(raw);if(!parsed)return{...base,verification_status:"INVALID"};
    const data=parsed.data_readiness.receipt,restore=data.inner_restore.receipt,created=Date.parse(parsed.created_at),verified=Date.parse(parsed.verified_at),recoveryPoint=Date.parse(restore.consistency.recovery_point_at);if(created>now+5*60*1000||verified>now+5*60*1000||recoveryPoint>now+5*60*1000)return{...base,verification_status:"INVALID"};
    const expected=options.expectedIdentity??await configuredIdentity(options.runtimeIdentity||{},options.releaseIdentityFile||RUNTIME_RELEASE_IDENTITY_FILE,now);
    const identityMatch=!!expected&&restore.deployment.class===expected.deploymentClass&&restore.deployment.id===expected.deploymentId&&restore.deployment.database===expected.databaseName&&restore.deployment.database_system_identifier===expected.databaseSystemIdentifier&&restore.deployment.database_oid===expected.databaseOid&&restore.deployment.database_marker===expected.databaseMarker&&restore.deployment.database_server_major===expected.databaseServerMajor&&restore.deployment.database_encoding===expected.databaseEncoding&&restore.deployment.database_collate===expected.databaseCollate&&restore.deployment.database_ctype===expected.databaseCtype&&restore.deployment.database_locale_provider===expected.databaseLocaleProvider&&restore.deployment.database_collation_version===expected.databaseCollationVersion&&restore.application.version===expected.applicationVersion&&restore.application.git_commit===expected.gitCommit&&restore.application.web_image_digest===expected.webImageDigest&&restore.application.worker_image_digest===expected.workerImageDigest&&restore.migration.head===expected.migrationHead&&restore.migration.manifest_sha256===expected.migrationManifestSha256;
    const policyMatch=!!expected&&restore.policy.id===expected.policyId&&restore.policy.rpo_hours===expected.rpoHours&&data.operations.policy_id===expected.operationsPolicyId&&data.operations.policy_sha256===expected.operationsPolicySha256&&data.operations.policy_scope===expected.operationsPolicyScope;
    const assuranceMatch=!!expected&&parsed.result==="RECOVERY_READY"&&parsed.evidence_scope==="ACTUAL_OFFHOST"&&data.transfer.receiver_location_id===expected.offhostLocationId&&data.transfer.receiver_identity_sha256===expected.offhostReceiverIdentitySha256&&restore.location_id===expected.restoreLocationId&&restore.evidence.kind==="ISOLATED_RESTORE_VERIFICATION"&&restore.evidence.target.deployment_id===expected.restoreTargetDeploymentId&&restore.evidence.target.database_system_identifier===expected.restoreTargetSystemIdentifier&&restore.evidence.target.cluster_marker_id===expected.restoreTargetClusterMarkerId&&expected.trustMode==="TRUSTED_ROOT_EXECUTOR";
    const policyExpiry=expected?recoveryPoint+expected.rpoHours*60*60*1000:Date.parse(parsed.expires_at),stale=now>Math.min(Date.parse(parsed.expires_at),policyExpiry);
    const identityStatus=expected?(identityMatch?"MATCHED":"MISMATCH"):"UNCONFIGURED",policyStatus=expected?(policyMatch?"MATCHED":"MISMATCH"):"UNCONFIGURED",assuranceStatus=expected?(assuranceMatch?"MATCHED":"MISMATCH"):"UNCONFIGURED";
    const chainStatus={evidence_scope:parsed.evidence_scope,transfer_status:"VERIFIED",encryption_status:"VERIFIED",cluster_transfer_status:parsed.status.cluster_transfer,cluster_security_status:parsed.status.cluster_security,credential_binding_status:parsed.status.credential_binding,tablespace_status:parsed.status.tablespace,recovery_execution_status:parsed.status.recovery_execution,schedule_status:data.operations.schedule_status,retention_status:data.operations.retention_status};
    if(stale)return{...base,...chainStatus,verification_status:"STALE",identity_status:identityStatus,policy_status:policyStatus,assurance_status:assuranceStatus,latest_verification:safeRecoveryReadiness(parsed)};
    return{...base,...chainStatus,verification_status:parsed.result,identity_status:identityStatus,policy_status:policyStatus,assurance_status:assuranceStatus,recovery_ready:parsed.result==="RECOVERY_READY"&&identityMatch&&policyMatch&&assuranceMatch,latest_verification:safeRecoveryReadiness(parsed)};
  }catch(error){return{...base,verification_status:(error as NodeJS.ErrnoException)?.code==="ENOENT"?"UNVERIFIED":"INVALID"};}
}
