import type {Pool,PoolClient} from "pg";
import type {DashboardSnapshot,DecimalSummary,MigrationStatus,SafeAuditEvent,SafeBusinessEvent} from "./types.ts";
const integer=(value:unknown)=>Number.parseInt(String(value??"0"),10)||0;const decimal=(value:unknown)=>String(value??"0.000000");
export interface DashboardRepositoryPort{readSnapshot():Promise<DashboardSnapshot>}
export class PostgresDashboardRepository implements DashboardRepositoryPort{
  private readonly pool:Pool;constructor(pool:Pool){this.pool=pool;}
  async readSnapshot(){const client=await this.pool.connect();try{await client.query("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY");const value=await this.read(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}}
  private async read(client:PoolClient):Promise<DashboardSnapshot>{
    const core=await client.query(`select
      (select count(*) from material_master where material_status='ACTIVE') active_materials,(select count(*) from supplier_mappings where status='ACTIVE') total_mappings,(select count(*) from material_master where material_status in ('DRAFT','PENDING_REVIEW')) pending_materials,
      (select count(*) from material_import_review_rows where disposition='BIND_EXISTING') auto_count,(select count(*) from material_import_review_rows where row_status='PENDING') suspect_count,(select count(*) from material_import_review_rows where disposition='CREATE_DRAFT') new_count,
      (select count(*) from customers where status='ACTIVE') active_customers,(select count(*) from suppliers where status='ACTIVE') active_suppliers,
      (select count(*) from product_versions where status='RELEASED') released_products,(select count(*) from bom_versions bv join bom_headers bh on bh.id=bv.bom_header_id where bv.status='RELEASED' and bh.status='ACTIVE') valid_boms,
      (select count(distinct material_id) from inventory_stock_balances where on_hand_qty>0) inventory_material_kinds,(select count(distinct material_id) from inventory_stock_balances where on_hand_qty-reserved_qty-frozen_qty=0) inventory_zero_available_kinds,
      (select count(*) from purchase_orders) total_purchase_orders,(select count(*) from purchase_orders where status in ('OPEN','PARTIALLY_RECEIVED')) open_purchase_orders,(select coalesce(sum(order_qty-received_qty),0)::text from purchase_order_lines where status in ('OPEN','PARTIALLY_RECEIVED')) pending_receipt_qty,
      (select count(*) from production_work_orders) total_work_orders,(select count(*) from production_work_orders where status in ('RELEASED','IN_PROGRESS')) active_work_orders,(select coalesce(sum(pmr.required_qty-pmr.net_issued_qty),0)::text from production_material_requirements pmr join production_work_orders pwo on pwo.id=pmr.work_order_id where pwo.status in ('RELEASED','IN_PROGRESS')) pending_issue_qty,
      (select coalesce(sum(planned_qty-completed_qty),0)::text from production_work_orders where status in ('RELEASED','IN_PROGRESS','COMPLETED')) pending_completion_qty,(select count(*) from production_material_requirements pmr join production_work_orders pwo on pwo.id=pmr.work_order_id left join inventory_stock_balances b on b.material_id=pmr.material_id where pwo.status in ('RELEASED','IN_PROGRESS') and pmr.required_qty-pmr.net_issued_qty>coalesce(b.on_hand_qty-b.reserved_qty-b.frozen_qty,0)) shortage_requirement_count,
      (select count(*) from sales_quotations) total_quotations,(select count(*) from sales_quotations where status in ('DRAFT','PUBLISHED','ACCEPTED')) open_quotations,(select count(*) from sales_orders) total_sales_orders,(select count(*) from sales_orders where status in ('OPEN','PARTIALLY_SHIPPED')) open_sales_orders,(select coalesce(sum(ordered_qty-shipped_qty),0)::text from sales_orders where status in ('OPEN','PARTIALLY_SHIPPED')) pending_shipment_qty,
      (select count(*) from quality_inspections) total_quality_inspections,(select count(*) from quality_inspections where inspection_type='IQC' and lifecycle_status='OPEN') pending_iqc,(select count(*) from quality_inspections where inspection_type='IPQC' and lifecycle_status='OPEN') pending_ipqc,(select count(*) from quality_inspections where inspection_type='FQC' and lifecycle_status='OPEN') pending_fqc,(select count(*) from quality_inspections where lifecycle_status='OPEN' and (decision_status='HOLD' or failed_qty>0)) open_quality_exceptions,
      (select coalesce(sum(total_amount) filter(where doc_type='AR'),0)::text from finance_documents) ar_total,(select coalesce(sum(settled_amount) filter(where doc_type='AR'),0)::text from finance_documents) ar_settled,(select coalesce(sum(total_amount-settled_amount) filter(where doc_type='AR'),0)::text from finance_documents) ar_balance,
      (select coalesce(sum(total_amount) filter(where doc_type='AP'),0)::text from finance_documents) ap_total,(select coalesce(sum(settled_amount) filter(where doc_type='AP'),0)::text from finance_documents) ap_settled,(select coalesce(sum(total_amount-settled_amount) filter(where doc_type='AP'),0)::text from finance_documents) ap_balance,
      (select coalesce(sum(amount) filter(where settlement_type in ('RECEIPT','RECEIPT_REVERSAL')),0)::text from finance_settlements) net_receipts,(select coalesce(sum(amount) filter(where settlement_type in ('PAYMENT','PAYMENT_REVERSAL')),0)::text from finance_settlements) net_payments,
      (select count(*) from background_jobs where status in ('QUEUED','RUNNING')) pending_jobs,(select count(*) from background_jobs where status in ('FAILED','DEAD')) failed_jobs`);
    const quantities=await client.query("select u.code unit,coalesce(sum(b.on_hand_qty),0)::text on_hand,coalesce(sum(b.on_hand_qty-b.reserved_qty-b.frozen_qty),0)::text available,coalesce(sum(b.frozen_qty),0)::text frozen from inventory_stock_balances b join units u on u.id=b.unit_id group by u.code order by u.code limit 20");
    const migrations=await client.query("select version,checksum,applied_at::text from schema_migrations order by version desc limit 20");
    const events=await client.query(`select domain,action,object_code,actor,request_id::text,created_at::text from (
      select 'procurement' domain,e.event_type action,p.po_code object_code,e.created_by actor,e.request_id,e.created_at from purchase_order_status_events e join purchase_orders p on p.id=e.purchase_order_id
      union all select 'production',e.event_type,w.work_order_code,e.created_by,e.request_id,e.created_at from production_work_order_status_events e join production_work_orders w on w.id=e.work_order_id
      union all select 'sales',e.event_type,s.sales_order_code,e.created_by,e.request_id,e.created_at from sales_order_status_events e join sales_orders s on s.id=e.sales_order_id
      union all select 'quality',e.event_type,q.inspection_code,e.created_by,e.request_id,e.created_at from quality_inspection_events e join quality_inspections q on q.id=e.inspection_id
      union all select 'finance',e.event_type,d.doc_code,e.created_by,e.request_id,e.created_at from finance_document_events e join finance_documents d on d.id=e.document_id) e order by created_at desc limit 30`);
    const audits=await client.query("select action,result,username,route_code,request_id::text,created_at::text from audit_log order by id desc limit 20");
    const r=core.rows[0]??{};return{active_materials:integer(r.active_materials),total_mappings:integer(r.total_mappings),pending_materials:integer(r.pending_materials),auto_count:integer(r.auto_count),suspect_count:integer(r.suspect_count),new_count:integer(r.new_count),active_customers:integer(r.active_customers),active_suppliers:integer(r.active_suppliers),released_products:integer(r.released_products),valid_boms:integer(r.valid_boms),inventory_material_kinds:integer(r.inventory_material_kinds),inventory_zero_available_kinds:integer(r.inventory_zero_available_kinds),inventory_quantities:quantities.rows.map((x):DecimalSummary=>({unit:String(x.unit),on_hand:decimal(x.on_hand),available:decimal(x.available),frozen:decimal(x.frozen)})),total_purchase_orders:integer(r.total_purchase_orders),open_purchase_orders:integer(r.open_purchase_orders),pending_receipt_qty:decimal(r.pending_receipt_qty),total_work_orders:integer(r.total_work_orders),active_work_orders:integer(r.active_work_orders),pending_issue_qty:decimal(r.pending_issue_qty),pending_completion_qty:decimal(r.pending_completion_qty),shortage_requirement_count:integer(r.shortage_requirement_count),total_quotations:integer(r.total_quotations),open_quotations:integer(r.open_quotations),total_sales_orders:integer(r.total_sales_orders),open_sales_orders:integer(r.open_sales_orders),pending_shipment_qty:decimal(r.pending_shipment_qty),total_quality_inspections:integer(r.total_quality_inspections),pending_iqc:integer(r.pending_iqc),pending_ipqc:integer(r.pending_ipqc),pending_fqc:integer(r.pending_fqc),open_quality_exceptions:integer(r.open_quality_exceptions),ar_total:decimal(r.ar_total),ar_settled:decimal(r.ar_settled),ar_balance:decimal(r.ar_balance),ap_total:decimal(r.ap_total),ap_settled:decimal(r.ap_settled),ap_balance:decimal(r.ap_balance),net_receipts:decimal(r.net_receipts),net_payments:decimal(r.net_payments),pending_jobs:integer(r.pending_jobs),failed_jobs:integer(r.failed_jobs),migrations:migrations.rows.map((x):MigrationStatus=>({version:String(x.version),checksum:String(x.checksum),applied_at:String(x.applied_at)})),recent_events:events.rows.map((x):SafeBusinessEvent=>({domain:String(x.domain),action:String(x.action),object_code:String(x.object_code),actor:String(x.actor),request_id:String(x.request_id),created_at:String(x.created_at)})),recent_audits:audits.rows.map((x):SafeAuditEvent=>({action:String(x.action),result:String(x.result),username:String(x.username),route_code:String(x.route_code),request_id:String(x.request_id),created_at:String(x.created_at)})),generated_at:new Date().toISOString()};
  }
}
