import {hasPermission} from "../identity-selfhost/permissions.ts";import {backupGovernance} from "./backup-status.ts";import {DashboardError} from "./errors.ts";import {canReadDomain,permittedModules,requireDashboard,requireManagement} from "./permissions.ts";import type {DashboardRepositoryPort} from "./repository.ts";import type {DashboardActor,DashboardDomain,DashboardMetric,DashboardModule,DashboardRisk,DashboardSnapshot,DashboardSummary} from "./types.ts";
const MODULES:DashboardModule[]=[
 {code:"market-projects",label:"市场部门",description:"客户需求整理、修订与项目交接",href:"/business/projects",permission:"project.market.create",native:true},{code:"engineering-projects",label:"项目部门",description:"待接收项目、退回与已接收记录",href:"/engineering/projects",permission:"project.engineering.read",native:true},{code:"planning-handoffs",label:"计划部门",description:"项目产品、BOM 与零件规格交接",href:"/planning/handoffs",permission:"planning.read",native:true},
 {code:"material-requirements",label:"物料需求计划",description:"交接包汇总、库存/在途分配与提交",href:"/planning/material-requirements",permission:"planning.requirement.read",native:true},{code:"purchase-requests",label:"采购申请交接",description:"接收或退回净采购申请",href:"/planning/purchase-requests",permission:"planning.purchase_request.read",native:true},
 {code:"procurement-sourcing",label:"采购询价与定标",description:"候选供应商、报价版本、服务端比价与人工定标",href:"/procurement/sourcing",permission:"procurement.rfq.read",native:true},
 {code:"material",label:"物料 / 导入 / 审核",description:"原生物料主数据中心",href:"/materials",permission:"material.read",native:true},{code:"partners",label:"客户 / 供应商",description:"往来单位主数据",href:"/erp/index.html?tab=partners",permission:"master.customer.read",native:false},{code:"engineering",label:"产品 / BOM",description:"产品版本与有效 BOM",href:"/erp/index.html?tab=bom",permission:"master.bom.read",native:false},{code:"inventory",label:"库存",description:"余额、冻结与调整账本",href:"/erp/index.html?tab=purchase",permission:"inventory.read",native:false},{code:"procurement",label:"采购",description:"采购单、收货与冲销",href:"/erp/index.html?tab=purchase",permission:"procurement.read",native:false},{code:"production",label:"生产",description:"工单、领退料、报工与完工",href:"/erp/index.html?tab=production",permission:"production.read",native:false},{code:"sales",label:"销售",description:"报价、订单与出货",href:"/erp/index.html?tab=sales",permission:"sales.read",native:false},{code:"quality",label:"品质",description:"IQC / IPQC / FQC",href:"/erp/index.html?tab=quality",permission:"quality.read",native:false},{code:"finance",label:"财务",description:"AR / AP 与结算",href:"/erp/index.html?tab=finance",permission:"finance.read",native:false},{code:"users",label:"用户 / 审计",description:"账号和受控审计",href:"/erp/index.html?tab=operations",permission:"system.user.read",native:false},{code:"operations",label:"运维 / 备份状态",description:"只读治理；操作必须离线",href:"/#operations",permission:"system.backup.read",native:true},
];
const domainGroup=(s:DashboardSnapshot,d:DashboardDomain):unknown=>({material:{active_materials:s.active_materials},partners:{active_customers:s.active_customers,active_suppliers:s.active_suppliers},engineering:{released_products:s.released_products,valid_boms:s.valid_boms},inventory:{material_kinds:s.inventory_material_kinds,zero_available_kinds:s.inventory_zero_available_kinds,quantity_by_unit:s.inventory_quantities},procurement:{open_orders:s.open_purchase_orders,pending_receipt_qty:s.pending_receipt_qty},production:{active_work_orders:s.active_work_orders,pending_issue_qty:s.pending_issue_qty,pending_completion_qty:s.pending_completion_qty,shortage_requirement_count:s.shortage_requirement_count},sales:{open_orders:s.open_sales_orders,pending_shipment_qty:s.pending_shipment_qty},quality:{pending_iqc:s.pending_iqc,pending_ipqc:s.pending_ipqc,pending_fqc:s.pending_fqc,open_exceptions:s.open_quality_exceptions},finance:{ar_total:s.ar_total,ar_settled:s.ar_settled,ar_balance:s.ar_balance,ap_total:s.ap_total,ap_settled:s.ap_settled,ap_balance:s.ap_balance,net_receipts:s.net_receipts,net_payments:s.net_payments},operations:{pending_jobs:s.pending_jobs,failed_jobs:s.failed_jobs,migrations:s.migrations}}[d]);
export class DashboardService{
 private readonly repository:DashboardRepositoryPort;private readonly backupStatusFile:string;constructor(repository:DashboardRepositoryPort,backupStatusFile:string){this.repository=repository;this.backupStatusFile=backupStatusFile;}
 private project(actor:DashboardActor,s:DashboardSnapshot):DashboardSummary{
  const groups:DashboardSummary["groups"]={};for(const d of ["material","partners","engineering","inventory","procurement","production","sales","quality","finance","operations"] as DashboardDomain[])if(canReadDomain(actor,d))groups[d]=domainGroup(s,d);
  return{generated_at:s.generated_at,authority:"Node/PostgreSQL",consistency:"REPEATABLE_READ_READ_ONLY",inventory_quantity_aggregated:false,groups,modules:permittedModules(actor,MODULES),
   ...(canReadDomain(actor,"material")?{total_items:s.active_materials,total_mappings:s.total_mappings,pending:s.pending_materials,auto_count:s.auto_count,suspect_count:s.suspect_count,new_count:s.new_count}:{}),
   ...(canReadDomain(actor,"partners")?{total_customers:s.active_customers,total_suppliers:s.active_suppliers}:{}),...(canReadDomain(actor,"engineering")?{total_products:s.released_products,total_boms:s.valid_boms}:{}),...(hasPermission(actor,"planning.read")?{pending_planning_handoffs:s.pending_planning_handoffs}:{}),...(hasPermission(actor,"planning.requirement.read")?{accepted_planning_packages:s.accepted_planning_packages}:{}),...(hasPermission(actor,"planning.purchase_request.read")?{pending_purchase_requests:s.pending_purchase_requests}:{}),...(hasPermission(actor,"procurement.rfq.read")?{pending_sourcing_requests:s.pending_sourcing_requests,pending_quote_rfqs:s.pending_quote_rfqs,pending_award_rfqs:s.pending_award_rfqs}:{}),
   ...(canReadDomain(actor,"procurement")?{total_pos:s.total_purchase_orders,open_pos:s.open_purchase_orders}:{}),...(canReadDomain(actor,"production")?{total_work_orders:s.total_work_orders,active_work_orders:s.active_work_orders}:{}),
   ...(canReadDomain(actor,"sales")?{total_quotations:s.total_quotations,open_quotations:s.open_quotations,total_sales_orders:s.total_sales_orders,open_sales_orders:s.open_sales_orders}:{}),
   ...(canReadDomain(actor,"quality")?{total_quality_inspections:s.total_quality_inspections,open_quality_issues:s.open_quality_exceptions}:{}),...(canReadDomain(actor,"finance")?{receivable_balance:s.ar_balance,payable_balance:s.ap_balance}:{}),...(canReadDomain(actor,"operations")?{pending_jobs:s.pending_jobs,failed_jobs:s.failed_jobs}:{}),
  };}
 async summary(actor:DashboardActor){requireDashboard(actor);return this.project(actor,await this.repository.readSnapshot());}
 async management(actor:DashboardActor){requireManagement(actor);const s=await this.repository.readSnapshot();const summary=this.project(actor,s);const activity=hasPermission(actor,"system.audit.read")?s.recent_audits.map(e=>({...e,detail:e.route_code})):[];const events=s.recent_events.filter(e=>canReadDomain(actor,e.domain as DashboardDomain)).slice(0,20);return{summary,modules:summary.modules,metrics:this.metrics(actor,s),risks:this.risks(actor,s),recent_events:events,recent_activity:activity};}
 private metrics(actor:DashboardActor,s:DashboardSnapshot){const result:DashboardMetric[]=[];const add=(d:DashboardDomain,i:DashboardMetric)=>{if(canReadDomain(actor,d))result.push(i)};add("material",{code:"materials",label:"ACTIVE 物料",value:s.active_materials,hint:"关系化主数据",tone:"neutral",href:"/materials"});if(hasPermission(actor,"planning.read"))result.push({code:"planning-handoffs",label:"待接收计划交接",value:s.pending_planning_handoffs,hint:"项目到计划交接",tone:s.pending_planning_handoffs?"warning":"neutral",href:"/planning/handoffs"});if(hasPermission(actor,"planning.requirement.read"))result.push({code:"material-requirements",label:"待核算交接包",value:s.accepted_planning_packages,hint:"库存与在途独立分配",tone:s.accepted_planning_packages?"warning":"neutral",href:"/planning/material-requirements"});if(hasPermission(actor,"planning.purchase_request.read"))result.push({code:"purchase-requests",label:"待接收采购申请",value:s.pending_purchase_requests,hint:"不自动创建 RFQ 或 PO",tone:s.pending_purchase_requests?"warning":"neutral",href:"/planning/purchase-requests"});if(hasPermission(actor,"procurement.rfq.read")){result.push({code:"pending-sourcing",label:"待询价采购申请",value:s.pending_sourcing_requests,hint:"已接收且无有效 RFQ",tone:s.pending_sourcing_requests?"warning":"neutral",href:"/procurement/sourcing"},{code:"pending-quotes",label:"待报价 RFQ",value:s.pending_quote_rfqs,hint:"至少一家受邀供应商未报价",tone:s.pending_quote_rfqs?"warning":"neutral",href:"/procurement/sourcing"},{code:"pending-awards",label:"待定标 RFQ",value:s.pending_award_rfqs,hint:"人工选择，不自动审批",tone:s.pending_award_rfqs?"warning":"neutral",href:"/procurement/sourcing"});}add("procurement",{code:"purchase",label:"未完成采购",value:s.open_purchase_orders,hint:`待收货 ${s.pending_receipt_qty}`,tone:s.open_purchase_orders?"warning":"neutral",href:"/erp/index.html?tab=purchase"});add("production",{code:"production",label:"进行中工单",value:s.active_work_orders,hint:`待完工 ${s.pending_completion_qty}`,tone:s.shortage_requirement_count?"danger":"info",href:"/erp/index.html?tab=production"});add("sales",{code:"sales",label:"未关闭销售单",value:s.open_sales_orders,hint:`待发货 ${s.pending_shipment_qty}`,tone:s.open_sales_orders?"info":"neutral",href:"/erp/index.html?tab=sales"});add("quality",{code:"quality",label:"品质异常",value:s.open_quality_exceptions,hint:`IQC ${s.pending_iqc} · IPQC ${s.pending_ipqc} · FQC ${s.pending_fqc}`,tone:s.open_quality_exceptions?"danger":"neutral",href:"/erp/index.html?tab=quality"});add("finance",{code:"ar",label:"应收余额",value:s.ar_balance,hint:"CNY · decimal",tone:/^0(?:\.0+)?$/.test(s.ar_balance)?"neutral":"warning",href:"/erp/index.html?tab=finance"});add("finance",{code:"ap",label:"应付余额",value:s.ap_balance,hint:"CNY · decimal",tone:/^0(?:\.0+)?$/.test(s.ap_balance)?"neutral":"info",href:"/erp/index.html?tab=finance"});add("operations",{code:"jobs",label:"后台任务",value:s.pending_jobs,hint:s.failed_jobs?`${s.failed_jobs} 个失败 / DEAD`:"队列 / 运行中",tone:s.failed_jobs?"danger":"neutral",href:"/materials/imports"});return result;}
 private risks(actor:DashboardActor,s:DashboardSnapshot){const result:DashboardRisk[]=[];const add=(d:DashboardDomain,i:DashboardRisk)=>{if(canReadDomain(actor,d))result.push(i)};if(s.open_quality_exceptions)add("quality",{code:"QUALITY_OPEN",level:"high",text:`${s.open_quality_exceptions} 项品质异常未关闭`,href:"/erp/index.html?tab=quality"});if(s.shortage_requirement_count)add("production",{code:"PRODUCTION_SHORTAGE",level:"high",text:`${s.shortage_requirement_count} 项工单需求超过可用库存`,href:"/erp/index.html?tab=production"});if(s.failed_jobs)add("operations",{code:"BACKGROUND_JOB_FAILED",level:"high",text:`${s.failed_jobs} 个后台任务失败或进入 DEAD`,href:"/materials/imports"});if(s.open_purchase_orders)add("procurement",{code:"PURCHASE_OPEN",level:"medium",text:`${s.open_purchase_orders} 张采购单尚未完成收货`,href:"/erp/index.html?tab=purchase"});if(!result.length)result.push({code:"NO_VISIBLE_RISK",level:"low",text:"当前获准数据范围内没有立即待办",href:"/"});return result.slice(0,12);}
 async backup(actor:DashboardActor){if(!hasPermission(actor,"system.backup.read"))throw new DashboardError("PERMISSION_DENIED","没有权限读取备份状态",403);const s=await this.repository.readSnapshot();return{...(await backupGovernance(this.backupStatusFile)),current_migration:s.migrations[0]??null};}
 async operations(actor:DashboardActor){if(!hasPermission(actor,"operations.audit_status.read"))throw new DashboardError("PERMISSION_DENIED","没有权限读取运维状态",403);const s=await this.repository.readSnapshot();return{authority:"Node/PostgreSQL",environment:"NON_PRODUCTION_BASELINE",migration_head:s.migrations[0]??null,pending_jobs:s.pending_jobs,failed_jobs:s.failed_jobs,generated_at:s.generated_at};}
}
