import {hasPermission} from "../identity-selfhost/permissions.ts";import {backupGovernance} from "./backup-status.ts";import {DashboardError} from "./errors.ts";import {canReadDomain,permittedModules,requireDashboard,requireManagement} from "./permissions.ts";import type {DashboardRepositoryPort} from "./repository.ts";import type {DashboardActor,DashboardDomain,DashboardMetric,DashboardModule,DashboardRisk,DashboardSnapshot,DashboardSummary} from "./types.ts";
const MODULES:DashboardModule[]=[
 {code:"market-projects",label:"市场部门",description:"客户需求整理、修订与项目交接",href:"/business/projects",permission:"project.market.create",native:true},{code:"engineering-projects",label:"项目部门",description:"待接收项目、退回与已接收记录",href:"/engineering/projects",permission:"project.engineering.read",native:true},{code:"planning-handoffs",label:"计划部门",description:"项目产品、BOM 与零件规格交接",href:"/planning/handoffs",permission:"planning.read",native:true},
 {code:"material-requirements",label:"物料需求计划",description:"交接包汇总、库存/在途分配与提交",href:"/planning/material-requirements",permission:"planning.requirement.read",native:true},{code:"purchase-requests",label:"采购申请交接",description:"接收或退回净采购申请",href:"/planning/purchase-requests",permission:"planning.purchase_request.read",native:true},
 {code:"production-handoffs",label:"计划到生产交接",description:"版本化提交、退回、接收与唯一工单",href:"/planning/production-handoffs",permission:"production.handoff.read",native:true},{code:"production-work-orders",label:"生产工单与齐套",description:"接收交接、创建工单与显式释放",href:"/production/work-orders",permission:"production.handoff.read",native:true},{code:"production-issues",label:"生产领退料",description:"有效预留上的分批领料与受控退料",href:"/warehouse/production-issues",permission:"production.issue",native:true},{code:"production-reporting",label:"生产分批报工",description:"按净领料支持量追加良品与报废事实",href:"/production/reporting",permission:"production.report",native:true},{code:"production-completions",label:"生产完工入库",description:"消费报工良品并形成成品账本",href:"/warehouse/production-completions",permission:"production.complete",native:true},{code:"finished-goods-allocation",label:"成品订单分配",description:"完工明细到销售订单明细的稳定分配",href:"/sales/finished-goods-allocation",permission:"quality.finished_goods_allocation.read",native:true},{code:"production-quality",label:"生产与成品品质",description:"IPQC、FQC、处置关闭与订单放行额度",href:"/quality/production",permission:"quality.read",native:true},
 {code:"procurement-sourcing",label:"采购询价与定标",description:"候选供应商、报价版本、服务端比价与人工定标",href:"/procurement/sourcing",permission:"procurement.rfq.read",native:true},
 {code:"procurement-fulfillment",label:"定标转单与到货计划",description:"显式转 PO、关系化到货计划与履约追溯",href:"/procurement/fulfillment",permission:"procurement.fulfillment.read",native:true},{code:"warehouse-receiving",label:"仓库待入库",description:"按到货计划分批收货",href:"/warehouse/receiving",permission:"procurement.receiving.receive",native:true},{code:"finance-payables",label:"采购应付交接",description:"收货来源核对与显式 AP",href:"/finance/payables",permission:"finance.read",native:true},
 {code:"sales-delivery",label:"销售发货指令",description:"销售创建、提交并受控取消发货指令",href:"/sales/delivery",permission:"sales.delivery.read",native:true},{code:"warehouse-shipping",label:"仓库销售发货",description:"接收指令、分批出库与精确消费 FQC",href:"/warehouse/shipping",permission:"sales.delivery.execute",native:true},{code:"finance-receivables",label:"销售应收交接",description:"核对出货金额来源并显式生成 AR",href:"/finance/receivables",permission:"finance.read",native:true},
 {code:"finance-settlements",label:"客户收款与供应商付款",description:"部分核销、多次核销与追加式全额冲销",href:"/finance/settlements",permission:"finance.read",native:true},{code:"finance-projects",label:"项目收支追溯",description:"按稳定来源与币种查看项目收支和净现金",href:"/finance/projects",permission:"finance.project.read",native:true},
 {code:"material",label:"物料 / 导入 / 审核",description:"原生物料主数据中心",href:"/materials",permission:"material.read",native:true},{code:"partners",label:"客户 / 供应商",description:"往来单位主数据",href:"/erp/index.html?tab=partners",permission:"master.customer.read",native:false},{code:"engineering",label:"产品 / BOM",description:"产品版本与有效 BOM",href:"/erp/index.html?tab=bom",permission:"master.bom.read",native:false},{code:"inventory",label:"库存",description:"余额、冻结与调整账本",href:"/erp/index.html?tab=purchase",permission:"inventory.read",native:false},{code:"procurement",label:"采购",description:"采购单、收货与冲销",href:"/erp/index.html?tab=purchase",permission:"procurement.read",native:false},{code:"production",label:"生产",description:"工单、领退料、报工与完工",href:"/erp/index.html?tab=production",permission:"production.read",native:false},{code:"sales",label:"销售",description:"报价、订单与出货",href:"/erp/index.html?tab=sales",permission:"sales.read",native:false},{code:"quality",label:"品质",description:"IQC / IPQC / FQC",href:"/erp/index.html?tab=quality",permission:"quality.read",native:false},{code:"finance",label:"财务",description:"AR / AP 与结算",href:"/erp/index.html?tab=finance",permission:"finance.read",native:false},{code:"users",label:"用户 / 审计",description:"账号和受控审计",href:"/erp/index.html?tab=operations",permission:"system.user.read",native:false},{code:"operations",label:"运维 / 备份状态",description:"只读治理；操作必须离线",href:"/#operations",permission:"system.backup.read",native:true},
];
const domainGroup=(s:DashboardSnapshot,d:DashboardDomain):unknown=>({material:{active_materials:s.active_materials},partners:{active_customers:s.active_customers,active_suppliers:s.active_suppliers},engineering:{released_products:s.released_products,valid_boms:s.valid_boms},inventory:{material_kinds:s.inventory_material_kinds,zero_available_kinds:s.inventory_zero_available_kinds,quantity_by_unit:s.inventory_quantities},procurement:{open_orders:s.open_purchase_orders,pending_receipt_qty:s.pending_receipt_qty,pending_award_conversion:s.pending_award_conversion,pending_receiving_plans:s.pending_receiving_plans},production:{active_work_orders:s.active_work_orders,pending_issue_qty:s.pending_issue_qty,pending_completion_qty:s.pending_completion_qty,shortage_requirement_count:s.shortage_requirement_count,pending_production_accept:s.pending_production_accept,production_kitting_shortage:s.production_kitting_shortage,released_waiting_issue:s.released_waiting_issue,partial_issue_work_orders:s.partial_issue_work_orders,pending_reporting_work_orders:s.pending_reporting_work_orders,reported_waiting_receipt_qty:s.reported_waiting_receipt_qty,partial_completion_work_orders:s.partial_completion_work_orders,completed_waiting_quality_qty:s.completed_waiting_quality_qty},sales:{open_orders:s.open_sales_orders,pending_shipment_qty:s.pending_shipment_qty,pending_delivery_instructions:s.pending_delivery_instructions,partial_sales_orders:s.partial_sales_orders},quality:{pending_iqc:s.pending_iqc,pending_ipqc:s.pending_ipqc,pending_fqc:s.pending_fqc,open_exceptions:s.open_quality_exceptions,released_waiting_shipment_qty:s.released_waiting_shipment_qty},finance:{ar_total:s.ar_total,ar_settled:s.ar_settled,ar_balance:s.ar_balance,pending_sales_ar_count:s.pending_sales_ar_count,pending_sales_ar_amount:s.pending_sales_ar_amount,ap_total:s.ap_total,ap_settled:s.ap_settled,ap_balance:s.ap_balance,pending_purchase_ap_count:s.pending_purchase_ap_count,pending_purchase_ap_amount:s.pending_purchase_ap_amount,generated_purchase_ap_count:s.generated_purchase_ap_count,generated_purchase_ap_amount:s.generated_purchase_ap_amount,net_receipts:s.net_receipts,net_payments:s.net_payments,by_currency:s.finance_by_currency??[]},operations:{pending_jobs:s.pending_jobs,failed_jobs:s.failed_jobs,migrations:s.migrations}}[d]);
export class DashboardService{
 private readonly repository:DashboardRepositoryPort;private readonly backupStatusFile:string;constructor(repository:DashboardRepositoryPort,backupStatusFile:string){this.repository=repository;this.backupStatusFile=backupStatusFile;}
 private project(actor:DashboardActor,s:DashboardSnapshot):DashboardSummary{
  const groups:DashboardSummary["groups"]={};for(const d of ["material","partners","engineering","inventory","procurement","production","sales","quality","finance","operations"] as DashboardDomain[])if(canReadDomain(actor,d))groups[d]=domainGroup(s,d);
  return{generated_at:s.generated_at,authority:"Node/PostgreSQL",consistency:"REPEATABLE_READ_READ_ONLY",inventory_quantity_aggregated:false,groups,modules:permittedModules(actor,MODULES),
   ...(canReadDomain(actor,"material")?{total_items:s.active_materials,total_mappings:s.total_mappings,pending:s.pending_materials,auto_count:s.auto_count,suspect_count:s.suspect_count,new_count:s.new_count}:{}),
   ...(canReadDomain(actor,"partners")?{total_customers:s.active_customers,total_suppliers:s.active_suppliers}:{}),...(canReadDomain(actor,"engineering")?{total_products:s.released_products,total_boms:s.valid_boms}:{}),...(hasPermission(actor,"planning.read")?{pending_planning_handoffs:s.pending_planning_handoffs}:{}),...(hasPermission(actor,"planning.requirement.read")?{accepted_planning_packages:s.accepted_planning_packages}:{}),...(hasPermission(actor,"planning.purchase_request.read")?{pending_purchase_requests:s.pending_purchase_requests}:{}),...(hasPermission(actor,"procurement.rfq.read")?{pending_sourcing_requests:s.pending_sourcing_requests,pending_quote_rfqs:s.pending_quote_rfqs,pending_award_rfqs:s.pending_award_rfqs}:{}),
   ...(canReadDomain(actor,"procurement")?{total_pos:s.total_purchase_orders,open_pos:s.open_purchase_orders,pending_award_conversion:s.pending_award_conversion,pending_receiving_plans:s.pending_receiving_plans}:{}),...(canReadDomain(actor,"production")?{total_work_orders:s.total_work_orders,active_work_orders:s.active_work_orders,pending_reporting_work_orders:s.pending_reporting_work_orders,reported_waiting_receipt_qty:s.reported_waiting_receipt_qty,partial_completion_work_orders:s.partial_completion_work_orders,completed_waiting_quality_qty:s.completed_waiting_quality_qty}:{}),
   ...(canReadDomain(actor,"sales")?{total_quotations:s.total_quotations,open_quotations:s.open_quotations,total_sales_orders:s.total_sales_orders,open_sales_orders:s.open_sales_orders,...(hasPermission(actor,"sales.delivery.read")?{pending_delivery_instructions:s.pending_delivery_instructions,partial_sales_orders:s.partial_sales_orders}: {})}:{}),
   ...(canReadDomain(actor,"quality")?{total_quality_inspections:s.total_quality_inspections,open_quality_issues:s.open_quality_exceptions}:{}),...(canReadDomain(actor,"finance")?{receivable_balance:s.ar_balance,payable_balance:s.ap_balance,pending_purchase_ap_count:s.pending_purchase_ap_count,generated_purchase_ap_count:s.generated_purchase_ap_count,...(hasPermission(actor,"sales.finance_source.read")?{pending_sales_ar_count:s.pending_sales_ar_count,pending_sales_ar_amount:s.pending_sales_ar_amount}: {})}:{}),...(canReadDomain(actor,"operations")?{pending_jobs:s.pending_jobs,failed_jobs:s.failed_jobs}:{}),
  };}
 async summary(actor:DashboardActor){requireDashboard(actor);return this.project(actor,await this.repository.readSnapshot());}
 async management(actor:DashboardActor){requireManagement(actor);const s=await this.repository.readSnapshot();const summary=this.project(actor,s);const activity=hasPermission(actor,"system.audit.read")?s.recent_audits.map(e=>({...e,detail:e.route_code})):[];const events=s.recent_events.filter(e=>canReadDomain(actor,e.domain as DashboardDomain)).slice(0,20);return{summary,modules:summary.modules,metrics:[...this.productionHandoffMetrics(actor,s),...this.productionCompletionMetrics(actor,s),...this.productionQualityMetrics(actor,s),...this.metrics(actor,s)],risks:this.risks(actor,s),recent_events:events,recent_activity:activity};}
 private productionHandoffMetrics(actor:DashboardActor,s:DashboardSnapshot):DashboardMetric[]{
  if(!hasPermission(actor,"production.handoff.read"))return[];
  return[
   {code:"pending-production-accept",label:"待生产接收",value:s.pending_production_accept,hint:"已提交的计划到生产交接",tone:s.pending_production_accept?"warning":"neutral",href:"/production/work-orders"},
   {code:"production-kitting-shortage",label:"齐套不足",value:s.production_kitting_shortage,hint:"当前可用库存不足的生产需求",tone:s.production_kitting_shortage?"danger":"neutral",href:"/production/work-orders"},
   {code:"released-waiting-issue",label:"已释放待领料",value:s.released_waiting_issue,hint:"已有预留且尚未领料",tone:s.released_waiting_issue?"info":"neutral",href:"/warehouse/production-issues"},
   {code:"partial-production-issue",label:"部分领料",value:s.partial_issue_work_orders,hint:"仍有有效生产预留",tone:s.partial_issue_work_orders?"warning":"neutral",href:"/warehouse/production-issues"},
  ];
 }
 private productionCompletionMetrics(actor:DashboardActor,s:DashboardSnapshot):DashboardMetric[]{const result:DashboardMetric[]=[];
 if(hasPermission(actor,"production.report"))result.push({code:"pending-production-reporting",label:"待报工工单",value:s.pending_reporting_work_orders,hint:"净领料支持量大于累计报工",tone:s.pending_reporting_work_orders?"warning":"neutral",href:"/production/reporting"});
 if(hasPermission(actor,"production.complete"))result.push({code:"reported-waiting-receipt",label:"已报工待入库良品",value:s.reported_waiting_receipt_qty,hint:"只统计未冲销 Report 的未消费 good quantity",tone:/^0(?:\.0+)?$/.test(s.reported_waiting_receipt_qty)?"neutral":"warning",href:"/warehouse/production-completions"});
 if(hasPermission(actor,"production.read"))result.push({code:"partial-production-completion",label:"部分完工工单",value:s.partial_completion_work_orders,hint:"completed 大于 0 且小于 planned",tone:s.partial_completion_work_orders?"info":"neutral",href:"/production/work-orders"});
 if(hasPermission(actor,"quality.read"))result.push({code:"completed-waiting-quality",label:"已完成待品质处理数量",value:s.completed_waiting_quality_qty,hint:"只读提示，不创建或伪造 FQC",tone:/^0(?:\.0+)?$/.test(s.completed_waiting_quality_qty)?"neutral":"warning",href:"/erp/index.html?tab=quality"});return result;}
 private productionQualityMetrics(actor:DashboardActor,s:DashboardSnapshot):DashboardMetric[]{const result:DashboardMetric[]=[],zero=(value:string)=>/^0(?:\.0+)?$/.test(value);
 if(hasPermission(actor,"production.read")||hasPermission(actor,"quality.read"))result.push({code:"pending-ipqc-reports",label:"待 IPQC 报工",value:s.pending_ipqc_reports,hint:"未冲销 Report 的剩余可检验记录",tone:s.pending_ipqc_reports?"warning":"neutral",href:"/quality/production"});
 if(hasPermission(actor,"quality.finished_goods_allocation.read"))result.push({code:"completed-waiting-allocation",label:"已完工待订单分配",value:s.completed_waiting_allocation_qty,hint:"有效 Completion 尚未稳定分配的数量",tone:zero(s.completed_waiting_allocation_qty)?"neutral":"warning",href:"/sales/finished-goods-allocation"});
 if(hasPermission(actor,"quality.read"))result.push({code:"finished-goods-waiting-fqc",label:"待 FQC 成品",value:s.pending_fqc_finished_qty,hint:"有效分配尚未检验的数量",tone:zero(s.pending_fqc_finished_qty)?"neutral":"warning",href:"/quality/production"},{code:"quality-hold-qty",label:"HOLD 数量",value:s.quality_hold_qty,hint:"REWORK / SCRAP 等处置不形成放行",tone:zero(s.quality_hold_qty)?"neutral":"danger",href:"/quality/production"});
 if(hasPermission(actor,"sales.delivery.read")||hasPermission(actor,"quality.read"))result.push({code:"released-waiting-shipment",label:"FQC 已放行待发货数量",value:s.released_waiting_shipment_qty,hint:"逐笔放行额度减 Shipment→FQC 有效消费",tone:zero(s.released_waiting_shipment_qty)?"neutral":"info",href:"/sales/delivery"});return result;}
 private metrics(actor:DashboardActor,s:DashboardSnapshot){const result:DashboardMetric[]=[];const add=(d:DashboardDomain,i:DashboardMetric)=>{if(canReadDomain(actor,d))result.push(i)};const finance=s.finance_by_currency??[];const money=(field:Exclude<keyof DashboardSnapshot["finance_by_currency"][number],"currency_code">)=>finance.map(row=>`${row.currency_code} ${row[field]}`).join(" · ")||"—";const nonzero=(field:Exclude<keyof DashboardSnapshot["finance_by_currency"][number],"currency_code">)=>finance.some(row=>!/^0(?:\.0+)?$/.test(row[field]));
 if(hasPermission(actor,"sales.delivery.accept"))result.push({code:"pending-delivery-accept",label:"待仓库接收发货指令",value:s.pending_delivery_instructions,hint:"销售已提交且尚未接收",tone:s.pending_delivery_instructions?"warning":"neutral",href:"/warehouse/shipping"});
 if(hasPermission(actor,"sales.read"))result.push({code:"partial-sales-orders",label:"部分发货订单",value:s.partial_sales_orders,hint:"Sales Order 状态为 PARTIALLY_SHIPPED",tone:s.partial_sales_orders?"info":"neutral",href:"/sales/delivery"});
 if(hasPermission(actor,"sales.finance_source.read"))result.push({code:"pending-sales-ar",label:"已发货待生成 AR",value:s.pending_sales_ar_count,hint:`${s.pending_sales_ar_amount} CNY`,tone:s.pending_sales_ar_count?"warning":"neutral",href:"/finance/receivables"});
 if(hasPermission(actor,"finance.read")&&actor.role!=="purchase"&&actor.role!=="engineering")result.push({code:"sales-ar-balance",label:"AR 未结",value:money("ar_balance"),hint:"按币种独立展示",tone:nonzero("ar_balance")?"warning":"neutral",href:"/finance/settlements"},{code:"period-customer-receipts",label:"本期客户收款",value:money("period_customer_receipts"),hint:"仅已过账收款净额",tone:nonzero("period_customer_receipts")?"info":"neutral",href:"/finance/settlements"});
 if(hasPermission(actor,"finance.read")&&actor.role!=="sales"&&actor.role!=="engineering")result.push({code:"purchase-ap-balance",label:"AP 未结",value:money("ap_balance"),hint:"按币种独立展示",tone:nonzero("ap_balance")?"warning":"neutral",href:"/finance/settlements"},{code:"period-supplier-payments",label:"本期供应商付款",value:money("period_supplier_payments"),hint:"仅已过账付款净额",tone:nonzero("period_supplier_payments")?"info":"neutral",href:"/finance/settlements"});
 if(hasPermission(actor,"finance.project.read"))result.push({code:"project-unattributed",label:"项目未归属金额",value:money("project_unattributed_amount"),hint:"稳定来源缺失时不猜测",tone:nonzero("project_unattributed_amount")?"danger":"neutral",href:"/finance/projects"},{code:"project-net-cash",label:"项目净现金流",value:money("project_net_cash"),hint:"客户收款减供应商付款；非会计利润",tone:"info",href:"/finance/projects"});
 add("material",{code:"materials",label:"ACTIVE 物料",value:s.active_materials,hint:"关系化主数据",tone:"neutral",href:"/materials"});
 if(hasPermission(actor,"planning.read"))result.push({code:"planning-handoffs",label:"待接收计划交接",value:s.pending_planning_handoffs,hint:"项目到计划交接",tone:s.pending_planning_handoffs?"warning":"neutral",href:"/planning/handoffs"});
 if(hasPermission(actor,"planning.requirement.read"))result.push({code:"material-requirements",label:"待核算交接包",value:s.accepted_planning_packages,hint:"库存与在途独立分配",tone:s.accepted_planning_packages?"warning":"neutral",href:"/planning/material-requirements"});
 if(hasPermission(actor,"planning.purchase_request.read"))result.push({code:"purchase-requests",label:"待接收采购申请",value:s.pending_purchase_requests,hint:"不自动创建 RFQ 或 PO",tone:s.pending_purchase_requests?"warning":"neutral",href:"/planning/purchase-requests"});
 if(hasPermission(actor,"procurement.rfq.read")){result.push({code:"pending-sourcing",label:"待询价采购申请",value:s.pending_sourcing_requests,hint:"已接收且无有效 RFQ",tone:s.pending_sourcing_requests?"warning":"neutral",href:"/procurement/sourcing"},{code:"pending-quotes",label:"待报价 RFQ",value:s.pending_quote_rfqs,hint:"至少一家受邀供应商未报价",tone:s.pending_quote_rfqs?"warning":"neutral",href:"/procurement/sourcing"},{code:"pending-awards",label:"待定标 RFQ",value:s.pending_award_rfqs,hint:"人工选择，不自动审批",tone:s.pending_award_rfqs?"warning":"neutral",href:"/procurement/sourcing"});}if(hasPermission(actor,"procurement.fulfillment.read"))result.push({code:"award-conversion",label:"待转 PO Award",value:s.pending_award_conversion,hint:"采购显式操作",tone:s.pending_award_conversion?"warning":"neutral",href:"/procurement/fulfillment"},{code:"receiving-plans",label:"仓库待入库",value:s.pending_receiving_plans,hint:`待收数量 ${s.pending_receipt_qty}`,tone:s.pending_receiving_plans?"warning":"neutral",href:"/warehouse/receiving"});
 add("procurement",{code:"purchase",label:"未完成采购",value:s.open_purchase_orders,hint:`待收货 ${s.pending_receipt_qty}`,tone:s.open_purchase_orders?"warning":"neutral",href:"/procurement/fulfillment"});
 add("production",{code:"production",label:"进行中工单",value:s.active_work_orders,hint:`待完工 ${s.pending_completion_qty}`,tone:s.shortage_requirement_count?"danger":"info",href:"/erp/index.html?tab=production"});
 add("sales",{code:"sales",label:"未关闭销售单",value:s.open_sales_orders,hint:`待发货 ${s.pending_shipment_qty}`,tone:s.open_sales_orders?"info":"neutral",href:"/sales/delivery"});
 add("quality",{code:"quality",label:"品质异常",value:s.open_quality_exceptions,hint:`IQC ${s.pending_iqc} · IPQC ${s.pending_ipqc} · FQC ${s.pending_fqc}`,tone:s.open_quality_exceptions?"danger":"neutral",href:"/erp/index.html?tab=quality"});
 add("finance",{code:"purchase-ap-pending",label:"已收货待生成应付",value:s.pending_purchase_ap_count,hint:`${s.pending_purchase_ap_amount} CNY`,tone:s.pending_purchase_ap_count?"warning":"neutral",href:"/finance/payables"});
 add("finance",{code:"purchase-ap-generated",label:"已生成采购应付",value:s.generated_purchase_ap_count,hint:`${s.generated_purchase_ap_amount} CNY`,tone:s.generated_purchase_ap_count?"info":"neutral",href:"/finance/payables"});
 add("operations",{code:"jobs",label:"后台任务",value:s.pending_jobs,hint:s.failed_jobs?`${s.failed_jobs} 个失败 / DEAD`:"队列 / 运行中",tone:s.failed_jobs?"danger":"neutral",href:"/materials/imports"});return result;}
 private risks(actor:DashboardActor,s:DashboardSnapshot){const result:DashboardRisk[]=[];const add=(d:DashboardDomain,i:DashboardRisk)=>{if(canReadDomain(actor,d))result.push(i)};
 if(s.open_quality_exceptions)add("quality",{code:"QUALITY_OPEN",level:"high",text:`${s.open_quality_exceptions} 项品质异常未关闭`,href:"/erp/index.html?tab=quality"});
 if(s.shortage_requirement_count)add("production",{code:"PRODUCTION_SHORTAGE",level:"high",text:`${s.shortage_requirement_count} 项工单需求超过可用库存`,href:"/erp/index.html?tab=production"});
 if(s.failed_jobs)add("operations",{code:"BACKGROUND_JOB_FAILED",level:"high",text:`${s.failed_jobs} 个后台任务失败或进入 DEAD`,href:"/materials/imports"});
 if(s.open_purchase_orders)add("procurement",{code:"PURCHASE_OPEN",level:"medium",text:`${s.open_purchase_orders} 张采购单尚未完成收货`,href:"/erp/index.html?tab=purchase"});
 if(!result.length)result.push({code:"NO_VISIBLE_RISK",level:"low",text:"当前获准数据范围内没有立即待办",href:"/"});return result.slice(0,12);}
 async backup(actor:DashboardActor){if(!hasPermission(actor,"system.backup.read"))throw new DashboardError("PERMISSION_DENIED","没有权限读取备份状态",403);const s=await this.repository.readSnapshot();return{...(await backupGovernance(this.backupStatusFile)),current_migration:s.migrations[0]??null};}
 async operations(actor:DashboardActor){if(!hasPermission(actor,"operations.audit_status.read"))throw new DashboardError("PERMISSION_DENIED","没有权限读取运维状态",403);const s=await this.repository.readSnapshot();return{authority:"Node/PostgreSQL",environment:"NON_PRODUCTION_BASELINE",migration_head:s.migrations[0]??null,pending_jobs:s.pending_jobs,failed_jobs:s.failed_jobs,generated_at:s.generated_at};}
}
