import type { IdentityActor } from "../identity-selfhost/types.ts";

export type DashboardActor = Pick<IdentityActor,"username"|"role"|"permissions">;
export type DashboardDomain = "material"|"partners"|"engineering"|"inventory"|"procurement"|"production"|"sales"|"quality"|"finance"|"operations";
export type DecimalSummary = Readonly<{unit:string;on_hand:string;available:string;frozen:string}>;
export type SafeBusinessEvent = Readonly<{domain:string;action:string;object_code:string;actor:string;request_id:string;created_at:string}>;
export type SafeAuditEvent = Readonly<{action:string;result:string;username:string;route_code:string;request_id:string;created_at:string}>;
export type MigrationStatus = Readonly<{version:string;checksum:string;applied_at:string}>;
export type FinanceCurrencySummary = Readonly<{currency_code:string;ar_balance:string;ap_balance:string;period_customer_receipts:string;period_supplier_payments:string;project_unattributed_amount:string;project_net_cash:string}>;
export type DashboardSnapshot = Readonly<{
  active_materials:number;total_mappings:number;pending_materials:number;pending_material_reviews:number;auto_count:number;suspect_count:number;new_count:number;active_customers:number;active_suppliers:number;released_products:number;valid_boms:number;
  inventory_material_kinds:number;inventory_zero_available_kinds:number;inventory_quantities:DecimalSummary[];pending_nonconformance_count?:number;unresolved_nonconformance_qty?:string;pending_rework_accept_count?:number;accepted_rework_waiting_execution_qty?:string;accepted_rework_waiting_dispatch_qty?:string;rework_in_progress_qty?:string;rework_pending_reinspection_qty?:string;rework_reinspection_failed_qty?:string;rework_completed_qty?:string;final_operation_scrap_qty?:string;draft_batch_set_count?:number;released_waiting_batch_count?:number;batch_wip_count?:number;batch_quality_hold_count?:number;batch_rework_count?:number;batch_final_output_count?:number;completed_batch_count?:number;finished_goods_lot_count?:number;finished_goods_lot_frozen_qty?:string;
  total_purchase_orders:number;open_purchase_orders:number;pending_receipt_qty:string;pending_award_conversion:number;pending_receiving_plans:number;pending_purchase_ap_count:number;pending_purchase_ap_amount:string;generated_purchase_ap_count:number;generated_purchase_ap_amount:string;total_work_orders:number;active_work_orders:number;pending_issue_qty:string;pending_completion_qty:string;shortage_requirement_count:number;pending_production_accept:number;production_kitting_shortage:number;pending_routing_reviews?:number;product_versions_missing_routing?:number;released_waiting_first_operation?:number;legacy_unstructured_work_orders?:number;ready_operation_count?:number;in_progress_run_count?:number;inter_operation_wip_qty?:string;final_operation_output_qty?:string;waiting_predecessor_operation_count?:number;operation_pending_ipqc_sources?:number;operation_pending_ipqc_qty?:string;operation_ipqc_in_progress?:number;operation_quality_hold_qty?:string;operation_released_waiting_next_qty?:string;operation_released_waiting_final_qty?:string;released_waiting_issue:number;partial_issue_work_orders:number;pending_reporting_work_orders:number;reported_waiting_receipt_qty:string;partial_completion_work_orders:number;completed_waiting_quality_qty:string;pending_ipqc_reports:number;completed_waiting_allocation_qty:string;pending_fqc_finished_qty:string;quality_hold_qty:string;released_waiting_shipment_qty:string;
  total_quotations:number;open_quotations:number;total_sales_orders:number;open_sales_orders:number;pending_shipment_qty:string;pending_delivery_instructions:number;partial_sales_orders:number;pending_sales_ar_count:number;pending_sales_ar_amount:string;total_quality_inspections:number;pending_iqc:number;pending_ipqc:number;pending_fqc:number;open_quality_exceptions:number;
  ar_total:string;ar_settled:string;ar_balance:string;ap_total:string;ap_settled:string;ap_balance:string;net_receipts:string;net_payments:string;finance_by_currency:FinanceCurrencySummary[];
  pending_planning_handoffs:number;accepted_planning_packages:number;pending_purchase_requests:number;pending_sourcing_requests:number;pending_quote_rfqs:number;pending_award_rfqs:number;pending_jobs:number;failed_jobs:number;migrations:MigrationStatus[];database_identity?:Readonly<{name:string;system_identifier:string;oid:string;marker:string;server_major:string;encoding:string;collate:string;ctype:string;locale_provider:string;collation_version:string}>;recent_events:SafeBusinessEvent[];recent_audits:SafeAuditEvent[];generated_at:string;
}>;
export type DashboardMetric = Readonly<{code:string;label:string;value:string|number;hint:string;tone:"neutral"|"info"|"warning"|"danger";href:string}>;
export type DashboardRisk = Readonly<{code:string;level:"low"|"medium"|"high";text:string;href:string}>;
export type DashboardModule = Readonly<{code:string;label:string;description:string;href:string;permission:string;native:boolean;excludedRoles?:readonly string[]}>;
export type DashboardSummary = Readonly<{generated_at:string;authority:"Node/PostgreSQL";consistency:"REPEATABLE_READ_READ_ONLY";inventory_quantity_aggregated:false;groups:Partial<Record<DashboardDomain,unknown>>;modules:DashboardModule[];
  total_items?:number;total_mappings?:number;pending?:number;auto_count?:number;suspect_count?:number;new_count?:number;total_customers?:number;total_suppliers?:number;total_products?:number;total_boms?:number;pending_planning_handoffs?:number;accepted_planning_packages?:number;pending_purchase_requests?:number;pending_sourcing_requests?:number;pending_quote_rfqs?:number;pending_award_rfqs?:number;pending_award_conversion?:number;pending_receiving_plans?:number;pending_production_accept?:number;production_kitting_shortage?:number;released_waiting_issue?:number;partial_issue_work_orders?:number;pending_reporting_work_orders?:number;reported_waiting_receipt_qty?:string;partial_completion_work_orders?:number;completed_waiting_quality_qty?:string;pending_ipqc_reports?:number;completed_waiting_allocation_qty?:string;pending_fqc_finished_qty?:string;quality_hold_qty?:string;released_waiting_shipment_qty?:string;pending_delivery_instructions?:number;partial_sales_orders?:number;pending_sales_ar_count?:number;pending_sales_ar_amount?:string;pending_purchase_ap_count?:number;generated_purchase_ap_count?:number;total_pos?:number;open_pos?:number;total_work_orders?:number;active_work_orders?:number;total_quotations?:number;open_quotations?:number;total_sales_orders?:number;open_sales_orders?:number;total_quality_inspections?:number;open_quality_issues?:number;receivable_balance?:string;payable_balance?:string;pending_jobs?:number;failed_jobs?:number}>;
export type BackupArtifact = Readonly<{file:string;sha256:string;bytes:number;entries?:number}>;
export type BackupVerificationLevel = "LOCAL_VERIFIED"|"OFFHOST_VERIFIED"|"RESTORE_VERIFIED";
export type BackupEvidence =
  | Readonly<{kind:"LOCAL_CAPTURE_VERIFICATION";source_machine_identity_sha256:string;source_root_device:string;source_root_inode:string;source_root_identity_sha256:string;attestation:"TRUSTED_EXECUTION_UID_AND_FIXED_SOURCE_MACHINE_ROOT"}>
  | Readonly<{kind:"OFFHOST_RECEIVER_VERIFICATION";transfer_id:string;source_location_id:string;source_machine_identity_sha256:string;local_receipt_sha256:string;receiver_machine_identity_sha256:string;receiver_root_device:string;receiver_root_inode:string;receiver_identity_sha256:string;attestation:"TRUSTED_EXECUTION_UID_AND_DISTINCT_MACHINE_FIXED_RECEIVER_ROOT"}>
  | Readonly<{kind:"ISOLATED_RESTORE_VERIFICATION";source_location_id:string;offhost_location_id:string;offhost_receiver_identity_sha256:string;offhost_receipt_sha256:string;restore_run_id:string;restored_at:string;reconciliation:Readonly<{contract:"chenyida-erp-restore-reconciliation/v1";source_sha256:string;target_database_report_sha256:string;target_file_trees_sha256:string;result:"MATCHED"}>;reconciliation_sha256:string;attestation:"TRUSTED_EXECUTION_UID_AND_DISTINCT_CLUSTER_ACTIVE_INSPECTION";target:Readonly<{deployment_class:"TEST";deployment_id:string;database_name:string;database_system_identifier:string;database_oid:string;marker_id:string;cluster_marker_id:string;database_server_major:string;database_encoding:string;database_collate:string;database_ctype:string;database_locale_provider:string;database_collation_version:string;file_root_name:string}>}>;
export type BackupVerification = Readonly<{
  schema_version:2;contract:"chenyida-erp-backup-verification/v2";result:BackupVerificationLevel;
  backup_id:string;created_at:string;verified_at:string;expires_at:string;location_id:string;
  deployment:Readonly<{class:"TEST"|"UAT"|"PRODUCTION";id:string;database:string;database_system_identifier:string;database_oid:string;database_marker:string;database_bytes:number;database_server_major:string;database_encoding:string;database_collate:string;database_ctype:string;database_locale_provider:string;database_collation_version:string}>;
  application:Readonly<{version:string;git_commit:string;web_image_digest:string;worker_image_digest:string}>;
  migration:Readonly<{head:string;manifest_file:"migrations.txt";manifest_sha256:string}>;
  policy:Readonly<{id:string;rpo_hours:number}>;
  consistency:Readonly<{method:"QUIESCED_APPLICATION_AND_SNAPSHOT_WITH_CONTENT_RECONCILIATION";database_snapshot:"PG_DUMP_CONSISTENT_SNAPSHOT";database_guard:"DEFAULT_TRANSACTION_READ_ONLY_DEFENSE_IN_DEPTH";writer_boundary:"EXACT_COMPOSE_WEB_WORKER_STOPPED";content_reconciliation:"BEFORE_AFTER_FULL_RELATION_CONTENT_DIGESTS";dump_scope:"COMPLETE_APPLICATION_DATABASE_LOGICAL_DUMP_NO_OWNER_OR_ACL";web_container:string;web_container_id:string;worker_container:string;worker_container_id:string;recovery_point_at:string;verified_after:string}>;
  reconciliation:Readonly<{contract:"chenyida-erp-backup-reconciliation/v1";file:"reconciliation.json";sha256:string}>;
  manifest_sha256:string;
  artifacts:Readonly<{postgresql_dump:BackupArtifact;uploads:BackupArtifact;attachments:BackupArtifact;backup_status:BackupArtifact}>;
  evidence:BackupEvidence;
}>;
export type LegacyBackupVerification = Readonly<{schema_version:1;result:"VERIFIED";backup_id:string;created_at:string;verified_at:string;application_version:string;git_commit:string;migration_head:string;artifacts:Readonly<{postgresql_dump:BackupArtifact;uploads:BackupArtifact;attachments:BackupArtifact}>}>;
export type RuntimeReleaseIdentity = Readonly<{
  schema_version:2;contract:"chenyida-erp-runtime-release-identity/v2";deployment_class:"TEST"|"UAT"|"PRODUCTION";deployment_id:string;release_id:string;release_manifest_sha256:string;supervisor_bundle_sha256:string;authorization_sha256:string;
  application_version:string;git_commit:string;web_container_id:string;web_image_digest:string;worker_container_id:string;worker_image_digest:string;generated_at:string;
}>;
