import type { IdentityActor } from "../identity-selfhost/types.ts";

export type DashboardActor = Pick<IdentityActor,"username"|"role"|"permissions">;
export type DashboardDomain = "material"|"partners"|"engineering"|"inventory"|"procurement"|"production"|"sales"|"quality"|"finance"|"operations";
export type DecimalSummary = Readonly<{unit:string;on_hand:string;available:string;frozen:string}>;
export type SafeBusinessEvent = Readonly<{domain:string;action:string;object_code:string;actor:string;request_id:string;created_at:string}>;
export type SafeAuditEvent = Readonly<{action:string;result:string;username:string;route_code:string;request_id:string;created_at:string}>;
export type MigrationStatus = Readonly<{version:string;checksum:string;applied_at:string}>;
export type FinanceCurrencySummary = Readonly<{currency_code:string;ar_balance:string;ap_balance:string;period_customer_receipts:string;period_supplier_payments:string;project_unattributed_amount:string;project_net_cash:string}>;
export type DashboardSnapshot = Readonly<{
  active_materials:number;total_mappings:number;pending_materials:number;auto_count:number;suspect_count:number;new_count:number;active_customers:number;active_suppliers:number;released_products:number;valid_boms:number;
  inventory_material_kinds:number;inventory_zero_available_kinds:number;inventory_quantities:DecimalSummary[];
  total_purchase_orders:number;open_purchase_orders:number;pending_receipt_qty:string;pending_award_conversion:number;pending_receiving_plans:number;pending_purchase_ap_count:number;pending_purchase_ap_amount:string;generated_purchase_ap_count:number;generated_purchase_ap_amount:string;total_work_orders:number;active_work_orders:number;pending_issue_qty:string;pending_completion_qty:string;shortage_requirement_count:number;pending_production_accept:number;production_kitting_shortage:number;pending_routing_reviews?:number;product_versions_missing_routing?:number;released_waiting_first_operation?:number;legacy_unstructured_work_orders?:number;released_waiting_issue:number;partial_issue_work_orders:number;pending_reporting_work_orders:number;reported_waiting_receipt_qty:string;partial_completion_work_orders:number;completed_waiting_quality_qty:string;pending_ipqc_reports:number;completed_waiting_allocation_qty:string;pending_fqc_finished_qty:string;quality_hold_qty:string;released_waiting_shipment_qty:string;
  total_quotations:number;open_quotations:number;total_sales_orders:number;open_sales_orders:number;pending_shipment_qty:string;pending_delivery_instructions:number;partial_sales_orders:number;pending_sales_ar_count:number;pending_sales_ar_amount:string;total_quality_inspections:number;pending_iqc:number;pending_ipqc:number;pending_fqc:number;open_quality_exceptions:number;
  ar_total:string;ar_settled:string;ar_balance:string;ap_total:string;ap_settled:string;ap_balance:string;net_receipts:string;net_payments:string;finance_by_currency:FinanceCurrencySummary[];
  pending_planning_handoffs:number;accepted_planning_packages:number;pending_purchase_requests:number;pending_sourcing_requests:number;pending_quote_rfqs:number;pending_award_rfqs:number;pending_jobs:number;failed_jobs:number;migrations:MigrationStatus[];recent_events:SafeBusinessEvent[];recent_audits:SafeAuditEvent[];generated_at:string;
}>;
export type DashboardMetric = Readonly<{code:string;label:string;value:string|number;hint:string;tone:"neutral"|"info"|"warning"|"danger";href:string}>;
export type DashboardRisk = Readonly<{code:string;level:"low"|"medium"|"high";text:string;href:string}>;
export type DashboardModule = Readonly<{code:string;label:string;description:string;href:string;permission:string;native:boolean}>;
export type DashboardSummary = Readonly<{generated_at:string;authority:"Node/PostgreSQL";consistency:"REPEATABLE_READ_READ_ONLY";inventory_quantity_aggregated:false;groups:Partial<Record<DashboardDomain,unknown>>;modules:DashboardModule[];
  total_items?:number;total_mappings?:number;pending?:number;auto_count?:number;suspect_count?:number;new_count?:number;total_customers?:number;total_suppliers?:number;total_products?:number;total_boms?:number;pending_planning_handoffs?:number;accepted_planning_packages?:number;pending_purchase_requests?:number;pending_sourcing_requests?:number;pending_quote_rfqs?:number;pending_award_rfqs?:number;pending_award_conversion?:number;pending_receiving_plans?:number;pending_production_accept?:number;production_kitting_shortage?:number;released_waiting_issue?:number;partial_issue_work_orders?:number;pending_reporting_work_orders?:number;reported_waiting_receipt_qty?:string;partial_completion_work_orders?:number;completed_waiting_quality_qty?:string;pending_ipqc_reports?:number;completed_waiting_allocation_qty?:string;pending_fqc_finished_qty?:string;quality_hold_qty?:string;released_waiting_shipment_qty?:string;pending_delivery_instructions?:number;partial_sales_orders?:number;pending_sales_ar_count?:number;pending_sales_ar_amount?:string;pending_purchase_ap_count?:number;generated_purchase_ap_count?:number;total_pos?:number;open_pos?:number;total_work_orders?:number;active_work_orders?:number;total_quotations?:number;open_quotations?:number;total_sales_orders?:number;open_sales_orders?:number;total_quality_inspections?:number;open_quality_issues?:number;receivable_balance?:string;payable_balance?:string;pending_jobs?:number;failed_jobs?:number}>;
export type BackupArtifact = Readonly<{file:string;sha256:string;bytes:number;entries?:number}>;
export type BackupVerification = Readonly<{schema_version:1;result:"VERIFIED";backup_id:string;created_at:string;verified_at:string;application_version:string;git_commit:string;migration_head:string;artifacts:Readonly<{postgresql_dump:BackupArtifact;uploads:BackupArtifact;attachments:BackupArtifact}>}>;
