"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { api,ErpApiError } from "../../../public/erp/api-client.js";
import { roleLabel,statusLabel,statusPairLabel } from "../../../public/erp/status-localization.js";
import "../sourcing/sourcing.css";
type User={username:string;display_name:string;role:string;permissions:string[]};type Session={authenticated:boolean;user:User|null;csrf_token?:string};
type Award={award_id:number;award_version:number;rfq_code:string;request_code:string;line_count:number;total_quantity:string;converted_line_count:number;selected_at:string};
type Order={purchase_order_id:number;po_code:string;po_status:string;currency_code:string;po_version:number;supplier_code:string;supplier_name:string;line_count:number;plan_count:number;ordered_quantity:string;received_quantity:string;receipt_count:number;receipt_codes:string;internal_lots:string;supplier_lots:string;iqc_status:string};
const can=(u:User|null|undefined,p:string)=>Boolean(u&&(u.permissions.includes("*")||u.permissions.includes(p)));const message=(e:unknown)=>e instanceof ErpApiError?`${e.message}${e.requestId?`（请求 ${e.requestId}）`:""}`:"系统暂时无法完成请求";
async function post(session:Session,path:string,body:Record<string,unknown>){return api(path,{method:"POST",body:JSON.stringify(body),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}})}
export function ProcurementFulfillmentWorkspace(){const[session,setSession]=useState<Session|null>(null),[awards,setAwards]=useState<Award[]>([]),[orders,setOrders]=useState<Order[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const current=await api<Session>("/api/session");setSession(current);if(current.authenticated&&can(current.user,"procurement.fulfillment.read")){const[a,o]=await Promise.all([api<{data:Award[]}>("/api/procurement/fulfillment/pending-awards?page_size=100"),api<{data:Order[]}>("/api/procurement/fulfillment/orders?page_size=100")]);setAwards(a.data);setOrders(o.data)}}catch(e){setError(message(e))}},[]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function write(path:string,body:Record<string,unknown>,ok:string){if(!session)return;setBusy(true);setError("");try{await post(session,path,body);setNotice(ok);await load()}catch(e){setError(message(e))}finally{setBusy(false)}}
 if(!session)return <main className="sourcing-shell">正在读取会话…</main>;if(!session.authenticated)return <main className="sourcing-shell">请先登录。</main>;if(!can(session.user,"procurement.fulfillment.read"))return <main className="sourcing-shell"><div className="sourcing-state sourcing-error">没有采购履约读取权限。</div></main>;
 return <main className="sourcing-shell"><div className="sourcing-banner">并行验收环境 · 定标必须显式转 PO；采购只读查看收货单 → 供应商批次 → IQC 状态</div><header className="sourcing-header"><div><Link href="/procurement/sourcing" className="sourcing-back">← 供应商询价与定标</Link><p className="sourcing-kicker">寻源履约</p><h1>定标转单、到货计划与来料谱系</h1><p>采购确认不可变定标来源；仓库与品质分别负责收货和 IQC 放行。</p></div><div><b>{session.user!.display_name||session.user!.username}</b><span>{roleLabel(session.user!.role)}</span></div></header><section className="sourcing-metrics"><div><small>待转 PO 定标</small><strong>{awards.length}</strong></div><div><small>采购订单</small><strong>{orders.length}</strong></div><div><small>待建计划采购订单</small><strong>{orders.filter(o=>o.plan_count<o.line_count).length}</strong></div></section><div className="sourcing-grid"><section className="sourcing-panel"><h2>待显式转 PO 的定标</h2>{awards.map(row=><article className="sourcing-card" key={row.award_id}><div><b>{row.rfq_code} · 定标 #{row.award_id}</b><span className="sourcing-status status-awarded">已定标</span></div><p>{row.request_code} · {row.line_count} 行 · 数量 {row.total_quantity}</p><small>已转行 {row.converted_line_count} · 定标 v{row.award_version}</small>{can(session.user,"procurement.award.convert")?<button disabled={busy} onClick={()=>void write(`/api/procurement/awards/${row.award_id}/purchase-orders`,{expected_version:row.award_version},"采购订单已按供应商与币种确定性生成")}>显式生成采购订单</button>:null}</article>)}{!awards.length?<div className="sourcing-state">没有待转单定标。</div>:null}</section><section className="sourcing-panel"><h2>采购订单与到货计划</h2>{orders.map(row=><article className="sourcing-card" key={row.purchase_order_id}><div><b>{row.po_code} · {row.supplier_code}</b><span className={`sourcing-status status-${row.po_status.toLowerCase()}`}>{statusLabel(row.po_status)}</span></div><p>{row.supplier_name} · {row.currency_code} · 订购 {row.ordered_quantity} · 已收 {row.received_quantity}</p><small>{row.plan_count}/{row.line_count} 行已有计划 · PO v{row.po_version}</small>{row.receipt_count?<p>收货单：{row.receipt_codes}<br/>内部批次：{row.internal_lots||"兼容空批次"}<br/>供应商批次：{row.supplier_lots||"—"}<br/>IQC：{row.iqc_status?statusPairLabel(row.iqc_status):"待创建"}</p>:null}{row.plan_count===0&&can(session.user,"procurement.delivery_plan.manage")?<button disabled={busy} onClick={()=>void write(`/api/procurement/purchase-orders/${row.purchase_order_id}/delivery-plans`,{expected_version:row.po_version},"到货计划和待入库记录已建立；库存与应付仍为零")}>建立到货计划</button>:null}</article>)}</section></div>{notice?<div className="sourcing-state">{notice}</div>:null}{error?<div className="sourcing-state sourcing-error">{error}</div>:null}</main>}
