"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState,type ReactNode } from "react";
import { api,ErpApiError } from "../../../public/erp/api-client.js";
import { buildCreateRfqDraftRequest,RfqDraftRequestError,type StableOptionId } from "./create-rfq-draft-request";
import "./sourcing.css";

type User={username:string;display_name:string;role:string;permissions:string[]};type Session={authenticated:boolean;user:User|null;csrf_token?:string};
type RequestRow={id:StableOptionId;request_code:string;status:string;version:number;project_code:string;project_name:string;required_date:string;line_count:number;requested_quantity:string;rfq_available:boolean};
type RfqRow={id:number;rfq_code:string;request_code:string;round_no:number;status:string;response_deadline:string;version:number;supplier_count:number;submitted_quote_count:number;compared_line_count:number;award_id?:number;award_status?:string};
type Supplier={id:StableOptionId;supplier_code:string;supplier_name:string;status:string};
type RfqLine={id:number;line_no:number;internal_material_code:string;standard_name:string;unit_code:string;requested_quantity:string;required_date:string};
type RfqSupplier={supplier_id:number;supplier_code:string;supplier_name:string;status:string;supplier_status:string};
type Quote={id:number;supplier_id:number;supplier_code:string;supplier_name:string;quote_version_no:number;supplier_quote_reference:string;status:string;valid_until:string;tax_included:boolean;freight_included:boolean;payment_terms:string;version:number;quote_expired:boolean};
type QuoteLine={id:number;quote_id:number;rfq_line_id:number;quoted_quantity:string;minimum_order_quantity:string;unit_price:string;lead_time_days:number;promised_delivery_date:string};
type ComparisonLine={id:number;comparison_id:number;quote_line_id:number;supplier_id:number;supplier_code:string;supplier_name:string;currency_code:string;unit_id:number;tax_included:boolean;freight_included:boolean;unit_price:string;minimum_order_quantity:string;promised_delivery_date:string;price_rank:number|null;lowest_price:boolean;moq_satisfied:boolean;delivery_status:string;quote_expired:boolean;comparable_status:string;reason_code:string;awardable:boolean};
type Detail={header:RfqRow&{purchase_request_id:number;project_code:string;project_name:string;source_required_date:string;currency_code:string};lines:RfqLine[];suppliers:RfqSupplier[];quotes:Quote[];quote_lines:QuoteLine[];comparisons:Array<{id:number;rfq_line_id:number;comparison_version_no:number}>;comparison_lines:ComparisonLine[];award:null|{id:number;status:string;version:number;reason_code:string;reason:string;reversal_reason:string;lines:Array<Record<string,unknown>>};events:Array<{id:number;event_type:string;actor:string;reason:string;created_at:string}>};
const labels:Record<string,string>={DRAFT:"待发出",ISSUED:"询价中",CLOSED:"已定标",CANCELLED:"已取消",INVITED:"待报价",RESPONDED:"已报价",SUBMITTED:"当前报价",SUPERSEDED:"历史版本",WITHDRAWN:"已撤回",AWARDED:"已定标",REVERSED:"已撤销",ON_TIME:"交期满足",LATE:"晚于需求",COMPARABLE:"可比较",NOT_COMPARABLE:"不可比较"};
const can=(u:User|null|undefined,p:string)=>Boolean(u&&(u.permissions.includes("*")||u.permissions.includes(p)));const err=(e:unknown)=>e instanceof ErpApiError?`${e.message}${e.requestId?`（请求 ${e.requestId}）`:""}`:e instanceof RfqDraftRequestError?e.message:"系统暂时无法完成请求";const d=(v:string)=>String(v||"").slice(0,10);
function Status({value}:{value:string}){return <span className={`sourcing-status status-${value.toLowerCase()}`}>{labels[value]||value}</span>}
function State({children,error=false}:{children:ReactNode;error?:boolean}){return <div className={error?"sourcing-state sourcing-error":"sourcing-state"}>{children}</div>}
function Shell({user,title,subtitle,children}:{user:User;title:string;subtitle:string;children:ReactNode}){return <main className="sourcing-shell"><div className="sourcing-banner">并行验收环境 · 定标仅生成 Sourcing Award；不进入采购订单、收货、库存或应付</div><header className="sourcing-header"><div><Link href="/" className="sourcing-back">← 经营工作台</Link><p className="sourcing-kicker">PROCUREMENT SOURCING</p><h1>{title}</h1><p>{subtitle}</p></div><div><b>{user.display_name||user.username}</b><span>{user.role}</span></div></header>{children}</main>}
async function mutate(session:Session,path:string,body:Record<string,unknown>){if(!session.csrf_token)throw new Error("missing csrf");return api(path,{method:"POST",body:JSON.stringify(body),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}})}

export function ProcurementSourcingWorkspace(){const[session,setSession]=useState<Session|null>(null),[requests,setRequests]=useState<RequestRow[]>([]),[rfqs,setRfqs]=useState<RfqRow[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const current=await api<Session>("/api/session");setSession(current);if(!current.authenticated||!can(current.user,"procurement.rfq.read"))return;const [accepted,list,supplierList]=await Promise.all([api<{data:RequestRow[]}>("/api/procurement/rfqs?queue=accepted&page_size=100"),api<{data:RfqRow[]}>("/api/procurement/rfqs?page_size=100"),api<{rows:Supplier[]}>("/api/suppliers?page_size=100")]);setRequests(accepted.data);setRfqs(list.data);setSuppliers((supplierList.rows||[]).filter(row=>row.status==="ACTIVE"))}catch(e){setError(err(e))}},[]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!session)return;const form=new FormData(event.currentTarget);setBusy(true);setError("");try{const body=buildCreateRfqDraftRequest(requests,suppliers,{purchaseRequestId:form.get("purchase_request_id"),supplierIds:form.getAll("supplier_ids"),responseDeadline:form.get("response_deadline")});const result=await mutate(session,"/api/procurement/rfqs",body) as {rfq_id:number};setNotice("RFQ 草稿已建立；发出后范围和行将不可修改");location.href=`/procurement/sourcing/${result.rfq_id}`}catch(e){setError(err(e));setBusy(false)}}
 if(!session)return <State>{error||"正在读取会话…"}</State>;if(!session.authenticated)return <State>请先登录。</State>;if(!can(session.user,"procurement.rfq.read"))return <State error>没有权限读取采购询比价进度。</State>;
 const pendingQuote=rfqs.filter(row=>row.status==="ISSUED"&&row.submitted_quote_count<row.supplier_count).length,pendingAward=rfqs.filter(row=>row.status==="ISSUED"&&row.submitted_quote_count>0).length;
 return <Shell user={session.user!} title="供应商询价与定标" subtitle="采购人工发询价、代录报价、生成确定性比价并记录选择理由。"><section className="sourcing-metrics"><div><small>待询价采购申请</small><strong>{requests.filter(r=>r.rfq_available).length}</strong></div><div><small>待报价 RFQ</small><strong>{pendingQuote}</strong></div><div><small>待定标 RFQ</small><strong>{pendingAward}</strong></div></section><div className="sourcing-grid"><section className="sourcing-panel"><h2>已接收采购申请</h2>{requests.map(row=><article className="sourcing-card" key={String(row.id)}><div><b>{row.request_code} · {row.project_code}</b><Status value={row.status}/></div><p>{row.project_name} · {row.line_count} 行 · {row.requested_quantity} · 需求 {d(row.required_date)}</p><small>{row.rfq_available?"可创建新 Round":"已有有效 RFQ Round"}</small></article>)}{can(session.user,"procurement.rfq.manage")?<form className="sourcing-form sourcing-card" onSubmit={create}><h3>创建 RFQ 草稿</h3><label>采购申请<select name="purchase_request_id" required><option value="">请选择</option>{requests.filter(row=>row.rfq_available).map(row=><option key={String(row.id)} value={String(row.id)}>{row.request_code} · {row.project_code}</option>)}</select></label><fieldset><legend>候选 ACTIVE 供应商（每个供应商须完整 1:1 Mapping）</legend>{suppliers.map(row=><label className="sourcing-check" key={String(row.id)}><input type="checkbox" name="supplier_ids" value={String(row.id)}/>{row.supplier_code} · {row.supplier_name}</label>)}</fieldset><label>报价截止日<input type="date" name="response_deadline" required/></label><button disabled={busy}>建立询价草稿</button></form>:null}</section><section className="sourcing-panel"><h2>RFQ 列表</h2>{rfqs.map(row=><Link className="sourcing-card sourcing-link" href={`/procurement/sourcing/${row.id}`} key={row.id}><div><b>{row.rfq_code} · Round {row.round_no}</b><Status value={row.status}/></div><p>{row.request_code} · {row.supplier_count} 家供应商 · 当前报价 {row.submitted_quote_count}</p><small>比价行 {row.compared_line_count} · 截止 {d(row.response_deadline)}</small></Link>)}{!rfqs.length?<State>尚无 RFQ。</State>:null}</section></div>{notice?<State>{notice}</State>:null}{error?<State error>{error}</State>:null}</Shell>}

export function ProcurementSourcingDetailWorkspace({rfqId}:{rfqId:number}){const[session,setSession]=useState<Session|null>(null),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const current=await api<Session>("/api/session");setSession(current);if(current.authenticated&&can(current.user,"procurement.rfq.read"))setDetail((await api<{data:Detail}>(`/api/procurement/rfqs/${rfqId}`)).data)}catch(e){setError(err(e))}},[rfqId]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function write(path:string,body:Record<string,unknown>,message:string){if(!session)return;setBusy(true);setError("");try{await mutate(session,path,body);setNotice(message);await load()}catch(e){setError(err(e))}finally{setBusy(false)}}
 function quoteBody(form:FormData,supplierId:number){if(!detail)return{};return{expected_version:detail.header.version,supplier_id:supplierId,supplier_quote_reference:String(form.get("reference")||""),valid_until:String(form.get("valid_until")||""),tax_included:form.get("tax_included")==="on",freight_included:form.get("freight_included")==="on",payment_terms:String(form.get("payment_terms")||""),lines:detail.lines.map(line=>({rfq_line_id:line.id,quoted_quantity:String(form.get(`quoted_quantity_${line.id}`)||""),minimum_order_quantity:String(form.get(`moq_${line.id}`)||""),unit_price:String(form.get(`price_${line.id}`)||""),lead_time_days:Number(form.get(`lead_${line.id}`)),promised_delivery_date:String(form.get(`delivery_${line.id}`)||"")}))}}
 function recordQuote(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),supplierId=Number(form.get("supplier_id"));void write(`/api/procurement/rfqs/${rfqId}/quotes`,quoteBody(form,supplierId),"报价已作为不可变 SUBMITTED 版本保存")}
 function reviseQuote(event:FormEvent<HTMLFormElement>,quote:Quote){event.preventDefault();const form=new FormData(event.currentTarget),body=quoteBody(form,quote.supplier_id) as Record<string,unknown>;delete body.supplier_id;body.expected_version=quote.version;body.rfq_expected_version=detail?.header.version;void write(`/api/procurement/quotes/${quote.id}/revise`,body,"旧报价已 SUPERSEDED，新版本已提交")}
 function award(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detail)return;const form=new FormData(event.currentTarget);void write(`/api/procurement/rfqs/${rfqId}/award`,{expected_version:detail.header.version,reason_code:String(form.get("reason_code")||""),reason:String(form.get("reason")||""),lines:detail.lines.map(line=>({rfq_line_id:line.id,selected_quote_line_id:Number(form.get(`quote_line_${line.id}`)),selected_quantity:String(form.get(`quantity_${line.id}`)||""),selection_reason:String(form.get(`selection_reason_${line.id}`)||""),late_delivery_reason_code:String(form.get(`late_code_${line.id}`)||""),late_delivery_reason:String(form.get(`late_reason_${line.id}`)||""),excess_quantity_reason:String(form.get(`excess_reason_${line.id}`)||"")}))},"人工定标已形成 Sourcing Award；没有产生采购订单")}
 if(!session||!detail)return <State>{error||"正在读取询价…"}</State>;if(!session.authenticated)return <State>请先登录。</State>;if(!can(session.user,"procurement.rfq.read"))return <State error>没有权限读取采购询比价进度。</State>;
 return <Shell user={session.user!} title={`${detail.header.rfq_code} · Round ${detail.header.round_no}`} subtitle={`${detail.header.request_code} · ${detail.header.project_code} · CNY / 固定单位口径`}><section className="sourcing-panel"><div className="sourcing-title"><div><Link href="/procurement/sourcing" className="sourcing-back">← 返回询价列表</Link><h2>采购申请来源</h2></div><Status value={detail.header.status}/></div><dl className="sourcing-facts"><div><dt>项目</dt><dd>{detail.header.project_name}</dd></div><div><dt>需求日期</dt><dd>{d(detail.header.source_required_date)}</dd></div><div><dt>报价截止</dt><dd>{d(detail.header.response_deadline)}</dd></div><div><dt>RFQ 版本</dt><dd>v{detail.header.version}</dd></div></dl><table><thead><tr><th>行</th><th>物料</th><th>单位</th><th>申请数量</th><th>需求日期</th></tr></thead><tbody>{detail.lines.map(line=><tr key={line.id}><td>{line.line_no}</td><td><b>{line.internal_material_code}</b><br/>{line.standard_name}</td><td>{line.unit_code}</td><td>{line.requested_quantity}</td><td>{d(line.required_date)}</td></tr>)}</tbody></table>{detail.header.status==="DRAFT"&&can(session.user,"procurement.rfq.manage")?<button disabled={busy} onClick={()=>void write(`/api/procurement/rfqs/${rfqId}/issue`,{expected_version:detail.header.version},"RFQ 已发出，范围和行已冻结")}>发出询价并冻结范围</button>:null}</section>
 <section className="sourcing-panel"><h2>候选供应商与报价版本</h2><div className="sourcing-cards">{detail.suppliers.map(row=><article className="sourcing-card" key={row.supplier_id}><div><b>{row.supplier_code} · {row.supplier_name}</b><Status value={row.status}/></div><small>{row.supplier_status}</small></article>)}</div>{detail.quotes.map(quote=><article className="sourcing-card" key={quote.id}><div><b>{quote.supplier_name} · 报价 v{quote.quote_version_no}</b><Status value={quote.status}/></div><p>{quote.supplier_quote_reference} · 有效至 {d(quote.valid_until)} {quote.quote_expired?"· 已过期":""}</p><small>{quote.tax_included?"含税":"未税"} · {quote.freight_included?"含运费":"不含运费"} · {quote.payment_terms}</small>{quote.status==="SUBMITTED"&&detail.header.status==="ISSUED"&&can(session.user,"procurement.quote.record")?<QuoteForm detail={detail} quote={quote} submit={(e)=>reviseQuote(e,quote)} busy={busy}/>:null}</article>)}{detail.header.status==="ISSUED"&&can(session.user,"procurement.quote.record")?<QuoteForm detail={detail} submit={recordQuote} busy={busy}/>:null}</section>
 <section className="sourcing-panel"><div className="sourcing-title"><h2>服务端横向比价</h2>{detail.header.status==="ISSUED"&&can(session.user,"procurement.quote.compare")?<button disabled={busy} onClick={()=>void write(`/api/procurement/rfqs/${rfqId}/comparisons`,{expected_version:detail.header.version},"最新报价已按固定口径确定性排序")}>生成最新比价</button>:null}</div><p className="sourcing-note">按 CNY、单位、含税和运费口径分组；组内仅由服务端按单价、交期、Supplier ID 排名。结果不代表自动审批。</p><table><thead><tr><th>RFQ 行</th><th>供应商</th><th>口径</th><th>单价 / 排名</th><th>MOQ</th><th>交期</th><th>可定标</th></tr></thead><tbody>{detail.comparison_lines.map(row=>{const line=detail.quote_lines.find(q=>q.id===row.quote_line_id);return <tr key={row.id}><td>{line?.rfq_line_id}</td><td>{row.supplier_code} · {row.supplier_name}</td><td>{row.tax_included?"含税":"未税"} / {row.freight_included?"含运费":"不含运费"}</td><td>{row.unit_price} / {row.price_rank??"—"}{row.lowest_price?" · 最低价":""}</td><td>{row.minimum_order_quantity} · {row.moq_satisfied?"申请量满足":"需增量"}</td><td>{d(row.promised_delivery_date)} · <Status value={row.delivery_status}/></td><td>{row.quote_expired?"已过期":row.comparable_status==="COMPARABLE"?"可选择":"不可选择"}</td></tr>})}</tbody></table></section>
 <section className="sourcing-panel"><h2>人工定标与撤销</h2>{detail.award?<article className="sourcing-card"><div><b>定标 #{detail.award.id} · {detail.award.reason_code}</b><Status value={detail.award.status}/></div><p>{detail.award.reason}</p>{detail.award.reversal_reason?<small>撤销原因：{detail.award.reversal_reason}</small>:null}{detail.award.status==="AWARDED"&&can(session.user,"procurement.sourcing.reverse")?<form className="sourcing-form" onSubmit={e=>{e.preventDefault();void write(`/api/procurement/awards/${detail.award!.id}/reversal`,{expected_version:detail.award!.version,reason:String(new FormData(e.currentTarget).get("reason")||"")},"定标已撤销；历史保留，重新询价须创建新 Round")}}><label>撤销原因<textarea name="reason" required maxLength={1000}/></label><button className="danger" disabled={busy}>撤销定标并保留历史</button></form>:null}</article>:detail.header.status==="ISSUED"&&detail.comparison_lines.length&&can(session.user,"procurement.sourcing.award")?<form className="sourcing-form" onSubmit={award}><label>总体理由代码<select name="reason_code" required><option value="LOWEST_PRICE">LOWEST_PRICE</option><option value="DELIVERY_PRIORITY">DELIVERY_PRIORITY</option><option value="SOLE_SOURCE">SOLE_SOURCE</option><option value="LATE_DELIVERY_ACCEPTED">LATE_DELIVERY_ACCEPTED</option><option value="COMMERCIAL_TERMS">COMMERCIAL_TERMS</option><option value="OTHER">OTHER</option></select></label><label>总体理由<textarea name="reason" required maxLength={1000}/></label>{detail.lines.map(line=><fieldset key={line.id}><legend>RFQ 行 {line.line_no} · {line.internal_material_code}</legend><label>选择当前报价<select name={`quote_line_${line.id}`} required><option value="">请选择</option>{detail.comparison_lines.filter(c=>detail.quote_lines.find(q=>q.id===c.quote_line_id)?.rfq_line_id===line.id&&c.comparable_status==="COMPARABLE"&&!c.quote_expired).map(c=><option value={c.quote_line_id} key={c.id}>{c.supplier_code} · {c.unit_price} · 排名 {c.price_rank} · {labels[c.delivery_status]}</option>)}</select></label><label>中标数量<input name={`quantity_${line.id}`} defaultValue={line.requested_quantity} required/></label><label>选型理由（非最低价必填）<textarea name={`selection_reason_${line.id}`} maxLength={1000}/></label><label>晚交期代码<input name={`late_code_${line.id}`} placeholder="晚交期时填 LATE_DELIVERY_ACCEPTED"/></label><label>晚交期接受理由<textarea name={`late_reason_${line.id}`} maxLength={1000}/></label><label>超申请数量原因<textarea name={`excess_reason_${line.id}`} maxLength={1000}/></label></fieldset>)}<button disabled={busy}>确认人工定标</button></form>:<State>先录入当前有效报价并生成最新比较，之后才能人工定标。</State>}</section>
 <section className="sourcing-panel"><h2>不可变采购询比价事件</h2>{detail.events.map(event=><div className="sourcing-event" key={event.id}><Status value={event.event_type}/><b>{event.actor}</b><span>{new Date(event.created_at).toLocaleString("zh-CN")}</span><p>{event.reason}</p></div>)}</section>{notice?<State>{notice}</State>:null}{error?<State error>{error}</State>:null}</Shell>}

function QuoteForm({detail,quote,submit,busy}:{detail:Detail;quote?:Quote;submit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){const ownLines=quote?detail.quote_lines.filter(line=>line.quote_id===quote.id):[];return <form className="sourcing-form sourcing-quote" onSubmit={submit}><h3>{quote?`修订 ${quote.supplier_name} 报价` : "代录供应商报价"}</h3>{!quote?<label>受邀供应商<select name="supplier_id" required><option value="">请选择</option>{detail.suppliers.map(row=><option value={row.supplier_id} key={row.supplier_id}>{row.supplier_code} · {row.supplier_name}</option>)}</select></label>:null}<label>供应商报价参考<input name="reference" defaultValue={quote?.supplier_quote_reference} required maxLength={200}/></label><label>有效期<input type="date" name="valid_until" defaultValue={d(quote?.valid_until||"")} required/></label><label className="sourcing-check"><input type="checkbox" name="tax_included" defaultChecked={quote?.tax_included}/>含税</label><label className="sourcing-check"><input type="checkbox" name="freight_included" defaultChecked={quote?.freight_included}/>含运费</label><label>付款条款<textarea name="payment_terms" defaultValue={quote?.payment_terms} required maxLength={1000}/></label>{detail.lines.map(line=>{const prior=ownLines.find(q=>q.rfq_line_id===line.id);return <fieldset key={line.id}><legend>{line.internal_material_code} · {line.unit_code}</legend><label>报价数量<input name={`quoted_quantity_${line.id}`} defaultValue={prior?.quoted_quantity||line.requested_quantity} required/></label><label>MOQ<input name={`moq_${line.id}`} defaultValue={prior?.minimum_order_quantity||line.requested_quantity} required/></label><label>单价<input name={`price_${line.id}`} defaultValue={prior?.unit_price} required/></label><label>交期天数<input type="number" min="0" max="36500" name={`lead_${line.id}`} defaultValue={prior?.lead_time_days||0} required/></label><label>承诺交付日<input type="date" name={`delivery_${line.id}`} defaultValue={d(prior?.promised_delivery_date||line.required_date)} required/></label></fieldset>})}<button disabled={busy}>{quote?"创建新报价版本":"提交不可变报价"}</button></form>}
