"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type User = { username: string; display_name: string; role: string; permissions: string[] };
type Session = { authenticated: boolean; user: User | null; csrf_token?: string };
type Document = { id: number; doc_code: string; doc_type: "AR" | "AP"; counterparty: string; currency_code: string; total_amount: string; settled_amount: string; status: string; version: number };
type Settlement = { id: number; settlement_code: string; document_id: number; doc_code: string; settlement_type: string; amount: string; counterparty: string; accounting_date: string; document_version: number; is_reversed: boolean };
const can = (user: User | null | undefined, permission: string) => Boolean(user && (user.permissions.includes("*") || user.permissions.includes(permission)));
const message = (error: unknown) => error instanceof ErpApiError ? `${error.message}${error.requestId ? `（请求 ${error.requestId}）` : ""}` : "系统暂时无法完成请求";

export function FinanceSettlementsWorkspace() {
  const [session, setSession] = useState<Session | null>(null); const [documents, setDocuments] = useState<Document[]>([]); const [settlements, setSettlements] = useState<Settlement[]>([]);
  const [amounts, setAmounts] = useState<Record<number, string>>({}); const [accountName, setAccountName] = useState("内部结算账户"); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const current = await api<Session>("/api/session"); setSession(current); if (current.authenticated && can(current.user, "finance.read")) { const [docs, flows] = await Promise.all([api<{ data: Document[] }>("/api/financial-documents?page_size=100"), api<{ data: Settlement[] }>("/api/finance/settlements?page_size=100")]); setDocuments(docs.data); setSettlements(flows.data); } } catch (cause) { setError(message(cause)); } }, []);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  async function write(path: string, body: Record<string, unknown>, success: string) { if (!session?.csrf_token) return; setBusy(true); setError(""); try { await api(path, { method: "POST", body: JSON.stringify(body), protectedWrite: { csrfToken: session.csrf_token, idempotencyKey: crypto.randomUUID() } }); setNotice(success); await load(); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  async function settle(row: Document) { const value = amounts[row.id]; const today = new Date().toISOString().slice(0, 10); await write("/api/finance/settlements", { document_id: row.id, expected_version: row.version, settlement_type: row.doc_type === "AR" ? "RECEIPT" : "PAYMENT", amount: value, accounting_date: today, account_name: accountName, reason: "内部收付款登记" }, `${row.doc_code} 已登记${row.doc_type === "AR" ? "客户收款" : "供应商付款"} ${value} ${row.currency_code}`); }
  async function reverse(row: Settlement) { const today = new Date().toISOString().slice(0, 10); await write(`/api/finance-settlements/${row.id}/reversal`, { expected_version: row.document_version, accounting_date: today, reason: "受控全额冲销" }, `${row.settlement_code} 已全额冲销`); }
  if (!session) return <main className="sourcing-shell">正在读取会话…</main>; if (!session.authenticated) return <main className="sourcing-shell">请先登录。</main>; if (!can(session.user, "finance.read")) return <main className="sourcing-shell">没有财务读取权限。</main>;
  return <main className="sourcing-shell"><div className="sourcing-banner">内部核销事实 · 不连接真实银行 · 账户标签不代表银行余额已核验</div><header className="sourcing-header"><div><Link href="/" className="sourcing-back">← 经营工作台</Link><p className="sourcing-kicker">CUSTOMER RECEIPTS · SUPPLIER PAYMENTS</p><h1>客户收款与供应商付款</h1><p>AR 仅收款、AP 仅付款；金额、币种和往来方由服务端单据继承，支持部分和多次核销。</p></div></header>{can(session.user, "finance.pay") ? <section className="sourcing-panel"><h2>待核销单据</h2><label>内部记账账户标签<input value={accountName} maxLength={200} onChange={(event) => setAccountName(event.target.value)} /></label>{documents.filter((row) => row.status !== "SETTLED" && row.status !== "REVERSED").map((row) => <article className="sourcing-card" key={row.id}><div><b>{row.doc_code} · {row.doc_type}</b><span className="sourcing-status status-pending">{row.status}</span></div><p>{row.counterparty} · {row.currency_code} · 总额 {row.total_amount} · 已结 {row.settled_amount}</p><input aria-label={`${row.doc_code} 核销金额`} inputMode="decimal" placeholder="本次金额" value={amounts[row.id] || ""} onChange={(event) => setAmounts((state) => ({ ...state, [row.id]: event.target.value }))} /><button disabled={busy || !amounts[row.id]} onClick={() => void settle(row)}>{row.doc_type === "AR" ? "登记客户收款" : "登记供应商付款"}</button></article>)}{!documents.some((row) => !["SETTLED", "REVERSED"].includes(row.status)) ? <div className="sourcing-state">当前无待核销单据。</div> : null}</section> : null}<section className="sourcing-panel"><h2>不可变收付款流水</h2>{settlements.map((row) => <article className="sourcing-card" key={row.id}><div><b>{row.settlement_code} · {row.settlement_type}</b><span className="sourcing-status status-completed">{row.amount}</span></div><p>{row.doc_code} · {row.counterparty} · {row.accounting_date}</p>{can(session.user, "finance.reverse") && !row.is_reversed && !row.settlement_type.endsWith("_REVERSAL") ? <button disabled={busy} onClick={() => void reverse(row)}>受控全额冲销</button> : null}</article>)}{!settlements.length ? <div className="sourcing-state">尚无收付款流水。</div> : null}</section>{notice ? <div className="sourcing-state">{notice}</div> : null}{error ? <div className="sourcing-state sourcing-error">{error}</div> : null}</main>;
}
