"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};
type Operator={username:string;display_name:string};
type RequestRow={id:number;request_code:string;ncr_code:string;batch_code?:string;work_order_code:string;revision_no:number;target_snapshot_operation_id:number;target_sequence_no:number;target_operation_code:string;target_operation_name:string;target_work_center_code:string;quantity:string;reason:string;status:string;version:number;canonical_digest?:string;created_by:string;return_reason:string;failed_qty:string;execution_status?:string;execution_version?:number;accepted_rework_qty?:string;rework_waiting_dispatch_qty?:string;rework_dispatched_qty?:string;rework_in_progress_qty?:string;rework_reported_good_qty?:string;rework_reported_scrap_qty?:string;rework_pending_reinspection_qty?:string;rework_released_qty?:string;rework_completed_qty?:string;unresolved_rework_qty?:string};
const can=(s:Session|null,p:string)=>Boolean(s?.user&&(s.user.permissions.includes("*")||s.user.permissions.includes(p)));

export default function ProductionReworkRequestsPage(){
 const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<RequestRow[]>([]),[operators,setOperators]=useState<Operator[]>([]),[error,setError]=useState("");
 async function load(){const current=await api<Session>("/api/session");setSession(current);if(current.authenticated&&can(current,"production.rework_request.read")){const[requests,users]=await Promise.all([api<{data:RequestRow[]}>("/api/production/rework-requests?page_size=100"),api<{data:Operator[]}>("/api/production/operation-execution/operators")]);setRows(requests.data);setOperators(users.data);}}
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(c=>setError(c instanceof ErpApiError?c.message:"读取失败")),0);return()=>clearTimeout(timer);},[]);
 async function write(path:string,body:Record<string,unknown>){if(!session?.csrf_token)return;try{await api(path,{method:"POST",body:JSON.stringify(body),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}});await load();}catch(c){setError(c instanceof ErpApiError?`${c.message} (${c.code})`:"操作失败");}}
 async function decide(row:RequestRow,action:"accept"|"return"){const reason=action==="return"?window.prompt("退回原因（必填）","返工理由需补充")||"":"";if(action==="return"&&!reason)return;await write(`/api/production/rework-requests/${row.id}/${action}`,{expected_version:row.version,...(reason?{reason}:{})});}
 async function dispatch(event:FormEvent<HTMLFormElement>,row:RequestRow){event.preventDefault();const form=new FormData(event.currentTarget);await write(`/api/production/rework-requests/${row.id}/dispatch`,{expected_execution_version:row.execution_version,quantity:String(form.get("quantity")),assigned_operator:String(form.get("assigned_operator")),planned_start:"",planned_end:""});}
 return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/quality/nonconformances">← NCR 队列</Link><h1>生产返工接收与显式派工</h1><p>ACCEPTED 返工必须由 production 显式创建现有 Operation Run 的 REWORK 类型；批次身份由原 NCR/检验/Run Report 继承，浏览器不能选择或覆盖。返工不再次领料，也不增加工单净产量。</p><p>生产批次谱系已建立，但仓库批次库存尚未启用。</p><nav><Link href="/production/dispatch">普通派工</Link> · <Link href="/production/operations">NORMAL / REWORK 执行</Link> · <Link href="/quality/production">返工复检</Link></nav></div></header>{error?<div className="sourcing-state sourcing-error">{error}</div>:null}<section className="sourcing-panel">{rows.map(row=><article className="sourcing-card" key={row.id}><div><b>{row.batch_code??"ORDER"} · {row.request_code} · {row.ncr_code} · 提交 v{row.revision_no}</b><span className="sourcing-status">请求 {row.status} · 执行 {row.execution_status??"—"}</span></div><small>{row.work_order_code} · 原 failed {row.failed_qty} · 目标 Snapshot Operation #{row.target_snapshot_operation_id} · {row.target_sequence_no} {row.target_operation_code} {row.target_operation_name} · {row.target_work_center_code}</small><p>accepted/待派/已派/在制 {row.accepted_rework_qty??"—"}/{row.rework_waiting_dispatch_qty??"—"}/{row.rework_dispatched_qty??"—"}/{row.rework_in_progress_qty??"—"}</p><p>处理后 good/scrap/待复检/已放行/已完成/未解决 {row.rework_reported_good_qty??"—"}/{row.rework_reported_scrap_qty??"—"}/{row.rework_pending_reinspection_qty??"—"}/{row.rework_released_qty??"—"}/{row.rework_completed_qty??"—"}/{row.unresolved_rework_qty??"—"}</p>{row.canonical_digest?<code>{row.canonical_digest}</code>:null}{row.status==="SUBMITTED"&&can(session,"production.rework_request.decide")?<div><button onClick={()=>void decide(row,"accept")}>ACCEPT</button><button onClick={()=>void decide(row,"return")}>RETURN</button></div>:null}{row.status==="ACCEPTED"&&Number(row.rework_waiting_dispatch_qty)>0&&can(session,"production.dispatch")?<form onSubmit={event=>void dispatch(event,row)}><label>返工派工数量<input name="quantity" type="number" min="0.000001" step="0.000001" max={row.rework_waiting_dispatch_qty} defaultValue={row.rework_waiting_dispatch_qty} required/></label><label>执行人<select name="assigned_operator" required>{operators.map(item=><option value={item.username} key={item.username}>{item.display_name} ({item.username})</option>)}</select></label><button>创建 REWORK Run</button></form>:null}</article>)}</section></main>;
}
