"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};type RequestRow={id:number;request_code:string;ncr_code:string;work_order_code:string;revision_no:number;target_snapshot_operation_id:number;target_sequence_no:number;target_operation_code:string;target_operation_name:string;target_work_center_code:string;quantity:string;reason:string;status:string;version:number;canonical_digest?:string;created_by:string;return_reason:string};const can=(s:Session|null,p:string)=>Boolean(s?.user&&(s.user.permissions.includes("*")||s.user.permissions.includes(p)));
export default function ProductionReworkRequestsPage(){const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<RequestRow[]>([]),[error,setError]=useState("");async function load(){const current=await api<Session>("/api/session");setSession(current);if(current.authenticated&&can(current,"production.rework_request.read"))setRows((await api<{data:RequestRow[]}>("/api/production/rework-requests?page_size=100")).data);}useEffect(()=>{const timer=setTimeout(()=>void load().catch(c=>setError(c instanceof ErpApiError?c.message:"读取失败")),0);return()=>clearTimeout(timer);},[]);async function decide(row:RequestRow,action:"accept"|"return"){if(!session?.csrf_token)return;const reason=action==="return"?window.prompt("退回原因（必填）", "返工理由需补充")||"":"";if(action==="return"&&!reason)return;try{await api(`/api/production/rework-requests/${row.id}/${action}`,{method:"POST",body:JSON.stringify({expected_version:row.version,...(reason?{reason}:{})}),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}});await load();}catch(c){setError(c instanceof ErpApiError?`${c.message} (${c.code})`:"决策失败");}}return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/quality/nonconformances">← NCR 队列</Link><h1>生产返工申请接收</h1><p>生产只接收或退回；ACCEPTED 仍等待后续任务执行，不创建返工 Run、派工、WIP、领料或库存事实。</p></div></header>{error?<div className="sourcing-state sourcing-error">{error}</div>:null}<section className="sourcing-panel">{rows.map(row=><article className="sourcing-card" key={row.id}><div><b>{row.request_code} · {row.ncr_code} · v{row.revision_no}</b><span className="sourcing-status">{row.status} · CAS {row.version}</span></div><small>{row.work_order_code} · Snapshot Operation #{row.target_snapshot_operation_id} · {row.target_sequence_no} {row.target_operation_code} {row.target_operation_name} · Work Center {row.target_work_center_code}</small><p>数量 {row.quantity} · {row.reason} · 创建人 {row.created_by}</p>{row.canonical_digest?<code>{row.canonical_digest}</code>:null}{row.status==="SUBMITTED"&&can(session,"production.rework_request.decide")?<div><button onClick={()=>void decide(row,"accept")}>ACCEPT</button><button onClick={()=>void decide(row,"return")}>RETURN</button></div>:null}</article>)}</section></main>}
