"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};
type Source={allocation_id?:number;inventory_lot_id?:number;lot_code?:string;lot_status?:string;production_report_id?:number;operation_run_report_id?:number;production_batch_id?:number;batch_code?:string;source_kind?:"OPERATION_RUN_REPORT"|"LEGACY_PRODUCTION_REPORT";run_kind?:"NORMAL"|"REWORK";rework_request_id?:number;nonconformance_id?:number;source_code:string;work_order_code?:string;snapshot_operation_id?:number;sequence_no?:number;operation_code?:string;operation_name?:string;work_center_code?:string;quality_gate_mode?:"IPQC";material_code:string;material_name:string;unit_code:string;source_qty:string;remaining_qty:string};
type Inspection={id:number;inspection_code:string;inspection_type:"IPQC"|"FQC";inventory_lot_id?:number;lot_code?:string;lot_status?:string;production_operation_run_report_id?:number;production_report_id?:number;production_batch_id?:number;batch_code?:string;inspection_status:string;inspected_qty:string;passed_qty:string;failed_qty:string;released_qty:string;lifecycle_status:"OPEN"|"CLOSED";decision_status:"PENDING"|"HOLD"|"RELEASED";version:number;created_by:string;material_code:string;material_name:string};
type Pending={path:string;body:string;key:string;label:string};
const can=(s:Session|null,p:string)=>Boolean(s?.user&&(s.user.permissions.includes("*")||s.user.permissions.includes(p)));

export default function ProductionQualityPage(){
  const[session,setSession]=useState<Session|null>(null),[ipqc,setIpqc]=useState<Source[]>([]),[fqc,setFqc]=useState<Source[]>([]),[rows,setRows]=useState<Inspection[]>([]),[loading,setLoading]=useState(true),[forbidden,setForbidden]=useState(false),[error,setError]=useState(""),[pending,setPending]=useState<Pending|null>(null);
  async function load(){setLoading(true);try{const current=await api<Session>("/api/session");setSession(current);if(!current.authenticated||!can(current,"quality.read")){setForbidden(true);return;}setForbidden(false);const[reports,allocations,inspections]=await Promise.all([api<{data:Source[]}>("/api/quality/source-options?inspection_type=IPQC"),api<{data:Source[]}>("/api/quality/source-options?inspection_type=FQC"),api<{data:Inspection[]}>("/api/quality-inspections?page_size=100")]);setIpqc(reports.data);setFqc(allocations.data);setRows(inspections.data.filter(r=>r.inspection_type==="IPQC"||r.inspection_type==="FQC"));}catch(e){if(e instanceof ErpApiError&&e.status===403)setForbidden(true);else setError(e instanceof ErpApiError?e.message:"读取失败");}finally{setLoading(false);}}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[]);
  async function write(operation:Pending){if(!session?.csrf_token)return;setError("");try{await api(operation.path,{method:"POST",body:operation.body,protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:operation.key}});setPending(null);await load();}catch(e){if(e instanceof ErpApiError&&e.resultUnknown){setPending(operation);setError(`${operation.label}结果未知；请使用原操作标识安全重试。`);}else{setPending(null);setError(e instanceof ErpApiError?`${e.message}${e.code.includes("VERSION")||e.status===409?"；当前状态可能已变化，请刷新":""}`:`${operation.label}失败`);if(e instanceof ErpApiError&&[403,409].includes(e.status))await load();}}}
  async function inspect(event:FormEvent<HTMLFormElement>,type:"IPQC"|"FQC"){event.preventDefault();const form=new FormData(event.currentTarget),sources=type==="IPQC"?ipqc:fqc,source=sources[Number(form.get("source"))];if(!source)return;const inspected=String(form.get("inspected_qty")),failed=String(form.get("failed_qty")||"0"),passed=String(form.get("passed_qty"));const hasFailure=Number(failed)>0;const body:Record<string,unknown>={inspection_type:type,inspected_qty:inspected,passed_qty:passed,failed_qty:failed,responsible_stage:type==="IPQC"?"生产过程检验":"成品检验",results:[{characteristic:"综合判定",result:hasFailure?"FAIL":"PASS"}]};if(type==="IPQC"){if(source.operation_run_report_id)body.operation_run_report_id=source.operation_run_report_id;else body.production_report_id=source.production_report_id;}else body.allocation_id=source.allocation_id;if(hasFailure)body.defects=[{result_line_no:1,defect_type:String(form.get("defect_type")||"生产品质不良"),severity:"MAJOR",quantity:failed,description:String(form.get("reason")||"检验不良") }];await write({path:"/api/quality-inspections",body:JSON.stringify(body),key:crypto.randomUUID(),label:`创建 ${type}`});}
  async function disposition(row:Inspection,code:"RELEASE"|"REWORK"|"SCRAP"){await write({path:`/api/quality-inspections/${row.id}/dispositions`,body:JSON.stringify({expected_version:row.version,disposition_code:code,release_qty:code==="RELEASE"?row.passed_qty:undefined,reason:code==="RELEASE"?"经理确认合格数量放行":`${code} 保持 HOLD`}),key:crypto.randomUUID(),label:`${code} 处置`});}
  async function close(row:Inspection){await write({path:`/api/quality-inspections/${row.id}/close`,body:JSON.stringify({expected_version:row.version,reason:"品质确认处置完成并关闭"}),key:crypto.randomUUID(),label:"关闭检验"});}
  async function reopen(row:Inspection){await write({path:`/api/quality-inspections/${row.id}/reopen`,body:JSON.stringify({expected_version:row.version,reason:"经理受控重开检验"}),key:crypto.randomUUID(),label:"重开检验"});}
  if(loading)return <main className="sourcing-shell"><div className="sourcing-state">正在读取生产品质状态…</div></main>;
  if(forbidden)return <main className="sourcing-shell"><div className="sourcing-state sourcing-error">403：当前账号无权读取生产品质。</div></main>;
  const form=(type:"IPQC"|"FQC",sources:Source[])=><section className="sourcing-panel"><h2>{type} 创建{type==="IPQC"?"（NORMAL / REWORK 稳定来源）":"（服务端从稳定分配派生 Inventory Lot）"}</h2>{sources.length&&can(session,"quality.inspect")?<form className="sourcing-form" onSubmit={e=>inspect(e,type)}><label>稳定来源<select name="source">{sources.map((s,index)=><option value={index} key={s.allocation_id??s.operation_run_report_id??s.production_report_id}>{s.batch_code?`${s.batch_code} · ${s.lot_code?`${s.lot_code} · ${s.lot_status} · `:""}`:"ORDER · "}{s.source_kind==="OPERATION_RUN_REPORT"?`${s.run_kind??"NORMAL"}${s.run_kind==="REWORK"?` · NCR #${s.nonconformance_id} · Rework Request #${s.rework_request_id}`:""} · ${s.work_order_code} · Snapshot Operation #${s.snapshot_operation_id} · ${s.operation_code} ${s.operation_name} · Work Center ${s.work_center_code} · 门禁 ${s.quality_gate_mode} · `:s.source_kind==="LEGACY_PRODUCTION_REPORT"?"历史 Work Order Report · ":""}{s.source_code} · {s.material_code} · good {s.source_qty} · 待检 {s.remaining_qty} {s.unit_code}</option>)}</select></label><label>检验数量<input name="inspected_qty" required defaultValue={sources[0].remaining_qty}/></label><label>合格数量<input name="passed_qty" required defaultValue={sources[0].remaining_qty}/></label><label>不良数量<input name="failed_qty" required defaultValue="0"/></label><label>不良类型（有不良时）<input name="defect_type"/></label><label>原因<textarea name="reason"/></label><button>显式创建 {type}</button></form>:<div className="sourcing-state">{can(session,"quality.inspect")?"没有可检验来源。":"当前账号只有读取权限。"}</div>}</section>;
  return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/">← 经营工作台</Link><h1>生产 Batch 过程与成品品质</h1><p>Inspection/Result/Defect 沿 Run Report 稳定外键返回同一 Manufacturing Batch；显式创建 IPQC，只有 CLOSED/RELEASED 的稳定事实进入下游。成品 Manufacturing Batch 已绑定 Inventory Lot；原材料和供应商批次仍未启用。</p><nav><Link href="/production/batches">Batch genealogy</Link> · <Link href="/quality/nonconformances">IPQC NCR</Link> · <Link href="/quality/rework-requests">返工申请</Link></nav></div></header>{form("IPQC",ipqc)}{form("FQC",fqc)}
    <section className="sourcing-panel"><h2>检验、处置与关闭</h2>{rows.length?rows.map(row=><article className="sourcing-card" key={row.id}><div><b>{row.batch_code??"ORDER"}{row.lot_code?` / ${row.lot_code} / ${row.lot_status}`:""} · {row.inspection_code} · {row.inspection_type}</b><span className="sourcing-status">{row.inspection_status}</span></div><small>{row.material_code} {row.material_name} · 检验/合格/不良 {row.inspected_qty}/{row.passed_qty}/{row.failed_qty} · 放行 {row.released_qty} · 创建人 {row.created_by}</small>{row.lifecycle_status==="OPEN"&&row.decision_status==="PENDING"&&can(session,"quality.disposition")?<div><button onClick={()=>void disposition(row,"RELEASE")}>RELEASE</button><button onClick={()=>void disposition(row,"REWORK")}>REWORK/HOLD</button><button onClick={()=>void disposition(row,"SCRAP")}>SCRAP/HOLD</button></div>:null}{row.lifecycle_status==="OPEN"&&row.decision_status!=="PENDING"&&can(session,"quality.close")?<button onClick={()=>void close(row)}>关闭检验</button>:null}{row.lifecycle_status==="CLOSED"&&can(session,"quality.reopen")?<button onClick={()=>void reopen(row)}>经理重开</button>:null}</article>):<div className="sourcing-state">尚无 IPQC/FQC 记录。</div>}</section>
    {pending?<div className="sourcing-state"><button onClick={()=>void write(pending)}>使用原幂等键重试：{pending.label}</button></div>:null}{error?<div className="sourcing-state sourcing-error">{error}</div>:null}</main>;
}
