import { createHash, randomUUID } from "node:crypto";
import type { Pool } from "pg";
import type { IdentityActor } from "../identity-selfhost/types.ts";
import { QualityError, mapQualityError } from "./errors.ts";
import { id } from "./rules.ts";
import { QualityRepository } from "./repository.ts";
import { QUALITY_BOUNDARY, QualityService } from "./service.ts";

type Dependencies = Readonly<{ pool: Pool; actor: IdentityActor; requestId: string; requireCsrf: () => void }>;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const allowed = (actor: IdentityActor, permission: string) => actor.permissions.includes("*") || actor.permissions.includes(permission);
const requirePermission = (actor: IdentityActor, permission: string) => { if (!allowed(actor, permission)) throw new QualityError("PERMISSION_DENIED", "没有权限执行此操作", 403); };
const response = (body: unknown, status: number, requestId: string, replayed = false) => { const headers = new Headers({ "Cache-Control": "no-store", "X-Request-ID": requestId }); if (replayed) headers.set("Idempotency-Replayed", "true"); return Response.json(body, { status, headers }); };
const stable = (value: unknown): unknown => Array.isArray(value) ? value.map(stable) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, child]) => [key, stable(child)])) : value;
const pageValue = (value: string | null, field: string, fallback: number, maximum: number) => { if (!value) return fallback; const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 1 || parsed > maximum) throw new QualityError("REQUEST_VALIDATION_FAILED", `${field} 必须是正整数`); return parsed; };
async function readBody(request: Request) { const raw = await request.text(); if (!raw || Buffer.byteLength(raw) > 256 * 1024) throw new QualityError("REQUEST_VALIDATION_FAILED", "请求正文为空或超过 256 KiB"); let value: unknown; try { value = JSON.parse(raw); } catch { throw new QualityError("REQUEST_VALIDATION_FAILED", "请求正文不是有效 JSON"); } if (!value || typeof value !== "object" || Array.isArray(value)) throw new QualityError("REQUEST_VALIDATION_FAILED", "请求正文必须是对象"); const forbidden = ["username", "role", "permissions", "created_by", "createdBy", "request_id", "inspection_code", "defect_code", "lifecycle_status", "decision_status", "released_qty", "material_id", "unit_id", "operation_id", "ref_type", "ref_id"].find((key) => key in (value as Record<string, unknown>)); if (forbidden) throw new QualityError("REQUEST_VALIDATION_FAILED", `请求正文不能指定服务端字段：${forbidden}`); return { value: value as Record<string, unknown>, digest: createHash("sha256").update(JSON.stringify(stable(value))).digest("hex") }; }
function mutationMeta(request: Request, dependencies: Dependencies, route: string, action: string, requestDigest: string) { const key = request.headers.get("Idempotency-Key") || ""; if (key.length < 8 || key.length > 200) throw new QualityError("IDEMPOTENCY_KEY_REQUIRED", "写操作必须提供有效 Idempotency-Key"); return { actor: dependencies.actor, requestId: dependencies.requestId, operationId: randomUUID(), keyDigest: createHash("sha256").update(`${dependencies.actor.username}:${request.method}:${route}:${key}`).digest("hex"), requestDigest, method: request.method, route, action }; }

export async function handleQualityApi(request: Request, dependencies: Dependencies): Promise<Response | null> {
  const url = new URL(request.url); const path = url.pathname; const inspection = path.match(/^\/api\/quality-inspections\/([1-9]\d*)$/); const results = path.match(/^\/api\/quality-inspections\/([1-9]\d*)\/results$/); const defects = path.match(/^\/api\/quality-inspections\/([1-9]\d*)\/defects$/); const disposition = path.match(/^\/api\/quality-inspections\/([1-9]\d*)\/dispositions$/); const close = path.match(/^\/api\/quality-inspections\/([1-9]\d*)\/close$/); const reopen = path.match(/^\/api\/quality-inspections\/([1-9]\d*)\/reopen$/); const fixed = ["/api/quality-inspections", "/api/quality-defects", "/api/quality/source-options", "/api/quality/eligibility"];
  if (!fixed.includes(path) && !inspection && !results && !defects && !disposition && !close && !reopen) return null;
  const repository = new QualityRepository(dependencies.pool); const service = new QualityService(repository); let action = "QUALITY_REQUEST";
  try {
    if (request.method === "GET") { requirePermission(dependencies.actor, "quality.read"); if (inspection) return response({ data: await service.get(dependencies.actor, Number(inspection[1])), boundary: QUALITY_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId); if (results) { const found = await service.resultLines(dependencies.actor, Number(results[1])); return response({ rows: found.rows, data: found.rows, boundary: QUALITY_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId); } if (defects) { await service.resultLines(dependencies.actor, Number(defects[1])); const found = await service.listDefects(dependencies.actor, 100, 0, Number(defects[1])); return response({ rows: found.rows, data: found.rows, boundary: QUALITY_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId); } if (path === "/api/quality/source-options") { const result = await service.sourceOptions(dependencies.actor, url.searchParams.get("inspection_type") || "", pageValue(url.searchParams.get("limit"), "limit", 100, 100)); return response({ rows: result.rows, data: result.rows, boundary: QUALITY_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId); } if (path === "/api/quality/eligibility") return response({ data: await service.eligibility(dependencies.actor, id(url.searchParams.get("sales_order_line_id"), "sales_order_line_id")), boundary: QUALITY_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId); const page = pageValue(url.searchParams.get("page"), "page", 1, 1_000_000); const size = pageValue(url.searchParams.get("page_size"), "page_size", 50, 100); const offset = (page - 1) * size; const result = path === "/api/quality-defects" ? await service.listDefects(dependencies.actor, size, offset, url.searchParams.get("inspection_id") ? id(url.searchParams.get("inspection_id"), "inspection_id") : undefined) : await service.list(dependencies.actor, size, offset, url.searchParams.get("inspection_type") || undefined, url.searchParams.get("lifecycle_status") || undefined); return response({ rows: result.rows, data: result.rows, pagination: { page, page_size: size }, boundary: QUALITY_BOUNDARY, request_id: dependencies.requestId }, 200, dependencies.requestId); }
    if (request.method !== "POST") throw new QualityError("METHOD_NOT_ALLOWED", "接口不支持该请求方法", 405); dependencies.requireCsrf(); const parsed = await readBody(request); let result;
    if (path === "/api/quality-inspections") { action = "QUALITY_INSPECTION_CREATED"; requirePermission(dependencies.actor, "quality.inspect"); result = await service.create(mutationMeta(request, dependencies, path, action, parsed.digest), parsed.value); }
    else if (defects) { action = "QUALITY_DEFECT_ADDED"; requirePermission(dependencies.actor, "quality.defect"); result = await service.addDefect(Number(defects[1]), mutationMeta(request, dependencies, path, action, parsed.digest), parsed.value); }
    else if (disposition) { action = "QUALITY_INSPECTION_DISPOSITIONED"; requirePermission(dependencies.actor, "quality.disposition"); result = await service.disposition(Number(disposition[1]), mutationMeta(request, dependencies, path, action, parsed.digest), parsed.value); }
    else if (close) { action = "QUALITY_INSPECTION_CLOSED"; requirePermission(dependencies.actor, "quality.close"); result = await service.close(Number(close[1]), mutationMeta(request, dependencies, path, action, parsed.digest), parsed.value); }
    else if (reopen) { action = "QUALITY_INSPECTION_REOPENED"; requirePermission(dependencies.actor, "quality.reopen"); result = await service.reopen(Number(reopen[1]), mutationMeta(request, dependencies, path, action, parsed.digest), parsed.value); }
    else throw new QualityError("NOT_FOUND", "接口不存在", 404);
    return response(result.body, result.status, dependencies.requestId, result.replayed);
  } catch (error) { const known = mapQualityError(error); if (UUID.test(dependencies.requestId)) await repository.failureAudit(dependencies.actor.username, dependencies.requestId, action, known.code); console.error(JSON.stringify({ level: "error", event: "quality_api_failed", request_id: dependencies.requestId, code: known.code })); return response({ error: { code: known.code, message: known.message, request_id: dependencies.requestId }, code: known.code, message: known.message, request_id: dependencies.requestId }, known.status, dependencies.requestId); }
}
