"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};
type Order={id:number;work_order_code:string;status:string;version:number;planned_qty:string;completed_qty:string;finished_material_id:number;finished_balance_version:number;finished_on_hand_qty:string};
type Report={id:number;work_order_id:number;report_code:string;work_order_code:string;good_qty:string;available_good_qty:string;report_version:number;reversed:boolean;structured:boolean;process_stage:string};
type Completion={id:number;work_order_id:number;completion_code:string;work_order_code:string;quantity:string;completion_version:number;reversed:boolean};
const can=(s:Session|null,p:string)=>Boolean(s?.user&&(s.user.permissions.includes("*")||s.user.permissions.includes(p)));

export default function ProductionCompletionsPage(){
  const[session,setSession]=useState<Session|null>(null),[orders,setOrders]=useState<Order[]>([]),[reports,setReports]=useState<Report[]>([]),[completions,setCompletions]=useState<Completion[]>([]),[error,setError]=useState("");
  async function fetchData(){const current=await api<Session>("/api/session");if(!current.authenticated)return{current,orders:[],reports:[],completions:[]};const[work,reported,received]=await Promise.all([api<{data:Order[]}>("/api/work-orders?page_size=100"),api<{data:Report[]}>("/api/production/reports?page_size=100"),api<{data:Completion[]}>("/api/production/completions?page_size=100")]);return{current,orders:work.data,reports:reported.data,completions:received.data};}
  function applyData(value:Awaited<ReturnType<typeof fetchData>>){setSession(value.current);setOrders(value.orders);setReports(value.reports);setCompletions(value.completions);}
  async function load(){applyData(await fetchData());}
  useEffect(()=>{let cancelled=false;void (async()=>{const current=await api<Session>("/api/session");if(!current.authenticated){if(!cancelled){setSession(current);setOrders([]);setReports([]);setCompletions([]);}return;}const[work,reported,received]=await Promise.all([api<{data:Order[]}>("/api/work-orders?page_size=100"),api<{data:Report[]}>("/api/production/reports?page_size=100"),api<{data:Completion[]}>("/api/production/completions?page_size=100")]);if(!cancelled){setSession(current);setOrders(work.data);setReports(reported.data);setCompletions(received.data);}})().catch(e=>{if(!cancelled)setError(e instanceof ErpApiError?e.message:"读取失败");});return()=>{cancelled=true;};},[]);
  async function receive(event:FormEvent<HTMLFormElement>,report:Report){event.preventDefault();if(!session)return;const order=orders.find(o=>o.id===report.work_order_id);if(!order)return;const form=new FormData(event.currentTarget);const value=String(form.get("quantity"));setError("");try{await api("/api/production/completions",{method:"POST",body:JSON.stringify({work_order_id:order.id,expected_version:order.version,expected_balance_version:order.finished_balance_version,reason:"仓库确认生产完工入库",allocations:[{report_id:report.id,quantity:value,expected_report_version:report.report_version}]}),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});await load();}catch(e){setError(e instanceof ErpApiError?e.message:"完工入库失败");}}
  async function reverse(completion:Completion){if(!session)return;const order=orders.find(item=>item.id===completion.work_order_id);if(!order)return;setError("");try{await api(`/api/production/completions/${completion.id}/reverse`,{method:"POST",body:JSON.stringify({expected_completion_version:completion.completion_version,expected_work_order_version:order.version,reason:"生产完工入库全额冲销",expected_balance_versions:[{material_id:order.finished_material_id,expected_balance_version:order.finished_balance_version}]}),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});await load();}catch(e){setError(e instanceof ErpApiError?e.message:"完工入库冲销失败");}}
  return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/">← 经营工作台</Link><h1>生产完工入库</h1><p>warehouse 显式消费报工未入库良品；Completion、Allocation、成品 Ledger/Balance 与工单状态在同一事务提交。</p></div></header>
    <section className="sourcing-panel"><h2>已报工待入库良品</h2>{reports.filter(r=>!r.reversed&&Number(r.available_good_qty)>0).map(report=>{const order=orders.find(o=>o.id===report.work_order_id);return <article className="sourcing-card" key={report.id}><b>{report.report_code} · {report.work_order_code} · {report.structured?"末工序稳定来源":"历史兼容"}</b><small>报工良品 {report.good_qty} · 可入库 {report.available_good_qty} · 工单已入库 {order?.completed_qty??"-"}/{order?.planned_qty??"-"} · {report.process_stage}</small><p>仓库显式 Completion 将复用既有 Report→Completion Allocation，并在同一事务写成品 Ledger/Balance。</p>{order&&can(session,"production.complete")?<form className="sourcing-form" onSubmit={e=>receive(e,report)}><label>本次入库<input name="quantity" required defaultValue={report.available_good_qty}/></label><button>确认完工入库</button></form>:null}</article>})}</section>
    <section className="sourcing-panel"><h2>完工入库记录</h2>{completions.map(c=><article className="sourcing-card" key={c.id}><b>{c.completion_code} · {c.work_order_code}</b><small>{c.reversed?"已冲销":`成品入库 ${c.quantity}`}</small>{!c.reversed&&can(session,"production.complete.reverse")?<button onClick={()=>void reverse(c)}>全额冲销完工入库</button>:null}</article>)}</section>{error?<div className="sourcing-state sourcing-error">{error}</div>:null}</main>;
}
