import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import test from "node:test";
const workspace=await readFile(new URL("../app/procurement/sourcing/sourcing-workspace.tsx",import.meta.url),"utf8"),dialog=await readFile(new URL("../app/procurement/sourcing/rfq-issue-dialog.tsx",import.meta.url),"utf8"),requestBuilder=await readFile(new URL("../app/procurement/sourcing/create-rfq-draft-request.ts",import.meta.url),"utf8"),styles=await readFile(new URL("../app/procurement/sourcing/sourcing.css",import.meta.url),"utf8"),list=await readFile(new URL("../app/procurement/sourcing/page.tsx",import.meta.url),"utf8"),detail=await readFile(new URL("../app/procurement/sourcing/[rfqId]/page.tsx",import.meta.url),"utf8"),dashboard=await readFile(new URL("../app/lib/dashboard-selfhost/service.ts",import.meta.url),"utf8");
test("native sourcing routes expose accepted requests, quote history, server comparisons and manual awards",()=>{assert.match(list,/ProcurementSourcingWorkspace/);assert.match(detail,/ProcurementSourcingDetailWorkspace/);for(const text of ["已接收采购申请","RFQ 列表","报价版本","服务端横向比价","人工定标与撤销","MOQ","含税","含运费","LATE_DELIVERY_ACCEPTED","SOLE_SOURCE"])assert.match(workspace,new RegExp(text));for(const route of ["/api/procurement/rfqs","/issue","/quotes","/revise","/comparisons","/award","/reversal"])assert.match(workspace,new RegExp(route.replaceAll("/","\\/")));assert.match(workspace,/crypto\.randomUUID/);assert.doesNotMatch(workspace,/parseFloat|price_rank\s*=|sort\(.*unit_price/s)});
test("the sourcing UI does not offer downstream purchase-order operations",()=>{assert.doesNotMatch(workspace,/>创建采购订单</);assert.doesNotMatch(workspace,/\/api\/purchase-orders|\/api\/purchase-receipts/)});
test("RFQ draft options and DTO use stable IDs without display-text reverse lookup",()=>{assert.match(workspace,/value=\{String\(row\.id\)\}/);assert.match(workspace,/buildCreateRfqDraftRequest\(requests,suppliers/);assert.doesNotMatch(workspace,/row\.id===Number\(form\.get\("purchase_request_id"\)\)/);assert.match(requestBuilder,/purchase_request_id: purchaseRequestId/);assert.match(requestBuilder,/supplier_ids: supplierIds/);assert.match(requestBuilder,/new Set\(selectedSupplierIds\)/);assert.doesNotMatch(requestBuilder,/request_code|project_code|project_name|supplier_code|supplier_name/);assert.match(styles,/min-width:0/)});
test("dashboard publishes all three sourcing queues and the native entry",()=>{for(const field of ["pending_sourcing_requests","pending_quote_rfqs","pending_award_rfqs","procurement-sourcing"])assert.match(dashboard,new RegExp(field.replace("-","\\-")))});
test("RFQ detail exposes an exact creation credential, bilingual DRAFT semantics, and grouped Mapping lineage",()=>{for(const text of ["RFQ 创建成功凭证","权威来源","创建 actor","精确时间","request_id","Idempotency-Key 摘要","创建前后 Version / CAS","DRAFT / 草稿 / 待发出","历史草稿尚未固定 Mapping","当前资格检查 / 尚未冻结的拟绑定 Mapping","Mapping ID","Mapping Version","supplier_part_number","绑定时状态 / 来源","已绑定版本当前状态","最新 Mapping 版本","当前状态漂移","当前版本漂移"])assert.match(workspace+dialog,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(dialog,/groupMappings/);assert.match(dialog,/trace\.current_qualification/);assert.match(dialog,/trace\.bindings/);assert.match(dialog,/creation_receipt\?\.result === "SUCCESS"/);assert.match(workspace,/detail\.downstream_counts\.quotes/)});
test("issuance is a safe modal confirmation with zero-write exits, synchronous double-submit guard, and stable retry identity",()=>{for(const text of ["发出询价并冻结范围","发出前服务端重新校验 PRQ、Supplier、Mapping、截止日期、CAS","只有发出成功后才允许录入 Supplier 报价","不自动创建 Quote、Award、PO、库存或财务记录","取消","关闭确认窗口"])assert.match(workspace+dialog,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(dialog,/cancelRef\.current\?\.focus/);assert.match(dialog,/event\.key === "Escape"/);assert.match(dialog,/event\.target === event\.currentTarget/);assert.match(workspace,/scopeInFlight\.current/);assert.match(workspace,/createSessionWriteRegistry/);assert.match(workspace,/sessionPost\(/);assert.match(workspace,/\/mapping-bindings/);assert.doesNotMatch(dialog,/fetch\(|sessionPost\(|\/issue/)});
test("traceability and confirmation layouts are bounded at 390px",()=>{assert.match(styles,/overflow-x:hidden/);assert.match(styles,/overflow-wrap:anywhere/);assert.match(styles,/@media\(max-width:600px\)/);assert.match(styles,/\.rfq-dialog\{width:100%;height:100dvh/);assert.match(styles,/grid-template-columns:minmax\(0,1fr\)/);assert.match(styles,/word-break:break-all/)});
