import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=path=>readFile(new URL(path,import.meta.url),"utf8");
test("three native workspaces expose server-backed purchase, receiving and payable actions",async()=>{
  const purchase=await read("../app/procurement/fulfillment/procurement-fulfillment-workspace.tsx"),warehouse=await read("../app/warehouse/receiving/warehouse-receiving-workspace.tsx"),finance=await read("../app/finance/payables/finance-payables-workspace.tsx");
  assert.match(purchase,/pending-awards/);assert.match(purchase,/显式生成采购订单/);assert.match(purchase,/建立到货计划/);assert.match(purchase,/procurement\.award\.convert/);
  assert.match(warehouse,/receiving-queue/);assert.match(warehouse,/确认过账收货/);assert.match(warehouse,/expected_balance_version/);assert.match(warehouse,/expected_line_version/);
  assert.match(finance,/payable-handoff/);assert.match(finance,/核对并显式生成 AP/);assert.match(finance,/purchase_source_entry_id/);assert.doesNotMatch(finance,/name="amount"|total_amount:/);
});
test("Award conversion is a guarded preview dialog and only the explicit final action posts",async()=>{const workspace=await read("../app/procurement/fulfillment/procurement-fulfillment-workspace.tsx"),dialog=await read("../app/procurement/fulfillment/award-po-conversion-dialog.tsx"),preview=await read("../app/lib/procurement-fulfillment-selfhost/award-conversion-preview.ts");
  assert.match(workspace,/onClick=\{\(\) => void openConversion\(row\)\}/);assert.match(workspace,/purchase-order-conversion-preview/);assert.match(workspace,/cache: "no-store"/);assert.match(workspace,/conversionInFlight\.current/);assert.match(workspace,/setConversionSubmitted\(true\); setConversionBusy\(true\)/);assert.match(workspace,/\.\.\.conversionPreview\.confirmation/);assert.match(workspace,/remark: conversionRemark/);assert.match(workspace,/purchase-orders`, \{/);const openConversion=workspace.match(/async function openConversion\(row: Award\)[^]*?(?=\n  function cancelConversion)/)?.[0]||"";assert.doesNotMatch(openConversion,/post\(/);
  for(const text of ["定标转采购订单最终确认","完整业务谱系","Comparison固定Quote输入与获奖来源","Award成功Event","两类Award摘要","四条转换范围","将创建的权威记录","当前PO模型未采集外部参考","PO备注","最终确认生成PO及到货计划","Award、RFQ、Quote、Comparison不会被修改","Receipt","Warehouse Receipt","Inventory Ledger","IQC","AP","Payment","Work Order","其他生产记录","其他财务记录","供应商到货、仓库收货和IQC必须由后续独立任务完成","取消"])assert.match(dialog+preview,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
  assert.match(dialog,/cancelRef\.current\?\.focus/);assert.match(dialog,/event\.key === "Escape"/);assert.match(dialog,/event\.target === event\.currentTarget/);assert.match(dialog,/disabled=\{busy \|\| submitted\}/);assert.match(dialog,/event\.currentTarget\.disabled = true/);assert.doesNotMatch(dialog,/fetch\(|api\(|post\(/);assert.match(preview,/purchase_order_aggregate_count: groups\.size/);assert.match(preview,/delivery_plan_aggregate_count: lines\.length/);assert.match(preview,/delivery_plan_line_count: 0/);
  assert.doesNotMatch(dialog,/slice\(0,\s*2\)/);assert.match(dialog,/BigInt/);assert.match(dialog,/micros \+ 5_000n/);
});
test("native pages exist and the dashboard links distinguish pending and generated AP",async()=>{for(const path of ["../app/procurement/fulfillment/page.tsx","../app/warehouse/receiving/page.tsx","../app/finance/payables/page.tsx"])assert.match(await read(path),/Workspace/);const dashboard=await read("../app/lib/dashboard-selfhost/service.ts");assert.match(dashboard,/已收货待生成应付/);assert.match(dashboard,/已生成采购应付/);assert.match(dashboard,/\/finance\/payables/)});
