import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { handleProductionOperationApi } from "../app/lib/production-operation-selfhost/handler.ts";
import { ProductionOperationService } from "../app/lib/production-operation-selfhost/service.ts";
import { initializeOperationProjections } from "../app/lib/production-operation-selfhost/projections.ts";
import { ProductionRepository } from "../app/lib/production-selfhost/repository.ts";
import { handleQualityApi } from "../app/lib/quality-selfhost/handler.ts";

const databaseUrl=process.env.TEST_PRODUCTION_REWORK_DATABASE_URL;
if(!databaseUrl||!/production_rework_test/i.test(databaseUrl))throw new Error("isolated TEST_PRODUCTION_REWORK_DATABASE_URL containing production_rework_test is required");
const pool=new Pool({connectionString:databaseUrl,max:6,application_name:"production-rework-test"});
const actor=(role,username=`${role}01`)=>({username,display_name:role,role,is_active:true,must_change_password:false,version:1,last_login_at:null,permissions:permissionsForRole(role)});
const sha=value=>createHash("sha256").update(String(value)).digest("hex");
const meta=(action,key=randomUUID())=>({actor:actor("production"),requestId:randomUUID(),operationId:randomUUID(),keyDigest:sha(`${action}:${key}`),requestDigest:sha(`body:${action}:${key}`),method:"POST",route:`/test/${action}`,action});
async function operation(path,{role="production",body,key=randomUUID()}={}){const headers=new Headers({"X-Request-ID":randomUUID(),"X-CSRF-Token":"test-csrf","Idempotency-Key":key,"Content-Type":"application/json"});const response=await handleProductionOperationApi(new Request(`http://local.test${path}`,{method:"POST",headers,body:JSON.stringify(body)}),{pool,actor:actor(role),requestId:headers.get("X-Request-ID"),requireCsrf:()=>assert.equal(headers.get("X-CSRF-Token"),"test-csrf")});assert.ok(response);return{response,payload:await response.json()};}
async function quality(path,{role="quality",body,key=randomUUID()}={}){const headers=new Headers({"X-Request-ID":randomUUID(),"X-CSRF-Token":"test-csrf","Idempotency-Key":key,"Content-Type":"application/json"});const response=await handleQualityApi(new Request(`http://local.test${path}`,{method:"POST",headers,body:JSON.stringify(body)}),{pool,actor:actor(role),requestId:headers.get("X-Request-ID"),requireCsrf:()=>{}});assert.ok(response);return{response,payload:await response.json()};}

async function seed(){
 await pool.query("truncate app_users,units,material_categories,business_code_sequences,idempotency_keys,identity_write_rate_limit_buckets,audit_log restart identity cascade");
 await pool.query(`insert into app_users(username,display_name,role,password_hash,is_active) values ('admin01','管理员','admin','x',true),('manager01','经理','manager','x',true),('quality01','品质','quality','x',true),('production01','生产','production','x',true),('warehouse01','仓库','warehouse','x',true)`);
 const category=(await pool.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values('T30','TASK30',4,'ACTIVE','admin01','admin01',$1) returning id",[randomUUID()])).rows[0],unit=(await pool.query("insert into units(code,name,symbol,unit_type,enabled) values('T30PCS','件','PCS','COUNT',true) returning id")).rows[0],material=(await pool.query(`insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values('CYD-T30-FG','TASK30 成品',$1,'T30PCS',$2,'ACTIVE','MAKE','STOCKED','IPQC','ROHS','MANUAL','admin01','admin01','admin01',$3) returning id`,[category.id,unit.id,randomUUID()])).rows[0];
 const client=await pool.connect();try{await client.query("begin");await client.query("set local session_replication_role=replica");
  await client.query("insert into production_work_centers(id,work_center_code,name_cn,work_center_type,created_by,updated_by,request_id) values(6001,'REFLOW','回流焊','SMT','admin01','admin01',$1)",[randomUUID()]);
  await client.query(`insert into production_work_orders(id,work_order_code,product_id,product_version_id,bom_version_id,finished_material_id,finished_unit_id,planned_qty,status,owner,operation_id,created_by,request_id) values(6001,'WO-T30',1,1,1,$1,$2,10,'IN_PROGRESS','production01',$3,'production01',$4)`,[material.id,unit.id,randomUUID(),randomUUID()]);
  await client.query(`insert into production_work_order_routing_snapshots(id,work_order_id,routing_header_id,routing_version_id,product_version_id,routing_code,routing_version_no,routing_version_code,routing_digest,released_by,request_id) values(6001,6001,1,1,1,'RT-T30',1,'V1',$1,'manager01',$2)`,["a".repeat(64),randomUUID()]);
  await client.query(`insert into production_work_order_routing_snapshot_operations(id,snapshot_id,source_routing_operation_id,sequence_no,operation_code,operation_name,work_center_id,work_center_code,work_center_name,setup_minutes,run_minutes_per_unit,description,quality_gate_mode) values(6001,6001,1,30,'REFLOW','回流焊',6001,'REFLOW','回流焊',0,1,'IPQC','IPQC')`);
  await client.query(`insert into production_material_requirements(id,work_order_id,snapshot_line_id,material_id,unit_id,required_qty,net_issued_qty,version) values(6001,6001,1,$1,$2,10,10,1)`,[material.id,unit.id]);
  await client.query(`insert into production_operation_runs(id,run_code,run_kind,work_order_id,snapshot_operation_id,work_center_id,work_center_code,work_center_name,assigned_operator,dispatched_qty,processed_qty,good_qty,scrap_qty,status,source_digest,version,operation_id,created_by,request_id,started_by,started_at) values(6001,'RUN-NORMAL','NORMAL',6001,6001,6001,'REFLOW','回流焊','production01',10,10,10,0,'COMPLETED',$1,3,$2,'production01',$3,'production01',now())`,["b".repeat(64),randomUUID(),randomUUID()]);
  await client.query(`insert into production_operation_run_reports(id,report_code,run_id,snapshot_operation_id,processed_qty,good_qty,scrap_qty,operation_id,reported_by,request_id) values(6001,'ORR-NORMAL',6001,6001,10,10,0,$1,'production01',$2)`,[randomUUID(),randomUUID()]);
  await client.query(`insert into production_operation_run_events(run_id,report_id,event_type,from_status,to_status,processed_qty,good_qty,scrap_qty,actor,request_id) values(6001,null,'DISPATCHED',null,'READY',0,0,0,'production01',$1),(6001,null,'STARTED','READY','IN_PROGRESS',0,0,0,'production01',$2),(6001,6001,'REPORTED','IN_PROGRESS','COMPLETED',10,10,0,'production01',$3)`,[randomUUID(),randomUUID(),randomUUID()]);
  await client.query(`insert into quality_inspections(id,inspection_code,inspection_type,production_operation_run_report_id,material_id,unit_id,inspected_qty,passed_qty,failed_qty,lifecycle_status,decision_status,released_qty,version,operation_id,created_by,request_id) values(6001,'QI-ORIGINAL','IPQC',6001,$1,$2,10,8,2,'CLOSED','RELEASED',8,3,$3,'quality01',$4)`,[material.id,unit.id,randomUUID(),randomUUID()]);
  await client.query("insert into quality_inspection_results(id,inspection_id,line_no,characteristic,result) values(6001,6001,1,'回流焊','FAIL')");
  await client.query("insert into quality_defects(id,defect_code,inspection_id,result_line_id,defect_type,severity,quantity,description,operation_id,created_by,request_id) values(6001,'QD-ORIGINAL',6001,6001,'焊接不良','MAJOR',2,'返工',$1,'quality01',$2)",[randomUUID(),randomUUID()]);
  await client.query(`insert into production_nonconformances(id,ncr_code,inspection_id,production_operation_run_report_id,work_order_id,snapshot_operation_id,work_center_id,work_center_code,work_center_name,material_id,unit_id,inspected_qty,passed_qty,failed_qty,active_rework_qty,unresolved_qty,status,version,operation_id,created_by,request_id) values(6001,'NCR-T30',6001,6001,6001,6001,6001,'REFLOW','回流焊',$1,$2,10,8,2,2,0,'REWORK_ACCEPTED',3,$3,'quality01',$4)`,[material.id,unit.id,randomUUID(),randomUUID()]);
  const canonical="c".repeat(64);await client.query(`insert into production_rework_requests(id,request_code,nonconformance_id,revision_no,target_snapshot_operation_id,target_sequence_no,target_operation_code,target_operation_name,target_work_center_id,target_work_center_code,target_work_center_name,quantity,reason,status,version,canonical_digest,operation_id,created_by,request_id,submitted_by,submitted_request_id,submitted_at,decided_by,decided_request_id,decided_at) values(6001,'RWR-T30',6001,2,6001,30,'REFLOW','回流焊',6001,'REFLOW','回流焊',2,'返工','ACCEPTED',3,$1,$2,'quality01',$3,'quality01',$4,now(),'production01',$5,now())`,[canonical,randomUUID(),randomUUID(),randomUUID(),randomUUID()]);
  await client.query(`insert into production_rework_request_versions(id,rework_request_id,version_no,nonconformance_id,target_snapshot_operation_id,target_sequence_no,target_operation_code,target_operation_name,target_work_center_id,target_work_center_code,target_work_center_name,quantity,reason,canonical_digest,submitted_by,request_id) values(6001,6001,2,6001,6001,30,'REFLOW','回流焊',6001,'REFLOW','回流焊',2,'返工',$1,'quality01',$2)`,[canonical,randomUUID()]);
  await client.query(`insert into production_nonconformance_allocations(id,nonconformance_id,allocation_type,rework_request_id,quantity,status,operation_id,created_by,request_id) values(6001,6001,'REWORK',6001,2,'ACTIVE',$1,'quality01',$2)`,[randomUUID(),randomUUID()]);
  await client.query(`insert into production_rework_execution_projections(id,rework_request_id,nonconformance_id,accepted_rework_qty,rework_waiting_dispatch_qty,unresolved_rework_qty,status) values(6001,6001,6001,2,2,2,'ACCEPTED')`);
  await client.query("select setval(pg_get_serial_sequence('production_operation_runs','id'),7000,true),setval(pg_get_serial_sequence('production_operation_run_reports','id'),7000,true),setval(pg_get_serial_sequence('quality_inspections','id'),7000,true),setval(pg_get_serial_sequence('production_rework_run_allocations','id'),7000,true),setval(pg_get_serial_sequence('production_rework_execution_events','id'),7000,true)");
  await client.query("set local session_replication_role=origin");await client.query("select set_config('cyd.production_operation_service_write','allowed',true),set_config('cyd.rework_execution_service_write','allowed',true)");await initializeOperationProjections(client,6001);await client.query("commit");
 }catch(error){await client.query("rollback");throw error;}finally{client.release();}
}

test.beforeEach(()=>seed());test.after(()=>pool.end());

async function dispatch(key="dispatch-key"){return operation("/api/production/rework-requests/6001/dispatch",{key,body:{expected_execution_version:1,quantity:"2",assigned_operator:"production01",planned_start:"",planned_end:""}});}

test("REWORK good remains held until a separate CLOSED RELEASED IPQC then resolves execution and NCR",async()=>{const created=await dispatch(),replay=await dispatch();assert.equal(created.response.status,201,JSON.stringify(created.payload));assert.equal(replay.response.headers.get("Idempotency-Replayed"),"true");const run=created.payload.data;assert.equal(run.run_kind,"REWORK");assert.equal((await operation(`/api/production/operation-runs/${run.id}/start`,{body:{expected_version:1}})).response.status,200);const reported=await operation(`/api/production/operation-runs/${run.id}/reports`,{body:{expected_version:2,processed_qty:"2",good_qty:"2",scrap_qty:"0",remark:"返工完成"}});assert.equal(reported.response.status,201,JSON.stringify(reported.payload));let state=(await pool.query("select * from production_rework_execution_projections where rework_request_id=6001")).rows[0];assert.deepEqual([state.status,state.rework_reported_good_qty,state.rework_pending_reinspection_qty,state.rework_released_qty],["WAITING_REINSPECTION","2.000000","2.000000","0.000000"]);assert.equal((await pool.query("select final_output_available_qty::text value from production_operation_wip_projections where snapshot_operation_id=6001")).rows[0].value,"8.000000");const inspection=await quality("/api/quality-inspections",{body:{inspection_type:"IPQC",operation_run_report_id:reported.payload.data.report.id,inspected_qty:"2",passed_qty:"2",failed_qty:"0",responsible_stage:"返工复检",results:[{characteristic:"返工复检",result:"PASS"}]}});assert.equal(inspection.response.status,201,JSON.stringify(inspection.payload));const disposition=await quality(`/api/quality-inspections/${inspection.payload.inspection_id}/dispositions`,{role:"manager",body:{expected_version:1,disposition_code:"RELEASE",release_qty:"2",reason:"异人放行"}});assert.equal(disposition.response.status,200);const closed=await quality(`/api/quality-inspections/${inspection.payload.inspection_id}/close`,{role:"manager",body:{expected_version:2,reason:"复检完成"}});assert.equal(closed.response.status,200,JSON.stringify(closed.payload));state=(await pool.query("select * from production_rework_execution_projections where rework_request_id=6001")).rows[0];assert.deepEqual([state.status,state.rework_released_qty,state.rework_completed_qty,state.unresolved_rework_qty],["COMPLETED","2.000000","2.000000","0.000000"]);assert.equal((await pool.query("select status from production_nonconformances where id=6001")).rows[0].status,"RESOLVED");assert.equal((await pool.query("select final_output_available_qty::text value from production_operation_wip_projections where snapshot_operation_id=6001")).rows[0].value,"10.000000");assert.equal((await pool.query("select failed_qty::text value from quality_inspections where id=6001")).rows[0].value,"2.000000");const blocked=await operation(`/api/production/operation-runs/${run.id}/reverse`,{body:{expected_version:3,reason:"已有复检禁止冲销"}});assert.equal(blocked.response.status,409);});

test("concurrent over-dispatch, unauthorized dispatch and CAS fail closed",async()=>{const denied=await operation("/api/production/rework-requests/6001/dispatch",{role:"warehouse",body:{expected_execution_version:1,quantity:"2",assigned_operator:"production01"}});assert.equal(denied.response.status,403);const concurrent=await Promise.all([dispatch("parallel-a"),dispatch("parallel-b")]);assert.deepEqual(concurrent.map(item=>item.response.status).sort(),[201,409]);const active=(await pool.query("select coalesce(sum(quantity),0)::text qty,count(*)::int count from production_rework_run_allocations where status='ACTIVE'")).rows[0];assert.deepEqual(active,{qty:"2.000000",count:1});const conflict=await operation("/api/production/rework-requests/6001/dispatch",{body:{expected_execution_version:1,quantity:"1",assigned_operator:"production01"}});assert.equal(conflict.response.status,409);await assert.rejects(pool.query("update production_rework_execution_events set quantity=1"),/service|immutable/i);await assert.rejects(pool.query("insert into production_operation_runs(run_code,run_kind,work_order_id,snapshot_operation_id,work_center_id,work_center_code,work_center_name,assigned_operator,dispatched_qty,source_digest,operation_id,created_by,request_id) values('FORGED','REWORK',6001,6001,6001,'REFLOW','回流焊','production01',1,$1,$2,'production01',$3)",["d".repeat(64),randomUUID(),randomUUID()]),/check|service/i);});

test("unstarted cancellation and report reversal without quality restore dispatchable quantity",async()=>{let created=await dispatch("cancel-source"),run=created.payload.data;const cancelled=await operation(`/api/production/operation-runs/${run.id}/cancel`,{body:{expected_version:1,reason:"未开工取消"}});assert.equal(cancelled.response.status,200);let state=(await pool.query("select status,rework_waiting_dispatch_qty::text waiting from production_rework_execution_projections where rework_request_id=6001")).rows[0];assert.deepEqual(state,{status:"ACCEPTED",waiting:"2.000000"});created=await operation("/api/production/rework-requests/6001/dispatch",{body:{expected_execution_version:Number((await pool.query("select version from production_rework_execution_projections where rework_request_id=6001")).rows[0].version),quantity:"2",assigned_operator:"production01"}});run=created.payload.data;await operation(`/api/production/operation-runs/${run.id}/start`,{body:{expected_version:1}});await operation(`/api/production/operation-runs/${run.id}/reports`,{body:{expected_version:2,processed_qty:"2",good_qty:"2",scrap_qty:"0"}});const reversed=await operation(`/api/production/operation-runs/${run.id}/reverse`,{body:{expected_version:3,reason:"无下游全额冲销"}});assert.equal(reversed.response.status,201,JSON.stringify(reversed.payload));state=(await pool.query("select status,rework_waiting_dispatch_qty::text waiting,rework_reported_good_qty::text good from production_rework_execution_projections where rework_request_id=6001")).rows[0];assert.deepEqual(state,{status:"ACCEPTED",waiting:"2.000000",good:"0.000000"});});

test("fault injection rolls back run, allocation, projection, event, audit and idempotency",async()=>{const before=(await pool.query("select version from production_rework_execution_projections where rework_request_id=6001")).rows[0].version,service=new ProductionOperationService(new ProductionRepository(pool),checkpoint=>{if(checkpoint==="after_rework_dispatch_facts")throw new Error("forced rollback");});await assert.rejects(service.dispatchRework(6001,meta("FAULT_REWORK"),{expected_execution_version:before,quantity:"2",assigned_operator:"production01"}),error=>error.code==="INTERNAL_ERROR");const counts=(await pool.query("select (select count(*)::int from production_operation_runs where run_kind='REWORK') runs,(select count(*)::int from production_rework_run_allocations) allocations,(select count(*)::int from production_rework_execution_events) events,(select count(*)::int from audit_log) audits,(select count(*)::int from idempotency_keys) keys")).rows[0];assert.deepEqual(counts,{runs:0,allocations:0,events:0,audits:0,keys:0});assert.equal((await pool.query("select version from production_rework_execution_projections where rework_request_id=6001")).rows[0].version,before);});
