import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { handleProductionNonconformanceApi } from "../app/lib/production-nonconformance-selfhost/handler.ts";
import { ProductionNonconformanceService } from "../app/lib/production-nonconformance-selfhost/service.ts";
import { handleQualityApi } from "../app/lib/quality-selfhost/handler.ts";
import { QualityRepository } from "../app/lib/quality-selfhost/repository.ts";

const databaseUrl=process.env.TEST_PRODUCTION_NONCONFORMANCE_DATABASE_URL;
if(!databaseUrl||!/production_nonconformance_test/i.test(databaseUrl))throw new Error("isolated TEST_PRODUCTION_NONCONFORMANCE_DATABASE_URL containing production_nonconformance_test is required");
const pool=new Pool({connectionString:databaseUrl,max:8,application_name:"production-nonconformance-test"});
const actor=(role,username=`${role}01`)=>({username,display_name:role,role,is_active:true,must_change_password:false,version:1,last_login_at:null,permissions:permissionsForRole(role)});
const sha=value=>createHash("sha256").update(String(value)).digest("hex");
const meta=(role,action,key=randomUUID(),username)=>({actor:actor(role,username),requestId:randomUUID(),operationId:randomUUID(),keyDigest:sha(`${role}:${action}:${key}`),requestDigest:sha(`body:${action}:${key}`),method:"POST",route:`/test/${action}`,action});
async function request(path,{method="POST",role="quality",username,body,key=randomUUID()}={}){const headers=new Headers({"X-Request-ID":randomUUID(),"X-CSRF-Token":"test-csrf"});if(body!==undefined)headers.set("Content-Type","application/json");if(key)headers.set("Idempotency-Key",key);const response=await handleProductionNonconformanceApi(new Request(`http://local.test${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),{pool,actor:actor(role,username),requestId:headers.get("X-Request-ID"),requireCsrf:()=>{assert.equal(headers.get("X-CSRF-Token"),"test-csrf");}});assert.ok(response);return{response,payload:await response.json()};}
async function qualityRequest(path,{role="manager",body,key=randomUUID()}={}){const headers=new Headers({"X-Request-ID":randomUUID(),"X-CSRF-Token":"test-csrf","Idempotency-Key":key,"Content-Type":"application/json"});const response=await handleQualityApi(new Request(`http://local.test${path}`,{method:"POST",headers,body:JSON.stringify(body)}),{pool,actor:actor(role),requestId:headers.get("X-Request-ID"),requireCsrf:()=>{}});assert.ok(response);return{response,payload:await response.json()};}

async function seed({failed="2",withFail=true,withDefect=true}={}){
 await pool.query("truncate app_users,units,material_categories,business_code_sequences,idempotency_keys,identity_write_rate_limit_buckets,audit_log restart identity cascade");
 await pool.query(`insert into app_users(username,display_name,role,password_hash,is_active) values ('admin01','管理员','admin','x',true),('manager01','经理','manager','x',true),('quality01','品质一','quality','x',true),('quality02','品质二','quality','x',true),('production01','生产一','production','x',true),('production02','生产二','production','x',true),('engineering01','工程','engineering','x',true),('warehouse01','仓库','warehouse','x',true),('sales01','销售','sales','x',true),('finance01','财务','finance','x',true),('purchase01','采购','purchase','x',true),('planning01','计划','planning','x',true),('operations01','运营','operations','x',true)`);
 const category=(await pool.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values('T29','TASK29',4,'ACTIVE','admin01','admin01',$1) returning id",[randomUUID()])).rows[0];
 const unit=(await pool.query("insert into units(code,name,symbol,unit_type,enabled) values('T29PCS','件','PCS','COUNT',true) returning id")).rows[0];
 const material=(await pool.query(`insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values('CYD-T29-FG','TASK29 成品',$1,'T29PCS',$2,'ACTIVE','MAKE','STOCKED','IPQC','ROHS','MANUAL','admin01','admin01','admin01',$3) returning id`,[category.id,unit.id,randomUUID()])).rows[0];
 const client=await pool.connect();try{await client.query("begin");await client.query("set local session_replication_role=replica");
  await client.query(`insert into production_work_centers(id,work_center_code,name_cn,work_center_type,created_by,updated_by,request_id) values(2901,'REFLOW','回流焊','SMT','admin01','admin01',$1),(2902,'SMT-MOUNT','贴片','SMT','admin01','admin01',$2),(2999,'OTHER','其他','SMT','admin01','admin01',$3)`,[randomUUID(),randomUUID(),randomUUID()]);
  await client.query(`insert into production_work_orders(id,work_order_code,product_id,product_version_id,bom_version_id,finished_material_id,finished_unit_id,planned_qty,status,owner,operation_id,created_by,request_id) values(2901,'WO-T29',1,1,1,$1,$2,10,'IN_PROGRESS','production01',$3,'production01',$4),(2999,'WO-OTHER',2,2,2,$1,$2,10,'IN_PROGRESS','production02',$5,'production02',$6)`,[material.id,unit.id,randomUUID(),randomUUID(),randomUUID(),randomUUID()]);
  await client.query(`insert into production_work_order_routing_snapshots(id,work_order_id,routing_header_id,routing_version_id,product_version_id,routing_code,routing_version_no,routing_version_code,routing_digest,released_by,request_id) values(2901,2901,1,1,1,'RT-T29',1,'V1',$1,'manager01',$2),(2999,2999,2,2,2,'RT-OTHER',1,'V1',$3,'manager01',$4)`,["a".repeat(64),randomUUID(),"b".repeat(64),randomUUID()]);
  await client.query(`insert into production_work_order_routing_snapshot_operations(id,snapshot_id,source_routing_operation_id,sequence_no,operation_code,operation_name,work_center_id,work_center_code,work_center_name,setup_minutes,run_minutes_per_unit,description,quality_gate_mode) values(2901,2901,1,20,'MOUNT','贴片',2902,'SMT-MOUNT','贴片',0,1,'返工前序','NONE'),(2902,2901,2,30,'REFLOW','回流焊',2901,'REFLOW','回流焊',0,1,'IPQC 来源','IPQC'),(2903,2901,4,40,'AOI','AOI',2902,'SMT-MOUNT','贴片',0,1,'后序目标','NONE'),(2999,2999,3,10,'OTHER','其他',2999,'OTHER','其他',0,1,'跨工单','NONE')`);
  await client.query(`insert into production_operation_runs(id,run_code,work_order_id,snapshot_operation_id,work_center_id,work_center_code,work_center_name,assigned_operator,dispatched_qty,processed_qty,good_qty,scrap_qty,status,source_digest,version,operation_id,created_by,request_id,started_by,started_at) values(2901,'RUN-T29',2901,2902,2901,'REFLOW','回流焊','production01',10,10,10,0,'COMPLETED',$1,3,$2,'production01',$3,'production01',now())`,["c".repeat(64),randomUUID(),randomUUID()]);
  await client.query(`insert into production_operation_run_reports(id,report_code,run_id,snapshot_operation_id,processed_qty,good_qty,scrap_qty,operation_id,reported_by,request_id) values(2901,'ORR-T29',2901,2902,10,10,0,$1,'production01',$2)`,[randomUUID(),randomUUID()]);
  const passed=String(10-Number(failed));await client.query(`insert into quality_inspections(id,inspection_code,inspection_type,production_operation_run_report_id,material_id,unit_id,inspected_qty,passed_qty,failed_qty,lifecycle_status,decision_status,released_qty,version,operation_id,created_by,request_id) values(2901,'QI-T29','IPQC',2901,$1,$2,10,$3,$4,'CLOSED','RELEASED',$3,3,$5,'quality01',$6)`,[material.id,unit.id,passed,failed,randomUUID(),randomUUID()]);
  if(withFail)await client.query("insert into quality_inspection_results(id,inspection_id,line_no,characteristic,result) values(2901,2901,1,'回流焊检验','FAIL')");
  if(withDefect)await client.query("insert into quality_defects(id,defect_code,inspection_id,result_line_id,defect_type,severity,quantity,description,operation_id,created_by,request_id) values(2901,'QD-T29',2901,$1,'焊接不良','MAJOR',$2,'返工',$3,'quality01',$4)",[withFail?2901:null,failed==="0"?"1":failed,randomUUID(),randomUUID()]);
  await client.query("select setval(pg_get_serial_sequence('production_work_centers','id'),3000,true),setval(pg_get_serial_sequence('production_work_orders','id'),3000,true),setval(pg_get_serial_sequence('production_work_order_routing_snapshots','id'),3000,true),setval(pg_get_serial_sequence('production_work_order_routing_snapshot_operations','id'),3000,true),setval(pg_get_serial_sequence('production_operation_runs','id'),3000,true),setval(pg_get_serial_sequence('production_operation_run_reports','id'),3000,true),setval(pg_get_serial_sequence('quality_inspections','id'),3000,true),setval(pg_get_serial_sequence('quality_inspection_results','id'),3000,true),setval(pg_get_serial_sequence('quality_defects','id'),3000,true)");await client.query("commit");
 }catch(error){await client.query("rollback");throw error;}finally{client.release();}
 return{inspectionId:2901,sourceOperationId:2902,targetOperationId:2901,crossOperationId:2999};
}

test.beforeEach(()=>seed());test.after(()=>pool.end());

test("v1 return and immutable v2 acceptance conserve failed quantity without execution facts",async()=>{
 const created=await request("/api/quality/inspections/2901/nonconformance",{body:{expected_version:3},key:"create-ncr-key"}),replay=await request("/api/quality/inspections/2901/nonconformance",{body:{expected_version:3},key:"create-ncr-key"});assert.equal(created.response.status,201,JSON.stringify(created.payload));assert.equal(replay.response.headers.get("Idempotency-Replayed"),"true");const ncr=created.payload.data;assert.deepEqual([ncr.failed_qty,ncr.active_rework_qty,ncr.unresolved_qty,ncr.status],["2.000000","0.000000","2.000000","OPEN"]);
 const forged=await request(`/api/quality/nonconformances/${ncr.id}/rework-requests`,{body:{target_snapshot_operation_id:2902,quantity:"2",reason:"返工",work_order_id:2901}});assert.equal(forged.response.status,400);
 const v1=await request(`/api/quality/nonconformances/${ncr.id}/rework-requests`,{body:{target_snapshot_operation_id:2902,quantity:"2",reason:"第一次返工"}});assert.equal(v1.response.status,201);const submitted1=await request(`/api/quality/rework-requests/${v1.payload.data.id}/submit`,{body:{expected_version:1}});assert.equal(submitted1.response.status,200,JSON.stringify(submitted1.payload));assert.match(submitted1.payload.canonical_digest,/^[0-9a-f]{64}$/);
 const selfDecision=await request(`/api/production/rework-requests/${v1.payload.data.id}/accept`,{role:"production",username:"quality01",body:{expected_version:2}});assert.equal(selfDecision.response.status,403);
 const returned=await request(`/api/production/rework-requests/${v1.payload.data.id}/return`,{role:"production",body:{expected_version:2,reason:"补充返工原因"}});assert.equal(returned.response.status,200);assert.equal(returned.payload.ncr.unresolved_qty,"2.000000");
 const v2=await request(`/api/quality/nonconformances/${ncr.id}/rework-requests`,{body:{supersedes_request_id:v1.payload.data.id,target_snapshot_operation_id:2902,quantity:"2",reason:"第二版返工说明"}});assert.equal(v2.response.status,201);assert.equal(Number(v2.payload.data.revision_no),2);const submitted2=await request(`/api/quality/rework-requests/${v2.payload.data.id}/submit`,{body:{expected_version:1}});assert.equal(submitted2.response.status,200);const accepted=await request(`/api/production/rework-requests/${v2.payload.data.id}/accept`,{role:"production",body:{expected_version:2}});assert.equal(accepted.response.status,200,JSON.stringify(accepted.payload));assert.deepEqual([accepted.payload.ncr.failed_qty,accepted.payload.ncr.active_rework_qty,accepted.payload.ncr.final_scrap_qty,accepted.payload.ncr.unresolved_qty,accepted.payload.ncr.status],["2.000000","2.000000","0.000000","0.000000","REWORK_ACCEPTED"]);
 const immutable=await request(`/api/quality/rework-requests/${v2.payload.data.id}`,{method:"PATCH",body:{expected_version:3,target_snapshot_operation_id:2902,quantity:"1",reason:"非法改写"}});assert.equal(immutable.response.status,409);const cancel=await request(`/api/quality/rework-requests/${v2.payload.data.id}/cancel`,{body:{expected_version:3,reason:"非法取消"}});assert.equal(cancel.response.status,409);const reopen=await qualityRequest("/api/quality-inspections/2901/reopen",{body:{expected_version:3,reason:"已有接收返工不得重开"}});assert.equal(reopen.response.status,409);assert.equal(reopen.payload.code,"NONCONFORMANCE_DOWNSTREAM_EXISTS");
 const counts=(await pool.query(`select (select count(*)::int from production_operation_runs where id<>2901) rework_runs,(select count(*)::int from production_operation_run_reports where id<>2901) new_reports,(select count(*)::int from production_reports) production_reports,(select count(*)::int from production_completions) completions,(select count(*)::int from inventory_ledger_entries) ledger,(select count(*)::int from production_rework_request_versions) versions,(select count(*)::int from production_rework_request_events) request_events`)).rows[0];assert.deepEqual(counts,{rework_runs:0,new_reports:0,production_reports:0,completions:0,ledger:0,versions:2,request_events:6});
 await assert.rejects(pool.query("update production_rework_requests set quantity=1 where id=$1",[v2.payload.data.id]),/require service|immutable/i);
});

test("SCRAP is final, cannot overlap rework, and direct SQL rejects excess and cross-work-order targets",async()=>{const ncr=(await request("/api/quality/inspections/2901/nonconformance",{body:{expected_version:3}})).payload.data;const scrap=await request(`/api/quality/nonconformances/${ncr.id}/scrap-dispositions`,{role:"manager",body:{expected_version:1,quantity:"1",reason:"确认工序报废"}});assert.equal(scrap.response.status,201);assert.equal(scrap.payload.inventory_posting_created,false);const draft=await request(`/api/quality/nonconformances/${ncr.id}/rework-requests`,{body:{target_snapshot_operation_id:2901,quantity:"2",reason:"超过剩余数量"}});assert.equal(draft.response.status,201);const over=await request(`/api/quality/rework-requests/${draft.payload.data.id}/submit`,{body:{expected_version:1}});assert.equal(over.response.status,422);assert.equal(over.payload.code,"NONCONFORMANCE_QUANTITY_EXCEEDED");
 const cross=await request(`/api/quality/rework-requests/${draft.payload.data.id}`,{method:"PATCH",body:{expected_version:1,target_snapshot_operation_id:2999,quantity:"1",reason:"跨工单"}});assert.equal(cross.response.status,422);assert.equal(cross.payload.code,"REWORK_TARGET_INVALID");const later=await request(`/api/quality/rework-requests/${draft.payload.data.id}`,{method:"PATCH",body:{expected_version:1,target_snapshot_operation_id:2903,quantity:"1",reason:"后序目标"}});assert.equal(later.response.status,422);assert.equal(later.payload.code,"REWORK_TARGET_INVALID");
 const denied=await request(`/api/quality/nonconformances/${ncr.id}/scrap-dispositions`,{role:"quality",body:{expected_version:2,quantity:"1",reason:"越权"}});assert.equal(denied.response.status,403);const noInventory=(await pool.query("select (select count(*)::int from inventory_ledger_entries) ledger,(select count(*)::int from inventory_stock_balances) balances,(select count(*)::int from production_scrap_dispositions) scraps")).rows[0];assert.deepEqual(noInventory,{ledger:0,balances:0,scraps:1});await assert.rejects(pool.query("update production_scrap_dispositions set quantity=0.5"),/require service|immutable/i);});

test("source evidence, failed quantity, roles, concurrency, CAS, idempotency conflict and rollback fail closed",async()=>{await seed({failed:"0",withFail:false,withDefect:false});let response=await request("/api/quality/inspections/2901/nonconformance",{body:{expected_version:3}});assert.equal(response.response.status,422);await seed({failed:"2",withFail:false,withDefect:true});response=await request("/api/quality/inspections/2901/nonconformance",{body:{expected_version:3}});assert.equal(response.response.status,422);await seed();const denied=await request("/api/quality/inspections/2901/nonconformance",{role:"warehouse",body:{expected_version:3}});assert.equal(denied.response.status,403);
 const key="same-ncr-body-key",created=await request("/api/quality/inspections/2901/nonconformance",{body:{expected_version:3},key}),different=await request("/api/quality/inspections/2901/nonconformance",{body:{expected_version:4},key});assert.equal(created.response.status,201);assert.equal(different.payload.code,"IDEMPOTENCY_CONFLICT");const ncr=created.payload.data;
 const drafts=await Promise.all(["a","b"].map(suffix=>request(`/api/quality/nonconformances/${ncr.id}/rework-requests`,{key:`draft-${suffix}-key`,body:{target_snapshot_operation_id:2902,quantity:"2",reason:`并发 ${suffix}`}})));assert.deepEqual(drafts.map(item=>item.response.status).sort(),[201,409]);const draft=drafts.find(item=>item.response.status===201).payload.data;
 const submits=await Promise.all(["a","b"].map(suffix=>request(`/api/quality/rework-requests/${draft.id}/submit`,{key:`submit-${suffix}-key`,body:{expected_version:1}})));assert.deepEqual(submits.map(item=>item.response.status).sort(),[200,409]);const submitted=submits.find(item=>item.response.status===200).payload.data,ncrVersion=Number(submits.find(item=>item.response.status===200).payload.ncr.version);const decisions=await Promise.all([request(`/api/production/rework-requests/${submitted.id}/accept`,{role:"production",key:"concurrent-accept-key",body:{expected_version:2}}),request(`/api/quality/nonconformances/${ncr.id}/scrap-dispositions`,{role:"manager",key:"concurrent-scrap-key",body:{expected_version:ncrVersion,quantity:"1",reason:"并发报废"}})]);assert.deepEqual(decisions.map(item=>item.response.status).sort(),[200,422]);
 const before=(await pool.query("select (select count(*)::int from production_nonconformances) ncrs,(select count(*)::int from audit_log) audits,(select count(*)::int from idempotency_keys) keys")).rows[0];await seed();const fault=new ProductionNonconformanceService(pool,new QualityRepository(pool),checkpoint=>{if(checkpoint==="after_nonconformance_create")throw new Error("forced rollback");});await assert.rejects(fault.createNcr(2901,meta("quality","FAULT_CREATE"),{expected_version:3}),error=>error.code==="INTERNAL_ERROR");assert.deepEqual((await pool.query("select (select count(*)::int from production_nonconformances) ncrs,(select count(*)::int from audit_log) audits,(select count(*)::int from idempotency_keys) keys")).rows[0],{ncrs:0,audits:0,keys:0});assert.ok(before.ncrs>=1);
});
