import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { chmod, mkdir, mkdtemp, readFile, rm, symlink, unlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { backupGovernance, parseBackupVerification } from "../app/lib/dashboard-selfhost/backup-status.ts";
import { handleDashboardApi } from "../app/lib/dashboard-selfhost/handler.ts";
import { DashboardService } from "../app/lib/dashboard-selfhost/service.ts";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";

const actor=(role)=>({username:`${role}01`,role,permissions:permissionsForRole(role)});
const hash="a".repeat(64),receiverHash="d".repeat(64),targetSystemIdentifier="8612345678901234567";
const databaseProfile={database_server_major:"17",database_encoding:"UTF8",database_collate:"C.UTF-8",database_ctype:"C.UTF-8",database_locale_provider:"libc",database_collation_version:"NONE"};
const restoreReconciliation={contract:"chenyida-erp-restore-reconciliation/v1",source_sha256:hash,target_database_report_sha256:"e".repeat(64),target_file_trees_sha256:"f".repeat(64),result:"MATCHED"};
const expectedIdentity={deploymentClass:"UAT",deploymentId:"erp-uat",databaseName:"erp_uat",databaseSystemIdentifier:"7612345678901234567",databaseOid:"16384",databaseMarker:"UAT.erp-uat",databaseServerMajor:"17",databaseEncoding:"UTF8",databaseCollate:"C.UTF-8",databaseCtype:"C.UTF-8",databaseLocaleProvider:"libc",databaseCollationVersion:"NONE",applicationVersion:"0.1.0-alpha.46",gitCommit:"b".repeat(40),webImageDigest:`sha256:${hash}`,workerImageDigest:`sha256:${"c".repeat(64)}`,migrationHead:"0041_ai.sql",migrationManifestSha256:hash,policyId:"daily-rpo-v1",rpoHours:24,offhostLocationId:"offhost-a",offhostReceiverIdentitySha256:receiverHash,restoreLocationId:"isolated-restore",restoreTargetDeploymentId:"restore-test",restoreTargetSystemIdentifier:targetSystemIdentifier,restoreTargetClusterMarkerId:"restore-cluster",trustMode:"TRUSTED_ROOT_EXECUTOR"};
const valid={schema_version:2,contract:"chenyida-erp-backup-verification/v2",result:"RESTORE_VERIFIED",backup_id:"erp-20260725",created_at:"2026-07-25T01:00:00Z",verified_at:"2026-07-25T02:00:00Z",expires_at:"2026-07-26T00:58:00.000Z",location_id:"isolated-restore",deployment:{class:"UAT",id:"erp-uat",database:"erp_uat",database_system_identifier:"7612345678901234567",database_oid:"16384",database_marker:"UAT.erp-uat",database_bytes:16777216,...databaseProfile},application:{version:"0.1.0-alpha.46",git_commit:"b".repeat(40),web_image_digest:`sha256:${hash}`,worker_image_digest:`sha256:${"c".repeat(64)}`},migration:{head:"0041_ai.sql",manifest_file:"migrations.txt",manifest_sha256:hash},policy:{id:"daily-rpo-v1",rpo_hours:24},consistency:{method:"QUIESCED_APPLICATION_AND_SNAPSHOT_WITH_CONTENT_RECONCILIATION",database_snapshot:"PG_DUMP_CONSISTENT_SNAPSHOT",database_guard:"DEFAULT_TRANSACTION_READ_ONLY_DEFENSE_IN_DEPTH",writer_boundary:"EXACT_COMPOSE_WEB_WORKER_STOPPED",content_reconciliation:"BEFORE_AFTER_FULL_RELATION_CONTENT_DIGESTS",dump_scope:"COMPLETE_APPLICATION_DATABASE_LOGICAL_DUMP_NO_OWNER_OR_ACL",web_container:"web-test",web_container_id:hash,worker_container:"worker-test",worker_container_id:"c".repeat(64),recovery_point_at:"2026-07-25T00:58:00Z",verified_after:"2026-07-25T00:59:00Z"},reconciliation:{contract:"chenyida-erp-backup-reconciliation/v1",file:"reconciliation.json",sha256:hash},manifest_sha256:hash,artifacts:{postgresql_dump:{file:"postgresql.dump",sha256:hash,bytes:10},uploads:{file:"uploads.tar.gz",sha256:hash,bytes:20,entries:0},attachments:{file:"attachments.tar.gz",sha256:hash,bytes:20,entries:0},backup_status:{file:"backup-status.tar.gz",sha256:hash,bytes:20,entries:0}},evidence:{kind:"ISOLATED_RESTORE_VERIFICATION",source_location_id:"source-host",offhost_location_id:"offhost-a",offhost_receiver_identity_sha256:receiverHash,offhost_receipt_sha256:hash,restore_run_id:"restore-1",restored_at:"2026-07-25T02:00:00Z",target:{deployment_class:"TEST",deployment_id:"restore-test",database_name:"erp_restore_test",database_system_identifier:targetSystemIdentifier,database_oid:"16385",marker_id:"target-1",cluster_marker_id:"restore-cluster",...databaseProfile,file_root_name:"restore-1_restore_test"},reconciliation:restoreReconciliation,reconciliation_sha256:createHash("sha256").update(JSON.stringify(restoreReconciliation)).digest("hex"),attestation:"TRUSTED_EXECUTION_UID_AND_DISTINCT_CLUSTER_ACTIVE_INSPECTION"}};
const snapshot={active_materials:1,total_mappings:2,pending_materials:3,pending_material_reviews:0,auto_count:4,suspect_count:5,new_count:6,active_customers:2,active_suppliers:3,released_products:4,valid_boms:5,inventory_material_kinds:6,inventory_zero_available_kinds:1,inventory_quantities:[{unit:"PCS",on_hand:"9007199254740993.000001",available:"9007199254740992.000001",frozen:"1.000000"}],total_purchase_orders:8,open_purchase_orders:7,pending_receipt_qty:"8.000001",total_work_orders:10,active_work_orders:9,pending_issue_qty:"10.000001",pending_completion_qty:"11.000001",shortage_requirement_count:1,pending_production_accept:0,production_kitting_shortage:0,released_waiting_issue:0,partial_issue_work_orders:0,pending_reporting_work_orders:0,reported_waiting_receipt_qty:"0",partial_completion_work_orders:0,completed_waiting_quality_qty:"0",pending_ipqc_reports:0,completed_waiting_allocation_qty:"0",pending_fqc_finished_qty:"0",quality_hold_qty:"0",released_waiting_shipment_qty:"10",total_quotations:11,open_quotations:2,total_sales_orders:13,open_sales_orders:12,pending_shipment_qty:"13.000001",pending_delivery_instructions:2,partial_sales_orders:1,pending_sales_ar_count:2,pending_sales_ar_amount:"200",total_quality_inspections:10,pending_iqc:1,pending_ipqc:2,pending_fqc:3,open_quality_exceptions:4,ar_total:"100.000001",ar_settled:"20.000001",ar_balance:"80.000000",ap_total:"50.000001",ap_settled:"10.000001",ap_balance:"40.000000",pending_purchase_ap_count:0,pending_purchase_ap_amount:"0",generated_purchase_ap_count:0,generated_purchase_ap_amount:"0",pending_planning_handoffs:0,accepted_planning_packages:0,pending_purchase_requests:0,pending_sourcing_requests:0,pending_quote_rfqs:0,pending_award_rfqs:0,pending_award_conversion:0,pending_receiving_plans:0,net_receipts:"20.000001",net_payments:"10.000001",finance_by_currency:[],pending_jobs:1,failed_jobs:2,migrations:[{version:"0023_sales_delivery_receivable.sql",checksum:hash,applied_at:"2026-07-26T00:00:00Z"}],recent_events:[{domain:"finance",action:"SETTLED",object_code:"AR-1",actor:"finance01",request_id:"00000000-0000-4000-8000-000000000001",created_at:"2026-07-25T00:00:00Z"}],recent_audits:[{action:"LOGIN",result:"success",username:"admin01",route_code:"IDENTITY",request_id:"00000000-0000-4000-8000-000000000002",created_at:"2026-07-25T00:00:00Z"}],generated_at:"2026-07-25T00:00:00Z"};
const repository={readSnapshot:async()=>structuredClone(snapshot)};

test("fixed roles get dashboard while management and backup status use explicit capabilities",()=>{for(const role of ["admin","manager","purchase","engineering","production","warehouse","quality","sales","finance","operations"])assert.ok(permissionsForRole(role).includes("dashboard.read"),role);for(const role of ["admin","manager","operations"])assert.ok(permissionsForRole(role).includes("dashboard.management.read"),role);assert.ok(!permissionsForRole("finance").includes("dashboard.management.read"));assert.ok(permissionsForRole("admin").includes("system.backup.read"));for(const role of ["manager","purchase","engineering","production","warehouse","quality","sales","finance","operations"])assert.ok(!permissionsForRole(role).includes("system.backup.read"),role);});
test("summary is role-trimmed, keeps permitted compatibility fields and preserves decimal strings",async()=>{const service=new DashboardService(repository,"/missing");const finance=await service.summary(actor("finance"));assert.deepEqual(Object.keys(finance.groups).sort(),["finance","partners","procurement","sales"]);assert.equal(finance.groups.finance.ar_total,"100.000001");assert.equal(finance.receivable_balance,"80.000000");assert.equal(finance.pending_sales_ar_amount,"200");assert.equal(finance.groups.inventory,undefined);assert.equal(finance.total_items,undefined);const engineering=await service.summary(actor("engineering"));assert.deepEqual(Object.keys(engineering.groups).sort(),["engineering","inventory","material","partners"]);await assert.rejects(service.management(actor("finance")),e=>e.code==="PERMISSION_DENIED");const admin=await service.management(actor("admin"));assert.equal(admin.recent_activity[0].action,"LOGIN");assert.equal(admin.recent_events[0].object_code,"AR-1");assert.ok(admin.metrics.some(item=>item.label==="待仓库接收发货指令"));assert.ok(admin.metrics.some(item=>item.label==="FQC 已放行待发货数量"));assert.ok(admin.metrics.some(item=>item.label==="已发货待生成 AR"));});
test("warehouse homepage excludes supplier IQC while quality keeps the incoming-quality module",async()=>{const service=new DashboardService(repository,"/missing"),warehouse=await service.summary(actor("warehouse")),quality=await service.summary(actor("quality"));assert.ok(warehouse.modules.some(item=>item.code==="warehouse-receiving"));assert.ok(!warehouse.modules.some(item=>item.code==="incoming-quality"));assert.ok(quality.modules.some(item=>item.code==="incoming-quality"));});

test("backup status separates evidence validity, runtime identity, policy, and assurance",async()=>{
  assert.deepEqual(parseBackupVerification(valid),valid);
  for(const bad of [{...valid,result:"CREATED"},{...valid,backup_id:"../escape"},{...valid,deployment:{...valid.deployment,database_oid:"bad"}},{...valid,deployment:{...valid.deployment,database_bytes:0}},{...valid,migration:{...valid.migration,manifest_sha256:"bad"}},{...valid,evidence:{...valid.evidence,offhost_location_id:"isolated-restore"}},{...valid,evidence:{...valid.evidence,reconciliation_sha256:"0".repeat(64)}},{...valid,unexpected:true}])assert.equal(parseBackupVerification(bad),null);
  const dir=await mkdtemp(path.join(os.tmpdir(),"cyd-dashboard-"));try{
    assert.equal((await backupGovernance(path.join(dir,"none"))).verification_status,"UNVERIFIED");const file=path.join(dir,"latest.json");await writeFile(file,JSON.stringify(valid));
    const fresh=await backupGovernance(file,{now:new Date("2026-07-25T03:00:00Z"),expectedIdentity});assert.equal(fresh.verification_status,"RESTORE_VERIFIED");assert.equal(fresh.identity_status,"MATCHED");assert.equal(fresh.policy_status,"MATCHED");assert.equal(fresh.assurance_status,"MATCHED");assert.equal(fresh.recovery_ready,true);assert.equal(JSON.stringify(fresh).includes(dir),false);
    const mismatch=await backupGovernance(file,{now:new Date("2026-07-25T03:00:00Z"),expectedIdentity:{...expectedIdentity,migrationManifestSha256:"9".repeat(64)}});assert.equal(mismatch.identity_status,"MISMATCH");assert.equal(mismatch.recovery_ready,false);
    const receiverMismatch=await backupGovernance(file,{now:new Date("2026-07-25T03:00:00Z"),expectedIdentity:{...expectedIdentity,offhostReceiverIdentitySha256:"9".repeat(64)}});assert.equal(receiverMismatch.assurance_status,"MISMATCH");assert.equal(receiverMismatch.recovery_ready,false);
    assert.equal((await backupGovernance(file,{now:new Date("2026-07-27T03:00:00Z"),expectedIdentity})).verification_status,"STALE");
    const sourceMachineIdentity="1".repeat(64),sourceRootDevice="2049",sourceRootInode="128";const sourceRootIdentity=createHash("sha256").update(`${sourceMachineIdentity}\n${sourceRootDevice}\n${sourceRootInode}\n`).digest("hex");await writeFile(file,JSON.stringify({...valid,result:"LOCAL_VERIFIED",evidence:{kind:"LOCAL_CAPTURE_VERIFICATION",source_machine_identity_sha256:sourceMachineIdentity,source_root_device:sourceRootDevice,source_root_inode:sourceRootInode,source_root_identity_sha256:sourceRootIdentity,attestation:"TRUSTED_EXECUTION_UID_AND_FIXED_SOURCE_MACHINE_ROOT"}}));const local=await backupGovernance(file,{now:new Date("2026-07-25T03:00:00Z"),expectedIdentity});assert.equal(local.verification_status,"LOCAL_VERIFIED");assert.equal(local.recovery_ready,false);
    const legacy={schema_version:1,result:"VERIFIED",backup_id:"legacy-1",created_at:"2026-07-25T01:00:00Z",verified_at:"2026-07-25T02:00:00Z",application_version:"0.1.0-alpha.10",git_commit:"b".repeat(40),migration_head:"0013_finance.sql",artifacts:{postgresql_dump:{file:"postgresql.dump",sha256:hash,bytes:10},uploads:{file:"uploads.tar.gz",sha256:hash,bytes:10,entries:0},attachments:{file:"attachments.tar.gz",sha256:hash,bytes:10,entries:0}}};await writeFile(file,JSON.stringify(legacy));const legacyResult=await backupGovernance(file);assert.equal(legacyResult.verification_status,"LEGACY_LOCAL_ONLY");assert.equal(legacyResult.recovery_ready,false);
    await writeFile(file,'{"schema_version":1,"schema_version":2}');assert.equal((await backupGovernance(file)).verification_status,"INVALID");
  }finally{await rm(dir,{recursive:true,force:true});}
});

test("configured runtime release identity fails closed when missing, stale, forged, or replaced",{skip:typeof process.getuid!=="function"||process.getuid()!==0},async()=>{
  const directory=await mkdtemp(path.join(os.tmpdir(),"cyd-release-dashboard-")),releaseRoot=path.join(directory,"release"),releaseFile=path.join(releaseRoot,"release-identity.json"),marker=path.join(releaseRoot,".chenyida-erp-release-identity-root-v1");
  const release=(generated_at="2026-07-25T02:30:00.000Z",web_container_id="a".repeat(64))=>({schema_version:2,contract:"chenyida-erp-runtime-release-identity/v2",deployment_class:"UAT",deployment_id:"erp-uat",release_id:"fixture-release",release_manifest_sha256:"d".repeat(64),supervisor_bundle_sha256:"e".repeat(64),authorization_sha256:"f".repeat(64),application_version:"0.1.0-alpha.46",git_commit:"b".repeat(40),web_container_id,web_image_digest:`sha256:${hash}`,worker_container_id:"c".repeat(64),worker_image_digest:`sha256:${"c".repeat(64)}`,generated_at});
  const runtimeIdentity={database:{name:"erp_uat",system_identifier:"7612345678901234567",oid:"16384",marker:"chenyida-erp-deployment/v2:UAT:erp-uat",server_major:"17",encoding:"UTF8",collate:"C.UTF-8",ctype:"C.UTF-8",locale_provider:"libc",collation_version:"NONE"},applicationVersion:"0.1.0-alpha.46",gitCommit:"b".repeat(40),migrationHead:"0041_ai.sql",migrationManifestSha256:hash,hostname:"a".repeat(12)};
  const env={ERP_DEPLOYMENT_CLASS:"UAT",ERP_RELEASE_EXPECTED_DEPLOYMENT_ID:"erp-uat",ERP_RELEASE_EXPECTED_VERSION:"0.1.0-alpha.46",ERP_RELEASE_EXPECTED_GIT_COMMIT:"b".repeat(40),ERP_RELEASE_EXPECTED_MANIFEST_SHA256:"d".repeat(64),ERP_RELEASE_EXPECTED_SUPERVISOR_BUNDLE_SHA256:"e".repeat(64),ERP_RELEASE_IDENTITY_MAX_AGE_SECONDS:"3600",ERP_BACKUP_POLICY_ID:"daily-rpo-v1",ERP_BACKUP_RPO_HOURS:"24",ERP_BACKUP_EXPECTED_OFFHOST_LOCATION_ID:"offhost-a",ERP_BACKUP_EXPECTED_OFFHOST_RECEIVER_IDENTITY_SHA256:receiverHash,ERP_BACKUP_EXPECTED_RESTORE_LOCATION_ID:"isolated-restore",ERP_BACKUP_EXPECTED_RESTORE_TARGET_ID:"restore-test",ERP_BACKUP_EXPECTED_RESTORE_TARGET_SYSTEM_IDENTIFIER:targetSystemIdentifier,ERP_BACKUP_EXPECTED_RESTORE_TARGET_CLUSTER_MARKER_ID:"restore-cluster",ERP_BACKUP_EVIDENCE_TRUST_MODE:"TRUSTED_ROOT_EXECUTOR"};
  const prior=Object.fromEntries(Object.keys(env).map((key)=>[key,process.env[key]]));
  try{
    Object.assign(process.env,env);await mkdir(releaseRoot,{mode:0o750});await chmod(releaseRoot,0o750);await writeFile(marker,"chenyida-erp-release-identity-root/v1\n",{mode:0o440});await chmod(marker,0o440);await writeFile(releaseFile,JSON.stringify(release()),{mode:0o440});await chmod(releaseFile,0o440);
    const options={now:new Date("2026-07-25T03:00:00Z"),runtimeIdentity,releaseIdentityFile:releaseFile};
    const configured=await backupGovernance(path.join(directory,"status.json"),options);assert.equal(configured.verification_status,"UNVERIFIED");
    await writeFile(path.join(directory,"status.json"),JSON.stringify(valid));const matched=await backupGovernance(path.join(directory,"status.json"),options);assert.equal(matched.identity_status,"MATCHED");assert.equal(matched.policy_status,"MATCHED");assert.equal(matched.assurance_status,"MATCHED");assert.equal(matched.recovery_ready,true);
    for(const [name,file] of [["missing",path.join(releaseRoot,"missing.json")]]){const result=await backupGovernance(path.join(directory,"status.json"),{...options,releaseIdentityFile:file});assert.equal(result.identity_status,"UNCONFIGURED",name);assert.equal(result.recovery_ready,false,name);}
    await chmod(releaseFile,0o640);await writeFile(releaseFile,JSON.stringify(release("2026-07-25T00:00:00.000Z")));await chmod(releaseFile,0o440);const stale=await backupGovernance(path.join(directory,"status.json"),options);assert.equal(stale.identity_status,"UNCONFIGURED");assert.equal(stale.recovery_ready,false);
    await chmod(releaseFile,0o640);await writeFile(releaseFile,JSON.stringify(release(undefined,"9".repeat(64))));await chmod(releaseFile,0o440);const forged=await backupGovernance(path.join(directory,"status.json"),options);assert.equal(forged.identity_status,"UNCONFIGURED");assert.equal(forged.recovery_ready,false);
    const replacement=path.join(releaseRoot,"replacement.json");await writeFile(replacement,JSON.stringify(release()),{mode:0o440});await chmod(replacement,0o440);await unlink(releaseFile);await symlink(replacement,releaseFile);const replaced=await backupGovernance(path.join(directory,"status.json"),options);assert.equal(replaced.identity_status,"UNCONFIGURED");assert.equal(replaced.recovery_ready,false);
  }finally{for(const [key,value] of Object.entries(prior))if(value===undefined)delete process.env[key];else process.env[key]=value;await rm(directory,{recursive:true,force:true});}
});

test("dangerous legacy backup writes have stable offline-only errors",async()=>{const requestId="00000000-0000-4000-8000-000000000010";const pool={};for(const [route,code] of [["create","OFFLINE_OPERATION_REQUIRED"],["restore","IN_PLACE_RESTORE_FORBIDDEN"]]){const response=await handleDashboardApi(new Request(`http://local.test/api/backups/${route}`,{method:"POST"}),{pool,actor:actor("admin"),requestId,backupStatusFile:"/missing"});assert.equal(response.status,409);assert.equal((await response.json()).code,code);}const retired=await handleDashboardApi(new Request("http://local.test/api/sample-import"),{pool,actor:actor("admin"),requestId,backupStatusFile:"/missing"});assert.equal(retired.status,410);});
test("all retired one-step imports remain unavailable",async()=>{const requestId="00000000-0000-4000-8000-000000000011";const pool={};for(const [route,method] of [["sample-import","GET"],["import","GET"],["import","POST"],["import-file","POST"]]){const retired=await handleDashboardApi(new Request("http://local.test/api/"+route,{method}),{pool,actor:actor("admin"),requestId,backupStatusFile:"/missing"});assert.equal(retired.status,410);assert.equal((await retired.json()).code,"LEGACY_OPERATION_RETIRED");}});
test("active work-order metric excludes draft and completed orders",async()=>{const source=await readFile(new URL("../app/lib/dashboard-selfhost/repository.ts",import.meta.url),"utf8");assert.match(source,/status in \('RELEASED','IN_PROGRESS'\)\) active_work_orders/);assert.doesNotMatch(source,/status in \('DRAFT','RELEASED','IN_PROGRESS','COMPLETED'\)\) active_work_orders/);});
