import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import test from "node:test";
import { Pool } from "pg";

const url=process.env.TEST_PRODUCTION_REWORK_UPGRADE_DATABASE_URL;
if(!url||!/production_rework_upgrade_test/i.test(url))throw new Error("isolated TEST_PRODUCTION_REWORK_UPGRADE_DATABASE_URL containing production_rework_upgrade_test is required");
const pool=new Pool({connectionString:url,max:2,application_name:"production-rework-upgrade-test"}),dir=new URL("../drizzle-postgres/",import.meta.url);
const names=(await readdir(dir)).filter(name=>/^\d{4}_.+\.sql$/.test(name)&&name<="0030_production_rework_execution.sql").sort(),sources=new Map();for(const name of names)sources.set(name,await readFile(new URL(name,dir),"utf8"));
const checksum=name=>createHash("sha256").update(sources.get(name)).digest("hex");
async function reset(){await pool.query("drop schema public cascade;create schema public;create table schema_migrations(version text primary key,checksum text not null)");}
async function migrate(list){for(const name of list){const existing=await pool.query("select checksum from schema_migrations where version=$1",[name]);if(existing.rows[0]){assert.equal(existing.rows[0].checksum,checksum(name));continue;}const client=await pool.connect();try{await client.query("begin");await client.query(sources.get(name));await client.query("insert into schema_migrations values($1,$2)",[name,checksum(name)]);await client.query("commit");}catch(error){await client.query("rollback");throw error;}finally{client.release();}}}
test.after(()=>pool.end());

test("empty database and repeated runner reach exactly migration 0030",async()=>{assert.equal(names.length,30);assert.equal(names.at(-1),"0030_production_rework_execution.sql");await reset();await migrate(names);await migrate(names);assert.equal((await pool.query("select count(*)::int count from schema_migrations")).rows[0].count,30);for(const table of ["production_rework_run_allocations","production_rework_execution_projections","production_rework_execution_events"])assert.equal((await pool.query("select to_regclass($1) value",[`public.${table}`])).rows[0].value,table);});

test("0029 upgrades expand-only and historical runs remain NORMAL",async()=>{await reset();await migrate(names.slice(0,29));await pool.query("insert into app_users(username,display_name,role,password_hash) values('admin01','管理员','admin','x')");const before=(await pool.query("select count(*)::int count from app_users")).rows[0].count;await migrate(names.slice(29));assert.equal((await pool.query("select count(*)::int count from app_users")).rows[0].count,before);const column=(await pool.query("select column_default,is_nullable from information_schema.columns where table_name='production_operation_runs' and column_name='run_kind'")).rows[0];assert.match(column.column_default,/NORMAL/);assert.equal(column.is_nullable,"NO");});

test("0030 failure rolls back all additions and migration row",async()=>{await reset();await migrate(names.slice(0,29));await pool.query("create table production_rework_execution_projections(id bigint)");await assert.rejects(migrate(names.slice(29)),/production_rework_execution_projections.*already exists/i);assert.equal((await pool.query("select to_regclass('public.production_rework_run_allocations') value")).rows[0].value,null);assert.equal((await pool.query("select count(*)::int count from schema_migrations where version=$1",[names.at(-1)])).rows[0].count,0);});

test("snapshot journal and full SHA-256 describe 0030",async()=>{const schema=await readFile(new URL("../db/schema.ts",import.meta.url),"utf8"),snapshot=JSON.parse(await readFile(new URL("../drizzle-postgres/meta/0030_snapshot.json",import.meta.url),"utf8")),journal=JSON.parse(await readFile(new URL("../drizzle-postgres/meta/_journal.json",import.meta.url),"utf8"));for(const table of ["production_rework_run_allocations","production_rework_execution_projections","production_rework_execution_events"])assert.ok(snapshot.tables[`public.${table}`],table);for(const token of ["productionReworkRunAllocations","productionReworkExecutionProjections","productionReworkExecutionEvents","runKind","RESOLVED"])assert.match(schema,new RegExp(token));assert.equal(snapshot.prevId,JSON.parse(await readFile(new URL("../drizzle-postgres/meta/0029_snapshot.json",import.meta.url),"utf8")).id);assert.equal(journal.entries.find(entry=>entry.tag==="0030_production_rework_execution")?.tag,"0030_production_rework_execution");assert.match(checksum(names.at(-1)),/^[0-9a-f]{64}$/);});

test("0030 contains lineage, conservation, immutable, quality and direct SQL guards",async()=>{const sql=sources.get(names.at(-1));for(const token of ["invalid accepted rework source","rework dispatch exceeds accepted quantity","invalid rework run allocation lineage","accepted rework quantity over-allocated","rework execution events are immutable","rework execution does not reconcile","run_kind='NORMAL'","run_kind='REWORK'","quality_inspections","DEFERRABLE INITIALLY DEFERRED"])assert.match(sql,new RegExp(token));for(const forbidden of ['CREATE TABLE "quality_inspections"','CREATE TABLE "production_operation_runs"','CREATE TABLE "inventory_ledger_entries"'])assert.doesNotMatch(sql,new RegExp(forbidden));});
