import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { canonicalDigest, decimal } from "../app/lib/procurement-sourcing-selfhost/validation.ts";

const all=["procurement.rfq.read","procurement.rfq.manage","procurement.quote.record","procurement.quote.compare","procurement.sourcing.award","procurement.sourcing.reverse"];
test("purchase owns sourcing writes, planning is progress-only, managers retain the full loop",()=>{for(const value of all)assert.ok(permissionsForRole("purchase").includes(value),value);assert.ok(permissionsForRole("planning").includes("procurement.rfq.read"));for(const value of all.slice(1))assert.ok(!permissionsForRole("planning").includes(value),value);for(const role of ["admin","manager"])for(const value of all)assert.ok(permissionsForRole(role).includes(value),`${role}:${value}`);for(const role of ["engineering","production","warehouse","finance"])for(const value of all.slice(1))assert.ok(!permissionsForRole(role).includes(value),`${role}:${value}`)});
test("numeric inputs and quote basis digests remain deterministic",()=>{assert.equal(decimal("9007199254740993.000001","price"),"9007199254740993.000001");assert.throws(()=>decimal("1.0000001","price"),/6 位/);assert.equal(canonicalDigest({tax:true,price:"2.000000"}),canonicalDigest({price:"2.000000",tax:true}))});
test("service ranks only in PostgreSQL and never creates downstream facts",async()=>{const service=await readFile(new URL("../app/lib/procurement-sourcing-selfhost/service.ts",import.meta.url),"utf8");assert.match(service,/row_number\(\) over\(partition by q\.currency_code,ql\.unit_id,q\.tax_included,q\.freight_included order by \(q\.valid_until<current_date\),ql\.unit_price,ql\.promised_delivery_date,q\.supplier_id\)/);assert.match(service,/purchase_order_created: false/);assert.match(service,/SOLE_SOURCE/);assert.match(service,/LATE_DELIVERY_ACCEPTED/);assert.doesNotMatch(service,/parseFloat|insert into purchase_orders|insert into purchase_receipts|update inventory_stock_balances|insert into finance_documents/i)});
