import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=path=>readFile(new URL(path,import.meta.url),"utf8");
test("three native workspaces expose server-backed purchase, receiving and payable actions",async()=>{
  const purchase=await read("../app/procurement/fulfillment/procurement-fulfillment-workspace.tsx"),warehouse=await read("../app/warehouse/receiving/warehouse-receiving-workspace.tsx"),finance=await read("../app/finance/payables/finance-payables-workspace.tsx");
  assert.match(purchase,/pending-awards/);assert.match(purchase,/显式生成采购订单/);assert.match(purchase,/建立到货计划/);assert.match(purchase,/procurement\.award\.convert/);
  assert.match(warehouse,/receiving-queue/);assert.match(warehouse,/确认过账收货/);assert.match(warehouse,/expected_balance_version/);assert.match(warehouse,/expected_line_version/);
  assert.match(finance,/payable-handoff/);assert.match(finance,/核对并显式生成 AP/);assert.match(finance,/purchase_source_entry_id/);assert.doesNotMatch(finance,/name="amount"|total_amount:/);
});
test("warehouse receiving is a return-first GET preview with one guarded final POST and responsive evidence fields",async()=>{
  const workspace=await read("../app/warehouse/receiving/warehouse-receiving-workspace.tsx");
  const css=await read("../app/warehouse/receiving/warehouse-receiving.css");
  const openPreview=workspace.match(/async function openPreview[^]*?(?=\n  function cancelPreview)/)?.[0]||"";
  const cancelPreview=workspace.match(/function cancelPreview[^]*?(?=\n  function confirmationReady)/)?.[0]||"";
  const confirmReceipt=workspace.match(/async function confirmReceipt[^]*?(?=\n  async function logout)/)?.[0]||"";
  assert.match(openPreview,/receipt-preview/);assert.match(openPreview,/cache: "no-store"/);assert.doesNotMatch(openPreview,/method:\s*"POST"|protectedWrite/);
  assert.doesNotMatch(cancelPreview,/api\(|fetch\(|method:\s*"POST"|protectedWrite/);
  assert.match(confirmReceipt,/method: "POST"/);assert.match(confirmReceipt,/protectedWrite/);assert.match(confirmReceipt,/button\.disabled = true/);assert.match(confirmReceipt,/postInFlight\.current = true/);assert.match(confirmReceipt,/setSubmitted\(true\)/);assert.doesNotMatch(confirmReceipt,/retry|setTimeout|setInterval|while\s*\(/i);
  assert.match(workspace,/cancelRef\.current\?\.focus/);assert.match(workspace,/event\.key === "Escape"/);assert.match(workspace,/event\.target === event\.currentTarget/);assert.match(workspace,/aria-label="关闭收货确认窗口"/);
  assert.match(workspace,/disabled=\{busy \|\| submitted \|\| !ready\}/);assert.match(workspace,/crypto\.randomUUID\(\)/);
  assert.match(workspace,/const EMPTY_DRAFT[^]*?quantity: ""/);assert.match(workspace,/reason: ""/);assert.doesNotMatch(workspace,/name="quantity"[^>]*(?:value|defaultValue)="[1-9]/);assert.doesNotMatch(workspace,/name="reason"[^>]*(?:value|defaultValue)="[^\"]+/);
  for(const field of ["evidence_type","evidence_reference","evidence_document_date","supplier_lot_code","early_arrival_reason","early_arrival_confirmed","physical_receipt_confirmed","expected_purchase_order_version","expected_line_version","expected_version","expected_queue_version","expected_balance_version","expected_early_arrival","expected_target_location_code"])assert.match(workspace,new RegExp(`\\b${field}\\b`),field);
  for(const text of ["PO OPEN不代表已到货","Plan PENDING不代表已收货","queue OPEN_PENDING不代表库存增加","实际物理收货","供应商通知或在途登记当前未建模","服务端当前时间","承诺/计划日期","实际收货时间规则","送货凭证","Supplier批次","目标仓库","目标库位","经办账号","收货说明","本次过账后果与职责边界","IQC检验、处置与关闭由quality负责","收货不会自动创建AP、付款、Work Order或其他生产记录"])assert.match(workspace,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")),text);
  assert.match(css,/overflow-x:\s*hidden/);assert.match(css,/overflow-wrap:\s*anywhere/);assert.match(css,/@media\s*\(max-width:\s*600px\)/);assert.doesNotMatch(css,/min-width:\s*[4-9]\d\dpx/);
});
test("warehouse preview sends the evidence date, fails closed on server errors and returns to the preserved form draft",async()=>{
  const workspace=await read("../app/warehouse/receiving/warehouse-receiving-workspace.tsx");
  const readModel=await read("../app/lib/procurement-fulfillment-selfhost/warehouse-receipt-readiness.ts");
  const reset=workspace.match(/function resetConfirmationState[^]*?(?=\n  async function openPreview)/)?.[0]||"";
  const openPreview=workspace.match(/async function openPreview[^]*?(?=\n  function cancelPreview)/)?.[0]||"";
  const cancelPreview=workspace.match(/function cancelPreview[^]*?(?=\n  function confirmationReady)/)?.[0]||"";
  const confirmationReady=workspace.match(/function confirmationReady[^]*?(?=\n  async function confirmReceipt)/)?.[0]||"";
  assert.match(openPreview,/new URLSearchParams\(\)/);assert.match(openPreview,/parameters\.set\("evidence_document_date", nextDraft\.evidence_document_date\)/);assert.match(openPreview,/parameters\.toString\(\)/);
  assert.match(openPreview,/setPreview\(response\.data\)/);assert.match(openPreview,/resetConfirmationState\(\)/);assert.match(openPreview,/setPreviewError\(\{ deliveryPlanId: row\.id, text: message\(previewError\) \}\)/);
  assert.doesNotMatch(openPreview,/method:\s*"POST"|protectedWrite|Date\.now|new Date/);
  assert.match(workspace,/data-receipt-preview-error/);assert.match(workspace,/error\.requestId/);assert.match(workspace,/error\.code/);
  assert.match(confirmationReady,/evidence_document_date === value\.selected_receipt\.evidence_document_date/);assert.match(confirmationReady,/evidence_document_date <= value\.selected_receipt\.server_date_shanghai/);assert.doesNotMatch(confirmationReady,/Date\.now|new Date/);
  for(const state of [/setPreviewLoading\(false\)/,/setPreview\(null\)/,/setDraft\(EMPTY_DRAFT\)/,/setPosting\(false\)/,/setSubmitted\(false\)/,/setDialogError\(""\)/,/postInFlight\.current = false/,/idempotencyKey\.current = ""/])assert.match(reset,state);
  assert.match(cancelPreview,/resetConfirmationState\(true\)/);assert.doesNotMatch(cancelPreview,/api\(|fetch\(|method:\s*"POST"|protectedWrite/);
  assert.match(workspace,/>返回修改<\/button>/);assert.match(workspace,/event\.key === "Escape"[^]*?onCancel\(\)/);assert.match(workspace,/event\.target === event\.currentTarget[^]*?onCancel\(\)/);assert.match(workspace,/aria-label="关闭收货确认窗口"[^]*?onClick=\{onCancel\}/);
  assert.doesNotMatch(workspace,/form\.reset\(|清空本行/);assert.match(openPreview,/new FormData\(event\.currentTarget\)/);
  assert.doesNotMatch(readModel,/若物料权威配置为IQC|不创建内部RML Lot|不创建IQC冻结|不创建供应商来料IQC责任队列/);
  for(const text of ["普通Purchase Receipt及Receipt Line","普通RECEIPT入账","available立即按现有权威余额公式重算","普通收货事务完成后，本次warehouse收货流程结束","初始状态FROZEN","UNFREEZE Ledger","下一责任队列属于quality"])assert.match(readModel,new RegExp(text));
});
test("Award conversion V2 shares Mapping qualification with preview and guards the only explicit POST",async()=>{const workspace=await read("../app/procurement/fulfillment/procurement-fulfillment-workspace.tsx"),dialog=await read("../app/procurement/fulfillment/award-po-conversion-dialog.tsx"),preview=await read("../app/lib/procurement-fulfillment-selfhost/award-conversion-preview.ts");
  assert.match(workspace,/onClick=\{\(\) => void openConversion\(row\)\}/);assert.match(workspace,/purchase-order-conversion-preview/);assert.match(workspace,/cache: "no-store"/);assert.match(workspace,/AWARD_PO_CONFIRMATION_V2/);assert.match(workspace,/AWARD_PO_MAPPING_QUALIFICATION_V1/);assert.match(workspace,/mapping_qualification\.qualification_digest/);assert.match(workspace,/conversionPreview\.po_convertible_now !== true \|\| conversionPreview\.mapping_qualification\.all_qualified !== true/);assert.match(workspace,/conversionInFlight\.current/);assert.match(workspace,/setConversionSubmitted\(true\); setConversionBusy\(true\)/);assert.match(workspace,/\.\.\.conversionPreview\.confirmation/);assert.match(workspace,/remark: conversionRemark/);assert.match(workspace,/purchase-orders`, \{/);const openConversion=workspace.match(/async function openConversion\(row: Award\)[^]*?(?=\n  function cancelConversion)/)?.[0]||"";assert.doesNotMatch(openConversion,/post\(/);
  for(const text of ["定标转采购订单最终确认","完整业务谱系","Comparison固定Quote输入与获奖来源","Award成功Event","两类Award摘要","四条转换范围","Supplier Mapping资格凭证","qualified=true / 合格","将创建的权威记录","当前PO模型未采集外部参考","PO备注","最终确认生成PO及到货计划","Award、RFQ、Quote、Comparison不会被修改","Receipt","Warehouse Receipt","Inventory Ledger","IQC","AP","Payment","Work Order","其他生产记录","其他财务记录","供应商到货、仓库收货和IQC必须由后续独立任务完成","取消"])assert.match(dialog+preview,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
  for(const field of ["award_line_id","candidate_id","quote_line_id","rfq_binding_id","supplier_id","supplier_code","material_id","mapping_uuid","mapping_fact_id","mapping_version_no","mapping_row_cas","binding_status","mapping_status","supplier_status","material_status","supplier_part_number","supplier_unit_id","supplier_unit_code","internal_unit_id","internal_unit_code","conversion_numerator","conversion_denominator","valid_from","valid_to","content_digest","supplier_material_conflict_count","supplier_part_number_conflict_count","qualified","error_code","reason"])assert.match(dialog,new RegExp(`line\\.${field}\\b`),field);
  assert.match(dialog,/award-po-qualification-desktop/);assert.match(dialog,/award-po-qualification-mobile/);assert.match(dialog,/const mappingQualified = preview\.po_convertible_now === true && mappingQualification\?\.all_qualified === true/);assert.match(dialog,/disabled=\{busy \|\| submitted \|\| !mappingQualified\}/);assert.match(dialog,/Supplier Mapping资格凭证缺失，已禁止最终转换/);
  assert.match(dialog,/cancelRef\.current\?\.focus/);assert.match(dialog,/event\.key === "Escape"/);assert.match(dialog,/event\.target === event\.currentTarget/);assert.match(dialog,/event\.currentTarget\.disabled = true/);assert.doesNotMatch(dialog,/fetch\(|api\(|post\(/);
  assert.match(preview,/contract_version: "AWARD_PO_CONFIRMATION_V2"/);assert.match(preview,/mapping_qualification: mappingQualification/);assert.match(preview,/expected_mapping_qualification_digest: mappingQualification\.qualification_digest/);assert.match(preview,/const poConvertibleNow = mappingQualification\.all_qualified/);assert.match(preview,/po_convertible_now: poConvertibleNow/);assert.match(preview,/purchase_order_aggregate_count: groups\.size/);assert.match(preview,/delivery_plan_aggregate_count: lines\.length/);assert.match(preview,/delivery_plan_line_count: 0/);
  assert.doesNotMatch(dialog,/slice\(0,\s*2\)/);assert.match(dialog,/BigInt/);assert.match(dialog,/micros \+ 5_000n/);
});
test("native pages exist and the dashboard links distinguish pending and generated AP",async()=>{for(const path of ["../app/procurement/fulfillment/page.tsx","../app/warehouse/receiving/page.tsx","../app/finance/payables/page.tsx"])assert.match(await read(path),/Workspace/);const dashboard=await read("../app/lib/dashboard-selfhost/service.ts");assert.match(dashboard,/已收货待生成应付/);assert.match(dashboard,/已生成采购应付/);assert.match(dashboard,/\/finance\/payables/)});

test("PO history is a generic read-only responsive component with no downstream controls",async()=>{
  const workspace=await read("../app/procurement/fulfillment/purchase-order-history-workspace.tsx");
  const css=await read("../app/procurement/fulfillment/purchase-order-history.css");
  const model=await read("../app/lib/procurement-fulfillment-selfhost/purchase-order-history.ts");
  const page=await read("../app/procurement/fulfillment/purchase-orders/[purchaseOrderId]/page.tsx");
  const list=await read("../app/procurement/fulfillment/procurement-fulfillment-workspace.tsx");
  assert.match(page,/purchaseOrderId/);assert.match(list,/purchase-orders\/\$\{row\.purchase_order_id\}/);
  assert.match(workspace,/PO_HISTORY_TRACEABILITY_V1/);assert.match(workspace,/cache: "no-store"/);
  for(const text of ["PO聚合摘要","完整上游谱系","PO Line稳定谱系","Delivery Plan与queue","Event、Audit与幂等凭证","历史失败请求","下游零写入状态","PO OPEN不等于已到货","Delivery Plan PENDING不等于已收货","queue OPEN_PENDING","本页面不自动执行任何下游动作","模型没有独立Delivery Plan Line","无通用system.audit.read","实际存储备注"])assert.match(workspace+model,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
  for(const field of ["purchase_order_line_id","award_line_id","candidate_id","quote_line_id","binding_id","mapping_fact_id","mapping_uuid","mapping_version","mapping_row_cas","delivery_plan_id","plan_event_id","queue_id","queue_status","queue_version","comparison_output_digest","persisted_award_digest","derived_award_decision_digest","key_digest","request_digest"])assert.match(workspace,new RegExp(`\\b${field}\\b`),field);
  assert.match(workspace,/po-history-mobile-card/);assert.match(css,/@media \(max-width: 600px\)/);assert.match(css,/\.po-history-desktop-table \{ display: none; \}/);assert.match(css,/overflow-x: hidden/);assert.match(css,/overflow-wrap: anywhere/);
  assert.doesNotMatch(workspace,/method:\s*["']POST|protectedWrite|Idempotency-Key|<form|type=["']submit|到货按钮|收货按钮|IQC按钮|AP按钮/);
  assert.doesNotMatch(workspace,/PO-00000001|D-105|已获事前授权|合规转换|补办授权|授权已验证/);
});
