import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { InventoryService } from "../app/lib/inventory-selfhost/service.ts";
import { PostgresInventoryRepository } from "../app/lib/inventory-selfhost/repository.ts";
import { ProductionError } from "../app/lib/production-selfhost/errors.ts";
import { handleProductionApi } from "../app/lib/production-selfhost/handler.ts";
import { ProductionRepository } from "../app/lib/production-selfhost/repository.ts";
import { ProductionService } from "../app/lib/production-selfhost/service.ts";
import { SalesRepository } from "../app/lib/sales-selfhost/repository.ts";
import { SalesService } from "../app/lib/sales-selfhost/service.ts";

const databaseUrl=process.env.TEST_PRODUCTION_DATABASE_URL;
if(!databaseUrl||!/production_test/i.test(databaseUrl))throw new Error("isolated TEST_PRODUCTION_DATABASE_URL containing production_test is required");
const pool=new Pool({connectionString:databaseUrl,max:20,application_name:"production-completion-integration-test"});
const actor=(role,username=`${role}01`)=>({username,display_name:role,role,is_active:true,must_change_password:false,version:1,last_login_at:null,permissions:permissionsForRole(role)});
async function api(path,{method="GET",role="admin",username,body,key=randomUUID(),csrf=true}={}){const headers=new Headers({"X-Request-ID":randomUUID()});if(body!==undefined)headers.set("Content-Type","application/json");if(key)headers.set("Idempotency-Key",key);if(csrf)headers.set("X-CSRF-Token","test-csrf");const request=new Request(`http://local.test${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const result=await handleProductionApi(request,{pool,actor:actor(role,username),requestId:headers.get("X-Request-ID"),requireCsrf:()=>{if(headers.get("X-CSRF-Token")!=="test-csrf")throw new ProductionError("CSRF_INVALID","CSRF Token 无效",403);}});assert.ok(result);return{response:result,payload:await result.json()};}
const meta=(role,action,marker=randomUUID())=>({actor:actor(role),requestId:randomUUID(),operationId:randomUUID(),keyDigest:Buffer.from(`task07-${marker}`).toString("hex").padEnd(64,"0").slice(0,64),requestDigest:Buffer.from(`body-${marker}`).toString("hex").padEnd(64,"0").slice(0,64),method:"POST",route:"/test/task07",action});

async function seed(){
  await pool.query(`insert into app_users(username,display_name,role,password_hash) values ('admin01','admin','admin','test-only'),('manager01','manager','manager','test-only'),('production01','production','production','test-only'),('production02','production2','production','test-only'),('warehouse01','warehouse','warehouse','test-only'),('quality01','quality','quality','test-only'),('planning01','planning','planning','test-only'),('purchase01','purchase','purchase','test-only'),('finance01','finance','finance','test-only'),('sales01','sales','sales','test-only')`);
  const category=await pool.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values('TASK07','TASK07',4,'ACTIVE','admin01','admin01',$1) returning id",[randomUUID()]);const unit=await pool.query("insert into units(code,name,symbol,unit_type,enabled) values('T7PCS','件','T7PCS','COUNT',true) returning id");
  const materials=await pool.query(`insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values ('CYD-T7-RAW','TASK07原料',$1,'T7PCS',$2,'ACTIVE','PURCHASE','STOCKED','IQC','ROHS','MANUAL','admin01','admin01','admin01',$3),('CYD-T7-FG','TASK07成品',$1,'T7PCS',$2,'ACTIVE','MAKE','STOCKED','FQC','ROHS','MANUAL','admin01','admin01','admin01',$4) returning id,internal_material_code`,[category.rows[0].id,unit.rows[0].id,randomUUID(),randomUUID()]);const raw=materials.rows.find(row=>row.internal_material_code==='CYD-T7-RAW'),finished=materials.rows.find(row=>row.internal_material_code==='CYD-T7-FG');
  const customer=await pool.query("insert into customers(customer_code,customer_name,normalized_name,created_by,updated_by,request_id) values('T7-C','TASK07客户','TASK07客户','admin01','admin01',$1) returning id",[randomUUID()]);const product=await pool.query("insert into products(product_code,product_name,customer_id,created_by,updated_by,request_id) values('T7-P','TASK07产品',$1,'admin01','admin01',$2) returning id",[customer.rows[0].id,randomUUID()]);const pv=await pool.query("insert into product_versions(product_id,version_no,version_code,status,product_type,lifecycle_status,released_by,released_at,created_by,updated_by,request_id) values($1,1,'A0','RELEASED','PCB','MASS','admin01',now(),'admin01','admin01',$2) returning id",[product.rows[0].id,randomUUID()]);const bh=await pool.query("insert into bom_headers(bom_code,product_id,created_by,updated_by,request_id) values('T7-BOM',$1,'admin01','admin01',$2) returning id",[product.rows[0].id,randomUUID()]);const bv=await pool.query("insert into bom_versions(bom_header_id,product_version_id,version_no,version_code,status,created_by,updated_by,request_id) values($1,$2,1,'A0','DRAFT','admin01','admin01',$3) returning id",[bh.rows[0].id,pv.rows[0].id,randomUUID()]);await pool.query("insert into bom_lines(bom_version_id,line_no,material_id,quantity_per,unit_id,loss_rate,process_stage,created_by,updated_by,request_id) values($1,1,$2,1,$3,0,'ASSEMBLY','admin01','admin01',$4)",[bv.rows[0].id,raw.id,unit.rows[0].id,randomUUID()]);await pool.query("update bom_versions set status='RELEASED',released_by='admin01',released_at=now() where id=$1",[bv.rows[0].id]);
  const inventory=new InventoryService(new PostgresInventoryRepository(pool));await inventory.post(meta("admin","TASK07_STOCK_SEED"),{operation_type:"RECEIPT",reason:"TASK07隔离原料",lines:[{material_id:Number(raw.id),unit_id:Number(unit.rows[0].id),quantity:"10",expected_balance_version:0}]});
  return{rawId:Number(raw.id),finishedId:Number(finished.id),unitId:Number(unit.rows[0].id),customerId:Number(customer.rows[0].id),productId:Number(product.rows[0].id),productVersionId:Number(pv.rows[0].id),bomVersionId:Number(bv.rows[0].id)};
}
async function createReleased(refs,planned="10"){const created=await api("/api/work-orders",{method:"POST",role:"production",body:{product_id:refs.productId,product_version_id:refs.productVersionId,bom_version_id:refs.bomVersionId,finished_material_id:refs.finishedId,finished_unit_id:refs.unitId,planned_qty:planned,owner:"TASK07"}});assert.equal(created.response.status,201);const workOrderId=Number(created.payload.data.id);assert.equal((await api(`/api/work-orders/${workOrderId}/release`,{method:"POST",role:"production",body:{expected_version:1}})).response.status,200);return workOrderId;}
async function issueAll(workOrderId){const rows=(await api(`/api/production/material-requirements?work_order_id=${workOrderId}`)).payload.rows;const issued=await api("/api/production/material-issues",{method:"POST",role:"warehouse",body:{work_order_id:workOrderId,reason:"完整领料",lines:rows.map(row=>({requirement_id:Number(row.id),quantity:row.required_qty,expected_requirement_version:Number(row.version),expected_balance_version:Number(row.balance_version)}))}});assert.equal(issued.response.status,201);return rows;}
async function report(workOrderId,expectedVersion,reported,good=reported,scrap="0",key=randomUUID()){return api("/api/production/reports",{method:"POST",role:"production",key,body:{work_order_id:workOrderId,expected_version:expectedVersion,reported_qty:reported,good_qty:good,scrap_qty:scrap,process_stage:"ASSEMBLY",operator:"production01"}});}
async function complete(workOrderId,expectedVersion,balanceVersion,reportId,quantity,reportVersion=1,key=randomUUID()){return api("/api/production/completions",{method:"POST",role:"warehouse",key,body:{work_order_id:workOrderId,expected_version:expectedVersion,expected_balance_version:balanceVersion,reason:"TASK07成品入库",allocations:[{report_id:reportId,quantity,expected_report_version:reportVersion}]}});}

test.beforeEach(async()=>{await pool.query("truncate app_users,material_categories,units,customers,idempotency_keys,audit_log,business_code_sequences,identity_write_rate_limit_buckets restart identity cascade");});
test.after(async()=>pool.end());

test("two reports 4/6 hand off to two finished-goods receipts 4/6 without quality, shipment or finance side effects",async()=>{
  const refs=await seed(),workOrderId=await createReleased(refs);await issueAll(workOrderId);
  const reportBody={work_order_id:workOrderId,expected_version:3,reported_qty:"4",good_qty:"4",scrap_qty:"0",process_stage:"ASSEMBLY",operator:"production01"};const first=await api("/api/production/reports",{method:"POST",role:"production",key:"task07-report-first",body:reportBody});assert.equal(first.response.status,201);const replay=await api("/api/production/reports",{method:"POST",role:"production",key:"task07-report-first",body:reportBody});assert.equal(replay.response.headers.get("Idempotency-Replayed"),"true");const changed=await api("/api/production/reports",{method:"POST",role:"production",key:"task07-report-first",body:{...reportBody,remark:"异正文"}});assert.equal(changed.payload.code,"IDEMPOTENCY_CONFLICT");
  const firstCompletion=await complete(workOrderId,4,0,Number(first.payload.data.id),"4",1,"task07-completion-first");assert.equal(firstCompletion.response.status,201);assert.equal(firstCompletion.payload.data.work_order.status,"IN_PROGRESS");
  const second=await report(workOrderId,5,"6");assert.equal(second.response.status,201);const secondCompletion=await complete(workOrderId,6,1,Number(second.payload.data.id),"6");assert.equal(secondCompletion.response.status,201);assert.equal(secondCompletion.payload.data.work_order.status,"COMPLETED");
  const wo=(await pool.query("select planned_qty,reported_qty,good_qty,scrap_qty,completed_qty,status,version from production_work_orders where id=$1",[workOrderId])).rows[0];assert.deepEqual(wo,{planned_qty:"10.000000",reported_qty:"10.000000",good_qty:"10.000000",scrap_qty:"0.000000",completed_qty:"10.000000",status:"COMPLETED",version:7});const reports=await pool.query("select r.reported_qty,r.good_qty,p.allocated_good_qty,p.version,p.reversed from production_reports r join production_report_receipt_projections p on p.report_id=r.id order by r.id");assert.deepEqual(reports.rows,[{reported_qty:"4.000000",good_qty:"4.000000",allocated_good_qty:"4.000000",version:2,reversed:false},{reported_qty:"6.000000",good_qty:"6.000000",allocated_good_qty:"6.000000",version:2,reversed:false}]);assert.deepEqual((await pool.query("select quantity from production_completion_report_allocations order by id")).rows.map(row=>row.quantity),["4.000000","6.000000"]);assert.deepEqual((await pool.query("select l.on_hand_delta from inventory_ledger_entries l join production_completion_lines c on c.inventory_ledger_entry_id=l.id order by c.id")).rows.map(row=>row.on_hand_delta),["4.000000","6.000000"]);assert.deepEqual((await pool.query("select on_hand_qty,version from inventory_stock_balances where material_id=$1",[refs.finishedId])).rows[0],{on_hand_qty:"10.000000",version:2});
  for(const table of ["quality_inspections","sales_shipments","sales_financial_source_entries"])assert.equal(Number((await pool.query(`select count(*) count from ${table}`)).rows[0].count),0,table);assert.equal(Number((await pool.query("select count(*) count from finance_documents where doc_type='AR'")).rows[0].count),0);assert.equal(Number((await pool.query("select count(*) count from production_work_order_status_events where to_status='CLOSED'")).rows[0].count),0);assert.equal((await pool.query("select count(*)::int count from audit_log where route_code='PRODUCTION'")).rows[0].count,8);
});

test("issued support, conservation, report capacity, work-order capacity, CAS, concurrency, roles and scrap all fail closed",async()=>{
  const refs=await seed(),workOrderId=await createReleased(refs);let result=await report(workOrderId,2,"1");assert.equal(result.payload.code,"PRODUCTION_REPORT_QUANTITY_CONFLICT");await issueAll(workOrderId);result=await report(workOrderId,3,"2","2","1");assert.equal(result.payload.code,"PRODUCTION_REPORT_QUANTITY_CONFLICT");const scrap=await report(workOrderId,3,"2","1","1");assert.equal(scrap.response.status,201);assert.equal((await pool.query("select count(*)::int count from inventory_stock_balances where material_id=$1",[refs.finishedId])).rows[0].count,0);const tooMuch=await complete(workOrderId,4,0,Number(scrap.payload.data.id),"2");assert.equal(tooMuch.payload.code,"PRODUCTION_REPORT_GOOD_EXHAUSTED");const stale=await complete(workOrderId,999,0,Number(scrap.payload.data.id),"1");assert.equal(stale.payload.code,"WORK_ORDER_VERSION_CONFLICT");const unauthorized=await api("/api/production/completions",{method:"POST",role:"finance",body:{work_order_id:workOrderId,expected_version:4,expected_balance_version:0,allocations:[{report_id:Number(scrap.payload.data.id),quantity:"1",expected_report_version:1}]}});assert.equal(unauthorized.response.status,403);
  const concurrent=await Promise.all(["a","b"].map(key=>complete(workOrderId,4,0,Number(scrap.payload.data.id),"1",1,`task07-race-${key}`)));assert.deepEqual(concurrent.map(item=>item.response.status).sort(),[201,409]);assert.equal((await pool.query("select on_hand_qty from inventory_stock_balances where material_id=$1",[refs.finishedId])).rows[0].on_hand_qty,"1.000000");
  const client=await pool.connect();try{await client.query("begin");await client.query("select set_config('cyd.production_service_write','allowed',true)");const legacy=await client.query("insert into production_reports(report_code,work_order_id,reported_qty,good_qty,scrap_qty,process_stage,operator_name,operation_id,created_by,request_id) values('WR-LEGACY-OVER',$1,10,10,0,'LEGACY','production01',$2,'production01',$3) returning id",[workOrderId,randomUUID(),randomUUID()]);await client.query("insert into production_report_receipt_projections(report_id) values($1)",[legacy.rows[0].id]);await client.query("commit");const overPlan=await complete(workOrderId,5,1,Number(legacy.rows[0].id),"11");assert.equal(overPlan.payload.code,"PRODUCTION_REPORT_GOOD_EXHAUSTED");const overRemaining=await complete(workOrderId,5,1,Number(legacy.rows[0].id),"10");assert.equal(overRemaining.payload.code,"PRODUCTION_OVER_COMPLETION");}catch(error){await client.query("rollback").catch(()=>undefined);throw error;}finally{client.release();}
});

test("append-only reversals restore projections and inventory, block downstream quality or shipment, and roll back injected faults",async()=>{
  const refs=await seed(),workOrderId=await createReleased(refs,"4");await issueAll(workOrderId);const reported=await report(workOrderId,3,"4");const completion=await complete(workOrderId,4,0,Number(reported.payload.data.id),"4");assert.equal(completion.response.status,201);const completionId=Number(completion.payload.data.id);
  const reversal=await api(`/api/production/completions/${completionId}/reverse`,{method:"POST",role:"warehouse",body:{expected_completion_version:1,expected_work_order_version:5,reason:"安全完工冲销",expected_balance_versions:[{material_id:refs.finishedId,expected_balance_version:1}]}});assert.equal(reversal.response.status,201);assert.deepEqual((await pool.query("select on_hand_qty,version from inventory_stock_balances where material_id=$1",[refs.finishedId])).rows[0],{on_hand_qty:"0.000000",version:2});assert.deepEqual((await pool.query("select allocated_good_qty,version,reversed from production_report_receipt_projections where report_id=$1",[reported.payload.data.id])).rows[0],{allocated_good_qty:"0.000000",version:3,reversed:false});assert.equal((await pool.query("select completed_qty,status from production_work_orders where id=$1",[workOrderId])).rows[0].completed_qty,"0.000000");
  const reportReversal=await api(`/api/production/reports/${reported.payload.data.id}/reverse`,{method:"POST",role:"production",body:{expected_report_version:3,expected_work_order_version:6,reason:"安全报工冲销"}});assert.equal(reportReversal.response.status,201);assert.deepEqual((await pool.query("select reported_qty,good_qty,scrap_qty,completed_qty,status from production_work_orders where id=$1",[workOrderId])).rows[0],{reported_qty:"0.000000",good_qty:"0.000000",scrap_qty:"0.000000",completed_qty:"0.000000",status:"RELEASED"});assert.equal(Number((await pool.query("select count(*) count from production_reports where id=$1",[reported.payload.data.id])).rows[0].count),1);
  const ipqcSource=await report(workOrderId,7,"1");assert.equal(ipqcSource.response.status,201);const qualityClient=await pool.connect();try{await qualityClient.query("begin");await qualityClient.query("select set_config('cyd.quality_service_write','allowed',true)");await qualityClient.query("insert into quality_inspections(inspection_code,inspection_type,production_report_id,material_id,unit_id,inspected_qty,passed_qty,failed_qty,operation_id,created_by,request_id) values('IPQC-T7-GATE','IPQC',$1,$2,$3,1,1,0,$4,'quality01',$5)",[ipqcSource.payload.data.id,refs.finishedId,refs.unitId,randomUUID(),randomUUID()]);await qualityClient.query("commit");}catch(error){await qualityClient.query("rollback").catch(()=>undefined);throw error;}finally{qualityClient.release();}const wrongOwner=await api(`/api/production/reports/${ipqcSource.payload.data.id}/reverse`,{method:"POST",role:"production",username:"production02",body:{expected_report_version:1,expected_work_order_version:9,reason:"非本人冲销"}});assert.equal(wrongOwner.response.status,403);const ipqcBlocked=await api(`/api/production/reports/${ipqcSource.payload.data.id}/reverse`,{method:"POST",role:"production",body:{expected_report_version:1,expected_work_order_version:9,reason:"已有IPQC"}});assert.equal(ipqcBlocked.payload.code,"PRODUCTION_REPORT_DOWNSTREAM_EXISTS");
  const gatedWorkOrder=await createReleased(refs,"4");await issueAll(gatedWorkOrder);const gatedReport=await report(gatedWorkOrder,3,"4");const gatedCompletion=await complete(gatedWorkOrder,4,2,Number(gatedReport.payload.data.id),"4");const lineId=Number(gatedCompletion.payload.data.lines[0].id);const client=await pool.connect();try{await client.query("begin");await client.query("select set_config('cyd.quality_service_write','allowed',true),set_config('cyd.sales_service_write','allowed',true)");const order=await client.query("insert into sales_orders(sales_order_code,customer_id,ordered_qty,operation_id,created_by,request_id) values('SO-T7-GATE',$1,4,$2,'admin01',$3) returning id",[refs.customerId,randomUUID(),randomUUID()]);const ov=await client.query("insert into sales_order_versions(sales_order_id,version_no,total_amount,created_by,request_id) values($1,1,4,'admin01',$2) returning id",[order.rows[0].id,randomUUID()]);const ol=await client.query("insert into sales_order_lines(sales_order_version_id,line_no,product_id,product_version_id,finished_material_id,unit_id,ordered_qty,unit_price,line_amount) values($1,1,$2,$3,$4,$5,4,1,4) returning id",[ov.rows[0].id,refs.productId,refs.productVersionId,refs.finishedId,refs.unitId]);await client.query("insert into quality_inspections(inspection_code,inspection_type,production_completion_line_id,sales_order_line_id,material_id,unit_id,inspected_qty,passed_qty,failed_qty,lifecycle_status,decision_status,released_qty,operation_id,created_by,request_id) values('FQC-T7-GATE','FQC',$1,$2,$3,$4,4,4,0,'CLOSED','RELEASED',4,$5,'quality01',$6)",[lineId,ol.rows[0].id,refs.finishedId,refs.unitId,randomUUID(),randomUUID()]);await client.query("commit");const sales=new SalesService(new SalesRepository(pool));const shipped=await sales.createShipment(meta("warehouse","TASK07_DOWNSTREAM_SHIPMENT"),{sales_order_id:Number(order.rows[0].id),expected_order_version:1,reason:"下游门禁",lines:[{sales_order_line_id:Number(ol.rows[0].id),quantity:"1",expected_line_version:1,expected_balance_version:3}]});assert.equal(shipped.status,201);}catch(error){await client.query("rollback").catch(()=>undefined);throw error;}finally{client.release();}
  const blocked=await api(`/api/production/completions/${gatedCompletion.payload.data.id}/reverse`,{method:"POST",role:"warehouse",body:{expected_completion_version:1,expected_work_order_version:5,reason:"应被下游阻止",expected_balance_versions:[{material_id:refs.finishedId,expected_balance_version:4}]}});assert.equal(blocked.payload.code,"PRODUCTION_COMPLETION_DOWNSTREAM_EXISTS");assert.equal(Number((await pool.query("select count(*) count from sales_shipments where shipment_type='SHIPMENT'")).rows[0].count),1);
  const faultWorkOrder=await createReleased(refs,"1");await issueAll(faultWorkOrder);const faultReport=await report(faultWorkOrder,3,"1");const balance=(await pool.query("select version from inventory_stock_balances where material_id=$1",[refs.finishedId])).rows[0];const faultCompletion=await complete(faultWorkOrder,4,Number(balance.version),Number(faultReport.payload.data.id),"1");const faultMeta=meta("warehouse","PRODUCTION_COMPLETION_REVERSED","fault-reversal");const service=new ProductionService(new ProductionRepository(pool),undefined,checkpoint=>{if(checkpoint==="after_completion_reversal_inventory")throw new Error("forced reversal rollback");});const currentBalance=(await pool.query("select on_hand_qty,version from inventory_stock_balances where material_id=$1",[refs.finishedId])).rows[0];await assert.rejects(service.reverseCompletion(Number(faultCompletion.payload.data.id),faultMeta,{expected_completion_version:1,expected_work_order_version:5,reason:"故障冲销",expected_balance_versions:[{material_id:refs.finishedId,expected_balance_version:Number(currentBalance.version)}]}),/服务器暂时无法处理生产请求/);assert.deepEqual((await pool.query("select on_hand_qty,version from inventory_stock_balances where material_id=$1",[refs.finishedId])).rows[0],currentBalance);assert.equal(Number((await pool.query("select count(*) count from production_completion_reversals where completion_id=$1",[faultCompletion.payload.data.id])).rows[0].count),0);assert.equal(Number((await pool.query("select count(*) count from idempotency_keys where key_digest=$1",[faultMeta.keyDigest])).rows[0].count),0);
});
