import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=path=>readFile(new URL(path,import.meta.url),"utf8");

test("rework execution reuses operation and quality authorities with explicit quantities",async()=>{const[source,projection,quality]=await Promise.all([read("../app/lib/production-operation-selfhost/service.ts"),read("../app/lib/production-rework-execution-selfhost/projections.ts"),read("../app/lib/quality-selfhost/service.ts")]);for(const token of ["dispatchRework","run_kind","REWORK","production_operation_runs","production_operation_run_reports","production_rework_run_allocations","expected_execution_version","REWORK_DISPATCH_OVER_ACCEPTED","OPERATION_OPERATOR_INELIGIBLE","after_rework_dispatch_facts"])assert.match(source,new RegExp(token));for(const token of ["rework_waiting_dispatch_qty","rework_dispatched_qty","rework_in_progress_qty","rework_reported_good_qty","rework_reported_scrap_qty","rework_pending_reinspection_qty","rework_released_qty","rework_completed_qty","unresolved_rework_qty","WAITING_REINSPECTION","COMPLETED_WITH_SCRAP"])assert.match(projection,new RegExp(token));assert.match(quality,/refreshReworkExecution/);});

test("normal projection excludes repeat-processing while released quality includes rework",async()=>{const source=await read("../app/lib/production-operation-selfhost/projections.ts");assert.match(source,/run_kind='NORMAL'/);assert.match(source,/const allGood/);assert.match(source,/qualityRequired = .*allGood/);assert.match(source,/outputCapacity = .*qualityReleased.*allGood/);});

test("handlers enforce permissions, server ownership and persistent write controls",async()=>{const[handler,productionRepo,qualityRepo,permissions]=await Promise.all([read("../app/lib/production-operation-selfhost/handler.ts"),read("../app/lib/production-selfhost/repository.ts"),read("../app/lib/quality-selfhost/repository.ts"),read("../app/lib/identity-selfhost/permissions.ts")]);for(const token of ["rework-requests","dispatch","production.dispatch","production.execute","production.operation.reverse","Idempotency-Key","64 * 1024","requireCsrf"])assert.match(handler,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const repo of [productionRepo,qualityRepo])for(const token of ["idempotency_keys","audit_log","pg_advisory_xact_lock","rework_execution_service_write"])assert.match(repo,new RegExp(token));assert.match(permissions,/production\.operation\.reverse/);});
