import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { handleMaterialRequirementApi } from "../app/lib/material-requirement-selfhost/handler.ts";
import { MaterialRequirementRepository } from "../app/lib/material-requirement-selfhost/repository.ts";
import { MaterialRequirementService } from "../app/lib/material-requirement-selfhost/service.ts";

const databaseUrl=process.env.TEST_MATERIAL_REQUIREMENT_DATABASE_URL;if(!databaseUrl||!/material_requirement_test/i.test(databaseUrl))throw new Error("isolated TEST_MATERIAL_REQUIREMENT_DATABASE_URL containing material_requirement_test is required");
const pool=new Pool({connectionString:databaseUrl,max:20,application_name:"material-requirement-integration-test"});const actor=(role,username=`${role}01`)=>({username,display_name:role,role,is_active:true,must_change_password:false,version:1,last_login_at:null,permissions:permissionsForRole(role)});
async function api(path,{method="GET",role="planning",username,body,key=randomUUID(),csrf=true}={}){const requestId=randomUUID(),headers=new Headers({"X-Request-ID":requestId});if(body!==undefined)headers.set("Content-Type","application/json");if(key)headers.set("Idempotency-Key",key);if(csrf)headers.set("X-CSRF-Token","test-csrf");const request=new Request(`http://local.test${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const result=await handleMaterialRequirementApi(request,{pool,actor:actor(role,username),requestId,requireCsrf:()=>{if(headers.get("X-CSRF-Token")!=="test-csrf")throw Object.assign(new Error("CSRF Token 无效"),{code:"CSRF_INVALID",status:403})}});assert.ok(result);return{response:result,payload:await result.json()}}

async function seed(){
 const client=await pool.connect();try{await client.query("begin");await client.query("select set_config('cyd.project_service_write','allowed',true),set_config('cyd.planning_service_write','allowed',true),set_config('cyd.inventory_service_write','allowed',true),set_config('cyd.procurement_service_write','allowed',true)");
  await client.query(`insert into app_users(username,display_name,role,password_hash) values ('admin01','管理员','admin','test'),('manager01','经理','manager','test'),('engineering01','项目','engineering','test'),('planning01','计划','planning','test'),('planning02','计划乙','planning','test'),('purchase01','采购','purchase','test'),('production01','生产','production','test')`);
  const unit=await client.query("insert into units(code,name,symbol,unit_type,enabled) values('PCS','件','PCS','COUNT',true) returning id"),unitId=Number(unit.rows[0].id);const category=await client.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values('MRP-COMP','计划零件',1,'ACTIVE','admin01','admin01',$1) returning id",[randomUUID()]);
  async function material(code,name){return Number((await client.query("insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values($1,$2,$3,'PCS',$4,'ACTIVE','PURCHASED','STOCK','IQC','RoHS','MANUAL','admin01','admin01','admin01',$5) returning id",[code,name,category.rows[0].id,unitId,randomUUID()])).rows[0].id)}
  const materialId=await material("MAT-MRP-001","聚合连接器"),zeroMaterialId=await material("MAT-MRP-002","库存充足件");const customer=await client.query("insert into customers(customer_code,customer_name,normalized_name,status,created_by,updated_by,request_id) values('CUS-MRP','需求客户','需求客户','ACTIVE','admin01','admin01',$1) returning id",[randomUUID()]);
  const product=await client.query("insert into products(product_code,product_name,customer_id,status,created_by,updated_by,request_id) values('PROD-MRP','需求产品',$1,'ACTIVE','engineering01','engineering01',$2) returning id",[customer.rows[0].id,randomUUID()]);const pv=await client.query("insert into product_versions(product_id,version_no,version_code,status,product_type,lifecycle_status,engineering_owner,released_by,released_at,created_by,updated_by,request_id) values($1,1,'V1','RELEASED','ASSEMBLY','ACTIVE','engineering01','engineering01',now(),'engineering01','engineering01',$2) returning id",[product.rows[0].id,randomUUID()]);const bh=await client.query("insert into bom_headers(bom_code,product_id,status,created_by,updated_by,request_id) values('BOM-MRP',$1,'ACTIVE','engineering01','engineering01',$2) returning id",[product.rows[0].id,randomUUID()]);const bv=await client.query("insert into bom_versions(bom_header_id,product_version_id,version_no,version_code,status,created_by,updated_by,request_id) values($1,$2,1,'V1','DRAFT','engineering01','engineering01',$3) returning id",[bh.rows[0].id,pv.rows[0].id,randomUUID()]);
  const bom1=await client.query("insert into bom_lines(bom_version_id,line_no,material_id,quantity_per,unit_id,loss_rate,created_by,updated_by,request_id) values($1,1,$2,1,$3,0,'engineering01','engineering01',$4) returning id",[bv.rows[0].id,materialId,unitId,randomUUID()]);const bom2=await client.query("insert into bom_lines(bom_version_id,line_no,material_id,quantity_per,unit_id,loss_rate,created_by,updated_by,request_id) values($1,2,$2,1,$3,0,'engineering01','engineering01',$4) returning id",[bv.rows[0].id,zeroMaterialId,unitId,randomUUID()]);await client.query("update bom_versions set status='RELEASED',released_by='engineering01',released_at=now() where id=$1",[bv.rows[0].id]);
  let sequence=0;async function acceptedPackage(code,grosses,sourceBomId,targetMaterialId){sequence++;const project=await client.query("insert into business_projects(project_code,customer_id,project_name,project_goal,market_owner,project_owner,status,target_delivery_date,current_requirement_version_no,version,request_id,created_by) values($1,$2,$3,'物料需求闭环','admin01','engineering01','ACCEPTED','2026-10-01',1,4,$4,'admin01') returning id",[code,customer.rows[0].id,`项目 ${code}`,randomUUID()]);const rv=await client.query("insert into project_requirement_versions(project_id,version_no,customer_requirement_summary,quantity_requirement,quantity_unit,content_digest,created_by) values($1,1,'固化需求',100,'PCS',$2,'admin01') returning id",[project.rows[0].id,String(sequence).padStart(64,"a").slice(-64)]);const packageRow=await client.query("insert into project_planning_packages(project_id,package_version_no,requirement_version_id,status,target_delivery_date,package_digest,prepared_by,submitted_by,submitted_at,accepted_by,accepted_at,version,request_id) values($1,1,$2,'ACCEPTED','2026-10-01',$3,'engineering01','engineering01',now(),'planning01',now(),3,$4) returning id",[project.rows[0].id,rv.rows[0].id,String(sequence).padStart(64,"b").slice(-64),randomUUID()]);let line=0;for(const gross of grosses){line++;const item=await client.query("insert into project_requirement_items(requirement_version_id,line_no,provisional_name,quantity,unit_id,unit_pending) values($1,$2,$3,$4,$5,false) returning id",[rv.rows[0].id,line,`需求 ${line}`,gross,unitId]);const pi=await client.query("insert into project_planning_package_items(package_id,requirement_item_id,product_version_id,bom_version_id,required_quantity,unit_id,line_no,source_digest) values($1,$2,$3,$4,$5,$6,$7,$8) returning id",[packageRow.rows[0].id,item.rows[0].id,pv.rows[0].id,bv.rows[0].id,gross,unitId,line,String(line).padStart(64,"c").slice(-64)]);const snapshot={internal_material_code:targetMaterialId===materialId?"MAT-MRP-001":"MAT-MRP-002",standard_name:targetMaterialId===materialId?"聚合连接器":"库存充足件"};await client.query("insert into project_planning_package_bom_lines(package_item_id,source_bom_line_id,material_id,unit_id,quantity_per,loss_rate,calculated_gross_quantity,specification_snapshot,material_digest,line_no) values($1,$2,$3,$4,1,0,$5,$6,$7,1)",[pi.rows[0].id,sourceBomId,targetMaterialId,unitId,gross,snapshot,String(targetMaterialId).padStart(64,"d").slice(-64)])}return Number(packageRow.rows[0].id)}
  const packageA=await acceptedPackage("PRJ-00000171",["40.000000","60.000000"],bom1.rows[0].id,materialId),packageB=await acceptedPackage("PRJ-00000172",["100.000000"],bom1.rows[0].id,materialId),packageZero=await acceptedPackage("PRJ-00000173",["10.000000"],bom2.rows[0].id,zeroMaterialId);
  await client.query("insert into inventory_stock_balances(material_id,unit_id,on_hand_qty,reserved_qty,frozen_qty,version) values($1,$2,70,10,5,1),($3,$2,20,0,0,1)",[materialId,unitId,zeroMaterialId]);const supplier=await client.query("insert into suppliers(supplier_code,supplier_name,normalized_name,status,created_by,updated_by,request_id) values('SUP-MRP','在途供应商','在途供应商','ACTIVE','admin01','admin01',$1) returning id",[randomUUID()]);const mapping=await client.query("insert into supplier_mappings(material_id,supplier_id,supplier_name,supplier_key,supplier_item_code,purchase_uom,purchase_unit_id,status,valid_from,created_by,updated_by,request_id) values($1,$2,'在途供应商','SUP-MRP','SUP-PART','PCS',$3,'ACTIVE',now(),'admin01','admin01',$4) returning id",[materialId,supplier.rows[0].id,unitId,randomUUID()]);const po=await client.query("insert into purchase_orders(po_code,supplier_id,status,currency_code,source_type,expected_at,operation_id,created_by,request_id) values('PO-MRP-INBOUND',$1,'OPEN','CNY','MANUAL','2026-09-01',$2,'purchase01',$3) returning id",[supplier.rows[0].id,randomUUID(),randomUUID()]);await client.query("insert into purchase_order_lines(purchase_order_id,line_no,material_id,unit_id,supplier_mapping_id,order_qty,unit_price,received_qty,status,version) values($1,1,$2,$3,$4,50,1,10,'PARTIALLY_RECEIVED',1)",[po.rows[0].id,materialId,unitId,mapping.rows[0].id]);await client.query("commit");return{packageA,packageB,packageZero,materialId}
 }catch(error){await client.query("rollback");throw error}finally{client.release()}}

test.beforeEach(async()=>{await pool.query("truncate app_users,units,material_categories,customers,suppliers,business_code_sequences,idempotency_keys,identity_write_rate_limit_buckets,audit_log restart identity cascade")});test.after(async()=>pool.end());

test("aggregate preview, locked submission, double-allocation prevention, return and revision form a closed loop",async()=>{
 const refs=await seed();const forbidden=await api(`/api/planning-packages/${refs.packageA}/material-requirement-plans`,{method:"POST",role:"purchase",username:"purchase01",body:{required_date:"2026-10-01"}});assert.equal(forbidden.response.status,403);
 const [previewA,previewB]=await Promise.all([refs.packageA,refs.packageB].map((id,index)=>api(`/api/planning-packages/${id}/material-requirement-plans`,{method:"POST",key:`preview-concurrent-${index}`,body:{required_date:"2026-10-01"}})));for(const preview of [previewA,previewB]){assert.equal(preview.response.status,201,JSON.stringify(preview.payload));assert.equal(preview.payload.lines.length,1);assert.deepEqual([preview.payload.lines[0].grossRequirement,preview.payload.lines[0].stockAvailable,preview.payload.lines[0].eligibleInbound,preview.payload.lines[0].stockAllocated,preview.payload.lines[0].inboundAllocated,preview.payload.lines[0].netPurchaseRequirement],["100.000000","55.000000","40.000000","55.000000","40.000000","5.000000"])}
 assert.equal(Number((await pool.query("select count(*) count from planning_material_allocations")).rows[0].count),0);const before=(await pool.query("select reserved_qty::text from inventory_stock_balances where material_id=$1",[refs.materialId])).rows[0].reserved_qty;
 const submissions=await Promise.all([previewA,previewB].map((preview,index)=>api(`/api/material-requirement-plans/${preview.payload.plan_id}/submit`,{method:"POST",key:`submit-concurrent-${index}`,body:{expected_version:1}})));assert.deepEqual(submissions.map(item=>item.response.status).sort(),[200,409]);const winner=submissions.find(item=>item.response.status===200),loser=submissions.find(item=>item.response.status===409);assert.equal(loser.payload.code,"MATERIAL_REQUIREMENT_RECALC_REQUIRED");assert.equal(winner.payload.purchase_required,true);assert.match(winner.payload.purchase_request.request_code,/^PRQ-\d{8}$/);
 assert.deepEqual((await pool.query("select allocation_type,quantity::text from planning_material_allocations order by allocation_type")).rows,[{allocation_type:"INBOUND",quantity:"40.000000"},{allocation_type:"STOCK",quantity:"55.000000"}]);assert.equal((await pool.query("select reserved_qty::text from inventory_stock_balances where material_id=$1",[refs.materialId])).rows[0].reserved_qty,before);assert.equal((await pool.query("select requested_quantity::text from planning_purchase_request_lines where purchase_request_id=$1",[winner.payload.purchase_request.id])).rows[0].requested_quantity,"5.000000");
 const planningDecision=await api(`/api/purchase-requests/${winner.payload.purchase_request.id}/accept`,{method:"POST",role:"planning",username:"planning01",body:{expected_version:1}});assert.equal(planningDecision.response.status,403);const returned=await api(`/api/purchase-requests/${winner.payload.purchase_request.id}/return`,{method:"POST",role:"purchase",username:"purchase01",body:{expected_version:1,reason:"需求日期与项目节奏需重新确认"}});assert.equal(returned.response.status,200);assert.equal(returned.payload.allocations_released,true);
 const winnerPackage=winner.payload.planning_package_id||Number((await pool.query("select planning_package_id from planning_material_requirement_plans where id=$1",[winner.payload.plan_id])).rows[0].planning_package_id);const revised=await api(`/api/planning-packages/${winnerPackage}/material-requirement-plans`,{method:"POST",body:{required_date:"2026-10-01"}});assert.equal(revised.response.status,201);assert.equal(Number(revised.payload.data.plan_version_no),2);
 const inventoryClient=await pool.connect();try{await inventoryClient.query("begin");await inventoryClient.query("select set_config('cyd.inventory_service_write','allowed',true)");await inventoryClient.query("update inventory_stock_balances set version=version+1 where material_id=$1",[refs.materialId]);await inventoryClient.query("commit")}catch(error){await inventoryClient.query("rollback");throw error}finally{inventoryClient.release()}const staleSubmit=await api(`/api/material-requirement-plans/${revised.payload.plan_id}/submit`,{method:"POST",body:{expected_version:1}});assert.equal(staleSubmit.response.status,409);assert.equal(staleSubmit.payload.code,"MATERIAL_REQUIREMENT_RECALC_REQUIRED");
 const regenerated=await api(`/api/planning-packages/${winnerPackage}/material-requirement-plans`,{method:"POST",body:{required_date:"2026-10-01"}});assert.equal(Number(regenerated.payload.data.plan_version_no),3);const resubmitted=await api(`/api/material-requirement-plans/${regenerated.payload.plan_id}/submit`,{method:"POST",body:{expected_version:1}});assert.equal(resubmitted.response.status,200);const accepted=await api(`/api/purchase-requests/${resubmitted.payload.purchase_request.id}/accept`,{method:"POST",role:"purchase",username:"purchase01",body:{expected_version:1}});assert.equal(accepted.response.status,200);assert.equal(Number((await pool.query("select count(*) count from purchase_orders")).rows[0].count),1);assert.equal(Number((await pool.query("select count(*) count from planning_purchase_requests")).rows[0].count),2);await assert.rejects(pool.query("delete from planning_material_allocations where plan_id=$1",[winner.payload.plan_id]),/service|immutable/i);
});

test("zero net requirement remains an immutable submitted plan without a fake request line",async()=>{
 const refs=await seed();const preview=await api(`/api/planning-packages/${refs.packageZero}/material-requirement-plans`,{method:"POST",body:{required_date:"2026-10-01"}});assert.equal(preview.payload.lines[0].netPurchaseRequirement,"0.000000");const submitted=await api(`/api/material-requirement-plans/${preview.payload.plan_id}/submit`,{method:"POST",body:{expected_version:1}});assert.equal(submitted.response.status,200);assert.equal(submitted.payload.purchase_required,false);assert.equal(submitted.payload.purchase_request,null);assert.equal(Number((await pool.query("select count(*) count from planning_purchase_requests where plan_id=$1",[preview.payload.plan_id])).rows[0].count),0);assert.equal((await pool.query("select status from planning_material_requirement_plans where id=$1",[preview.payload.plan_id])).rows[0].status,"SUBMITTED");
});

test("fault after preview insertion rolls back plan, lines, events, audit and idempotency",async()=>{
 const refs=await seed(),repository=new MaterialRequirementRepository(pool),service=new MaterialRequirementService(repository,checkpoint=>{if(checkpoint==="after_preview_saved")throw new Error("forced")});const keyDigest="f".repeat(64),requestId=randomUUID();const meta={actor:actor("planning","planning01"),requestId,operationId:randomUUID(),keyDigest,requestDigest:"e".repeat(64),method:"POST",route:`/api/planning-packages/${refs.packageA}/material-requirement-plans`,action:"MATERIAL_REQUIREMENT_GENERATED"};await assert.rejects(service.generate(refs.packageA,meta,{required_date:"2026-10-01"}),/服务器暂时无法处理物料需求计划/);assert.equal(Number((await pool.query("select count(*) count from planning_material_requirement_plans")).rows[0].count),0);assert.equal(Number((await pool.query("select count(*) count from idempotency_keys where key_digest=$1",[keyDigest])).rows[0].count),0);assert.equal(Number((await pool.query("select count(*) count from audit_log where request_id=$1",[requestId])).rows[0].count),0);
});
