import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { InventoryService } from "../app/lib/inventory-selfhost/service.ts";
import { PostgresInventoryRepository } from "../app/lib/inventory-selfhost/repository.ts";
import { handleProductionRoutingApi } from "../app/lib/production-routing-selfhost/handler.ts";
import { ProductionRoutingService } from "../app/lib/production-routing-selfhost/service.ts";
import { ProductionError } from "../app/lib/production-selfhost/errors.ts";
import { handleProductionApi } from "../app/lib/production-selfhost/handler.ts";
import { ProductionRepository } from "../app/lib/production-selfhost/repository.ts";
import { ProductionService } from "../app/lib/production-selfhost/service.ts";

const databaseUrl=process.env.TEST_PRODUCTION_ROUTING_DATABASE_URL;
if(!databaseUrl||!/production_routing_test/i.test(databaseUrl))throw new Error("isolated TEST_PRODUCTION_ROUTING_DATABASE_URL containing production_routing_test is required");
const pool=new Pool({connectionString:databaseUrl,max:20,application_name:"production-routing-integration-test"});
const actor=(role,username=`${role}01`)=>({username,display_name:role,role,is_active:true,must_change_password:false,version:1,last_login_at:null,permissions:permissionsForRole(role)});
const digest=value=>createHash("sha256").update(String(value)).digest("hex");
const meta=(role,action,key=randomUUID())=>({actor:actor(role),requestId:randomUUID(),operationId:randomUUID(),keyDigest:digest(`${action}:${key}`),requestDigest:digest(`body:${action}:${key}`),method:"POST",route:"/test/production-routing",action});
async function request(handler,path,{method="GET",role="admin",username,body,key=randomUUID(),csrf=true}={}){const headers=new Headers({"X-Request-ID":randomUUID()});if(body!==undefined)headers.set("Content-Type","application/json");if(key)headers.set("Idempotency-Key",key);if(csrf)headers.set("X-CSRF-Token","test-csrf");const response=await handler(new Request(`http://local.test${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),{pool,actor:actor(role,username),requestId:headers.get("X-Request-ID"),requireCsrf:()=>{if(headers.get("X-CSRF-Token")!=="test-csrf")throw new ProductionError("CSRF_INVALID","CSRF Token 无效",403);}});assert.ok(response);return{response,payload:await response.json()};}
const routing=(path,options)=>request(handleProductionRoutingApi,path,options),production=(path,options)=>request(handleProductionApi,path,options);

async function seed(){await pool.query(`insert into app_users(username,display_name,role,password_hash) values ('admin01','管理员','admin','x'),('operations01','运营','operations','x'),('engineering01','工程','engineering','x'),('manager01','经理','manager','x'),('production01','生产','production','x'),('planning01','计划','planning','x'),('warehouse01','仓库','warehouse','x'),('sales01','销售','sales','x')`);const category=(await pool.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values('T25-LEAF','TASK25',4,'ACTIVE','admin01','admin01',$1) returning id",[randomUUID()])).rows[0];const unit=(await pool.query("insert into units(code,name,symbol,unit_type,enabled) values('T25PCS','件','PCS','COUNT',true) returning id")).rows[0];const materials=(await pool.query(`insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values ('CYD-T25-RAW','TASK25 原料',$1,'T25PCS',$2,'ACTIVE','PURCHASE','STOCKED','NONE','ROHS','MANUAL','admin01','admin01','admin01',$3),('CYD-T25-FG1','TASK25 成品一',$1,'T25PCS',$2,'ACTIVE','MAKE','STOCKED','NONE','ROHS','MANUAL','admin01','admin01','admin01',$4),('CYD-T25-FG2','TASK25 成品二',$1,'T25PCS',$2,'ACTIVE','MAKE','STOCKED','NONE','ROHS','MANUAL','admin01','admin01','admin01',$5) returning id,internal_material_code`,[category.id,unit.id,randomUUID(),randomUUID(),randomUUID()])).rows;const raw=materials.find(x=>x.internal_material_code==='CYD-T25-RAW'),fg1=materials.find(x=>x.internal_material_code==='CYD-T25-FG1'),fg2=materials.find(x=>x.internal_material_code==='CYD-T25-FG2');const customer=(await pool.query("insert into customers(customer_code,customer_name,normalized_name,created_by,updated_by,request_id) values('CUS-T25','TASK25客户','TASK25客户','admin01','admin01',$1) returning id",[randomUUID()])).rows[0];
  async function product(code,name,fg){const p=(await pool.query("insert into products(product_code,product_name,customer_id,status,created_by,updated_by,request_id) values($1,$2,$3,'ACTIVE','admin01','admin01',$4) returning id",[code,name,customer.id,randomUUID()])).rows[0];const pv=(await pool.query("insert into product_versions(product_id,version_no,version_code,status,product_type,lifecycle_status,released_by,released_at,created_by,updated_by,request_id) values($1,1,'A0','RELEASED','PCB','MASS','admin01',now(),'admin01','admin01',$2) returning id",[p.id,randomUUID()])).rows[0];const bh=(await pool.query("insert into bom_headers(bom_code,product_id,status,created_by,updated_by,request_id) values($1,$2,'ACTIVE','admin01','admin01',$3) returning id",[`BOM-${code}`,p.id,randomUUID()])).rows[0];const bv=(await pool.query("insert into bom_versions(bom_header_id,product_version_id,version_no,version_code,status,created_by,updated_by,request_id) values($1,$2,1,'A0','DRAFT','admin01','admin01',$3) returning id",[bh.id,pv.id,randomUUID()])).rows[0];await pool.query("insert into bom_lines(bom_version_id,line_no,material_id,quantity_per,unit_id,loss_rate,process_stage,created_by,updated_by,request_id) values($1,1,$2,1,$3,0,'SMT','admin01','admin01',$4)",[bv.id,raw.id,unit.id,randomUUID()]);await pool.query("update bom_versions set status='RELEASED',released_by='admin01',released_at=now() where id=$1",[bv.id]);return{productId:Number(p.id),productVersionId:Number(pv.id),bomVersionId:Number(bv.id),finishedId:Number(fg.id)};}
  const primary=await product('PRD-T25-1','TASK25产品一',fg1),missing=await product('PRD-T25-2','TASK25产品二',fg2);const inventory=new InventoryService(new PostgresInventoryRepository(pool));await inventory.post(meta('admin','TEST_STOCK'),{operation_type:'RECEIPT',reason:'TASK25隔离库存',lines:[{material_id:Number(raw.id),unit_id:Number(unit.id),quantity:'100',expected_balance_version:0}]});return{...primary,missing,rawId:Number(raw.id),unitId:Number(unit.id)};}
const workOrderBody=(refs,target=refs,planned='10')=>({product_id:target.productId,product_version_id:target.productVersionId,bom_version_id:target.bomVersionId,finished_material_id:target.finishedId,finished_unit_id:refs.unitId,planned_qty:planned,owner:'production01'});
async function createDraft(refs,target=refs,planned='10'){const result=await production('/api/work-orders',{method:'POST',role:'production',body:workOrderBody(refs,target,planned)});assert.equal(result.response.status,201,JSON.stringify(result.payload));return Number(result.payload.data.id);}

test.beforeEach(async()=>{await pool.query("truncate app_users,units,material_categories,customers,business_code_sequences,idempotency_keys,identity_write_rate_limit_buckets,audit_log restart identity cascade");});
test.after(async()=>pool.end());

test("work centers, routing v1/v2 and immutable work-order snapshots preserve transactional production facts",async()=>{const refs=await seed();assert.equal((await routing('/api/production/work-centers',{method:'POST',role:'sales',body:{work_center_code:'NOPE',name_cn:'越权',work_center_type:'TEST'}})).response.status,403);const definitions=[['SMT-PRINT','锡膏印刷'],['SMT-MOUNT','贴片'],['REFLOW','回流焊'],['AOI','自动光学检测']],centers=[];for(const [work_center_code,name_cn] of definitions){const saved=await routing('/api/production/work-centers',{method:'POST',role:'operations',body:{work_center_code,name_cn,work_center_type:'SMT'}});assert.equal(saved.response.status,201,JSON.stringify(saved.payload));centers.push(saved.payload.data);}const duplicate=await routing('/api/production/work-centers',{method:'POST',role:'operations',body:{work_center_code:'smt-print',name_cn:'重复',work_center_type:'SMT'}});assert.equal(duplicate.response.status,409);assert.equal(duplicate.payload.code,'WORK_CENTER_CODE_CONFLICT');
  const invalidProduct=await routing('/api/production/routings',{method:'POST',role:'engineering',body:{routing_code:'RT-BAD',product_id:refs.productId,product_version_id:refs.missing.productVersionId,version_code:'V1',operations:[]}});assert.equal(invalidProduct.response.status,422);assert.equal(invalidProduct.payload.code,'ROUTING_PRODUCT_VERSION_INVALID');const created=await routing('/api/production/routings',{method:'POST',role:'engineering',key:'routing-v1-create',body:{routing_code:'RT-T25-001',product_id:refs.productId,product_version_id:refs.productVersionId,version_code:'V1',operations:[]}});assert.equal(created.response.status,201,JSON.stringify(created.payload));const v1Id=Number(created.payload.data.id),headerId=Number(created.payload.data.routing_header_id);const empty=await routing(`/api/production/routing-versions/${v1Id}/submit`,{method:'POST',role:'engineering',body:{expected_version:1}});assert.equal(empty.payload.code,'ROUTING_EMPTY');const badSequence=await routing(`/api/production/routing-versions/${v1Id}/operations`,{method:'PATCH',role:'engineering',body:{expected_version:1,operations:[{sequence_no:10,operation_code:'A',operation_name:'A',work_center_id:centers[0].id},{sequence_no:10,operation_code:'B',operation_name:'B',work_center_id:centers[1].id}]}});assert.equal(badSequence.payload.code,'ROUTING_SEQUENCE_CONFLICT');const operations=definitions.map(([code,name],index)=>({sequence_no:(index+1)*10,operation_code:`OP${(index+1)*10}`,operation_name:name,work_center_id:Number(centers[index].id),setup_minutes:String(index),run_minutes_per_unit:String(index+1),description:code}));const replaced=await routing(`/api/production/routing-versions/${v1Id}/operations`,{method:'PATCH',role:'engineering',body:{expected_version:1,operations}});assert.equal(replaced.response.status,200);const submitted=await routing(`/api/production/routing-versions/${v1Id}/submit`,{method:'POST',role:'engineering',body:{expected_version:2}});assert.equal(submitted.payload.data.status,'SUBMITTED');const direct=new ProductionRoutingService(new ProductionRepository(pool));await assert.rejects(direct.transition(v1Id,'release',meta('engineering','ROUTING_RELEASED'),{expected_version:3}),error=>error.code==='ROUTING_SEPARATION_OF_DUTIES');const released=await routing(`/api/production/routing-versions/${v1Id}/release`,{method:'POST',role:'manager',body:{expected_version:3}});assert.equal(released.payload.data.status,'RELEASED');const v1Digest=released.payload.data.canonical_digest;assert.match(v1Digest,/^[0-9a-f]{64}$/);
  const beforeStock=(await pool.query('select on_hand_qty::text from inventory_stock_balances where material_id=$1',[refs.rawId])).rows[0].on_hand_qty,workOrder1=await createDraft(refs);const release1=await production(`/api/work-orders/${workOrder1}/release`,{method:'POST',role:'production',key:'work-order-v1-release',body:{expected_version:1}});assert.equal(release1.response.status,200,JSON.stringify(release1.payload));const facts1=(await pool.query(`select (select count(*)::int from production_bom_snapshots where work_order_id=$1) bom_snapshots,(select count(*)::int from production_work_order_routing_snapshots where work_order_id=$1) routing_snapshots,(select count(*)::int from production_work_order_routing_snapshot_operations o join production_work_order_routing_snapshots s on s.id=o.snapshot_id where s.work_order_id=$1) routing_operations,(select coalesce(sum(reserved_qty),0)::text from production_inventory_reservations where work_order_id=$1) reserved,(select count(*)::int from production_material_issues where work_order_id=$1) issues,(select count(*)::int from production_reports where work_order_id=$1) reports,(select count(*)::int from production_completions where work_order_id=$1) completions`,[workOrder1])).rows[0];assert.deepEqual(facts1,{bom_snapshots:1,routing_snapshots:1,routing_operations:4,reserved:'10.000000',issues:0,reports:0,completions:0});assert.equal((await pool.query('select on_hand_qty::text from inventory_stock_balances where material_id=$1',[refs.rawId])).rows[0].on_hand_qty,beforeStock);const snapshotV1=(await pool.query('select * from production_work_order_routing_snapshots where work_order_id=$1',[workOrder1])).rows[0];assert.equal(snapshotV1.routing_digest,v1Digest);assert.deepEqual((await pool.query('select sequence_no from production_work_order_routing_snapshot_operations where snapshot_id=$1 order by sequence_no',[snapshotV1.id])).rows.map(x=>x.sequence_no),[10,20,30,40]);
  const revised=await routing(`/api/production/routings/${headerId}/versions`,{method:'POST',role:'engineering',body:{expected_header_version:1,product_version_id:refs.productVersionId,version_code:'V2',remark:'标准时间修订'}});assert.equal(revised.response.status,201,JSON.stringify(revised.payload));const v2Id=Number(revised.payload.data.id);const changed=operations.map((op,index)=>index===2?{...op,run_minutes_per_unit:'9.5'}:op);await routing(`/api/production/routing-versions/${v2Id}/operations`,{method:'PATCH',role:'engineering',body:{expected_version:1,operations:changed}});await routing(`/api/production/routing-versions/${v2Id}/submit`,{method:'POST',role:'engineering',body:{expected_version:2}});const disabled=await routing(`/api/production/work-centers/${centers[2].id}/status`,{method:'POST',role:'operations',body:{expected_version:1,status:'INACTIVE'}});assert.equal(disabled.response.status,200);const blocked=await routing(`/api/production/routing-versions/${v2Id}/release`,{method:'POST',role:'manager',body:{expected_version:3}});assert.equal(blocked.payload.code,'ROUTING_WORK_CENTER_INACTIVE');const stale=await routing(`/api/production/work-centers/${centers[2].id}/status`,{method:'POST',role:'operations',body:{expected_version:1,status:'ACTIVE'}});assert.equal(stale.payload.code,'WORK_CENTER_VERSION_CONFLICT');await routing(`/api/production/work-centers/${centers[2].id}/status`,{method:'POST',role:'operations',body:{expected_version:2,status:'ACTIVE'}});const concurrent=await Promise.all(['a','b'].map(key=>routing(`/api/production/routing-versions/${v2Id}/release`,{method:'POST',role:'manager',key:`release-v2-${key}`,body:{expected_version:3}})));assert.deepEqual(concurrent.map(x=>x.response.status).sort(),[200,409]);const v2=(await pool.query('select * from production_routing_versions where id=$1',[v2Id])).rows[0];assert.equal(v2.status,'RELEASED');assert.equal((await pool.query('select status from production_routing_versions where id=$1',[v1Id])).rows[0].status,'SUPERSEDED');assert.notEqual(v2.canonical_digest,v1Digest);assert.deepEqual((await pool.query('select routing_version_id,routing_digest from production_work_order_routing_snapshots where work_order_id=$1',[workOrder1])).rows[0],{routing_version_id:String(v1Id),routing_digest:v1Digest});const workOrder2=await createDraft(refs);await production(`/api/work-orders/${workOrder2}/release`,{method:'POST',role:'production',body:{expected_version:1}});assert.equal(Number((await pool.query('select routing_version_id from production_work_order_routing_snapshots where work_order_id=$1',[workOrder2])).rows[0].routing_version_id),v2Id);await assert.rejects(pool.query('update production_routing_versions set remark=$2 where id=$1',[v2Id,'非法']),/ProductionRoutingService|immutable/i);await assert.rejects(pool.query('delete from production_work_order_routing_snapshots where work_order_id=$1',[workOrder1]),/ProductionService|insert-only|immutable/i);});

test("missing routing and injected snapshot failure leave no release half-records",async()=>{const refs=await seed();const missingWorkOrder=await createDraft(refs,refs.missing);const before=await pool.query("select (select count(*)::int from audit_log) audits,(select count(*)::int from production_work_order_status_events where work_order_id=$1) events",[missingWorkOrder]);const failed=await production(`/api/work-orders/${missingWorkOrder}/release`,{method:'POST',role:'production',key:'missing-routing-release',body:{expected_version:1}});assert.equal(failed.payload.code,'WORK_ORDER_ROUTING_MISSING');const zero=await pool.query(`select (select count(*)::int from production_bom_snapshots where work_order_id=$1) bom,(select count(*)::int from production_work_order_routing_snapshots where work_order_id=$1) routing,(select count(*)::int from production_material_requirements where work_order_id=$1) requirements,(select count(*)::int from production_inventory_reservations where work_order_id=$1) reservations,(select count(*)::int from production_work_order_status_events where work_order_id=$1) events,(select count(*)::int from audit_log) audits,(select count(*)::int from idempotency_keys where path=$2) keys`,[missingWorkOrder,`/api/work-orders/${missingWorkOrder}/release`]);assert.deepEqual(zero.rows[0],{bom:0,routing:0,requirements:0,reservations:0,events:before.rows[0].events,audits:before.rows[0].audits,keys:0});
  const wc=await new ProductionRoutingService(new ProductionRepository(pool)).createWorkCenter(meta('admin','WC'),{work_center_code:'FAULT-WC',name_cn:'故障工作中心',work_center_type:'TEST'}),service=new ProductionRoutingService(new ProductionRepository(pool));const route=await service.createRouting(meta('engineering','ROUTE'),{routing_code:'FAULT-RT',product_id:refs.productId,product_version_id:refs.productVersionId,version_code:'V1',operations:[{sequence_no:10,operation_code:'FAULT',operation_name:'故障点',work_center_id:Number(wc.body.data.id)}]});const routeId=Number(route.body.data.id),submitted=await service.transition(routeId,'submit',meta('engineering','SUBMIT'),{expected_version:1});await service.transition(routeId,'release',meta('manager','RELEASE'),{expected_version:Number(submitted.body.data.version)});const workOrder=await createDraft(refs),faultMeta=meta('production','WORK_ORDER_RELEASED','fault-after-route'),faultService=new ProductionService(new ProductionRepository(pool),undefined,checkpoint=>{if(checkpoint==='after_routing_snapshot')throw new Error('forced routing snapshot rollback');});await assert.rejects(faultService.releaseWorkOrder(workOrder,faultMeta,{expected_version:1}),/服务器暂时无法处理生产请求/);const rollback=(await pool.query(`select (select count(*)::int from production_work_order_routing_snapshots where work_order_id=$1) routing,(select count(*)::int from production_bom_snapshots where work_order_id=$1) bom,(select count(*)::int from production_material_requirements where work_order_id=$1) requirements,(select count(*)::int from production_inventory_reservations where work_order_id=$1) reservations,(select count(*)::int from idempotency_keys where key_digest=$2) keys,(select status from production_work_orders where id=$1) status`,[workOrder,faultMeta.keyDigest])).rows[0];assert.deepEqual(rollback,{routing:0,bom:0,requirements:0,reservations:0,keys:0,status:'DRAFT'});});
