import assert from "node:assert/strict";
import { createHash,randomUUID } from "node:crypto";
import { readdir,readFile } from "node:fs/promises";
import test from "node:test";
import { Pool } from "pg";

const databaseUrl=process.env.TEST_PRODUCTION_QUALITY_UPGRADE_DATABASE_URL;
if(!databaseUrl||!/production_quality_upgrade_test/i.test(databaseUrl))throw new Error("isolated TEST_PRODUCTION_QUALITY_UPGRADE_DATABASE_URL containing production_quality_upgrade_test is required");
const pool=new Pool({connectionString:databaseUrl,max:3,application_name:"production-quality-upgrade-test"}),directory=new URL("../drizzle-postgres/",import.meta.url);
const names=(await readdir(directory)).filter(name=>/^\d{4}_.+\.sql$/.test(name)&&name<="0022_production_quality_release.sql").sort(),sources=new Map();for(const name of names)sources.set(name,await readFile(new URL(name,directory),"utf8"));
const checksum=name=>createHash("sha256").update(sources.get(name)).digest("hex");
async function reset(){await pool.query("drop schema public cascade;create schema public;create table schema_migrations(version text primary key,checksum text not null)");}
async function migrate(list){for(const name of list){const previous=await pool.query("select checksum from schema_migrations where version=$1",[name]);if(previous.rows[0]){assert.equal(previous.rows[0].checksum,checksum(name));continue;}const client=await pool.connect();try{await client.query("begin");await client.query(sources.get(name));await client.query("insert into schema_migrations values($1,$2)",[name,checksum(name)]);await client.query("commit");}catch(error){await client.query("rollback");throw error;}finally{client.release();}}}
test.after(async()=>pool.end());

test("empty database and repeated migrator run produce exactly the guarded 0022 model",async()=>{assert.equal(names.length,22);assert.equal(names.at(-1),"0022_production_quality_release.sql");await reset();await migrate(names);await migrate(names);const relations=await pool.query("select to_regclass('finished_goods_sales_allocations') allocations,to_regclass('finished_goods_sales_allocation_events') events");assert.deepEqual(relations.rows[0],{allocations:"finished_goods_sales_allocations",events:"finished_goods_sales_allocation_events"});const column=await pool.query("select data_type from information_schema.columns where table_name='quality_inspections' and column_name='fqc_allocation_id'");assert.equal(column.rows[0].data_type,"bigint");const triggers=await pool.query("select tgname from pg_trigger where not tgisinternal and tgname=any($1) order by tgname",[["finished_goods_sales_allocations_guard","finished_goods_sales_allocation_events_immutable","production_completion_reversals_allocation_gate"]]);assert.equal(triggers.rowCount,3);});

test("0021 quality history survives expand-only 0022 without inferred allocation backfill",async()=>{await reset();await migrate(names.slice(0,21));await pool.query("insert into app_users(username,display_name,role,password_hash) values('quality01','品质','quality','x')");const category=await pool.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values('Q22','升级',4,'ACTIVE','quality01','quality01',$1) returning id",[randomUUID()]),unit=await pool.query("insert into units(code,name,symbol,unit_type) values('Q22PCS','件','Q22PCS','COUNT') returning id"),material=await pool.query("insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values('CYD-Q22','历史品质',$1,'Q22PCS',$2,'ACTIVE','MAKE','STOCKED','FQC','ROHS','MANUAL','quality01','quality01','quality01',$3) returning id",[category.rows[0].id,unit.rows[0].id,randomUUID()]);await pool.query("set session_replication_role=replica");try{await pool.query("insert into quality_inspections(inspection_code,inspection_type,production_completion_line_id,sales_order_line_id,material_id,unit_id,inspected_qty,passed_qty,failed_qty,operation_id,created_by,request_id) values('FQC-HISTORY','FQC',999,999,$1,$2,1,1,0,$3,'quality01',$4)",[material.rows[0].id,unit.rows[0].id,randomUUID(),randomUUID()]);}finally{await pool.query("set session_replication_role=origin");}await migrate(names.slice(21));assert.deepEqual((await pool.query("select inspection_code,fqc_allocation_id from quality_inspections")).rows,[{inspection_code:"FQC-HISTORY",fqc_allocation_id:null}]);assert.equal((await pool.query("select count(*)::int count from finished_goods_sales_allocations")).rows[0].count,0);});

test("0022 DDL failure rolls back every new relation and migration record",async()=>{await reset();await migrate(names.slice(0,21));await pool.query("create table finished_goods_sales_allocations(id bigint primary key)");await assert.rejects(migrate(names.slice(21)),/finished_goods_sales_allocations.*already exists/i);assert.equal((await pool.query("select to_regclass('finished_goods_sales_allocation_events') value")).rows[0].value,null);assert.equal((await pool.query("select count(*)::int count from schema_migrations where version='0022_production_quality_release.sql'")).rows[0].count,0);});
