import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import test from "node:test";
import { Pool } from "pg";

const url=process.env.TEST_PRODUCTION_NONCONFORMANCE_UPGRADE_DATABASE_URL;
if(!url||!/production_nonconformance_upgrade_test/i.test(url))throw new Error("isolated TEST_PRODUCTION_NONCONFORMANCE_UPGRADE_DATABASE_URL containing production_nonconformance_upgrade_test is required");
const pool=new Pool({connectionString:url,max:2,application_name:"production-nonconformance-upgrade-test"}),dir=new URL("../drizzle-postgres/",import.meta.url);
const names=(await readdir(dir)).filter(name=>/^\d{4}_.+\.sql$/.test(name)&&name<="0029_production_nonconformance_rework_handoff.sql").sort(),sources=new Map();for(const name of names)sources.set(name,await readFile(new URL(name,dir),"utf8"));
const checksum=name=>createHash("sha256").update(sources.get(name)).digest("hex");
async function reset(){await pool.query("drop schema public cascade;create schema public;create table schema_migrations(version text primary key,checksum text not null)");}
async function migrate(list){for(const name of list){const existing=await pool.query("select checksum from schema_migrations where version=$1",[name]);if(existing.rows[0]){assert.equal(existing.rows[0].checksum,checksum(name));continue;}const client=await pool.connect();try{await client.query("begin");await client.query(sources.get(name));await client.query("insert into schema_migrations values($1,$2)",[name,checksum(name)]);await client.query("commit");}catch(error){await client.query("rollback");throw error;}finally{client.release();}}}
test.after(()=>pool.end());

test("empty database and repeated runner reach exactly migration 0029",async()=>{assert.equal(names.length,29);assert.equal(names.at(-1),"0029_production_nonconformance_rework_handoff.sql");await reset();await migrate(names);await migrate(names);assert.equal((await pool.query("select count(*)::int count from schema_migrations")).rows[0].count,29);for(const table of ["production_nonconformances","production_nonconformance_events","production_rework_requests","production_rework_request_versions","production_rework_request_events","production_nonconformance_allocations","production_scrap_dispositions"])assert.equal((await pool.query("select to_regclass($1) value",[`public.${table}`])).rows[0].value,table);});

test("0028 history upgrades expand-only and keeps existing rows",async()=>{await reset();await migrate(names.slice(0,28));await pool.query("insert into app_users(username,display_name,role,password_hash) values('admin01','管理员','admin','x')");const before=(await pool.query("select count(*)::int count from app_users")).rows[0].count;await migrate(names.slice(28));assert.equal((await pool.query("select count(*)::int count from app_users")).rows[0].count,before);assert.equal((await pool.query("select count(*)::int count from production_nonconformances")).rows[0].count,0);});

test("0029 failure rolls back all tables, functions and migration row",async()=>{await reset();await migrate(names.slice(0,28));await pool.query("create table production_nonconformances(id bigint)");await assert.rejects(migrate(names.slice(28)),/production_nonconformances.*already exists/i);assert.equal((await pool.query("select to_regclass('public.production_rework_requests') value")).rows[0].value,null);assert.equal((await pool.query("select to_regprocedure('cyd_nonconformance_consistency_guard()') value")).rows[0].value,null);assert.equal((await pool.query("select count(*)::int count from schema_migrations where version=$1",[names.at(-1)])).rows[0].count,0);});

test("schema snapshot journal and full SHA-256 describe 0029",async()=>{const schema=await readFile(new URL("../db/schema.ts",import.meta.url),"utf8"),snapshot=JSON.parse(await readFile(new URL("../drizzle-postgres/meta/0029_snapshot.json",import.meta.url),"utf8")),journal=JSON.parse(await readFile(new URL("../drizzle-postgres/meta/_journal.json",import.meta.url),"utf8"));for(const table of ["production_nonconformances","production_nonconformance_events","production_rework_requests","production_rework_request_versions","production_rework_request_events","production_nonconformance_allocations","production_scrap_dispositions"]){assert.ok(snapshot.tables[`public.${table}`],table);assert.match(schema,new RegExp(table.replace(/_([a-z])/g,(_,letter)=>letter.toUpperCase())));}assert.equal(snapshot.prevId,JSON.parse(await readFile(new URL("../drizzle-postgres/meta/0028_snapshot.json",import.meta.url),"utf8")).id);assert.equal(journal.entries.at(-1).tag,"0029_production_nonconformance_rework_handoff");assert.match(checksum(names.at(-1)),/^[0-9a-f]{64}$/);assert.equal(checksum(names.at(-1)),createHash("sha256").update(await readFile(new URL(`../drizzle-postgres/${names.at(-1)}`,import.meta.url))).digest("hex"));});

test("0029 contains direct SQL target, source, conservation, immutability and reopen guards",async()=>{const sql=sources.get(names.at(-1));for(const token of ["NCR requires closed structured failed IPQC evidence","invalid rework target snapshot operation","NCR failed quantity over-allocated","rework submitted snapshot mismatch","NCR quantity projection mismatch","NCR facts are immutable","inspection NCR must be safely cancelled before reopen","DEFERRABLE INITIALLY DEFERRED"])assert.match(sql,new RegExp(token));for(const forbidden of ['CREATE TABLE "quality_inspections"','CREATE TABLE "production_operation_runs"','CREATE TABLE "inventory_ledger_entries"'])assert.doesNotMatch(sql,new RegExp(forbidden));assert.ok(randomUUID());});
