import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readdir,readFile } from "node:fs/promises";
import test from "node:test";
import { Pool } from "pg";

const url=process.env.TEST_FINISHED_GOODS_LOT_SHIPMENT_DATABASE_URL;
if(!url||!/finished_goods_lot_shipment_test/i.test(url))throw new Error("isolated TEST_FINISHED_GOODS_LOT_SHIPMENT_DATABASE_URL containing finished_goods_lot_shipment_test is required");
const pool=new Pool({connectionString:url,max:2,application_name:"task09-lot-shipment-migration-test"}),dir=new URL("../drizzle-postgres/",import.meta.url),names=(await readdir(dir)).filter(name=>/^\d{4}_.*\.sql$/.test(name)&&name<="0033_finished_goods_lot_fqc_shipment.sql").sort(),sources=new Map(await Promise.all(names.map(async name=>[name,await readFile(new URL(name,dir),"utf8")]))),checksum=name=>createHash("sha256").update(sources.get(name)).digest("hex");
async function reset(){await pool.query("drop schema public cascade;create schema public;create table schema_migrations(version text primary key,checksum text not null)")}
async function migrate(list){for(const name of list){const prior=await pool.query("select checksum from schema_migrations where version=$1",[name]);if(prior.rows[0]){assert.equal(prior.rows[0].checksum,checksum(name));continue}const client=await pool.connect();try{await client.query("begin");await client.query(sources.get(name));await client.query("insert into schema_migrations values($1,$2)",[name,checksum(name)]);await client.query("commit")}catch(error){await client.query("rollback").catch(()=>undefined);throw error}finally{client.release()}}}
test.after(()=>pool.end());

test("empty database and repeat reach exactly 0033",async()=>{await reset();assert.equal(names.length,33);assert.equal(names.at(-1),"0033_finished_goods_lot_fqc_shipment.sql");await migrate(names);await migrate(names);assert.equal((await pool.query("select count(*)::int count from schema_migrations")).rows[0].count,33)});
test("0033 failure rolls back every new column",async()=>{await reset();await migrate(names.slice(0,32));await pool.query("alter table quality_inspections add column inventory_lot_id bigint");await assert.rejects(migrate(names.slice(32)),/already exists/i);for(const table of ["finished_goods_sales_allocations","sales_shipment_lines","sales_shipment_line_fqc_allocations"])assert.equal((await pool.query("select count(*)::int count from information_schema.columns where table_name=$1 and column_name='inventory_lot_id'",[table])).rows[0].count,0);assert.equal((await pool.query("select count(*)::int count from schema_migrations where version=$1",[names.at(-1)])).rows[0].count,0);await reset();await migrate(names)});
test("schema journal snapshot and checksum describe 0033",async()=>{const schema=await readFile(new URL("../db/schema.ts",import.meta.url),"utf8"),snapshot=JSON.parse(await readFile(new URL("../drizzle-postgres/meta/0033_snapshot.json",import.meta.url),"utf8")),previous=JSON.parse(await readFile(new URL("../drizzle-postgres/meta/0032_snapshot.json",import.meta.url),"utf8")),journal=JSON.parse(await readFile(new URL("../drizzle-postgres/meta/_journal.json",import.meta.url),"utf8"));for(const table of ["finished_goods_sales_allocations","quality_inspections","sales_shipment_lines","sales_shipment_line_fqc_allocations"])assert.ok(snapshot.tables[`public.${table}`].columns.inventory_lot_id,table);assert.match(schema,/SHIPMENT_ISSUED/);assert.equal(snapshot.prevId,previous.id);assert.ok(journal.entries.some(entry=>entry.tag==="0033_finished_goods_lot_fqc_shipment"));assert.match(checksum(names.at(-1)),/^[0-9a-f]{64}$/)});
