import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { InventoryService } from "../app/lib/inventory-selfhost/service.ts";
import { PostgresInventoryRepository } from "../app/lib/inventory-selfhost/repository.ts";
import { handleSalesApi } from "../app/lib/sales-selfhost/handler.ts";
import { SalesRepository } from "../app/lib/sales-selfhost/repository.ts";
import { SalesService } from "../app/lib/sales-selfhost/service.ts";

const databaseUrl = process.env.TEST_SALES_DATABASE_URL;
if (!databaseUrl || !/sales_test/i.test(databaseUrl)) throw new Error("isolated TEST_SALES_DATABASE_URL containing sales_test is required");
const pool = new Pool({ connectionString: databaseUrl, max: 20, application_name: "sales-integration-test" });
const actor = (role, username = `${role}01`) => ({ username, display_name: role, role, is_active: true, must_change_password: false, version: 1, last_login_at: null, permissions: permissionsForRole(role) });

async function api(path, { method = "GET", role = "admin", username, body, key = randomUUID(), csrf = true } = {}) {
  const headers = new Headers({ "X-Request-ID": randomUUID() }); if (body !== undefined) headers.set("Content-Type", "application/json"); if (key) headers.set("Idempotency-Key", key); if (csrf) headers.set("X-CSRF-Token", "test-csrf");
  const request = new Request(`http://local.test${path}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const result = await handleSalesApi(request, { pool, actor: actor(role, username), requestId: headers.get("X-Request-ID"), requireCsrf: () => { if (headers.get("X-CSRF-Token") !== "test-csrf") throw Object.assign(new Error("CSRF Token 无效"), { code: "CSRF_INVALID", status: 403 }); } });
  assert.ok(result); return { response: result, payload: await result.json() };
}

async function seed() {
  await pool.query(`insert into app_users(username,display_name,role,password_hash) values ('admin01','admin','admin','test-only'),('manager01','manager','manager','test-only'),('sales01','sales','sales','test-only'),('warehouse01','warehouse','warehouse','test-only'),('finance01','finance','finance','test-only'),('production01','production','production','test-only')`);
  await pool.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values('SALES_LEAF','销售测试',4,'ACTIVE','test','test',$1)", [randomUUID()]); const category = await pool.query("select id from material_categories where category_code='SALES_LEAF'");
  await pool.query("insert into units(code,name,symbol,unit_type,enabled) values('PCS','件','PCS','COUNT',true),('BOX','箱','BOX','COUNT',true)"); const units = await pool.query("select id,code from units order by code"); const pcs = units.rows.find((row) => row.code === "PCS"); const box = units.rows.find((row) => row.code === "BOX");
  await pool.query("insert into customers(customer_code,customer_name,normalized_name,status,created_by,updated_by,request_id) values('CUS-SALES-1','销售客户','销售客户','ACTIVE','test','test',$1),('CUS-SALES-2','停用客户','停用客户','INACTIVE','test','test',$2)", [randomUUID(), randomUUID()]); const customers = await pool.query("select id,status from customers order by id");
  const material = await pool.query(`insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values ('CYD-FG-000001','销售成品',$1,'PCS',$2,'ACTIVE','MAKE','STOCKED','FQC','ROHS','MANUAL','test','test','test',$3) returning id,base_unit_id`, [category.rows[0].id, pcs.id, randomUUID()]);
  const product = await pool.query("insert into products(product_code,product_name,customer_id,created_by,updated_by,request_id) values('PRD-SALES','销售产品',$1,'test','test',$2) returning id", [customers.rows[0].id, randomUUID()]); const productVersion = await pool.query("insert into product_versions(product_id,version_no,version_code,status,product_type,lifecycle_status,created_by,updated_by,request_id,released_by,released_at) values($1,1,'A0','RELEASED','PCB','MASS','test','test',$2,'test',now()) returning id", [product.rows[0].id, randomUUID()]);
  await pool.query("insert into material_customer_restrictions(material_id,customer_id,status,created_by,request_id) values($1,$2,'ACTIVE','admin01',$3)", [material.rows[0].id, customers.rows[0].id, randomUUID()]);
  const inventory = new InventoryService(new PostgresInventoryRepository(pool)); const meta = { actor: actor("manager"), requestId: randomUUID(), operationId: randomUUID(), keyDigest: "a".repeat(64), requestDigest: "b".repeat(64), method: "POST", route: "/seed/inventory", action: "TEST_INVENTORY_SEED" }; await inventory.post(meta, { operation_type: "RECEIPT", reason: "测试成品入库", lines: [{ material_id: Number(material.rows[0].id), unit_id: Number(pcs.id), quantity: "20", expected_balance_version: 0 }] });
  return { customerId: Number(customers.rows[0].id), inactiveCustomerId: Number(customers.rows[1].id), productId: Number(product.rows[0].id), productVersionId: Number(productVersion.rows[0].id), materialId: Number(material.rows[0].id), unitId: Number(pcs.id), boxId: Number(box.id) };
}

function quoteBody(refs, quantity = "10", unitPrice = "1.234567") { return { customer_id: refs.customerId, currency_code: "CNY", valid_until: "2027-08-01T00:00:00Z", owner: "业务员", remark: "未税报价", lines: [{ product_id: refs.productId, product_version_id: refs.productVersionId, finished_material_id: refs.materialId, unit_id: refs.unitId, quantity, unit_price: unitPrice }] }; }
async function acceptedQuote(refs, suffix = randomUUID()) { const created = await api("/api/quotations", { method: "POST", role: "sales", key: `quote-create-${suffix}`, body: quoteBody(refs) }); const quoteId = Number(created.payload.quote_id); await api(`/api/quotations/${quoteId}/publish`, { method: "POST", role: "sales", key: `quote-publish-${suffix}`, body: { expected_version: 1, reason: "" } }); await api(`/api/quotations/${quoteId}/accept`, { method: "POST", role: "sales", key: `quote-accept-${suffix}`, body: { expected_version: 2, reason: "" } }); return { quoteId, created }; }

test.beforeEach(async () => {
  await pool.query(`truncate sales_financial_source_entries,sales_shipment_lines,sales_shipments,sales_order_status_events,sales_quote_order_links,sales_order_lines,sales_order_versions,sales_orders,sales_quotation_status_events,sales_quotation_lines,sales_quotation_versions,sales_quotations,
    production_completion_lines,production_completions,production_reports,production_material_return_lines,production_material_returns,production_material_issue_lines,production_material_issues,production_material_requirements,production_bom_snapshot_lines,production_bom_snapshots,production_work_order_status_events,production_work_orders,
    inventory_adjustment_lines,inventory_ledger_entries,inventory_stock_balances,inventory_adjustments,material_customer_restrictions,product_versions,products,customers,business_code_sequences,identity_write_rate_limit_buckets,idempotency_keys,audit_log,app_users,material_master,units,material_categories restart identity cascade`);
});
test.after(async () => pool.end());

test("quotation lifecycle, exact server amount, atomic conversion, shipment, reversal and close stay consistent", async () => {
  const refs = await seed(); const body = quoteBody(refs); const created = await api("/api/quotations", { method: "POST", role: "sales", key: "sales-quote-0001", body }); assert.equal(created.response.status, 201); assert.equal(created.payload.data.current_version.total_amount, "12.345670"); const quoteId = Number(created.payload.quote_id);
  const replay = await api("/api/quotations", { method: "POST", role: "sales", key: "sales-quote-0001", body }); assert.equal(replay.response.headers.get("Idempotency-Replayed"), "true"); const conflict = await api("/api/quotations", { method: "POST", role: "sales", key: "sales-quote-0001", body: { ...body, remark: "不同正文" } }); assert.equal(conflict.response.status, 409); assert.equal(conflict.payload.code, "IDEMPOTENCY_CONFLICT");
  const updated = await api(`/api/quotations/${quoteId}`, { method: "PATCH", role: "sales", body: { ...body, expected_version: 1, remark: "更新草稿" } }); assert.equal(updated.response.status, 200); assert.equal(updated.payload.data.version, 2); assert.equal(updated.payload.data.current_version.total_amount, "12.345670");
  assert.equal((await api(`/api/quotations/${quoteId}/publish`, { method: "POST", role: "sales", body: { expected_version: 2, reason: "" } })).response.status, 200); assert.equal((await api(`/api/quotations/${quoteId}/accept`, { method: "POST", role: "sales", body: { expected_version: 3, reason: "" } })).response.status, 200);
  const converted = await api(`/api/quotations/${quoteId}/convert`, { method: "POST", role: "sales", key: "sales-convert-0001", body: { expected_version: 4, owner: "业务员" } }); assert.equal(converted.response.status, 201); const orderId = Number(converted.payload.sales_order_id); const orderLineId = Number(converted.payload.data.sales_order.current_version.lines[0].id); assert.equal(converted.payload.data.sales_order.current_version.total_amount, "12.345670");
  const duplicate = await api(`/api/quotations/${quoteId}/convert`, { method: "POST", role: "sales", body: { expected_version: 4 } }); assert.equal(duplicate.response.status, 409);
  const first = await api("/api/shipments", { method: "POST", role: "warehouse", body: { sales_order_id: orderId, expected_order_version: 1, reason: "首批出货", lines: [{ sales_order_line_id: orderLineId, quantity: "4", expected_line_version: 1, expected_balance_version: 1 }] } }); assert.equal(first.response.status, 201); assert.equal(first.payload.data.financial_source.amount, "4.938268");
  const second = await api("/api/shipments", { method: "POST", role: "warehouse", body: { sales_order_id: orderId, expected_order_version: 2, reason: "剩余出货", lines: [{ sales_order_line_id: orderLineId, quantity: "6", expected_line_version: 2, expected_balance_version: 2 }] } }); assert.equal(second.response.status, 201); assert.equal(second.payload.data.sales_order.status, "SHIPPED");
  const reversed = await api(`/api/shipments/${second.payload.shipment_id}/reversal`, { method: "POST", role: "warehouse", body: { reason: "录入错误", expected_balance_versions: [{ material_id: refs.materialId, expected_balance_version: 3 }] } }); assert.equal(reversed.response.status, 201); assert.equal(reversed.payload.data.financial_source.amount, "-7.407402"); assert.equal(reversed.payload.data.sales_order.status, "PARTIALLY_SHIPPED");
  const repeated = await api(`/api/shipments/${second.payload.shipment_id}/reversal`, { method: "POST", role: "warehouse", body: { reason: "重复冲销", expected_balance_versions: [{ material_id: refs.materialId, expected_balance_version: 4 }] } }); assert.equal(repeated.response.status, 409); assert.equal(repeated.payload.code, "SHIPMENT_ALREADY_REVERSED");
  const final = await api("/api/shipments", { method: "POST", role: "warehouse", body: { sales_order_id: orderId, expected_order_version: 4, reason: "重新出货", lines: [{ sales_order_line_id: orderLineId, quantity: "6", expected_line_version: 4, expected_balance_version: 4 }] } }); assert.equal(final.response.status, 201); const closed = await api(`/api/sales-orders/${orderId}/close`, { method: "POST", role: "manager", body: { expected_version: 5, reason: "交付完成" } }); assert.equal(closed.response.status, 200); assert.equal(closed.payload.data.status, "CLOSED");
  const balance = await pool.query("select on_hand_qty,version from inventory_stock_balances where material_id=$1", [refs.materialId]); assert.deepEqual(balance.rows[0], { on_hand_qty: "10.000000", version: 5 }); const finance = await pool.query("select entry_type,amount::text,reversal_of_source_entry_id from sales_financial_source_entries order by id"); assert.deepEqual(finance.rows.map((row) => [row.entry_type, row.amount]), [["SHIPMENT", "4.938268"], ["SHIPMENT", "7.407402"], ["SHIPMENT_REVERSAL", "-7.407402"], ["SHIPMENT", "7.407402"]]); assert.ok(finance.rows[2].reversal_of_source_entry_id);
  assert.equal(Number((await pool.query("select count(*) count from erp_records where kind in ('quotation','sales_order','shipment','financial_document','financial_payment')")).rows[0].count), 0); await assert.rejects(pool.query("update sales_shipments set reason='tamper'"), /posted sales records are immutable/); await assert.rejects(pool.query("update sales_order_versions set remark='tamper'"), /posted sales records are immutable/);
});

test("permissions, references, concurrency and cross-domain rollback fail closed", async () => {
  const refs = await seed(); assert.equal((await api("/api/quotations", { method: "POST", role: "warehouse", body: quoteBody(refs) })).response.status, 403); assert.equal((await api("/api/quotations", { method: "POST", role: "sales", csrf: false, body: quoteBody(refs) })).response.status, 403);
  const wrongCustomer = await api("/api/quotations", { method: "POST", role: "sales", body: { ...quoteBody(refs), customer_id: refs.inactiveCustomerId } }); assert.equal(wrongCustomer.response.status, 422); assert.equal(wrongCustomer.payload.code, "CUSTOMER_NOT_ACTIVE"); const wrongUnit = await api("/api/quotations", { method: "POST", role: "sales", body: { ...quoteBody(refs), lines: [{ ...quoteBody(refs).lines[0], unit_id: refs.boxId }] } }); assert.equal(wrongUnit.response.status, 422); assert.equal(wrongUnit.payload.code, "SALES_REFERENCE_NOT_ACTIVE");
  const accepted = await acceptedQuote(refs, "concurrent"); const conversions = await Promise.all(["A", "B"].map((suffix) => api(`/api/quotations/${accepted.quoteId}/convert`, { method: "POST", role: "sales", key: `parallel-convert-${suffix}`, body: { expected_version: 3 } }))); assert.deepEqual(conversions.map((item) => item.response.status).sort(), [201, 409]); assert.equal(Number((await pool.query("select count(*) count from sales_quote_order_links where quotation_id=$1", [accepted.quoteId])).rows[0].count), 1); assert.equal(Number((await pool.query("select count(*) count from sales_orders")).rows[0].count), 1);
  const order = conversions.find((item) => item.response.status === 201).payload.data.sales_order; const orderId = Number(order.id); const lineId = Number(order.current_version.lines[0].id); const shipments = await Promise.all(["A", "B"].map((suffix) => api("/api/shipments", { method: "POST", role: "warehouse", key: `parallel-ship-${suffix}`, body: { sales_order_id: orderId, expected_order_version: 1, reason: suffix, lines: [{ sales_order_line_id: lineId, quantity: "7", expected_line_version: 1, expected_balance_version: 1 }] } }))); assert.deepEqual(shipments.map((item) => item.response.status).sort(), [201, 409]); assert.equal((await pool.query("select shipped_qty from sales_order_lines where id=$1", [lineId])).rows[0].shipped_qty, "7.000000"); assert.equal((await pool.query("select on_hand_qty from inventory_stock_balances where material_id=$1", [refs.materialId])).rows[0].on_hand_qty, "13.000000");
  const service = new SalesService(new SalesRepository(pool), undefined, (checkpoint) => { if (checkpoint === "after_shipment_inventory") throw new Error("forced sales rollback"); }); const meta = { actor: actor("warehouse"), requestId: randomUUID(), operationId: randomUUID(), keyDigest: "f".repeat(64), requestDigest: "e".repeat(64), method: "POST", route: "/api/shipments", action: "SALES_SHIPMENT_POSTED" }; await assert.rejects(service.createShipment(meta, { sales_order_id: orderId, expected_order_version: 2, reason: "故障注入", lines: [{ sales_order_line_id: lineId, quantity: "1", expected_line_version: 2, expected_balance_version: 2 }] }), /服务器暂时无法处理销售请求/); assert.equal(Number((await pool.query("select count(*) count from sales_shipments where reason='故障注入'")).rows[0].count), 0); assert.equal((await pool.query("select shipped_qty,version from sales_order_lines where id=$1", [lineId])).rows[0].shipped_qty, "7.000000"); assert.equal((await pool.query("select on_hand_qty,version from inventory_stock_balances where material_id=$1", [refs.materialId])).rows[0].on_hand_qty, "13.000000"); assert.equal(Number((await pool.query("select count(*) count from idempotency_keys where key_digest=$1", [meta.keyDigest])).rows[0].count), 0);
});

test("concurrent quotation, order and shipment codes remain unique and audit failure rolls back all facts", async () => {
  const refs = await seed(); const quotes = await Promise.all(Array.from({ length: 6 }, (_, index) => api("/api/quotations", { method: "POST", role: "sales", key: `parallel-quote-${index}`, body: { ...quoteBody(refs, "1", "2"), remark: String(index) } }))); assert.ok(quotes.every((item) => item.response.status === 201)); assert.equal(new Set(quotes.map((item) => item.payload.quote_code)).size, 6);
  const orders = await Promise.all(Array.from({ length: 6 }, (_, index) => api("/api/sales-orders", { method: "POST", role: "sales", key: `parallel-order-${index}`, body: { ...quoteBody(refs, "1", "2"), remark: String(index) } }))); assert.ok(orders.every((item) => item.response.status === 201)); assert.equal(new Set(orders.map((item) => item.payload.sales_order_code)).size, 6);
  const selected = orders[0].payload.data; await pool.query(`create or replace function fail_sales_audit_for_test() returns trigger language plpgsql as $$ begin if new.action='SALES_SHIPMENT_POSTED' then raise exception 'forced sales audit failure'; end if; return new; end $$`); await pool.query("create trigger fail_sales_audit_for_test before insert on audit_log for each row execute function fail_sales_audit_for_test()"); const failed = await api("/api/shipments", { method: "POST", role: "warehouse", key: "sales-audit-failure", body: { sales_order_id: Number(selected.id), expected_order_version: 1, reason: "审计失败", lines: [{ sales_order_line_id: Number(selected.current_version.lines[0].id), quantity: "1", expected_line_version: 1, expected_balance_version: 1 }] } }); assert.equal(failed.response.status, 500); assert.equal(Number((await pool.query("select count(*) count from sales_shipments where reason='审计失败'")).rows[0].count), 0); assert.equal((await pool.query("select on_hand_qty,version from inventory_stock_balances where material_id=$1", [refs.materialId])).rows[0].on_hand_qty, "20.000000"); await pool.query("drop trigger fail_sales_audit_for_test on audit_log; drop function fail_sales_audit_for_test()");
});
