import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { InventoryService } from "../app/lib/inventory-selfhost/service.ts";
import { PostgresInventoryRepository } from "../app/lib/inventory-selfhost/repository.ts";
import { handleProductionHandoffApi } from "../app/lib/production-handoff-selfhost/handler.ts";
import { ProductionError } from "../app/lib/production-selfhost/errors.ts";
import { handleProductionApi } from "../app/lib/production-selfhost/handler.ts";
import { ProductionRepository } from "../app/lib/production-selfhost/repository.ts";
import { ProductionService } from "../app/lib/production-selfhost/service.ts";
import { ensureReleasedRouting } from "./helpers/production-routing.mjs";

const databaseUrl=process.env.TEST_PRODUCTION_HANDOFF_DATABASE_URL;
if(!databaseUrl||!/production_handoff_test/i.test(databaseUrl))throw new Error("isolated TEST_PRODUCTION_HANDOFF_DATABASE_URL containing production_handoff_test is required");
const pool=new Pool({connectionString:databaseUrl,max:20,application_name:"production-handoff-integration-test"});
const digest=(value)=>createHash("sha256").update(String(value)).digest("hex");
const actor=(role)=>({username:`${role}01`,display_name:role,role,is_active:true,must_change_password:false,version:1,last_login_at:null,permissions:permissionsForRole(role)});

async function request(handler,path,{method="GET",role="admin",body,key=randomUUID(),csrf=true}={}){
  const headers=new Headers({"X-Request-ID":randomUUID()});if(body!==undefined)headers.set("Content-Type","application/json");if(key)headers.set("Idempotency-Key",key);if(csrf)headers.set("X-CSRF-Token","test-csrf");
  const response=await handler(new Request(`http://local.test${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),{pool,actor:actor(role),requestId:headers.get("X-Request-ID"),requireCsrf:()=>{if(headers.get("X-CSRF-Token")!=="test-csrf")throw new ProductionError("CSRF_INVALID","CSRF Token 无效",403);}});
  assert.ok(response);return{response,payload:await response.json()};
}
const handoff=(path,options)=>request(handleProductionHandoffApi,path,options);
const production=(path,options)=>request(handleProductionApi,path,options);

async function seed(){
  const client=await pool.connect();try{await client.query("begin");await client.query("select set_config('cyd.project_service_write','allowed',true),set_config('cyd.planning_service_write','allowed',true)");
    await client.query(`insert into app_users(username,display_name,role,password_hash) values ('admin01','管理员','admin','x'),('planning01','计划','planning','x'),('production01','生产','production','x'),('warehouse01','仓库','warehouse','x'),('engineering01','工程','engineering','x'),('manager01','经理','manager','x')`);
    const category=(await client.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values('TASK06_LEAF','TASK06',4,'ACTIVE','admin01','admin01',$1) returning id",[randomUUID()])).rows[0];
    const unit=(await client.query("insert into units(code,name,symbol,unit_type,enabled) values('PCS','件','PCS','COUNT',true) returning id")).rows[0];
    const materials=(await client.query(`insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values
      ('CYD-T06-RAW','TASK06 原材料',$1,'PCS',$2,'ACTIVE','PURCHASE','STOCKED','NONE','ROHS','MANUAL','admin01','admin01','admin01',$3),
      ('CYD-T06-FG','TASK06 成品',$1,'PCS',$2,'ACTIVE','MAKE','STOCKED','NONE','ROHS','MANUAL','admin01','admin01','admin01',$4) returning id,internal_material_code`,[category.id,unit.id,randomUUID(),randomUUID()])).rows;
    const raw=materials.find(row=>row.internal_material_code==="CYD-T06-RAW"),finished=materials.find(row=>row.internal_material_code==="CYD-T06-FG");
    const customer=(await client.query("insert into customers(customer_code,customer_name,normalized_name,created_by,updated_by,request_id) values('CUS-T06','TASK06 客户','TASK06 客户','admin01','admin01',$1) returning id",[randomUUID()])).rows[0];
    const product=(await client.query("insert into products(product_code,product_name,customer_id,status,created_by,updated_by,request_id) values('PRD-T06','TASK06 产品',$1,'ACTIVE','admin01','admin01',$2) returning id",[customer.id,randomUUID()])).rows[0];
    const productVersion=(await client.query("insert into product_versions(product_id,version_no,version_code,status,product_type,lifecycle_status,released_by,released_at,created_by,updated_by,request_id) values($1,1,'A0','RELEASED','ASSEMBLY','MASS','admin01',now(),'admin01','admin01',$2) returning id",[product.id,randomUUID()])).rows[0];
    const bomHeader=(await client.query("insert into bom_headers(bom_code,product_id,status,created_by,updated_by,request_id) values('BOM-T06',$1,'ACTIVE','admin01','admin01',$2) returning id",[product.id,randomUUID()])).rows[0];
    const bomVersion=(await client.query("insert into bom_versions(bom_header_id,product_version_id,version_no,version_code,status,created_by,updated_by,request_id) values($1,$2,1,'A0','DRAFT','admin01','admin01',$3) returning id",[bomHeader.id,productVersion.id,randomUUID()])).rows[0];
    const bomLine=(await client.query("insert into bom_lines(bom_version_id,line_no,material_id,quantity_per,unit_id,loss_rate,process_stage,created_by,updated_by,request_id) values($1,1,$2,1,$3,0,'ASSEMBLY','admin01','admin01',$4) returning id",[bomVersion.id,raw.id,unit.id,randomUUID()])).rows[0];
    await client.query("update bom_versions set status='RELEASED',released_by='admin01',released_at=now() where id=$1",[bomVersion.id]);
    const project=(await client.query("insert into business_projects(project_code,customer_id,project_name,project_goal,market_owner,project_owner,status,target_delivery_date,current_requirement_version_no,version,request_id,created_by) values('PRJ-00000006',$1,'TASK06 项目','生产交接','admin01','engineering01','ACCEPTED','2026-12-31',1,4,$2,'admin01') returning id",[customer.id,randomUUID()])).rows[0];
    const requirementVersion=(await client.query("insert into project_requirement_versions(project_id,version_no,customer_requirement_summary,quantity_requirement,quantity_unit,content_digest,created_by) values($1,1,'生产 10 件',10,'PCS',$2,'admin01') returning id",[project.id,digest("requirement")])).rows[0];
    const requirementItem=(await client.query("insert into project_requirement_items(requirement_version_id,line_no,provisional_name,quantity,unit_id,unit_pending,product_id) values($1,1,'TASK06 产品',10,$2,false,$3) returning id",[requirementVersion.id,unit.id,product.id])).rows[0];
    const packageRow=(await client.query("insert into project_planning_packages(project_id,package_version_no,requirement_version_id,status,target_delivery_date,package_digest,prepared_by,version,request_id) values($1,1,$2,'DRAFT','2026-12-31',$3,'engineering01',1,$4) returning id,version",[project.id,requirementVersion.id,digest("package"),randomUUID()])).rows[0];
    const packageItem=(await client.query("insert into project_planning_package_items(package_id,requirement_item_id,product_version_id,bom_version_id,required_quantity,unit_id,line_no,source_digest) values($1,$2,$3,$4,10,$5,1,$6) returning id",[packageRow.id,requirementItem.id,productVersion.id,bomVersion.id,unit.id,digest("package-item")])).rows[0];
    await client.query("insert into project_planning_package_bom_lines(package_item_id,source_bom_line_id,material_id,unit_id,quantity_per,loss_rate,calculated_gross_quantity,specification_snapshot,material_digest,line_no) values($1,$2,$3,$4,1,0,10,'{}',$5,1)",[packageItem.id,bomLine.id,raw.id,unit.id,digest("material")]);
    await client.query("update project_planning_packages set status='SUBMITTED',submitted_by='engineering01',submitted_at=now(),version=2 where id=$1",[packageRow.id]);
    await client.query("update project_planning_packages set status='ACCEPTED',accepted_by='planning01',accepted_at=now(),version=3 where id=$1",[packageRow.id]);
    await client.query("commit");const refs={unitId:Number(unit.id),rawId:Number(raw.id),finishedId:Number(finished.id),packageId:Number(packageRow.id),packageItemId:Number(packageItem.id),productId:Number(product.id),productVersionId:Number(productVersion.id),bomVersionId:Number(bomVersion.id)};await ensureReleasedRouting(pool,refs,"T06");return refs;
  }catch(error){await client.query("rollback");throw error;}finally{client.release();}
}

async function stock(refs,quantity,expectedVersion=0){const service=new InventoryService(new PostgresInventoryRepository(pool)),key=digest(randomUUID());return service.post({actor:actor("admin"),requestId:randomUUID(),operationId:randomUUID(),keyDigest:key,requestDigest:digest(`stock-${key}`),method:"POST",route:"/test/stock",action:"TEST_STOCK"},{operation_type:"RECEIPT",reason:"隔离采购收货库存",lines:[{material_id:refs.rawId,unit_id:refs.unitId,quantity,expected_balance_version:expectedVersion}]});}
async function directDraft(refs,planned="10"){const result=await production("/api/work-orders",{method:"POST",role:"production",body:{product_id:refs.productId,product_version_id:refs.productVersionId,bom_version_id:refs.bomVersionId,finished_material_id:refs.finishedId,finished_unit_id:refs.unitId,planned_qty:planned,owner:"production01"}});assert.equal(result.response.status,201,JSON.stringify(result.payload));return Number(result.payload.data.id);}

test.beforeEach(async()=>{await pool.query("truncate app_users,units,material_categories,customers,business_code_sequences,idempotency_keys,identity_write_rate_limit_buckets,audit_log restart identity cascade");});
test.after(async()=>pool.end());

test("v1 return, v2 accept, unique draft, reserve 10 and issue 4/6 with no downstream facts",async()=>{
  const refs=await seed();await stock(refs,"10");
  const denied=await handoff(`/api/planning-packages/${refs.packageId}/production-handoffs`,{method:"POST",role:"engineering",body:{items:[{package_item_id:refs.packageItemId,finished_material_id:refs.finishedId}]}});assert.equal(denied.response.status,403);
  const forbidden=await handoff(`/api/planning-packages/${refs.packageId}/production-handoffs`,{method:"POST",role:"planning",body:{product_id:refs.productId,items:[{package_item_id:refs.packageItemId,finished_material_id:refs.finishedId}]}});assert.equal(forbidden.payload.code,"SERVER_MANAGED_FIELD_FORBIDDEN");
  const prepared1=await handoff(`/api/planning-packages/${refs.packageId}/production-handoffs`,{method:"POST",role:"planning",body:{items:[{package_item_id:refs.packageItemId,finished_material_id:refs.finishedId}]}});assert.equal(prepared1.response.status,201,JSON.stringify(prepared1.payload));const handoff1=Number(prepared1.payload.data.id);
  const submitted1=await handoff(`/api/production-handoffs/${handoff1}/submit`,{method:"POST",role:"planning",body:{expected_version:1}});assert.equal(submitted1.response.status,200);
  const returned1=await handoff(`/api/production-handoffs/${handoff1}/return`,{method:"POST",role:"production",body:{expected_version:2,reason:"BOM 资料需修订"}});assert.equal(returned1.payload.data.status,"RETURNED");
  const staleResubmit=await handoff(`/api/production-handoffs/${handoff1}/submit`,{method:"POST",role:"planning",body:{expected_version:3}});assert.equal(staleResubmit.response.status,409);assert.equal(staleResubmit.payload.code,"PRODUCTION_HANDOFF_VERSION_OR_STATE_CONFLICT");
  const prepared2=await handoff(`/api/planning-packages/${refs.packageId}/production-handoffs`,{method:"POST",role:"planning",body:{items:[{package_item_id:refs.packageItemId,finished_material_id:refs.finishedId}]}});assert.equal(prepared2.payload.data.handoff_version_no,2);const handoff2=Number(prepared2.payload.data.id);
  await handoff(`/api/production-handoffs/${handoff2}/submit`,{method:"POST",role:"planning",body:{expected_version:1}});const accepted=await handoff(`/api/production-handoffs/${handoff2}/accept`,{method:"POST",role:"production",body:{expected_version:2}});assert.equal(accepted.payload.data.status,"ACCEPTED");
  const detail=await handoff(`/api/production-handoffs/${handoff2}`,{role:"production"}),handoffItemId=Number(detail.payload.data.items[0].id);
  const created=await handoff(`/api/production-handoff-items/${handoffItemId}/work-order`,{method:"POST",role:"production",key:"handoff-work-order-main",body:{}});assert.equal(created.response.status,201,JSON.stringify(created.payload));const workOrder=created.payload.data.work_order,workOrderId=Number(workOrder.id);
  const replay=await handoff(`/api/production-handoff-items/${handoffItemId}/work-order`,{method:"POST",role:"production",key:"handoff-work-order-main",body:{}});assert.equal(replay.response.headers.get("Idempotency-Replayed"),"true");
  const duplicate=await handoff(`/api/production-handoff-items/${handoffItemId}/work-order`,{method:"POST",role:"production",body:{}});assert.equal(duplicate.payload.code,"PRODUCTION_HANDOFF_WORK_ORDER_EXISTS");
  let facts=(await pool.query("select (select reserved_qty::text from inventory_stock_balances where material_id=$1) reserved,(select count(*)::int from production_material_issues where work_order_id=$2) issues,(select count(*)::int from inventory_ledger_entries where source_type='PRODUCTION_MATERIAL_ISSUE' and source_id=$2) issue_ledger",[refs.rawId,workOrderId])).rows[0];assert.deepEqual(facts,{reserved:"0.000000",issues:0,issue_ledger:0});
  const released=await production(`/api/work-orders/${workOrderId}/release`,{method:"POST",role:"production",body:{expected_version:1}});assert.equal(released.response.status,200,JSON.stringify(released.payload));
  let requirement=(await production(`/api/production/material-requirements?work_order_id=${workOrderId}`,{role:"warehouse"})).payload.rows[0];assert.equal(requirement.required_qty,"10.000000");
  let balance=(await pool.query("select on_hand_qty::text,reserved_qty::text,frozen_qty::text,(on_hand_qty-reserved_qty-frozen_qty)::text available_qty,version from inventory_stock_balances where material_id=$1",[refs.rawId])).rows[0];assert.deepEqual(balance,{on_hand_qty:"10.000000",reserved_qty:"10.000000",frozen_qty:"0.000000",available_qty:"0.000000",version:2});
  const first=await production("/api/production/material-issues",{method:"POST",role:"warehouse",key:"issue-four-main",body:{work_order_id:workOrderId,reason:"首批领料 4",lines:[{requirement_id:Number(requirement.id),quantity:"4",expected_requirement_version:1,expected_balance_version:2}]}});assert.equal(first.response.status,201,JSON.stringify(first.payload));
  const firstReplay=await production("/api/production/material-issues",{method:"POST",role:"warehouse",key:"issue-four-main",body:{work_order_id:workOrderId,reason:"首批领料 4",lines:[{requirement_id:Number(requirement.id),quantity:"4",expected_requirement_version:1,expected_balance_version:2}]}});assert.equal(firstReplay.response.headers.get("Idempotency-Replayed"),"true");
  const conflict=await production("/api/production/material-issues",{method:"POST",role:"warehouse",key:"issue-four-main",body:{work_order_id:workOrderId,reason:"冲突",lines:[{requirement_id:Number(requirement.id),quantity:"3",expected_requirement_version:1,expected_balance_version:2}]}});assert.equal(conflict.payload.code,"IDEMPOTENCY_CONFLICT");
  balance=(await pool.query("select on_hand_qty::text,reserved_qty::text,version from inventory_stock_balances where material_id=$1",[refs.rawId])).rows[0];assert.deepEqual(balance,{on_hand_qty:"6.000000",reserved_qty:"6.000000",version:4});
  requirement=(await production(`/api/production/material-requirements?work_order_id=${workOrderId}`,{role:"warehouse"})).payload.rows[0];assert.equal(requirement.net_issued_qty,"4.000000");
  const over=await production("/api/production/material-issues",{method:"POST",role:"warehouse",body:{work_order_id:workOrderId,lines:[{requirement_id:Number(requirement.id),quantity:"7",expected_requirement_version:2,expected_balance_version:4}]}});assert.equal(over.response.status,409);
  const second=await production("/api/production/material-issues",{method:"POST",role:"warehouse",body:{work_order_id:workOrderId,reason:"第二批领料 6",lines:[{requirement_id:Number(requirement.id),quantity:"6",expected_requirement_version:2,expected_balance_version:4}]}});assert.equal(second.response.status,201,JSON.stringify(second.payload));
  const final=(await pool.query(`select (select on_hand_qty::text from inventory_stock_balances where material_id=$1) on_hand,(select reserved_qty::text from inventory_stock_balances where material_id=$1) reserved,(select net_issued_qty::text from production_material_requirements where work_order_id=$2) issued,(select status from production_work_orders where id=$2) work_status,(select count(*)::int from production_material_issues where work_order_id=$2) issues,(select count(*)::int from production_material_issue_lines l join production_material_issues i on i.id=l.issue_id where i.work_order_id=$2 and l.inventory_ledger_entry_id is not null) ledger,(select count(*)::int from production_reports where work_order_id=$2) reports,(select count(*)::int from production_completions where work_order_id=$2) completions,(select count(*)::int from quality_inspections) quality`,[refs.rawId,workOrderId])).rows[0];assert.deepEqual(final,{on_hand:"0.000000",reserved:"0.000000",issued:"10.000000",work_status:"IN_PROGRESS",issues:2,ledger:2,reports:0,completions:0,quality:0});
  const cancelled=await production(`/api/work-orders/${workOrderId}/cancel`,{method:"POST",role:"production",body:{expected_version:3,reason:"已有领料不得取消"}});assert.equal(cancelled.response.status,409);
});

test("shortage rollback, competing reservations, unused cancellation and return restoration fail closed",async()=>{
  const refs=await seed();
  const shortageId=await directDraft(refs);const shortage=await production(`/api/work-orders/${shortageId}/release`,{method:"POST",role:"production",body:{expected_version:1}});assert.equal(shortage.payload.code,"PRODUCTION_MATERIAL_SHORTAGE");assert.equal(shortage.payload.details.shortages[0].shortage_qty,"10.000000");assert.deepEqual((await pool.query("select (select count(*)::int from production_bom_snapshots where work_order_id=$1) snapshots,(select count(*)::int from production_material_requirements where work_order_id=$1) requirements,(select count(*)::int from production_inventory_reservations where work_order_id=$1) reservations",[shortageId])).rows[0],{snapshots:0,requirements:0,reservations:0});
  await stock(refs,"10");const faultId=await directDraft(refs),faultKey=digest("release-fault"),faultService=new ProductionService(new ProductionRepository(pool),undefined,checkpoint=>{if(checkpoint==="after_material_reservations")throw new Error("forced release failure");});await assert.rejects(faultService.releaseWorkOrder(faultId,{actor:actor("production"),requestId:randomUUID(),operationId:randomUUID(),keyDigest:faultKey,requestDigest:digest("release-fault-body"),method:"POST",route:`/api/work-orders/${faultId}/release`,action:"PRODUCTION_WORK_ORDER_RELEASED"},{expected_version:1}),/服务器暂时无法处理生产请求/);assert.deepEqual((await pool.query("select (select count(*)::int from production_bom_snapshots where work_order_id=$1) snapshots,(select count(*)::int from production_inventory_reservations where work_order_id=$1) reservations,(select reserved_qty::text from inventory_stock_balances where material_id=$2) reserved",[faultId,refs.rawId])).rows[0],{snapshots:0,reservations:0,reserved:"0.000000"});
  const firstId=await directDraft(refs),secondId=await directDraft(refs);const releases=await Promise.all([firstId,secondId].map((id,index)=>production(`/api/work-orders/${id}/release`,{method:"POST",role:"production",key:`competing-release-${index}`,body:{expected_version:1}})));assert.deepEqual(releases.map(item=>item.response.status).sort(),[200,409]);assert.equal((await pool.query("select reserved_qty::text value from inventory_stock_balances where material_id=$1",[refs.rawId])).rows[0].value,"10.000000");const winner=releases[0].response.status===200?firstId:secondId;
  const cancelled=await production(`/api/work-orders/${winner}/cancel`,{method:"POST",role:"production",body:{expected_version:2,reason:"未领料取消"}});assert.equal(cancelled.response.status,200);assert.equal((await pool.query("select reserved_qty::text value from inventory_stock_balances where material_id=$1",[refs.rawId])).rows[0].value,"0.000000");
  const returnId=await directDraft(refs);await production(`/api/work-orders/${returnId}/release`,{method:"POST",role:"production",body:{expected_version:1}});let requirement=(await production(`/api/production/material-requirements?work_order_id=${returnId}`,{role:"warehouse"})).payload.rows[0];await production("/api/production/material-issues",{method:"POST",role:"warehouse",body:{work_order_id:returnId,reason:"领 4",lines:[{requirement_id:Number(requirement.id),quantity:"4",expected_requirement_version:1,expected_balance_version:4}]}});const returned=await production("/api/production/material-returns",{method:"POST",role:"warehouse",body:{work_order_id:returnId,reason:"退 4",lines:[{requirement_id:Number(requirement.id),quantity:"4",expected_requirement_version:2,expected_balance_version:6}]}});assert.equal(returned.response.status,201,JSON.stringify(returned.payload));const restored=(await pool.query("select b.on_hand_qty::text,b.reserved_qty::text,r.net_issued_qty::text from inventory_stock_balances b join production_material_requirements r on r.material_id=b.material_id where r.work_order_id=$1",[returnId])).rows[0];assert.deepEqual(restored,{on_hand_qty:"10.000000",reserved_qty:"10.000000",net_issued_qty:"0.000000"});
  await assert.rejects(pool.query("update production_inventory_reservation_events set quantity=1"),/service write required/);await assert.rejects(pool.query("delete from production_inventory_reservations"),/service write required/);
});
