import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { InventoryService } from "../app/lib/inventory-selfhost/service.ts";
import { PostgresInventoryRepository } from "../app/lib/inventory-selfhost/repository.ts";
import { ProductionError } from "../app/lib/production-selfhost/errors.ts";
import { handleProductionApi } from "../app/lib/production-selfhost/handler.ts";
import { ProductionRepository } from "../app/lib/production-selfhost/repository.ts";
import { ProductionService } from "../app/lib/production-selfhost/service.ts";
import { convertReleasedWorkOrderToLegacyFixture,ensureReleasedRouting } from "./helpers/production-routing.mjs";

const databaseUrl = process.env.TEST_PRODUCTION_DATABASE_URL;
if (!databaseUrl || !/production_test/i.test(databaseUrl)) throw new Error("isolated TEST_PRODUCTION_DATABASE_URL containing production_test is required");
const pool = new Pool({ connectionString: databaseUrl, max: 20, application_name: "production-integration-test" });
const actor = (role, username = `${role}01`) => ({ username, display_name: role, role, is_active: true, must_change_password: false, version: 1, last_login_at: null, permissions: permissionsForRole(role) });

async function api(path, { method = "GET", role = "admin", username, body, key = randomUUID(), csrf = true } = {}) {
  const headers = new Headers({ "X-Request-ID": randomUUID() }); if (body !== undefined) headers.set("Content-Type", "application/json"); if (key) headers.set("Idempotency-Key", key); if (csrf) headers.set("X-CSRF-Token", "test-csrf");
  const request = new Request(`http://local.test${path}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const result = await handleProductionApi(request, { pool, actor: actor(role, username), requestId: headers.get("X-Request-ID"), requireCsrf: () => { if (headers.get("X-CSRF-Token") !== "test-csrf") throw new ProductionError("CSRF_INVALID", "CSRF Token 无效", 403); } });
  assert.ok(result); return { response: result, payload: await result.json() };
}

async function seed() {
  await pool.query(`insert into app_users(username,display_name,role,password_hash) values ('admin01','admin','admin','test-only'),('manager01','manager','manager','test-only'),('production01','production','production','test-only'),('warehouse01','warehouse','warehouse','test-only'),('engineering01','engineering','engineering','test-only'),('quality01','quality','quality','test-only'),('purchase01','purchase','purchase','test-only'),('finance01','finance','finance','test-only')`);
  await pool.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values('PROD_LEAF','生产测试',4,'ACTIVE','test','test',$1)", [randomUUID()]); const category = await pool.query("select id from material_categories where category_code='PROD_LEAF'");
  await pool.query("insert into units(code,name,symbol,unit_type,enabled) values('PCS','件','PCS','COUNT',true),('KG','千克','KG','WEIGHT',true)"); const units = await pool.query("select id,code from units"); const pcs = units.rows.find((row) => row.code === "PCS");
  await pool.query(`insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values
    ('CYD-RAW-000001','原料一',$1,'PCS',$2,'ACTIVE','PURCHASE','STOCKED','IQC','ROHS','MANUAL','test','test','test',$3),
    ('CYD-RAW-000002','原料二',$1,'PCS',$2,'ACTIVE','PURCHASE','STOCKED','IQC','ROHS','MANUAL','test','test','test',$4),
    ('CYD-FG-000001','成品一',$1,'PCS',$2,'ACTIVE','MAKE','STOCKED','FQC','ROHS','MANUAL','test','test','test',$5)`, [category.rows[0].id, pcs.id, randomUUID(), randomUUID(), randomUUID()]); const materials = await pool.query("select id,internal_material_code from material_master order by id");
  const customer = await pool.query("insert into customers(customer_code,customer_name,normalized_name,created_by,updated_by,request_id) values('CUS-PROD','生产客户','生产客户','test','test',$1) returning id", [randomUUID()]);
  const product = await pool.query("insert into products(product_code,product_name,customer_id,created_by,updated_by,request_id) values('PRD-000001','生产产品',$1,'test','test',$2) returning id", [customer.rows[0].id, randomUUID()]);
  const pv = await pool.query("insert into product_versions(product_id,version_no,version_code,status,product_type,lifecycle_status,released_by,released_at,created_by,updated_by,request_id) values($1,1,'A0','RELEASED','PCB','MASS','test',now(),'test','test',$2) returning id", [product.rows[0].id, randomUUID()]);
  const bh = await pool.query("insert into bom_headers(bom_code,product_id,created_by,updated_by,request_id) values('BOM-PROD-001',$1,'test','test',$2) returning id", [product.rows[0].id, randomUUID()]);
  const bv = await pool.query("insert into bom_versions(bom_header_id,product_version_id,version_no,version_code,status,created_by,updated_by,request_id) values($1,$2,1,'A0','DRAFT','test','test',$3) returning id", [bh.rows[0].id, pv.rows[0].id, randomUUID()]);
  await pool.query("insert into bom_lines(bom_version_id,line_no,material_id,quantity_per,unit_id,loss_rate,process_stage,created_by,updated_by,request_id) values($1,1,$2,2,$4,0.1,'SMT','test','test',$5),($1,2,$3,1,$4,0,'组装','test','test',$6)", [bv.rows[0].id, materials.rows[0].id, materials.rows[1].id, pcs.id, randomUUID(), randomUUID()]);
  await pool.query("update bom_versions set status='RELEASED',released_by='test',released_at=now() where id=$1", [bv.rows[0].id]);
  const refs = { customerId: Number(customer.rows[0].id), productId: Number(product.rows[0].id), productVersionId: Number(pv.rows[0].id), bomHeaderId: Number(bh.rows[0].id), bomVersionId: Number(bv.rows[0].id), rawOne: materials.rows[0], rawTwo: materials.rows[1], finished: materials.rows[2], pcs }; await ensureReleasedRouting(pool, refs, "PROD"); return refs;
}

async function stock(materialId, unitId, qty) { const service = new InventoryService(new PostgresInventoryRepository(pool)); const unique = randomUUID(); return service.post({ actor: actor("admin"), requestId: randomUUID(), operationId: randomUUID(), keyDigest: unique.replaceAll("-", "").padEnd(64, "0"), requestDigest: randomUUID().replaceAll("-", "").padEnd(64, "0"), method: "POST", route: "/test/seed-stock", action: "TEST_STOCK_SEED" }, { operation_type: "RECEIPT", reason: "隔离测试初始库存", lines: [{ material_id: materialId, unit_id: unitId, quantity: qty, expected_balance_version: 0 }] }); }
function workOrderBody(refs, planned = "10") { return { product_id: refs.productId, product_version_id: refs.productVersionId, bom_version_id: refs.bomVersionId, finished_material_id: Number(refs.finished.id), finished_unit_id: Number(refs.pcs.id), planned_qty: planned, planned_start: "2026-08-01T00:00:00Z", planned_finish: "2026-08-02T00:00:00Z", owner: "计划员", remark: "隔离生产" }; }
async function createReleased(refs, planned = "10") { const created = await api("/api/work-orders", { method: "POST", role: "production", body: workOrderBody(refs, planned) }); assert.equal(created.response.status, 201); const workOrderId = Number(created.payload.data.id); const released = await api(`/api/work-orders/${workOrderId}/release`, { method: "POST", role: "production", body: { expected_version: 1 } }); assert.equal(released.response.status, 200); await convertReleasedWorkOrderToLegacyFixture(pool,workOrderId); return { workOrderId, created, released }; }

test.beforeEach(async () => { await pool.query(`truncate production_completion_lines,production_completions,production_reports,production_material_return_lines,production_material_returns,production_material_issue_lines,production_material_issues,production_material_requirements,production_bom_snapshot_lines,production_bom_snapshots,production_work_order_status_events,production_work_orders,material_customer_restrictions,purchase_financial_source_entries,purchase_receipt_lines,purchase_receipts,purchase_order_status_events,purchase_order_source_links,purchase_order_lines,purchase_orders,inventory_adjustment_lines,inventory_ledger_entries,inventory_stock_balances,inventory_adjustments,bom_lines,bom_versions,bom_headers,product_versions,products,customers,supplier_mapping_price_history,supplier_mappings,suppliers,business_code_sequences,identity_write_rate_limit_buckets,idempotency_keys,audit_log,app_users,material_master,units,material_categories restart identity cascade`); });
test.after(async () => pool.end());

test("work order release snapshots decimal BOM then issue report allocate complete and close atomically", async () => {
  const refs = await seed(); await stock(Number(refs.rawOne.id), Number(refs.pcs.id), "30"); await stock(Number(refs.rawTwo.id), Number(refs.pcs.id), "20");
  const body = workOrderBody(refs); const created = await api("/api/work-orders", { method: "POST", role: "production", key: "production-create-0001", body }); assert.equal(created.response.status, 201); assert.match(created.payload.work_order_code, /^WO-\d{6}$/); const replay = await api("/api/work-orders", { method: "POST", role: "production", key: "production-create-0001", body }); assert.equal(replay.response.headers.get("Idempotency-Replayed"), "true"); const conflict = await api("/api/work-orders", { method: "POST", role: "production", key: "production-create-0001", body: { ...body, remark: "不同正文" } }); assert.equal(conflict.response.status, 409);
  const workOrderId = Number(created.payload.data.id); const release = await api(`/api/work-orders/${workOrderId}/release`, { method: "POST", role: "production", body: { expected_version: 1 } }); assert.equal(release.response.status, 200); const requirements = await api(`/api/production/material-requirements?work_order_id=${workOrderId}`, { role: "engineering" }); assert.deepEqual(requirements.payload.rows.map((row) => row.required_qty), ["22.000000", "10.000000"]); const snapshotBefore = await api(`/api/work-orders/${workOrderId}/bom-snapshot`, { role: "engineering" });
  await pool.query("insert into bom_versions(bom_header_id,product_version_id,version_no,version_code,status,released_by,released_at,created_by,updated_by,request_id) values($1,$2,2,'B0','RELEASED','test',now(),'test','test',$3)", [refs.bomHeaderId, refs.productVersionId, randomUUID()]); const snapshotAfter = await api(`/api/work-orders/${workOrderId}/bom-snapshot`, { role: "engineering" }); assert.deepEqual(snapshotAfter.payload.data, snapshotBefore.payload.data); await convertReleasedWorkOrderToLegacyFixture(pool,workOrderId);
  const issueBody={ work_order_id: workOrderId, reason: "完整领料", lines: requirements.payload.rows.map(row=>({requirement_id:Number(row.id),quantity:row.required_qty,expected_requirement_version:1,expected_balance_version:2}))};const issued = await api("/api/production/material-issues", { method: "POST", role: "warehouse", key: "production-issue-0001", body:issueBody }); assert.equal(issued.response.status, 201); assert.equal((await api("/api/production/material-issues", { method: "POST", role: "warehouse", key: "production-issue-0001", body:issueBody })).response.headers.get("Idempotency-Replayed"), "true");
  const firstReport = await api("/api/production/reports", { method: "POST", role: "production", body: { work_order_id: workOrderId, expected_version: 3, reported_qty: "4", good_qty: "4", scrap_qty: "0", process_stage: "终检前", operator: "班组A" } }); assert.equal(firstReport.response.status, 201);
  const partial = await api("/api/production/completions", { method: "POST", role: "warehouse", body: { work_order_id: workOrderId, expected_version: 4, expected_balance_version: 0, reason: "首批完工",allocations:[{report_id:Number(firstReport.payload.data.id),quantity:"4",expected_report_version:1}] } }); assert.equal(partial.response.status, 201); assert.equal(partial.payload.data.work_order.status, "IN_PROGRESS");
  const secondReport = await api("/api/production/reports", { method: "POST", role: "production", body: { work_order_id: workOrderId, expected_version: 5, reported_qty: "6", good_qty: "6", scrap_qty: "0", process_stage: "终检前", operator: "班组A" } }); assert.equal(secondReport.response.status, 201);
  const final = await api("/api/production/completions", { method: "POST", role: "warehouse", body: { work_order_id: workOrderId, expected_version: 6, expected_balance_version: 1, reason: "全部完工",allocations:[{report_id:Number(secondReport.payload.data.id),quantity:"6",expected_report_version:1}] } }); assert.equal(final.response.status, 201); assert.equal(final.payload.data.work_order.status, "COMPLETED");
  const closed = await api(`/api/work-orders/${workOrderId}/close`, { method: "POST", role: "manager", body: { expected_version: 7, reason: "生产归档" } }); assert.equal(closed.response.status, 200); assert.equal(closed.payload.data.status, "CLOSED");
  const balances = await pool.query("select material_id,on_hand_qty,version from inventory_stock_balances order by material_id"); assert.deepEqual(balances.rows.map((row) => row.on_hand_qty), ["8.000000", "10.000000", "10.000000"]); const req = await pool.query("select net_issued_qty,version from production_material_requirements order by id"); assert.deepEqual(req.rows.map(row=>row.net_issued_qty),["22.000000","10.000000"]); const reconcile = await pool.query(`select count(*)::int mismatches from inventory_stock_balances b left join (select balance_id,sum(on_hand_delta) qty from inventory_ledger_entries group by balance_id) l on l.balance_id=b.id where b.on_hand_qty<>coalesce(l.qty,0)`); assert.equal(reconcile.rows[0].mismatches, 0); assert.equal(Number((await pool.query("select count(*) count from erp_records where kind in ('work_order','production_report','financial_document')")).rows[0].count), 0);
  await assert.rejects(pool.query("update production_bom_snapshot_lines set quantity_per=99"), /posted production records are immutable/); await assert.rejects(pool.query("update production_reports set good_qty=0"), /posted production records are immutable/);
});

test("permissions, customer restriction, over issue/return/report/completion and concurrent completion fail closed", async () => {
  const refs = await seed(); await stock(Number(refs.rawOne.id), Number(refs.pcs.id), "100"); await stock(Number(refs.rawTwo.id), Number(refs.pcs.id), "100");
  assert.equal((await api("/api/work-orders", { method: "POST", role: "warehouse", body: workOrderBody(refs) })).response.status, 403); assert.equal((await api("/api/work-orders", { method: "POST", role: "production", csrf: false, body: workOrderBody(refs) })).response.status, 403);
  const other = await pool.query("insert into customers(customer_code,customer_name,normalized_name,created_by,updated_by,request_id) values('CUS-OTHER','其他客户','其他客户','test','test',$1) returning id", [randomUUID()]); await pool.query("insert into material_customer_restrictions(material_id,customer_id,created_by,request_id) values($1,$2,'admin01',$3)", [refs.rawOne.id, other.rows[0].id, randomUUID()]); const blocked = await api("/api/work-orders", { method: "POST", role: "production", body: workOrderBody(refs) }); const blockedId = Number(blocked.payload.data.id); const blockedRelease = await api(`/api/work-orders/${blockedId}/release`, { method: "POST", role: "production", body: { expected_version: 1 } }); assert.equal(blockedRelease.response.status, 422); assert.equal(blockedRelease.payload.code, "MATERIAL_CUSTOMER_RESTRICTED"); await pool.query("truncate material_customer_restrictions restart identity");
  const { workOrderId } = await createReleased(refs, "10"); const requirements = (await api(`/api/production/material-requirements?work_order_id=${workOrderId}`)).payload.rows; const first = requirements[0];
  const overIssue = await api("/api/production/material-issues", { method: "POST", role: "warehouse", body: { work_order_id: workOrderId, lines: [{ requirement_id: Number(first.id), quantity: "23", expected_requirement_version: 1, expected_balance_version: 2 }] } }); assert.equal(overIssue.response.status, 409); assert.equal(overIssue.payload.code, "PRODUCTION_ISSUE_OVER_REQUIREMENT");
  const issue = await api("/api/production/material-issues", { method: "POST", role: "warehouse", body: { work_order_id: workOrderId, lines: [{ requirement_id: Number(first.id), quantity: "5", expected_requirement_version: 1, expected_balance_version: 2 }] } }); assert.equal(issue.response.status, 201);
  const overReturn = await api("/api/production/material-returns", { method: "POST", role: "warehouse", body: { work_order_id: workOrderId, reason: "超退", lines: [{ requirement_id: Number(first.id), quantity: "6", expected_requirement_version: 2, expected_balance_version: 4 }] } }); assert.equal(overReturn.response.status, 409); assert.equal(overReturn.payload.code, "PRODUCTION_RETURN_OVER_ISSUED");
  const badReport = await api("/api/production/reports", { method: "POST", role: "production", body: { work_order_id: workOrderId, expected_version: 3, reported_qty: "2", good_qty: "2", scrap_qty: "1", process_stage: "测试" } }); assert.equal(badReport.response.status, 409);
  const remainingIssue=await api("/api/production/material-issues",{method:"POST",role:"warehouse",body:{work_order_id:workOrderId,reason:"补齐领料",lines:[{requirement_id:Number(requirements[0].id),quantity:"17",expected_requirement_version:2,expected_balance_version:4},{requirement_id:Number(requirements[1].id),quantity:"10",expected_requirement_version:1,expected_balance_version:2}]}});assert.equal(remainingIssue.response.status,201);
  const report=await api("/api/production/reports",{method:"POST",role:"production",body:{work_order_id:workOrderId,expected_version:3,reported_qty:"6",good_qty:"6",scrap_qty:"0",process_stage:"测试"}});assert.equal(report.response.status,201);const allocation={report_id:Number(report.payload.data.id),quantity:"6",expected_report_version:1};
  const concurrent = await Promise.all(["A", "B"].map((suffix) => api("/api/production/completions", { method: "POST", role: "warehouse", key: `production-completion-${suffix}`, body: { work_order_id: workOrderId, expected_version: 4, expected_balance_version: 0, reason: suffix,allocations:[allocation] } }))); assert.deepEqual(concurrent.map((item) => item.response.status).sort(), [201, 409]); assert.equal((await pool.query("select completed_qty from production_work_orders where id=$1", [workOrderId])).rows[0].completed_qty, "6.000000"); assert.equal((await pool.query("select on_hand_qty from inventory_stock_balances where material_id=$1", [refs.finished.id])).rows[0].on_hand_qty, "6.000000");
  const overComplete = await api("/api/production/completions", { method: "POST", role: "warehouse", body: { work_order_id: workOrderId, expected_version: 5, expected_balance_version: 1, reason: "重复消费",allocations:[{...allocation,quantity:"1",expected_report_version:2}] } }); assert.equal(overComplete.response.status, 409); assert.equal(overComplete.payload.code, "PRODUCTION_REPORT_GOOD_EXHAUSTED");
});

test("concurrent work-order coding, release, issue and return preserve one snapshot and bounded quantities", async () => {
  const refs = await seed(); await stock(Number(refs.rawOne.id), Number(refs.pcs.id), "100"); await stock(Number(refs.rawTwo.id), Number(refs.pcs.id), "100");
  const created = await Promise.all(["A", "B"].map((suffix) => api("/api/work-orders", { method: "POST", role: "production", key: `production-concurrent-create-${suffix}`, body: { ...workOrderBody(refs), remark: suffix } })));
  assert.deepEqual(created.map((item) => item.response.status), [201, 201]); assert.equal(new Set(created.map((item) => item.payload.work_order_code)).size, 2);
  const workOrderId = Number(created[0].payload.work_order_id); const releases = await Promise.all(["A", "B"].map((suffix) => api(`/api/work-orders/${workOrderId}/release`, { method: "POST", role: "production", key: `production-concurrent-release-${suffix}`, body: { expected_version: 1 } })));
  assert.deepEqual(releases.map((item) => item.response.status).sort(), [200, 409]); assert.equal(Number((await pool.query("select count(*) count from production_bom_snapshots where work_order_id=$1", [workOrderId])).rows[0].count), 1); assert.equal(Number((await pool.query("select count(*) count from production_material_requirements where work_order_id=$1", [workOrderId])).rows[0].count), 2);
  const requirement = (await api(`/api/production/material-requirements?work_order_id=${workOrderId}`)).payload.rows[0]; const issues = await Promise.all(["A", "B"].map((suffix) => api("/api/production/material-issues", { method: "POST", role: "warehouse", key: `production-concurrent-issue-${suffix}`, body: { work_order_id: workOrderId, reason: suffix, lines: [{ requirement_id: Number(requirement.id), quantity: "12", expected_requirement_version: 1, expected_balance_version: 2 }] } })));
  assert.deepEqual(issues.map((item) => item.response.status).sort(), [201, 409]); assert.equal((await pool.query("select net_issued_qty from production_material_requirements where id=$1", [requirement.id])).rows[0].net_issued_qty, "12.000000"); assert.equal(Number((await pool.query("select count(*) count from production_material_issue_lines where requirement_id=$1", [requirement.id])).rows[0].count), 1);
  const returns = await Promise.all(["A", "B"].map((suffix) => api("/api/production/material-returns", { method: "POST", role: "warehouse", key: `production-concurrent-return-${suffix}`, body: { work_order_id: workOrderId, reason: suffix, lines: [{ requirement_id: Number(requirement.id), quantity: "7", expected_requirement_version: 2, expected_balance_version: 4 }] } })));
  assert.deepEqual(returns.map((item) => item.response.status).sort(), [201, 409]); assert.equal((await pool.query("select net_issued_qty from production_material_requirements where id=$1", [requirement.id])).rows[0].net_issued_qty, "5.000000"); assert.equal(Number((await pool.query("select count(*) count from production_material_return_lines where requirement_id=$1", [requirement.id])).rows[0].count), 1);
});

test("inventory fault and audit fault roll back every production, ledger, balance, audit and idempotency write", async () => {
  const refs = await seed(); await stock(Number(refs.rawOne.id),Number(refs.pcs.id),"11");await stock(Number(refs.rawTwo.id),Number(refs.pcs.id),"5");const { workOrderId } = await createReleased(refs, "5");const requirements=(await api(`/api/production/material-requirements?work_order_id=${workOrderId}`)).payload.rows;assert.equal((await api("/api/production/material-issues",{method:"POST",role:"warehouse",body:{work_order_id:workOrderId,lines:requirements.map(row=>({requirement_id:Number(row.id),quantity:row.required_qty,expected_requirement_version:1,expected_balance_version:2}))}})).response.status,201);const report=await api("/api/production/reports",{method:"POST",role:"production",body:{work_order_id:workOrderId,expected_version:3,reported_qty:"2",good_qty:"2",scrap_qty:"0",process_stage:"故障前"}});assert.equal(report.response.status,201); const service = new ProductionService(new ProductionRepository(pool), undefined, (checkpoint) => { if (checkpoint === "after_completion_inventory") throw new Error("forced production rollback"); }); const meta = { actor: actor("warehouse"), requestId: randomUUID(), operationId: randomUUID(), keyDigest: "f".repeat(64), requestDigest: "e".repeat(64), method: "POST", route: "/api/production/completions", action: "PRODUCTION_COMPLETED" };
  await assert.rejects(service.complete(meta, { work_order_id: workOrderId, expected_version: 4, expected_balance_version: 0, reason: "故障注入",allocations:[{report_id:Number(report.payload.data.id),quantity:"2",expected_report_version:1}] }), /服务器暂时无法处理生产请求/); assert.equal(Number((await pool.query("select count(*) count from production_completions")).rows[0].count), 0); assert.equal(Number((await pool.query("select count(*) count from inventory_ledger_entries")).rows[0].count), 4); assert.equal(Number((await pool.query("select count(*) count from inventory_stock_balances")).rows[0].count), 2); assert.equal((await pool.query("select completed_qty,version from production_work_orders where id=$1", [workOrderId])).rows[0].completed_qty, "0.000000"); assert.equal(Number((await pool.query("select count(*) count from idempotency_keys where key_digest=$1", [meta.keyDigest])).rows[0].count), 0);
  await pool.query(`create or replace function fail_production_audit_for_test() returns trigger language plpgsql as $$ begin if new.action='PRODUCTION_REPORTED' then raise exception 'forced production audit failure'; end if; return new; end $$`); await pool.query("create trigger fail_production_audit_for_test before insert on audit_log for each row execute function fail_production_audit_for_test()"); const failed = await api("/api/production/reports", { method: "POST", role: "production", key: "production-audit-rollback", body: { work_order_id: workOrderId, expected_version: 4, reported_qty: "1", good_qty: "1", scrap_qty: "0", process_stage: "故障" } }); assert.equal(failed.response.status, 500); assert.equal(Number((await pool.query("select count(*) count from production_reports")).rows[0].count), 1); assert.deepEqual((await pool.query("select reported_qty,status,version from production_work_orders where id=$1", [workOrderId])).rows[0], { reported_qty: "2.000000", status: "IN_PROGRESS", version: 4 }); await pool.query("drop trigger fail_production_audit_for_test on audit_log; drop function fail_production_audit_for_test()");
});

test("legacy adapters require stable finished material and preserve service permission boundaries", async () => {
  const refs = await seed(); await stock(Number(refs.rawOne.id), Number(refs.pcs.id), "30"); await stock(Number(refs.rawTwo.id), Number(refs.pcs.id), "20"); const created = await api("/api/work-orders/from-bom", { method: "POST", role: "production", body: { bom_id: refs.bomHeaderId, finished_material_id: Number(refs.finished.id), order_qty: "2", owner: "计划" } }); assert.equal(created.response.status, 201); const workOrderId = Number(created.payload.work_order_id); await convertReleasedWorkOrderToLegacyFixture(pool,workOrderId); assert.equal((await api("/api/work-orders/issue-materials", { method: "POST", role: "production", body: { work_order_id: workOrderId } })).response.status, 403); const issued = await api("/api/work-orders/issue-materials", { method: "POST", role: "warehouse", body: { work_order_id: workOrderId } }); assert.equal(issued.response.status, 201); assert.equal(issued.payload.issued.length, 2); assert.equal((await api("/api/work-orders/complete", { method: "POST", role: "warehouse", body: { work_order_id: workOrderId, good_qty: "1", scrap_qty: "0", operator: "仓库" } })).response.status, 403); const completed = await api("/api/work-orders/complete", { method: "POST", role: "manager", body: { work_order_id: workOrderId, good_qty: "2", scrap_qty: "0", operator: "联合岗位" } }); assert.equal(completed.response.status, 201); assert.equal(completed.payload.after_qty, "2.000000");
});
