import assert from "node:assert/strict";
import { createHash,randomUUID } from "node:crypto";
import test from "node:test";
import { Pool } from "pg";
import { permissionsForRole } from "../app/lib/identity-selfhost/permissions.ts";
import { InventoryService } from "../app/lib/inventory-selfhost/service.ts";
import { PostgresInventoryRepository } from "../app/lib/inventory-selfhost/repository.ts";
import { ProductionOperationService } from "../app/lib/production-operation-selfhost/service.ts";
import { ProductionError } from "../app/lib/production-selfhost/errors.ts";
import { handleProductionApi } from "../app/lib/production-selfhost/handler.ts";
import { ProductionRepository } from "../app/lib/production-selfhost/repository.ts";
import { ProductionService } from "../app/lib/production-selfhost/service.ts";
import { ensureReleasedRouting } from "./helpers/production-routing.mjs";

const databaseUrl=process.env.TEST_PRODUCTION_FINAL_OUTPUT_DATABASE_URL;
if(!databaseUrl||!/production_final_output_test/i.test(databaseUrl))throw new Error("isolated TEST_PRODUCTION_FINAL_OUTPUT_DATABASE_URL containing production_final_output_test is required");
const pool=new Pool({connectionString:databaseUrl,max:20,application_name:"production-final-output-integration-test"});
const actor=(role,username=`${role}01`)=>({username,display_name:role,role,is_active:true,must_change_password:false,version:1,last_login_at:null,permissions:permissionsForRole(role)});
const sha=value=>createHash("sha256").update(String(value)).digest("hex");
const meta=(role,action,key=randomUUID(),username)=>({actor:actor(role,username),requestId:randomUUID(),operationId:randomUUID(),keyDigest:sha(`${role}:${action}:${key}`),requestDigest:sha(`body:${action}:${key}`),method:"POST",route:`/test/task03/${action}`,action});
async function api(path,{method="GET",role="admin",username,body,key=randomUUID(),csrf=true}={}){const headers=new Headers({"X-Request-ID":randomUUID()});if(body!==undefined)headers.set("Content-Type","application/json");if(key)headers.set("Idempotency-Key",key);if(csrf)headers.set("X-CSRF-Token","task03-csrf");const response=await handleProductionApi(new Request(`http://local.test${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),{pool,actor:actor(role,username),requestId:headers.get("X-Request-ID"),requireCsrf:()=>{if(headers.get("X-CSRF-Token")!=="task03-csrf")throw new ProductionError("CSRF_INVALID","CSRF Token 无效",403);}});assert.ok(response);return{response,payload:await response.json()};}

async function seed(prefix=randomUUID().slice(0,6).toUpperCase()){
  const users=[["admin01","admin"],["manager01","manager"],["production01","production"],["production02","production"],["warehouse01","warehouse"],["quality01","quality"],["sales01","sales"],["finance01","finance"],["engineering01","engineering"],["planning01","planning"],["purchase01","purchase"],["operations01","operations"]];
  for(const [username,role] of users)await pool.query("insert into app_users(username,display_name,role,password_hash,is_active) values($1,$1,$2,'test-only',true) on conflict(username) do nothing",[username,role]);
  const category=(await pool.query("insert into material_categories(category_code,category_name_cn,category_level,status,created_by,updated_by,request_id) values($1,$2,4,'ACTIVE','admin01','admin01',$3) returning id",[`T27-${prefix}`,`TASK03 ${prefix}`,randomUUID()])).rows[0];
  const unit=(await pool.query("insert into units(code,name,symbol,unit_type,enabled) values($1,$2,$1,'COUNT',true) returning id",[`U${prefix}`,`件${prefix}`])).rows[0];
  const materials=(await pool.query(`insert into material_master(internal_material_code,standard_name,category_id,base_uom,base_unit_id,material_status,procurement_type,inventory_type,inspection_type,environmental_requirement,source_type,last_modified_by,created_by,updated_by,request_id) values ($1,$2,$3,$4,$5,'ACTIVE','PURCHASE','STOCKED','NONE','ROHS','MANUAL','admin01','admin01','admin01',$6),($7,$8,$3,$4,$5,'ACTIVE','MAKE','STOCKED','NONE','ROHS','MANUAL','admin01','admin01','admin01',$9) returning id,internal_material_code`,[`RAW-${prefix}`,`TASK03 原料 ${prefix}`,category.id,`U${prefix}`,unit.id,randomUUID(),`FG-${prefix}`,`TASK03 成品 ${prefix}`,randomUUID()])).rows;
  const raw=materials.find(row=>row.internal_material_code===`RAW-${prefix}`),finished=materials.find(row=>row.internal_material_code===`FG-${prefix}`);
  const customer=(await pool.query("insert into customers(customer_code,customer_name,normalized_name,created_by,updated_by,request_id) values($1,$2,$2,'admin01','admin01',$3) returning id",[`C-${prefix}`,`客户${prefix}`,randomUUID()])).rows[0];
  const product=(await pool.query("insert into products(product_code,product_name,customer_id,status,created_by,updated_by,request_id) values($1,$2,$3,'ACTIVE','admin01','admin01',$4) returning id",[`P-${prefix}`,`产品${prefix}`,customer.id,randomUUID()])).rows[0];
  const pv=(await pool.query("insert into product_versions(product_id,version_no,version_code,status,product_type,lifecycle_status,released_by,released_at,created_by,updated_by,request_id) values($1,1,'A0','RELEASED','PCB','MASS','admin01',now(),'admin01','admin01',$2) returning id",[product.id,randomUUID()])).rows[0];
  const bh=(await pool.query("insert into bom_headers(bom_code,product_id,status,created_by,updated_by,request_id) values($1,$2,'ACTIVE','admin01','admin01',$3) returning id",[`B-${prefix}`,product.id,randomUUID()])).rows[0];
  const bv=(await pool.query("insert into bom_versions(bom_header_id,product_version_id,version_no,version_code,status,created_by,updated_by,request_id) values($1,$2,1,'A0','DRAFT','admin01','admin01',$3) returning id",[bh.id,pv.id,randomUUID()])).rows[0];
  await pool.query("insert into bom_lines(bom_version_id,line_no,material_id,quantity_per,unit_id,loss_rate,process_stage,created_by,updated_by,request_id) values($1,1,$2,1,$3,0,'LEGACY','admin01','admin01',$4)",[bv.id,raw.id,unit.id,randomUUID()]);await pool.query("update bom_versions set status='RELEASED',released_by='admin01',released_at=now() where id=$1",[bv.id]);
  const inventory=new InventoryService(new PostgresInventoryRepository(pool));await inventory.post(meta("admin","TASK03_STOCK"),{operation_type:"RECEIPT",reason:"TASK03 隔离原料",lines:[{material_id:Number(raw.id),unit_id:Number(unit.id),quantity:"100",expected_balance_version:0}]});
  const refs={rawId:Number(raw.id),finishedId:Number(finished.id),unitId:Number(unit.id),productId:Number(product.id),productVersionId:Number(pv.id),bomVersionId:Number(bv.id)};await ensureReleasedRouting(pool,refs,`T27${prefix}`);
  return refs;
}
async function createIssued(refs,planned="10"){
  const production=new ProductionService(new ProductionRepository(pool)),created=await production.createWorkOrder(meta("production","WORK_ORDER_CREATE"),{product_id:refs.productId,product_version_id:refs.productVersionId,bom_version_id:refs.bomVersionId,finished_material_id:refs.finishedId,finished_unit_id:refs.unitId,planned_qty:planned,owner:"production01"}),workOrderId=Number(created.body.data.id);
  await production.releaseWorkOrder(workOrderId,meta("production","WORK_ORDER_RELEASE"),{expected_version:1});const requirement=(await pool.query("select * from production_material_requirements where work_order_id=$1",[workOrderId])).rows[0],balance=(await pool.query("select version from inventory_stock_balances where material_id=$1 and location_code='MAIN' and lot_code=''",[refs.rawId])).rows[0];
  await production.issueMaterials(meta("warehouse","MATERIAL_ISSUE"),{work_order_id:workOrderId,reason:"完整领料",lines:[{requirement_id:Number(requirement.id),quantity:planned,expected_requirement_version:Number(requirement.version),expected_balance_version:Number(balance.version)}]});return workOrderId;
}
async function executeFinal(workOrderId,batches){const service=new ProductionOperationService(new ProductionRepository(pool)),reports=[];for(const batch of batches){const op=(await service.operations(workOrderId)).rows.at(-1),dispatched=await service.dispatch(meta("production","OPERATION_DISPATCH"),{snapshot_operation_id:Number(op.snapshot_operation_id),quantity:String(batch),assigned_operator:"production01",expected_operation_version:Number(op.version)}),run=dispatched.body.data,started=await service.start(Number(run.id),meta("production","OPERATION_START"),{expected_version:Number(run.version)}),reported=await service.report(Number(run.id),meta("production","OPERATION_REPORT"),{expected_version:Number(started.body.data.version),processed_qty:String(batch),good_qty:String(batch),scrap_qty:"0"});reports.push({runId:Number(run.id),runVersion:Number(reported.body.data.run.version),reportId:Number(reported.body.data.report.id),quantity:String(batch)});}return reports;}
const state=workOrderId=>pool.query(`select wo.*,w.version final_output_version,w.final_output_available_qty::text from production_work_orders wo join production_work_order_operation_projections p on p.work_order_id=wo.id and p.next_snapshot_operation_id is null join production_operation_wip_projections w on w.operation_projection_id=p.id where wo.id=$1`,[workOrderId]).then(result=>result.rows[0]);
const reportBody=(workOrderId,workOrderVersion,finalVersion,source,quantity=source.quantity)=>({work_order_id:workOrderId,expected_work_order_version:workOrderVersion,expected_final_output_version:finalVersion,final_output_allocations:[{operation_run_report_id:source.reportId,quantity}],remark:"TASK03 稳定来源"});

test.beforeEach(async()=>{await pool.query("truncate app_users,units,material_categories,customers,business_code_sequences,idempotency_keys,identity_write_rate_limit_buckets,audit_log restart identity cascade");});
test.after(()=>pool.end());

test("stable final Run Reports 4/6 create formal reports 4/6 then existing completions and finished inventory 4/6",async()=>{
  const refs=await seed(),workOrderId=await createIssued(refs),sources=await executeFinal(workOrderId,[4,6]);let current=await state(workOrderId);assert.equal(current.final_output_available_qty,"10.000000");
  const firstBody=reportBody(workOrderId,Number(current.version),Number(current.final_output_version),sources[0]),first=await api("/api/production/reports",{method:"POST",role:"production",key:"task03-report-first",body:firstBody});assert.equal(first.response.status,201,JSON.stringify(first.payload));const replay=await api("/api/production/reports",{method:"POST",role:"production",key:"task03-report-first",body:firstBody});assert.equal(replay.response.headers.get("Idempotency-Replayed"),"true");assert.equal(replay.payload.data.id,first.payload.data.id);const conflict=await api("/api/production/reports",{method:"POST",role:"production",key:"task03-report-first",body:{...firstBody,remark:"异正文"}});assert.equal(conflict.payload.code,"IDEMPOTENCY_CONFLICT");
  current=await state(workOrderId);assert.equal(current.final_output_available_qty,"6.000000");const second=await api("/api/production/reports",{method:"POST",role:"production",body:reportBody(workOrderId,Number(current.version),Number(current.final_output_version),sources[1])});assert.equal(second.response.status,201,JSON.stringify(second.payload));current=await state(workOrderId);assert.equal(current.final_output_available_qty,"0.000000");
  assert.deepEqual((await pool.query("select quantity from production_report_operation_allocations order by id")).rows.map(row=>row.quantity),["4.000000","6.000000"]);for(const table of ["production_completions","quality_inspections","sales_shipments","sales_financial_source_entries"])assert.equal(Number((await pool.query(`select count(*) count from ${table}`)).rows[0].count),0,table);assert.equal(Number((await pool.query("select count(*) count from inventory_ledger_entries where material_id=$1",[refs.finishedId])).rows[0].count),0);
  let wo=await state(workOrderId),completion1=await api("/api/production/completions",{method:"POST",role:"warehouse",body:{work_order_id:workOrderId,expected_version:Number(wo.version),expected_balance_version:0,reason:"TASK03 成品入库 4",allocations:[{report_id:Number(first.payload.data.id),quantity:"4",expected_report_version:1}]}});assert.equal(completion1.response.status,201,JSON.stringify(completion1.payload));wo=await state(workOrderId);const completion2=await api("/api/production/completions",{method:"POST",role:"warehouse",body:{work_order_id:workOrderId,expected_version:Number(wo.version),expected_balance_version:1,reason:"TASK03 成品入库 6",allocations:[{report_id:Number(second.payload.data.id),quantity:"6",expected_report_version:1}]}});assert.equal(completion2.response.status,201,JSON.stringify(completion2.payload));
  const final=await state(workOrderId);assert.deepEqual({planned:final.planned_qty,reported:final.reported_qty,good:final.good_qty,scrap:final.scrap_qty,completed:final.completed_qty,status:final.status,output:final.final_output_available_qty},{planned:"10.000000",reported:"10.000000",good:"10.000000",scrap:"0.000000",completed:"10.000000",status:"COMPLETED",output:"0.000000"});assert.deepEqual((await pool.query("select quantity from production_completion_report_allocations order by id")).rows.map(row=>row.quantity),["4.000000","6.000000"]);assert.deepEqual((await pool.query("select on_hand_delta from inventory_ledger_entries where material_id=$1 order by id",[refs.finishedId])).rows.map(row=>row.on_hand_delta),["4.000000","6.000000"]);assert.equal((await pool.query("select on_hand_qty from inventory_stock_balances where material_id=$1",[refs.finishedId])).rows[0].on_hand_qty,"10.000000");for(const table of ["quality_inspections","sales_shipments","sales_financial_source_entries"])assert.equal(Number((await pool.query(`select count(*) count from ${table}`)).rows[0].count),0);assert.equal(Number((await pool.query("select count(*) count from finance_documents where doc_type='AR'")).rows[0].count),0);
});

test("append-only reversals restore final output only after downstream completion is safely reversed",async()=>{
  const refs=await seed(),workOrderId=await createIssued(refs),[source]=await executeFinal(workOrderId,[10]);let wo=await state(workOrderId),reported=await api("/api/production/reports",{method:"POST",role:"production",body:reportBody(workOrderId,Number(wo.version),Number(wo.final_output_version),source)});assert.equal(reported.response.status,201);
  const runBlocked=new ProductionOperationService(new ProductionRepository(pool));await assert.rejects(runBlocked.reverse(source.runId,meta("manager","OPERATION_REVERSE"),{expected_version:source.runVersion,reason:"已有正式报工"}),error=>error.code==="OPERATION_RUN_DOWNSTREAM_CONSUMED");
  wo=await state(workOrderId);const reversed=await api(`/api/production/reports/${reported.payload.data.id}/reverse`,{method:"POST",role:"production",body:{expected_report_version:1,expected_work_order_version:Number(wo.version),reason:"无下游安全冲销"}});assert.equal(reversed.response.status,201,JSON.stringify(reversed.payload));assert.equal((await state(workOrderId)).final_output_available_qty,"10.000000");assert.equal(Number((await pool.query("select count(*) count from production_reports where work_order_id=$1",[workOrderId])).rows[0].count),1);
  wo=await state(workOrderId);reported=await api("/api/production/reports",{method:"POST",role:"production",body:reportBody(workOrderId,Number(wo.version),Number(wo.final_output_version),source)});wo=await state(workOrderId);const completion=await api("/api/production/completions",{method:"POST",role:"warehouse",body:{work_order_id:workOrderId,expected_version:Number(wo.version),expected_balance_version:0,reason:"TASK03 入库",allocations:[{report_id:Number(reported.payload.data.id),quantity:"10",expected_report_version:1}]}});assert.equal(completion.response.status,201);
  wo=await state(workOrderId);const blocked=await api(`/api/production/reports/${reported.payload.data.id}/reverse`,{method:"POST",role:"production",body:{expected_report_version:2,expected_work_order_version:Number(wo.version),reason:"已有 Completion"}});assert.equal(blocked.payload.code,"WORK_ORDER_STATE_CONFLICT");
  const completionReversal=await api(`/api/production/completions/${completion.payload.data.id}/reverse`,{method:"POST",role:"warehouse",body:{expected_completion_version:1,expected_work_order_version:Number(wo.version),reason:"安全冲销入库",expected_balance_versions:[{material_id:refs.finishedId,expected_balance_version:1}]}});assert.equal(completionReversal.response.status,201,JSON.stringify(completionReversal.payload));wo=await state(workOrderId);const finalReverse=await api(`/api/production/reports/${reported.payload.data.id}/reverse`,{method:"POST",role:"production",body:{expected_report_version:3,expected_work_order_version:Number(wo.version),reason:"下游已安全冲销"}});assert.equal(finalReverse.response.status,201,JSON.stringify(finalReverse.payload));assert.equal((await state(workOrderId)).final_output_available_qty,"10.000000");
});

test("CAS, concurrent source and completion consumption, authorization, direct SQL guards and fault rollback fail closed",async()=>{
  const refs=await seed(),workOrderId=await createIssued(refs),[source]=await executeFinal(workOrderId,[10]);let wo=await state(workOrderId);const forged=await api("/api/production/reports",{method:"POST",role:"production",body:{...reportBody(workOrderId,Number(wo.version),Number(wo.final_output_version),source,"1"),process_stage:"伪造"}});assert.equal(forged.payload.code,"STRUCTURED_REPORT_SERVER_FIELDS_ONLY");const stale=await api("/api/production/reports",{method:"POST",role:"production",body:reportBody(workOrderId,Number(wo.version),999,source,"1")});assert.equal(stale.payload.code,"FINAL_OUTPUT_VERSION_CONFLICT");const denied=await api("/api/production/reports",{method:"POST",role:"sales",body:reportBody(workOrderId,Number(wo.version),Number(wo.final_output_version),source,"1")});assert.equal(denied.response.status,403);assert.equal((await api(`/api/production/final-output-sources?work_order_id=${workOrderId}`,{role:"quality"})).response.status,200);assert.equal((await api(`/api/production/final-output-sources?work_order_id=${workOrderId}`,{role:"sales"})).response.status,403);
  const concurrent=await Promise.all(["a","b"].map(key=>api("/api/production/reports",{method:"POST",role:"production",key:`task03-source-race-${key}`,body:reportBody(workOrderId,Number(wo.version),Number(wo.final_output_version),source,"6")})));assert.deepEqual(concurrent.map(item=>item.response.status).sort(),[201,409]);const winner=concurrent.find(item=>item.response.status===201);assert.equal((await state(workOrderId)).final_output_available_qty,"4.000000");
  await assert.rejects(pool.query("insert into production_report_operation_allocations(production_report_id,operation_run_report_id,snapshot_operation_id,quantity,operation_id,created_by,request_id) select $1,$2,snapshot_operation_id,1,$3,'production01',$4 from production_operation_run_reports where id=$2",[winner.payload.data.id,source.reportId,randomUUID(),randomUUID()]),/requires service transaction/i);
  const guard=await pool.connect();try{await guard.query("begin");await guard.query("select set_config('cyd.production_service_write','allowed',true)");await assert.rejects(guard.query("insert into production_report_operation_allocations(production_report_id,operation_run_report_id,snapshot_operation_id,quantity,operation_id,created_by,request_id) select $1,$2,snapshot_operation_id,5,$3,'production01',$4 from production_operation_run_reports where id=$2",[winner.payload.data.id,source.reportId,randomUUID(),randomUUID()]),/over-consumed/i);await guard.query("rollback");}finally{guard.release();}
  wo=await state(workOrderId);const completionRace=await Promise.all(["a","b"].map(key=>api("/api/production/completions",{method:"POST",role:"warehouse",key:`task03-completion-race-${key}`,body:{work_order_id:workOrderId,expected_version:Number(wo.version),expected_balance_version:0,reason:"并发入库",allocations:[{report_id:Number(winner.payload.data.id),quantity:"6",expected_report_version:1}]}})));assert.deepEqual(completionRace.map(item=>item.response.status).sort(),[201,409]);assert.equal((await pool.query("select on_hand_qty from inventory_stock_balances where material_id=$1",[refs.finishedId])).rows[0].on_hand_qty,"6.000000");
  const refs2=await seed(),otherWorkOrder=await createIssued(refs2,"1"),[otherSource]=await executeFinal(otherWorkOrder,[1]);wo=await state(workOrderId);const cross=await api("/api/production/reports",{method:"POST",role:"production",body:reportBody(workOrderId,Number(wo.version),Number(wo.final_output_version),otherSource,"1")});assert.equal(cross.payload.code,"FINAL_OUTPUT_WORK_ORDER_MISMATCH");
  let other=await state(otherWorkOrder);const faultMeta=meta("production","FAULT_FINAL_REPORT","task03-final-output-fault"),faultService=new ProductionService(new ProductionRepository(pool),undefined,checkpoint=>{if(checkpoint==="after_final_output_report_projection")throw new Error("forced rollback");});await assert.rejects(faultService.createReport(faultMeta,reportBody(otherWorkOrder,Number(other.version),Number(other.final_output_version),otherSource,"1")),error=>error.code==="INTERNAL_ERROR");other=await state(otherWorkOrder);assert.deepEqual({reported:other.reported_qty,good:other.good_qty,available:other.final_output_available_qty},{reported:"0.000000",good:"0.000000",available:"1.000000"});assert.equal(Number((await pool.query("select count(*) count from production_reports where work_order_id=$1",[otherWorkOrder])).rows[0].count),0);assert.equal(Number((await pool.query("select count(*) count from idempotency_keys where key_digest=$1",[faultMeta.keyDigest])).rows[0].count),0);
});
