"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};
type Order={id:number;work_order_code:string;product_name:string;status:string;version:number;planned_qty:string;issued_supported_qty:string;reported_qty:string;good_qty:string;scrap_qty:string;completed_qty:string;structured_routing:boolean;final_output_version:number;final_output_available_qty:string};
type FinalSource={work_order_id:number;work_order_code:string;work_order_version:number;production_batch_id?:number;batch_code?:string;snapshot_operation_id:number;sequence_no:number;operation_code:string;operation_name:string;work_center_code:string;final_output_version:number;final_output_available_qty:string;operation_run_id:number;run_code:string;assigned_operator:string;operation_run_report_id:number;operation_run_report_code:string;source_good_qty:string;reported_from_source_qty:string;source_available_qty:string};
type Report={id:number;work_order_id:number;production_batch_id?:number;batch_code?:string;report_code:string;work_order_code:string;reported_qty:string;good_qty:string;scrap_qty:string;allocated_good_qty:string;available_good_qty:string;process_stage:string;operator:string;report_version:number;reversed:boolean;structured:boolean};
const can=(s:Session|null,p:string)=>Boolean(s?.user&&(s.user.permissions.includes("*")||s.user.permissions.includes(p)));

export default function ProductionReportingPage(){
  const[session,setSession]=useState<Session|null>(null),[orders,setOrders]=useState<Order[]>([]),[sources,setSources]=useState<FinalSource[]>([]),[reports,setReports]=useState<Report[]>([]),[error,setError]=useState("");
  async function fetchData(){const current=await api<Session>("/api/session");if(!current.authenticated)return{current,orders:[],sources:[],reports:[]};const[work,available,reported]=await Promise.all([api<{data:Order[]}>("/api/work-orders?page_size=100"),api<{data:FinalSource[]}>("/api/production/final-output-sources?page_size=100"),api<{data:Report[]}>("/api/production/reports?page_size=100")]);return{current,orders:work.data,sources:available.data,reports:reported.data};}
  function applyData(value:Awaited<ReturnType<typeof fetchData>>){setSession(value.current);setOrders(value.orders);setSources(value.sources);setReports(value.reports);}
  async function load(){applyData(await fetchData());}
  useEffect(()=>{let cancelled=false;void fetchData().then(value=>{if(!cancelled){setSession(value.current);setOrders(value.orders);setSources(value.sources);setReports(value.reports);}}).catch(e=>{if(!cancelled)setError(e instanceof ErpApiError?e.message:"读取失败");});return()=>{cancelled=true;};},[]);
  async function submitStructured(event:FormEvent<HTMLFormElement>,order:Order,source:FinalSource){event.preventDefault();if(!session)return;const form=new FormData(event.currentTarget);setError("");try{await api("/api/production/reports",{method:"POST",body:JSON.stringify({work_order_id:order.id,expected_work_order_version:order.version,expected_final_output_version:order.final_output_version,final_output_allocations:[{operation_run_report_id:source.operation_run_report_id,quantity:String(form.get("quantity"))}],remark:String(form.get("remark")??"")}),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});await load();}catch(e){setError(e instanceof ErpApiError?e.message:"结构化报工失败");}}
  async function submitLegacy(event:FormEvent<HTMLFormElement>,order:Order){event.preventDefault();if(!session)return;const form=new FormData(event.currentTarget);setError("");try{await api("/api/production/reports",{method:"POST",body:JSON.stringify({work_order_id:order.id,expected_version:order.version,reported_qty:String(form.get("reported_qty")),good_qty:String(form.get("good_qty")),scrap_qty:String(form.get("scrap_qty")),process_stage:String(form.get("process_stage")),operator:String(form.get("operator"))}),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});await load();}catch(e){setError(e instanceof ErpApiError?e.message:"兼容报工失败");}}
  async function reverse(report:Report){if(!session)return;const order=orders.find(item=>item.id===report.work_order_id);if(!order)return;setError("");try{await api(`/api/production/reports/${report.id}/reverse`,{method:"POST",body:JSON.stringify({expected_report_version:report.report_version,expected_work_order_version:order.version,reason:"生产报工全额冲销"}),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});await load();}catch(e){setError(e instanceof ErpApiError?e.message:"报工冲销失败");}}
  return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/">← 经营工作台</Link><h1>按 Manufacturing Batch 末工序正式报工</h1><p>一条结构化 Production Report 只能消费同一 Batch 的末工序 Run Report；不写库存。生产批次谱系已建立，但仓库批次库存尚未启用。</p><nav><Link href="/production/batches">Batch genealogy</Link> · <Link href="/production/wip">查看 WIP</Link> · <Link href="/warehouse/production-completions">成品入库</Link></nav></div></header>
    <section className="sourcing-panel"><h2>结构化末工序来源</h2>{orders.filter(o=>o.structured_routing&&["RELEASED","IN_PROGRESS"].includes(o.status)).map(order=>{const rows=sources.filter(source=>source.work_order_id===order.id);return <article className="sourcing-card" key={order.id}><b>{order.work_order_code} · {order.product_name}</b><small>计划 {order.planned_qty} · 已正式报工 {order.reported_qty} · 已入库 {order.completed_qty} · 末工序待最终报工 {order.final_output_available_qty} · Final Output v{order.final_output_version}</small>{rows.length===0?<p>尚无有效末工序 Run Report good 来源。</p>:rows.map(source=><div key={source.operation_run_report_id}><p><b>{source.batch_code??"ORDER"} · {source.sequence_no} {source.operation_code} {source.operation_name}</b> · {source.work_center_code} · Run {source.run_code} · Run Report {source.operation_run_report_code}</p><small>来源 good {source.source_good_qty} · 已正式报工 {source.reported_from_source_qty} · 可报工 {source.source_available_qty} · 稳定来源 #{source.operation_run_report_id}</small>{Number(source.source_available_qty)>0&&can(session,"production.report")?<form className="sourcing-form" onSubmit={e=>submitStructured(e,order,source)}><label>本次来源分配<input name="quantity" required defaultValue={source.source_available_qty}/></label><label>备注（可选）<input name="remark"/></label><button>从稳定来源正式报工</button></form>:null}</div>)}</article>})}</section>
    <section className="sourcing-panel"><h2>历史兼容模式</h2><p>仅无 Routing Snapshot 的历史工单可使用自由字段；结构化工单不会显示此表单。</p>{orders.filter(o=>!o.structured_routing&&["RELEASED","IN_PROGRESS"].includes(o.status)).map(order=><article className="sourcing-card" key={order.id}><b>{order.work_order_code} · {order.product_name} · 兼容模式</b><small>计划 {order.planned_qty} · 领料支持 {order.issued_supported_qty} · 已报 {order.reported_qty}</small>{can(session,"production.report")?<form className="sourcing-form" onSubmit={e=>submitLegacy(e,order)}><label>报工数量<input name="reported_qty" required/></label><label>良品<input name="good_qty" required/></label><label>报废<input name="scrap_qty" required defaultValue="0"/></label><label>工序阶段<input name="process_stage" required defaultValue="历史兼容报工"/></label><label>操作员<input name="operator" required/></label><button>兼容报工</button></form>:null}</article>)}</section>
    <section className="sourcing-panel"><h2>正式报工与待成品入库</h2>{reports.map(r=><article className="sourcing-card" key={r.id}><b>{r.report_code} · {r.work_order_code} · {r.structured?"末工序稳定来源":"历史兼容"}</b><small>{r.reversed?"已冲销":`报工 ${r.reported_qty} · 良品 ${r.good_qty} · 报废 ${r.scrap_qty} · 待入库 ${r.available_good_qty}`} · {r.process_stage} · {r.operator}</small>{!r.reversed&&Number(r.allocated_good_qty)===0&&can(session,"production.report.reverse")?<button onClick={()=>void reverse(r)}>全额冲销报工</button>:null}</article>)}</section>{error?<div className="sourcing-state sourcing-error">{error}</div>:null}</main>;
}
