"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};
type Order={id:number;work_order_code:string;product_name:string;status:string;version:number;planned_qty:string;issued_supported_qty:string;reported_qty:string;good_qty:string;scrap_qty:string;completed_qty:string;waiting_receipt_qty:string};
type Report={id:number;work_order_id:number;report_code:string;work_order_code:string;reported_qty:string;good_qty:string;scrap_qty:string;allocated_good_qty:string;available_good_qty:string;process_stage:string;operator:string;report_version:number;reversed:boolean};
const can=(s:Session|null,p:string)=>Boolean(s?.user&&(s.user.permissions.includes("*")||s.user.permissions.includes(p)));

export default function ProductionReportingPage(){
  const[session,setSession]=useState<Session|null>(null),[orders,setOrders]=useState<Order[]>([]),[reports,setReports]=useState<Report[]>([]),[error,setError]=useState("");
  async function fetchData(){const current=await api<Session>("/api/session");if(!current.authenticated)return{current,orders:[],reports:[]};const [work,reported]=await Promise.all([api<{data:Order[]}>("/api/work-orders?page_size=100"),api<{data:Report[]}>("/api/production/reports?page_size=100")]);return{current,orders:work.data,reports:reported.data};}
  function applyData(value:Awaited<ReturnType<typeof fetchData>>){setSession(value.current);setOrders(value.orders);setReports(value.reports);}
  async function load(){applyData(await fetchData());}
  useEffect(()=>{let cancelled=false;void (async()=>{const current=await api<Session>("/api/session");if(!current.authenticated){if(!cancelled){setSession(current);setOrders([]);setReports([]);}return;}const[work,reported]=await Promise.all([api<{data:Order[]}>("/api/work-orders?page_size=100"),api<{data:Report[]}>("/api/production/reports?page_size=100")]);if(!cancelled){setSession(current);setOrders(work.data);setReports(reported.data);}})().catch(e=>{if(!cancelled)setError(e instanceof ErpApiError?e.message:"读取失败");});return()=>{cancelled=true;};},[]);
  async function submit(event:FormEvent<HTMLFormElement>,order:Order){event.preventDefault();if(!session)return;const form=new FormData(event.currentTarget);setError("");try{await api("/api/production/reports",{method:"POST",body:JSON.stringify({work_order_id:order.id,expected_version:order.version,reported_qty:String(form.get("reported_qty")),good_qty:String(form.get("good_qty")),scrap_qty:String(form.get("scrap_qty")),process_stage:String(form.get("process_stage")),operator:String(form.get("operator"))}),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});await load();}catch(e){setError(e instanceof ErpApiError?e.message:"报工失败");}}
  async function reverse(report:Report){if(!session)return;const order=orders.find(item=>item.id===report.work_order_id);if(!order)return;setError("");try{await api(`/api/production/reports/${report.id}/reverse`,{method:"POST",body:JSON.stringify({expected_report_version:report.report_version,expected_work_order_version:order.version,reason:"生产报工全额冲销"}),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});await load();}catch(e){setError(e instanceof ErpApiError?e.message:"报工冲销失败");}}
  return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/">← 经营工作台</Link><h1>生产分批报工</h1><p>报工只追加事实，不修改库存；累计数量由服务端按计划与 BOM 净领料支持量校验。</p></div></header>
    <section className="sourcing-panel"><h2>可报工工单</h2>{orders.filter(o=>["RELEASED","IN_PROGRESS"].includes(o.status)).map(order=><article className="sourcing-card" key={order.id}><b>{order.work_order_code} · {order.product_name}</b><small>计划 {order.planned_qty} · 领料支持 {order.issued_supported_qty} · 已报 {order.reported_qty} · 良品 {order.good_qty} · 报废 {order.scrap_qty} · 已入库 {order.completed_qty}</small>{can(session,"production.report")?<form className="sourcing-form" onSubmit={e=>submit(e,order)}><label>报工数量<input name="reported_qty" required/></label><label>良品<input name="good_qty" required/></label><label>报废<input name="scrap_qty" required defaultValue="0"/></label><label>工序阶段<input name="process_stage" required defaultValue="完工报工"/></label><label>操作员<input name="operator" required/></label><button>确认报工</button></form>:null}</article>)}</section>
    <section className="sourcing-panel"><h2>报工与待入库良品</h2>{reports.map(r=><article className="sourcing-card" key={r.id}><b>{r.report_code} · {r.work_order_code}</b><small>{r.reversed?"已冲销":`报工 ${r.reported_qty} · 良品 ${r.good_qty} · 报废 ${r.scrap_qty} · 待入库 ${r.available_good_qty}`} · {r.process_stage} · {r.operator}</small>{!r.reversed&&Number(r.allocated_good_qty)===0&&can(session,"production.report.reverse")?<button onClick={()=>void reverse(r)}>全额冲销报工</button>:null}</article>)}</section>{error?<div className="sourcing-state sourcing-error">{error}</div>:null}</main>;
}
