"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api, ErpApiError } from "../../../public/erp/api-client.js";
import "../../procurement/sourcing/sourcing.css";

type Session={authenticated:boolean;csrf_token?:string;user:{permissions:string[]}|null};
type Inspection={id:number;inspection_code:string;inspection_type:string;lifecycle_status:string;failed_qty:string;version:number;production_operation_run_report_id?:number};
type Target={target_snapshot_operation_id:number;sequence_no:number;operation_code:string;operation_name:string;work_center_code:string;description:string};
type Revision={id:number;revision_no:number;status:string;canonical_digest?:string;return_reason?:string};
type Ncr={id:number;ncr_code:string;inspection_id:number;inspection_code:string;work_order_code:string;run_report_code:string;source_sequence_no:number;work_center_code:string;work_center_name:string;inspected_qty:string;passed_qty:string;failed_qty:string;active_rework_qty:string;final_scrap_qty:string;unresolved_qty:string;status:string;version:number;rework_requests?:Revision[]};
const can=(session:Session|null,permission:string)=>Boolean(session?.user&&(session.user.permissions.includes("*")||session.user.permissions.includes(permission)));

export default function NonconformancesPage(){
 const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<Ncr[]>([]),[inspections,setInspections]=useState<Inspection[]>([]),[targets,setTargets]=useState<Record<number,Target[]>>({}),[error,setError]=useState(""),[forbidden,setForbidden]=useState(false);
 async function load(){try{const current=await api<Session>("/api/session");setSession(current);if(!current.authenticated||!can(current,"quality.nonconformance.read")){setForbidden(true);return;}const[ncr,quality]=await Promise.all([api<{data:Ncr[]}>("/api/quality/nonconformances?page_size=100"),api<{data:Inspection[]}>("/api/quality-inspections?inspection_type=IPQC&lifecycle_status=CLOSED&page_size=100")]);const details=await Promise.all(ncr.data.map(n=>api<{data:Ncr}>(`/api/quality/nonconformances/${n.id}`).then(value=>value.data)));setRows(details);setInspections(quality.data.filter(row=>Number(row.failed_qty)>0&&row.production_operation_run_report_id&&!ncr.data.some(n=>n.inspection_id===row.id)));const options=await Promise.all(ncr.data.map(async n=>[n.id,(await api<{data:Target[]}>(`/api/quality/nonconformances/${n.id}/target-operations`)).data] as const));setTargets(Object.fromEntries(options));}catch(cause){if(cause instanceof ErpApiError&&cause.status===403)setForbidden(true);else setError(cause instanceof ErpApiError?`${cause.message} (${cause.code})`:"读取失败");}}
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[]);
 async function post(path:string,body:Record<string,unknown>){if(!session?.csrf_token)return;setError("");try{await api(path,{method:"POST",body:JSON.stringify(body),protectedWrite:{csrfToken:session.csrf_token,idempotencyKey:crypto.randomUUID()}});await load();}catch(cause){setError(cause instanceof ErpApiError?`${cause.message} (${cause.code})`:"操作失败");}}
 async function draft(event:FormEvent<HTMLFormElement>,ncr:Ncr){event.preventDefault();const form=new FormData(event.currentTarget),previous=ncr.rework_requests?.at(-1);await post(`/api/quality/nonconformances/${ncr.id}/rework-requests`,{target_snapshot_operation_id:Number(form.get("target")),quantity:String(form.get("quantity")),reason:String(form.get("reason")),...(previous&&["RETURNED","CANCELLED"].includes(previous.status)?{supersedes_request_id:previous.id}:{})});}
 async function scrap(event:FormEvent<HTMLFormElement>,ncr:Ncr){event.preventDefault();const form=new FormData(event.currentTarget);await post(`/api/quality/nonconformances/${ncr.id}/scrap-dispositions`,{expected_version:ncr.version,quantity:String(form.get("quantity")),reason:String(form.get("reason"))});}
 if(forbidden)return <main className="sourcing-shell"><div className="sourcing-state sourcing-error">403：当前账号无权读取 NCR。</div></main>;
 return <main className="sourcing-shell"><header className="sourcing-header"><div><Link href="/quality/production">← 生产品质</Link><h1>IPQC 不合格处置</h1><p>failed 数量保持 Quality Hold；返工申请不会增加下工序 available，也不会创建 Run Report、库存或财务事实。</p><nav><Link href="/quality/rework-requests">质量返工申请</Link> · <Link href="/production/rework-requests">生产接收队列</Link></nav></div></header>
  {error?<div className="sourcing-state sourcing-error">{error}</div>:null}
  {can(session,"quality.nonconformance.create")&&inspections.length?<section className="sourcing-panel"><h2>符合条件的 CLOSED IPQC</h2>{inspections.map(row=><article className="sourcing-card" key={row.id}><b>{row.inspection_code}</b><small>failed {row.failed_qty} · Operation Run Report #{row.production_operation_run_report_id}</small><button onClick={()=>void post(`/api/quality/inspections/${row.id}/nonconformance`,{expected_version:row.version})}>建立稳定 NCR</button></article>)}</section>:null}
  <section className="sourcing-panel"><h2>NCR 队列与数量守恒</h2>{rows.length?rows.map(ncr=><article className="sourcing-card" key={ncr.id}><div><b>{ncr.ncr_code} · {ncr.work_order_code}</b><span className="sourcing-status">{ncr.status} · v{ncr.version}</span></div><small>Run Report {ncr.run_report_code} · Snapshot Operation #{ncr.source_sequence_no} · Work Center {ncr.work_center_code} {ncr.work_center_name}</small><p>检验/合格/不合格 {ncr.inspected_qty}/{ncr.passed_qty}/{ncr.failed_qty} · 有效返工 {ncr.active_rework_qty} + 最终报废 {ncr.final_scrap_qty} + 未解决 {ncr.unresolved_qty}</p>
   {ncr.rework_requests?.map(request=><p key={request.id}>申请 v{request.revision_no} · {request.status}{request.return_reason?` · 退回：${request.return_reason}`:""}{request.canonical_digest?` · digest ${request.canonical_digest}`:""}</p>)}
   {can(session,"quality.rework_request.create")&&Number(ncr.unresolved_qty)>0&&targets[ncr.id]?.length&&(!ncr.rework_requests?.length||["RETURNED","CANCELLED"].includes(ncr.rework_requests.at(-1)!.status))?<form onSubmit={event=>void draft(event,ncr)}><label>稳定目标工序<select name="target">{targets[ncr.id].map(op=><option value={op.target_snapshot_operation_id} key={op.target_snapshot_operation_id}>{op.sequence_no} · {op.operation_code} {op.operation_name} · {op.work_center_code}</option>)}</select></label><label>返工数量<input name="quantity" required defaultValue={ncr.unresolved_qty}/></label><label>原因<input name="reason" required defaultValue="IPQC 不合格申请返工"/></label><button>{ncr.rework_requests?.length?"创建不可变修订 DRAFT":"创建 DRAFT"}</button></form>:null}
   {can(session,"quality.nonconformance.scrap")&&Number(ncr.unresolved_qty)>0?<form onSubmit={event=>void scrap(event,ncr)}><label>工序报废数量<input name="quantity" required defaultValue={ncr.unresolved_qty}/></label><label>最终原因<input name="reason" required/></label><button>追加不可逆 SCRAP 事实</button><small>不会写 Inventory Ledger 或 MAIN Balance。</small></form>:null}</article>):<div className="sourcing-state">尚无 NCR。</div>}</section>
 </main>;
}
