import { createHash, randomUUID } from "node:crypto";
import type { Pool } from "pg";
import type { IdentityActor } from "../identity-selfhost/types.ts";
import { ProcurementSourcingError, mapProcurementSourcingError } from "./errors.ts";
import { ProcurementSourcingRepository } from "./repository.ts";
import { ProcurementSourcingService } from "./service.ts";
import { canonicalDigest, normalizeCreateRfqInput, positiveId } from "./validation.ts";

type Dependencies = Readonly<{ pool: Pool; actor: IdentityActor; requestId: string; requireCsrf: () => void }>;
const allowed = (actor: IdentityActor, permission: string) => actor.permissions.includes("*") || actor.permissions.includes(permission);
const requirePermission = (actor: IdentityActor, permission: string) => { if (!allowed(actor, permission)) throw new ProcurementSourcingError("PERMISSION_DENIED", "没有权限执行此操作", 403); };
const response = (body: unknown, status: number, requestId: string, replayed = false) => { const headers = new Headers({ "Cache-Control": "no-store", "X-Request-ID": requestId }); if (replayed) headers.set("Idempotency-Replayed", "true"); return Response.json(body, { status, headers }); };
const pageValue = (value: string | null, field: string, fallback: number, maximum: number) => { if (!value) return fallback; const result = Number(value); if (!Number.isSafeInteger(result) || result < 1 || result > maximum) throw new ProcurementSourcingError("REQUEST_VALIDATION_FAILED", `${field} 必须是正整数`); return result; };
async function readBody(request: Request) { const raw = await request.text(); if (!raw || Buffer.byteLength(raw) > 128 * 1024) throw new ProcurementSourcingError("REQUEST_VALIDATION_FAILED", "请求正文为空或超过 128 KiB"); let value: unknown; try { value = JSON.parse(raw); } catch { throw new ProcurementSourcingError("REQUEST_VALIDATION_FAILED", "请求正文不是有效 JSON"); } if (!value || typeof value !== "object" || Array.isArray(value)) throw new ProcurementSourcingError("REQUEST_VALIDATION_FAILED", "请求正文必须是对象"); const forbidden = ["status", "rfq_code", "round_no", "currency_code", "quote_version_no", "quote_digest", "basis_digest", "award_digest", "price_rank", "lowest_price", "recorded_by", "selected_by", "request_id"].find((key) => key in (value as Record<string, unknown>)); if (forbidden) throw new ProcurementSourcingError("REQUEST_VALIDATION_FAILED", `请求正文不能指定服务端字段：${forbidden}`); return { value: value as Record<string, unknown>, digest: canonicalDigest(value) }; }
function mutationMeta(request: Request, dependencies: Dependencies, action: string, requestDigest: string) { const key = request.headers.get("Idempotency-Key") || ""; if (key.length < 8 || key.length > 200 || !/^[\x21-\x7e]+$/.test(key)) throw new ProcurementSourcingError("IDEMPOTENCY_KEY_REQUIRED", "写操作必须提供有效 Idempotency-Key"); const route = new URL(request.url).pathname; const rawKeyDigest = createHash("sha256").update(key).digest("hex"); return { actor: dependencies.actor, requestId: dependencies.requestId, operationId: randomUUID(), keyDigest: createHash("sha256").update(JSON.stringify([dependencies.actor.username, request.method, route, rawKeyDigest])).digest("hex"), requestDigest, method: request.method, route, action }; }

export async function handleProcurementSourcingApi(request: Request, dependencies: Dependencies): Promise<Response | null> {
  const url = new URL(request.url), path = url.pathname; const coverage = path === "/api/procurement/rfqs/coverage", rfqDetail = path.match(/^\/api\/procurement\/rfqs\/([1-9]\d*)$/), mappingBindings = path.match(/^\/api\/procurement\/rfqs\/([1-9]\d*)\/mapping-bindings$/), issue = path.match(/^\/api\/procurement\/rfqs\/([1-9]\d*)\/issue$/), quotes = path.match(/^\/api\/procurement\/rfqs\/([1-9]\d*)\/quotes$/), revise = path.match(/^\/api\/procurement\/quotes\/([1-9]\d*)\/revise$/), compare = path.match(/^\/api\/procurement\/rfqs\/([1-9]\d*)\/comparisons$/), comparison = path.match(/^\/api\/procurement\/comparisons\/([1-9]\d*)$/), award = path.match(/^\/api\/procurement\/rfqs\/([1-9]\d*)\/award$/), reversal = path.match(/^\/api\/procurement\/awards\/([1-9]\d*)\/reversal$/); const collection = path === "/api/procurement/rfqs";
  if (!collection && !coverage && !rfqDetail && !mappingBindings && !issue && !quotes && !revise && !compare && !comparison && !award && !reversal) return null;
  const repository = new ProcurementSourcingRepository(dependencies.pool), service = new ProcurementSourcingService(repository); let action = "PROCUREMENT_SOURCING_REQUEST";
  try {
    if (request.method === "GET") { requirePermission(dependencies.actor, "procurement.rfq.read"); if (coverage) return response({ data: await service.coverage(positiveId(url.searchParams.get("purchase_request_id"), "purchase_request_id")), request_id: dependencies.requestId }, 200, dependencies.requestId); if (rfqDetail) return response({ data: await service.detail(positiveId(rfqDetail[1], "rfqId")), request_id: dependencies.requestId }, 200, dependencies.requestId); if (comparison) return response({ data: await service.comparison(positiveId(comparison[1], "comparisonId")), request_id: dependencies.requestId }, 200, dependencies.requestId); if (collection) { const page = pageValue(url.searchParams.get("page"), "page", 1, 1_000_000), pageSize = pageValue(url.searchParams.get("page_size"), "page_size", 20, 100); const result = url.searchParams.get("queue") === "accepted" ? await service.acceptedRequests(page, pageSize) : await service.list(page, pageSize, url.searchParams.get("status") || undefined); return response({ data: result.rows, rows: result.rows, pagination: result.pagination, request_id: dependencies.requestId }, 200, dependencies.requestId); } throw new ProcurementSourcingError("METHOD_NOT_ALLOWED", "接口不支持该请求方法", 405); }
    if (request.method !== "POST") throw new ProcurementSourcingError("METHOD_NOT_ALLOWED", "接口不支持该请求方法", 405); dependencies.requireCsrf(); const parsed = await readBody(request); let result;
    if (collection) { action = "RFQ_CREATED"; requirePermission(dependencies.actor, "procurement.rfq.manage"); const normalized = normalizeCreateRfqInput(parsed.value); result = await service.create(mutationMeta(request, dependencies, action, canonicalDigest(normalized)), normalized); }
    else if (mappingBindings) { action = "RFQ_MAPPING_CONFIRMED"; requirePermission(dependencies.actor, "procurement.rfq.manage"); result = await service.confirmMappings(positiveId(mappingBindings[1], "rfqId"), mutationMeta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (issue) { action = "RFQ_ISSUED"; requirePermission(dependencies.actor, "procurement.rfq.manage"); result = await service.issue(positiveId(issue[1], "rfqId"), mutationMeta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (quotes) { action = "QUOTE_SUBMITTED"; requirePermission(dependencies.actor, "procurement.quote.record"); result = await service.recordQuote(positiveId(quotes[1], "rfqId"), mutationMeta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (revise) { action = "QUOTE_REVISED"; requirePermission(dependencies.actor, "procurement.quote.record"); result = await service.reviseQuote(positiveId(revise[1], "quoteId"), mutationMeta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (compare) { action = "COMPARISON_GENERATED"; requirePermission(dependencies.actor, "procurement.quote.compare"); result = await service.compare(positiveId(compare[1], "rfqId"), mutationMeta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (award) { action = "SOURCING_AWARDED"; requirePermission(dependencies.actor, "procurement.sourcing.award"); result = await service.award(positiveId(award[1], "rfqId"), mutationMeta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (reversal) { action = "SOURCING_AWARD_REVERSED"; requirePermission(dependencies.actor, "procurement.sourcing.reverse"); result = await service.reverseAward(positiveId(reversal[1], "awardId"), mutationMeta(request, dependencies, action, parsed.digest), parsed.value); }
    else throw new ProcurementSourcingError("NOT_FOUND", "接口不存在", 404); return response(result.body, result.status, dependencies.requestId, result.replayed);
  } catch (error) { const known = mapProcurementSourcingError(error); await repository.failureAudit(dependencies.actor.username, dependencies.requestId, action, known.code); console.error(JSON.stringify({ level: "error", event: "procurement_sourcing_api_failed", request_id: dependencies.requestId, code: known.code })); return response({ error: { code: known.code, message: known.message, request_id: dependencies.requestId }, code: known.code, message: known.message, request_id: dependencies.requestId }, known.status, dependencies.requestId); }
}
