import type { Pool,PoolClient } from "pg";
import { InventoryError } from "../inventory-selfhost/errors.ts";
import { formatQuantity,parseExpectedVersion,parseInventoryText,parseQuantityMicros } from "../inventory-selfhost/rules.ts";
import { InventoryService } from "../inventory-selfhost/service.ts";
import { PostgresInventoryRepository } from "../inventory-selfhost/repository.ts";
import type { InventoryMutationMeta,InventoryMutationResult } from "../inventory-selfhost/types.ts";

export const FINISHED_GOODS_LOT_BOUNDARY=Object.freeze({finished_goods_inventory_lot:true,raw_material_lot:false,supplier_receipt_lot:false,shipment_lot_consumption:true,message:"成品 Manufacturing Batch、FQC 放行与 Shipment 已形成 Inventory Lot 精确追溯；原材料和供应商批次仍未启用。"});

export class FinishedGoodsInventoryLotService{
  readonly pool:Pool;readonly repository:PostgresInventoryRepository;readonly inventory:InventoryService;
  constructor(pool:Pool){this.pool=pool;this.repository=new PostgresInventoryRepository(pool);this.inventory=new InventoryService(this.repository);}

  private access(actor:InventoryMutationMeta["actor"]){return actor.role==="production"?{sql:"and (wo.owner=$3 or exists(select 1 from production_operation_runs run where run.production_batch_id=l.source_production_batch_id and run.created_by=$3))",value:actor.username}:{sql:"",value:null};}
  async list(limit:number,offset:number,actor:InventoryMutationMeta["actor"],materialId?:number){const access=this.access(actor);const values:unknown[]=[limit,offset];let material="";if(materialId){values.push(materialId);material=`and l.material_id=$${values.length}`;}if(access.value){values.push(access.value);access.sql=access.sql.replaceAll("$3",`$${values.length}`);}return this.pool.query(`select l.*,b.batch_code,bs.batch_set_code,wo.work_order_code,m.internal_material_code,m.standard_name,u.code unit_code,
    coalesce(s.on_hand_qty,0)::text on_hand_qty,coalesce(s.reserved_qty,0)::text reserved_qty,coalesce(s.frozen_qty,0)::text frozen_qty,(coalesce(s.on_hand_qty,0)-coalesce(s.reserved_qty,0)-coalesce(s.frozen_qty,0))::text available_qty,coalesce(s.version,0) balance_version
    from inventory_lots l join production_batches b on b.id=l.source_production_batch_id join production_batch_sets bs on bs.id=b.batch_set_id join production_work_orders wo on wo.id=l.work_order_id join material_master m on m.id=l.material_id join units u on u.id=l.unit_id left join inventory_stock_balances s on s.inventory_lot_id=l.id and s.location_code='MAIN'
    where 1=1 ${material} ${access.sql} order by l.created_at desc,l.id desc limit $1 offset $2`,values);}
  async detail(id:number,actor:InventoryMutationMeta["actor"]){const access=this.access(actor);const values:unknown[]=[id];if(access.value){values.push(access.value);access.sql=access.sql.replaceAll("$3",`$${values.length}`);}const result=await this.pool.query(`select l.*,b.batch_code,bs.batch_set_code,wo.work_order_code,m.internal_material_code,m.standard_name,u.code unit_code,
    coalesce(s.on_hand_qty,0)::text on_hand_qty,coalesce(s.reserved_qty,0)::text reserved_qty,coalesce(s.frozen_qty,0)::text frozen_qty,(coalesce(s.on_hand_qty,0)-coalesce(s.reserved_qty,0)-coalesce(s.frozen_qty,0))::text available_qty,coalesce(s.version,0) balance_version
    from inventory_lots l join production_batches b on b.id=l.source_production_batch_id join production_batch_sets bs on bs.id=b.batch_set_id join production_work_orders wo on wo.id=l.work_order_id join material_master m on m.id=l.material_id join units u on u.id=l.unit_id left join inventory_stock_balances s on s.inventory_lot_id=l.id and s.location_code='MAIN' where l.id=$1 ${access.sql}`,values);if(!result.rows[0])throw new InventoryError("INVENTORY_LOT_NOT_FOUND","成品库存 Lot 不存在或不可见",404);const [completions,events,fqc,shipments]=await Promise.all([this.pool.query(`select x.*,c.completion_code,p.reversed,p.version completion_version from production_completion_inventory_lots x join production_completions c on c.id=x.production_completion_id join production_completion_receipt_projections p on p.completion_id=c.id where x.inventory_lot_id=$1 order by x.production_completion_id`,[id]),this.pool.query("select * from inventory_lot_events where inventory_lot_id=$1 order by id",[id]),this.pool.query(`select qi.id,qi.inspection_code,qi.lifecycle_status,qi.decision_status,qi.inspected_qty::text,qi.passed_qty::text,qi.released_qty::text,a.id allocation_id,so.sales_order_code,sol.line_no sales_order_line_no,coalesce(consumed.qty,0)::text consumed_qty from quality_inspections qi join finished_goods_sales_allocations a on a.id=qi.fqc_allocation_id join sales_order_lines sol on sol.id=qi.sales_order_line_id join sales_order_versions sov on sov.id=sol.sales_order_version_id join sales_orders so on so.id=sov.sales_order_id left join lateral(select coalesce(sum(case when fact.entry_type='SHIPMENT' then fact.quantity else -fact.quantity end),0) qty from sales_shipment_line_fqc_allocations fact where fact.quality_inspection_id=qi.id) consumed on true where qi.inventory_lot_id=$1 and qi.inspection_type='FQC' order by qi.id`,[id]),this.pool.query(`select sl.id shipment_line_id,sl.quantity::text,sh.id shipment_id,sh.shipment_code,sh.shipment_type,sh.original_shipment_id,sh.ship_date,so.sales_order_code,sl.inventory_ledger_entry_id from sales_shipment_lines sl join sales_shipments sh on sh.id=sl.shipment_id join sales_orders so on so.id=sh.sales_order_id where sl.inventory_lot_id=$1 order by sl.id`,[id])]);return {...result.rows[0],completions:completions.rows,fqc_releases:fqc.rows,shipments:shipments.rows,events:events.rows,boundary:FINISHED_GOODS_LOT_BOUNDARY};}
  async ledger(id:number,actor:InventoryMutationMeta["actor"],limit:number,offset:number){await this.detail(id,actor);return this.pool.query(`select e.*,a.adjustment_code,a.reason from inventory_ledger_entries e join inventory_adjustments a on a.id=e.adjustment_id where e.inventory_lot_id=$1 order by e.created_at desc,e.id desc limit $2 offset $3`,[id,limit,offset]);}

  async freeze(id:number,meta:InventoryMutationMeta,input:Record<string,unknown>,freeze:boolean):Promise<InventoryMutationResult>{const expectedLotVersion=parseExpectedVersion(input.expected_lot_version),expectedBalanceVersion=parseExpectedVersion(input.expected_balance_version),quantity=formatQuantity(parseQuantityMicros(input.quantity,"quantity",false)),reason=parseInventoryText(input.reason,freeze?"冻结原因":"解冻原因",1000,true);return this.repository.execute(meta,async(client:PoolClient)=>{
    const lot=(await client.query("select * from inventory_lots where id=$1 for update",[id])).rows[0];if(!lot)throw new InventoryError("INVENTORY_LOT_NOT_FOUND","成品库存 Lot 不存在",404);if(Number(lot.version)!==expectedLotVersion)throw new InventoryError("INVENTORY_LOT_VERSION_CONFLICT","Lot 版本已变化，请刷新后重试",409);if(lot.status==="REVERSED")throw new InventoryError("INVENTORY_LOT_STATE_CONFLICT","已冲销 Lot 不能冻结或解冻",409);
    const operationType=freeze?"FREEZE":"UNFREEZE";const result=await this.inventory.postLotInTransaction(client,meta,{inventoryLotId:id,operationType,quantity,expectedBalanceVersion,reason});const line=(result.body.data as {lines:Record<string,unknown>[]}).lines[0];const afterFrozen=String(line.after_frozen_qty),afterOnHand=String(line.after_on_hand_qty);const next=Number(afterFrozen)>0?"FROZEN":Number(afterOnHand)===0?"DEPLETED":"AVAILABLE";const updated=await client.query("update inventory_lots set status=$2,version=version+1,updated_at=now() where id=$1 and version=$3 returning *",[id,next,expectedLotVersion]);if(!updated.rows[0])throw new InventoryError("INVENTORY_LOT_VERSION_CONFLICT","Lot 并发更新冲突",409);await client.query(`insert into inventory_lot_events(inventory_lot_id,event_type,inventory_adjustment_id,inventory_ledger_entry_id,quantity,from_status,to_status,reason,actor,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,freeze?"FROZEN":"UNFROZEN",result.adjustmentId,Number(line.ledger_entry_id),quantity,lot.status,next,reason,meta.actor.username,meta.requestId]);return {...result,body:{...result.body,data:{...(result.body.data as object),lot:updated.rows[0]},inventory_lot_id:id},inventoryLotIds:[id]};});}
}
