import { createHash, randomUUID } from "node:crypto";
import type { Pool } from "pg";
import type { IdentityActor } from "../identity-selfhost/types.ts";
import { ProcurementError, mapProcurementError } from "../procurement-selfhost/errors.ts";
import { ProcurementRepository } from "../procurement-selfhost/repository.ts";
import { ProcurementFulfillmentService, numericId } from "./service.ts";

type Dependencies = Readonly<{ pool: Pool; actor: IdentityActor; requestId: string; requireCsrf: () => void }>;
const allowed = (actor: IdentityActor, permission: string) => actor.permissions.includes("*") || actor.permissions.includes(permission);
const requirePermission = (actor: IdentityActor, permission: string) => { if (!allowed(actor, permission)) throw new ProcurementError("PERMISSION_DENIED", "没有权限执行此操作", 403); };
const response = (body: unknown, status: number, requestId: string, replayed = false) => { const headers = new Headers({ "Cache-Control": "no-store", "X-Request-ID": requestId }); if (replayed) headers.set("Idempotency-Replayed", "true"); return Response.json(body, { status, headers }); };
const pageValue = (value: string | null, fallback: number, maximum: number) => { const parsed = value ? Number(value) : fallback; if (!Number.isSafeInteger(parsed) || parsed < 1 || parsed > maximum) throw new ProcurementError("REQUEST_VALIDATION_FAILED", "分页参数无效"); return parsed; };
const canonical = (value: unknown): unknown => Array.isArray(value) ? value.map(canonical) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonical(item)])) : value;
async function readBody(request: Request) { const raw = await request.text(); if (!raw || Buffer.byteLength(raw) > 64 * 1024) throw new ProcurementError("REQUEST_VALIDATION_FAILED", "请求正文为空或超过 64 KiB"); let value: unknown; try { value = JSON.parse(raw); } catch { throw new ProcurementError("REQUEST_VALIDATION_FAILED", "请求正文不是有效 JSON"); } if (!value || typeof value !== "object" || Array.isArray(value)) throw new ProcurementError("REQUEST_VALIDATION_FAILED", "请求正文必须是对象"); const forbidden = ["status", "received_quantity", "remaining_quantity", "created_by", "updated_by", "request_id", "purchase_order_id", "purchase_order_line_id", "financial_source", "lot_code", "inventory_lot_id", "material_id", "unit_id", "supplier_id"].find((key) => key in (value as Record<string, unknown>)); if (forbidden) throw new ProcurementError("REQUEST_VALIDATION_FAILED", `请求正文不能指定服务端字段：${forbidden}`); return { value: value as Record<string, unknown>, digest: createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex") }; }
function meta(request: Request, dependencies: Dependencies, action: string, requestDigest: string) { const key = request.headers.get("Idempotency-Key") || ""; if (key.length < 8 || key.length > 200 || !/^[\x21-\x7e]+$/.test(key)) throw new ProcurementError("IDEMPOTENCY_KEY_REQUIRED", "写操作必须提供有效 Idempotency-Key"); const route = new URL(request.url).pathname, raw = createHash("sha256").update(key).digest("hex"); return { actor: dependencies.actor, requestId: dependencies.requestId, operationId: randomUUID(), keyDigest: createHash("sha256").update(JSON.stringify([dependencies.actor.username, request.method, route, raw])).digest("hex"), requestDigest, method: request.method, route, action }; }

export async function handleProcurementFulfillmentApi(request: Request, dependencies: Dependencies): Promise<Response | null> {
  const url = new URL(request.url), path = url.pathname, convert = path.match(/^\/api\/procurement\/awards\/([1-9]\d*)\/purchase-orders$/), plans = path.match(/^\/api\/procurement\/purchase-orders\/([1-9]\d*)\/delivery-plans$/), receive = path.match(/^\/api\/procurement\/delivery-plans\/([1-9]\d*)\/receipts$/), planTransition = path.match(/^\/api\/procurement\/delivery-plans\/([1-9]\d*)\/(cancel|close)$/), reversal = path.match(/^\/api\/procurement\/fulfillment\/receipts\/([1-9]\d*)\/reversal$/);
  const collection = ["/api/procurement/fulfillment/pending-awards", "/api/procurement/fulfillment/orders", "/api/procurement/fulfillment/receiving-queue", "/api/procurement/fulfillment/payable-handoff"].includes(path);
  if (!collection && !convert && !plans && !receive && !planTransition && !reversal) return null;
  const repository = new ProcurementRepository(dependencies.pool), service = new ProcurementFulfillmentService(repository); let action = "PROCUREMENT_FULFILLMENT_REQUEST";
  try {
    if (request.method === "GET" && collection) { requirePermission(dependencies.actor, "procurement.fulfillment.read"); const page = pageValue(url.searchParams.get("page"), 1, 1_000_000), size = pageValue(url.searchParams.get("page_size"), 20, 100), offset = (page - 1) * size; const result = path.endsWith("pending-awards") ? await service.pendingAwards(size, offset) : path.endsWith("orders") ? await service.listOrdersAndPlans(size, offset) : path.endsWith("receiving-queue") ? await service.receivingQueue(size, offset) : await service.payableHandoff(size, offset); return response({ data: result.rows, rows: result.rows, pagination: { page, page_size: size }, request_id: dependencies.requestId }, 200, dependencies.requestId); }
    if (request.method !== "POST") throw new ProcurementError("METHOD_NOT_ALLOWED", "接口不支持该请求方法", 405);
    dependencies.requireCsrf(); const parsed = await readBody(request); let result;
    if (convert) { action = "SOURCING_AWARD_CONVERTED"; requirePermission(dependencies.actor, "procurement.award.convert"); result = await service.convertAward(numericId(convert[1], "awardId"), meta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (plans) { action = "DELIVERY_PLANS_CREATED"; requirePermission(dependencies.actor, "procurement.delivery_plan.manage"); result = await service.createDeliveryPlans(numericId(plans[1], "purchaseOrderId"), meta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (receive) { action = "DELIVERY_PLAN_RECEIVED"; requirePermission(dependencies.actor, "procurement.receiving.receive"); result = await service.receive(numericId(receive[1], "deliveryPlanId"), meta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (planTransition) { action = planTransition[2] === "cancel" ? "DELIVERY_PLAN_CANCELLED" : "DELIVERY_PLAN_CLOSED"; requirePermission(dependencies.actor, "procurement.delivery_plan.manage"); result = await service.transitionPlan(numericId(planTransition[1], "deliveryPlanId"), planTransition[2] as "cancel"|"close", meta(request, dependencies, action, parsed.digest), parsed.value); }
    else if (reversal) { action = "DELIVERY_PLAN_RECEIPT_REVERSED"; requirePermission(dependencies.actor, "procurement.receiving.reverse"); result = await service.reverseReceipt(numericId(reversal[1], "receiptId"), meta(request, dependencies, action, parsed.digest), parsed.value); }
    else throw new ProcurementError("NOT_FOUND", "接口不存在", 404);
    return response(result.body, result.status, dependencies.requestId, result.replayed);
  } catch (error) { const known = mapProcurementError(error); await repository.failureAudit(dependencies.actor.username, dependencies.requestId, action, known.code); console.error(JSON.stringify({ level: "error", event: "procurement_fulfillment_api_failed", request_id: dependencies.requestId, code: known.code })); return response({ error: { code: known.code, message: known.message, request_id: dependencies.requestId }, code: known.code, message: known.message, request_id: dependencies.requestId }, known.status, dependencies.requestId); }
}
