"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { api,ErpApiError } from "../../../public/erp/api-client.js";
import { roleLabel,statusLabel } from "../../../public/erp/status-localization.js";
import "../../procurement/sourcing/sourcing.css";
type User={username:string;display_name:string;role:string;permissions:string[]};type Session={authenticated:boolean;user:User|null;csrf_token?:string};
type Handoff={source_entry_id:number;amount:string;currency_code:string;created_at:string;receipt_id:number;receipt_code:string;purchase_order_id:number;po_code:string;supplier_code:string;supplier_name:string;ap_id:number|null;ap_code:string|null;ap_status:string|null;handoff_status:"PENDING_AP"|"AP_CREATED"};
const can=(u:User|null|undefined,p:string)=>Boolean(u&&(u.permissions.includes("*")||u.permissions.includes(p)));const msg=(e:unknown)=>e instanceof ErpApiError?`${e.message}${e.requestId?`（请求 ${e.requestId}）`:""}`:"系统暂时无法完成请求";
export function FinancePayablesWorkspace(){const[session,setSession]=useState<Session|null>(null),[rows,setRows]=useState<Handoff[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const load=useCallback(async()=>{try{const current=await api<Session>("/api/session");setSession(current);if(current.authenticated&&can(current.user,"finance.read"))setRows((await api<{data:Handoff[]}>("/api/procurement/fulfillment/payable-handoff?page_size=100")).data)}catch(e){setError(msg(e))}},[]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function createAp(row:Handoff){if(!session)return;setBusy(true);setError("");try{const today=new Date().toISOString().slice(0,10);await api("/api/finance/documents",{method:"POST",body:JSON.stringify({doc_type:"AP",purchase_source_entry_id:row.source_entry_id,accounting_date:today,due_date:today}),protectedWrite:{csrfToken:session.csrf_token!,idempotencyKey:crypto.randomUUID()}});setNotice(`已核对 ${row.receipt_code} 并显式生成应付 ${row.amount} ${row.currency_code}`);await load()}catch(e){setError(msg(e))}finally{setBusy(false)}}
 if(!session)return <main className="sourcing-shell">正在读取会话…</main>;if(!session.authenticated)return <main className="sourcing-shell">请先登录。</main>;if(!can(session.user,"finance.read"))return <main className="sourcing-shell"><div className="sourcing-state sourcing-error">没有财务读取权限。</div></main>;
 return <main className="sourcing-shell"><div className="sourcing-banner">收货只形成采购财务来源 · AP 必须由财务人员逐笔核对并显式生成</div><header className="sourcing-header"><div><Link href="/" className="sourcing-back">← 经营工作台</Link><p className="sourcing-kicker">采购应付交接</p><h1>采购收货应付交接</h1><p>每次分批收货形成独立金额来源；来源只能消费一次，页面金额不可编辑。</p></div><div><b>{session.user!.display_name||session.user!.username}</b><span>{roleLabel(session.user!.role)}</span></div></header><section className="sourcing-metrics"><div><small>已收货待生成应付</small><strong>{rows.filter(r=>r.handoff_status==="PENDING_AP").length}</strong></div><div><small>已生成应付</small><strong>{rows.filter(r=>r.handoff_status==="AP_CREATED").length}</strong></div><div><small>来源总数</small><strong>{rows.length}</strong></div></section><section className="sourcing-panel"><h2>采购财务来源</h2>{rows.map(row=><article className="sourcing-card" key={row.source_entry_id}><div><b>{row.receipt_code} · {row.po_code}</b><span className={`sourcing-status status-${row.handoff_status==="PENDING_AP"?"pending":"completed"}`}>{statusLabel(row.handoff_status)}</span></div><p>{row.supplier_code} · {row.supplier_name} · <b>{row.amount} {row.currency_code}</b></p><small>稳定来源 #{row.source_entry_id}{row.ap_code?` · ${row.ap_code} · ${statusLabel(row.ap_status)}`:""}</small>{row.handoff_status==="PENDING_AP"&&can(session.user,"finance.post")?<button disabled={busy} onClick={()=>void createAp(row)}>核对并显式生成 AP</button>:null}</article>)}{!rows.length?<div className="sourcing-state">尚无采购收货财务来源。</div>:null}</section>{notice?<div className="sourcing-state">{notice}</div>:null}{error?<div className="sourcing-state sourcing-error">{error}</div>:null}</main>}
